### ISSUE TITLE
Nikon D1x nefs not demosaicing properly

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#1074]
Originally reported on Google Code with ID 1088
```
When opening Nikon Nefs 3 lines appear at regular interval on the image. This happens
regarless of the demosaicing algorithm used. 

What steps will reproduce the problem?
1.load the D1X nef in a directory and navigate to it; the thumbnail appears
2.double click on the thumbnail
3.look at the image. Sometimes the lines do not appear immediately, change the zoom
level

Click on the Preferences icon (top-right corner) > About > Version, and
paste all that here.
note that the version is too wide to be displayed properly on the screen, but running
from a console I get :
changeset:1583:1a1fe5838576 Latest-tag:4.0.4,CSet:1583:1a1fe5838576



Operating system and architecture (e.g. winXP-32, ubuntu-10.10-64):
Pclinux OS64 test4



You will find a nef here : http://www.megaupload.com/?d=H0OD2DWY
and another one here: http://www.megaupload.com/?d=ZVKQI89I

they will remain there for 90 days from today; if you cannot deal with these before
that, just post a replay to this topic and upon notification, I will upload the files
again.

Thanks for your time
Didier


```

Reported by `didiergm` on 2011-11-02 12:51:51

**Comment by heckflosse** [comment]
I'll push a new branch which fixes the border Issue and an unreported Highlight Reconstruction Issue for D1x files at the weekend (I have some thousands of D1x files on my HD, without fixing the Issues, I'm not able to process them in RT)

**Comment by heckflosse** [comment]
Here's a link to some D1x files: http://filebin.net/clksq212bi

All files show border Issues in master branch. Additionally the dng file with the pp3 file applied to it shows vertical line artifacts in lower part of waterfall. All this Issues will be fixed in the upcoming branch (already works fine here, have to clean the code before pushing the branch)

**Comment by heckflosse** [comment]
036114c should fix the border and highlight reconstruction issues.

**Comment by Beep6581** [comment]
I tested branch d1xfix, no issues with D1X files.

**Comment by heckflosse** [comment]
I added two commits to the branch to clean the code a little bit

**Comment by adamreichold** [comment]
Had a look at the clean-up commits and I am definitely for merging the branch. Only added two questions where it isn't immediately clear to me what the best approach would be.

**Comment by adamreichold** [comment]
@heckflosse I know it is not strictly related, but during review of the above I think I noticed, that the only user of the `freeArray2` helper function is probably leaking memory using it since it will only free `a[0]` but `eahd_demoasic` will allocate 3 or 4 separate arrays. I push [the branch](https://github.com/adamreichold/RawTherapee/tree/remove-free-array2-helper) to fix this by introducing a jagged array helper class as a replacement for temporary array of arrays buffers. Could you have a look at it when merging the above? Should I just open a separate pull request?

**Comment by heckflosse** [comment]
@adamreichold I had a look.
Why is https://github.com/adamreichold/RawTherapee/commit/c877ea9cc7e276875cfa1b5801093517cbbb8fe4#diff-9a29b5c256b5541c61a874d88ce94be9R118 
declared const but https://github.com/adamreichold/RawTherapee/commit/c877ea9cc7e276875cfa1b5801093517cbbb8fe4#diff-9a29b5c256b5541c61a874d88ce94be9R249 is not declared const ?

I would prefer a separate pull request for your branch to avoid d1xfix branch becoming a never ending story ;-)

**Comment by adamreichold** [comment]
@heckflosse The missing has no reason other the clumsiness on my part. (Did I mention that I really like Rust's decision to make variables immutable by default and having to mark them `mut` for mutability instead of `const`... :-D)

I'll open a separate pull request in a minute...

**Comment by adamreichold** [comment]
@heckflosse The pull request is #3139.

**Comment by adamreichold** [comment]
@heckflosse @Beep6581 Since the D1x fixes got merged, do we close or do we await further retesting?

**Comment by heckflosse** [comment]
@adamreichold for me it's good now, so we can close it. Though the old acr 6 MP interpolation for D1X files was better than the 10 MP interpolation IMHO. But who, except me, has still old D1X files to process in RT?
