### ISSUE TITLE
thumbnail.cc uses Glib::Mutex recusively

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#1668]
Originally reported on Google Code with ID 1684
```
thumbnail.cc uses Glib::Mutex recusively, for example getThumbnailSize() locks the mutex,
and then calls  getProcParams() which itself locks the mutex.

The Glibmm docs say that this should not work:
"Glib::Mutex is not recursive, i.e. a thread will deadlock, if it already has locked
the mutex while calling lock(). Use Glib::RecMutex instead, if you need recursive mutexes."

It seems that while in the current version of glibmm on windows it works without a
deadlock, it does deadlock on linux (hence it being ifdef'ed out).

It would be wise to follow the advice of the docs, and switch the code to use RecMutex
(if recursiveness is needed). The attached patch does this. It works for me on linux,
but i have not tested on windows.

This was noticed while investigating issue 1675, but i think is really a separate issue.
There a plenty of other bits of code using Glib::Mutex, i have not checked those yet.

Click on Preferences > About > Version and paste all that here.
current hg b681d69af34d


```

Reported by `samtygier` on 2013-01-16 23:03:31

<hr>
 * *Attachment: [swtich_to_recmutex.diff](https://storage.googleapis.com/google-code-attachments/rawtherapee/issue-1684/comment-0/swtich_to_recmutex.diff)*

**Comment by Beep6581** [comment]
@Hombre57 what's the status here?

**Comment by Hombre57** [comment]
IIRC, I saw a change in gcc that would make both Linux and Windows pthread implementation works the same, maybe since gcc 5, but I can't find that information again. We can still close this issue, since the workaround shouldn't introduce any speed penalty. If one want to look in that again, he may simplify the MyMutex classes. However we should keep them for debugging purpose.
