### ISSUE TITLE
RTTI - migrate to compressed TIFF format

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#1853]
Originally reported on Google Code with ID 1869

```
Re: http://www.luminous-landscape.com/forum/index.php?topic=77666.0

"The lossy-compressed DNG is also the internal format used for Smart Previews in Lr
5 Beta"

This is quite nice, actually. If RTTI format is also lossy DNG it will offer
1. saving disk space
2. larger thumbnail size for more convenient editing in File Browser
3. could improve performance on some systems where IO is bottleneck

Visually lossy and lossless DNG are very close.
```

Reported by `michaelezra000` on 2013-05-11 20:32:40

**Comment by Hombre57** [comment]
Just to keep it under the hand, this issue should remain opened. Even if we don't go to lossy-compressed DNG or TIFF or whatever is compressed, I think it will bring preformance to have smaller thumbnail files, and reduce the HD footprint (which can be quite large even with today's capacity).

@adamreichold If you feel confident with file formats (more than me), this issue waits for you or for someone wanting to bring some performance to the File Browser.

**Comment by Beep6581** [comment]
Agreed, I've helped some users who had cache folders over 10GB!
There is #1895 for OpenEXR support. If we're talking about adding a new format, and the requirement of the new format is high bit depth (that's why we're not using JPEG, right?), then maybe OpenEXR is the way to go? It supports lossless and lossy compression. Kill two birds with one stone.

**Comment by Hombre57** [comment]
Yes, it has to support high bit depth. Having OpenEXR would be great ! But if that's not possible, I'd go TIFF or DNG. Darktable already implements OpenEXR, maybe we could get some code from them ;)

**Comment by adamreichold** [comment]
@Hombre57 Yes, I would like to try to work on that. Should I assign myself to this then? (You'll take care of the ICM preview properties tab then?)

@Beep6581 When removing in the `safegtk` API in my `remove-safegtk` branch, I think I noticed that the method `CacheManager::applyCacheSizeLimitation` is broken insofar it does not use the 'CacheManager::getCacheFileName` method to determine the file to delete, therefore missing the MD5-dependent part.
I have not yet reported this as a separate issue, because I could not yet properly verify this and I though it could be fixed along the way. But since that branch does depend on the C++11 example code and is itself pretty large, maybe I should isolate these changes for a separate pull request?

**Comment by Hombre57** [comment]
> Should I assign myself to this then?

Yes, if you're okay.

> You'll take care of the ICM preview properties tab then?

The ICM what ? :) You mean the monitor profile tab next to the History tab ??

**Comment by adamreichold** [comment]
@Hombre57 Yes, mean the tab to choose monitor profile and intent as well as soft proofing options, there I did call it colour management preview properties or something. :-)

**Comment by Beep6581** [comment]
@adamreichold when it comes to code I only take advice, I don't give it ;) If it's a minute's work then why not, that would be cleaner, but if it would waste much time then I don't think anyone would mind if that part wasn't in its own commit.

**Comment by heckflosse** [comment]
Closing because @adamreichold is no longer active since more than two years.
