### ISSUE TITLE
Logarithmic histogram

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#196]
Originally reported on Google Code with ID 205

```
It's sometimes necessary to have a logarithmic view of the histogram. A double click
(e.g.) should toggle between the linear and the logarithmic view.
```

Reported by `natureh.510` on 2010-09-02 17:42:34

**Comment by Thanatomanic** [comment]
Let me dust off this old feature request, because I have been looking for a way to implement this myself. It seems to be rather easy to do (except for the fact that I don't know yet how to make a dedicated toggle for it in the GUI).

My first attempt was to make a logarithmic scaling of the y-axis, by simply editing `rtgui\histogrampanel.cc`. I needed to add `#include <cmath>` in the header and modify `HistogramArea::drawCurve(...)` by adding 

`double factor = 2.0; // scaling factor for the strength of the curve, lower is stronger effect`
`double dvsize = (double)vsize;`
`val = dvsize * log(factor / (factor + val)) / log(factor / dvsize); \\ converting the value to a log scale`

I also made an alternative scaling system based on a cubic function that compresses the low and high values in the histogram and pulls apart (enhances) the middle values. This was done because in my experience the middle values are the most common, and most important. Very arbitrary for sure, but it gives nicely looking histograms.

`double factor = 2.0; // scaling factor for the strength of the curve, higher is stronger effect`
`val = (val * (4 * (-1.0 + factor) * val * val - 6.0 * (-1.0 + factor) * val * vsize + (-2.0 + 3.0 * factor) * vsize *vsize))/(factor * vsize * vsize);`

If people would be interested, I could figure out how to make a pull request out of this...

**Comment by heckflosse** [comment]
@Thanatomanic 

> If people would be interested, I could figure out how to make a pull request out of this...

Absosultely! Don't hesitate to to ask for help.

**Comment by heckflosse** [comment]
@Thanatomanic doesn't double click on histogram work already?

**Comment by Thanatomanic** [comment]
@heckflosse I'll see what I can do for the pull request. Currently if you double click the histogram you toggle the 'full' vs 'cutoff' mode, which is a different solution to showing more of the interesting parts of the histogram.

**Comment by Beep6581** [comment]
Handled by #4537
