### ISSUE TITLE
original EOS 1Ds  RAW support

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#277]
Originally reported on Google Code with ID 286

```
Hello developers,

it would be great, if You could include support with the original EOS 1Ds RAW ( 2002,
TIF format).
It loads only a thumb, however when I take the long rout (via DNG) it works.

Here´s a RAW to DL:
http://homepage.mac.com/uli.heckmann/.Public/EOS%201Ds001.TIF.zip

I do have an EOS with a removed AA filter, so using AMZE is tempting for me.

thank You very much


```

Reported by `trayloader@mac.com` on 2010-10-25 06:47:36

**Comment by Techwolf** [comment]
[RawTherapee](https://github.com/RawTherapee/RawTherapee) version 5.12 still has this bug.
[darktable](https://github.com/darktable-org/darktable) had the exact same bug. It was fixed with pull request https://github.com/darktable-org/darktable/pull/19055

This should be ported to fix this long standing bug once and for all.
