### ISSUE TITLE
Pink cast in Nikon D810 14-bit raw files

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#2814]
Originally reported on Google Code with ID 2834

```
Hello,

I already reported about this here https://code.google.com/p/rawtherapee/issues/detail?id=2731#c37
but was asked to open this as a new issue and provide some files to test

In short, here is the problem for me. I get that pink isssue similar as here http://rawtherapee.com/forum/viewtopic.php?f=3&t=6056
, I get everything pink when viewing .NEF files of Nikon D810.

here a screenshot of pink issue http://cl.ly/image/321J3L2U0q1O

I tracked the issue down to changes in concast.json code, see attached files, I provided
screenshotes of everything.

1. sample of pink cast + code of concast.json that I think is responsible new RT 4.2.222
2. preview of solved issue (at least for me) + code of concast.json … which was same
as in old RT 4.2.21

So basicaly, I used the code from RT 4.2.21, put that in new RT 4.2.222 … concast.json,
just the part for Nikon D810, and issue solved for me.

Here are all files http://filebin.net/gp2hdbc7ab

Kind regards,
Marck
```

Reported by `marck.goran.lorencin` on 2015-07-08 21:59:59

**Comment by iliasg** [comment]
Looks like not only uncompressed Nikon files are affected http://rawtherapee.com/oldforum/viewtopic.php?f=3&t=6322 same wrong black level detected !!
Copying my last message from the old forum. 
"Looks like it is the same problem we had with an uncompressed D810 file .. https://code.google.com/p/rawtherapee/i ... il?id=2834 (But this D5300 file is compressed).
Dcraw again reads BL=9 instead of 600 !!. So the manual correction in RT raw BlackLevels should be +591.00 (not +600).
I cannot find the reason now because I am unable to read the code
a workaround could be to change the camconst.json behavior regarding black level. As it is now RT adds the camconst_BL upon the BL which is read from exif. We need to not add but overwrite the exif_BL with the new value and then declare a BL=600 in camconst.json.
I think it's better to add a "black_offset" tag to be used with Panasonics (add "black_offset" upon the "exif_BL"), and reverting of the current "black" tag to it's earlier state (replace any calculated/detected by Dcraw value)

I am not sure if this BL=600 is always correct i.e in the case of a nef which comes from in_camera combination of multiple shots"
My folder for issue 2814 sample files .. only the D5300 file is available for the moment
https://drive.google.com/folderview?id=0B0NqktTgc54scjhRbEgtNlI2R3M&usp=sharing

**Comment by iliasg** [comment]
Fixed with Dcraw V9.27 merge .. https://github.com/Beep6581/RawTherapee/commit/18243db5bafb63595fd561c89a7b7676483ef843

**Comment by Beep6581** [comment]
Hey @iliasg, I fixed the quoted text and link in your post, hope you don't mind.

If fixed, can we close?

**Comment by iliasg** [comment]
@Beep6581 I just tested on the D5300 sample which is the only available at the moment .. when I will go back home I will be able to test on the D810 sample ..
I think we can close this after Dcrawupdate find it's way into master branch ..

**Comment by Beep6581** [comment]
@iliasg status?

**Comment by iliasg** [comment]
Fixed ..
