### ISSUE TITLE
Tint range too large

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#2836]
The white balance tint slider's range is too wide leaving too little room for the practical
range of values (0.8-1.2). If it's at all useful for it to go from 0.02 to 5, then it should map the values in some way that the practical range gets much more slider space than the rarely used range.

**Comment by Beep6581** [comment]
Someone needs a larger range for IR, which makes this request more necessary:
https://discuss.pixls.us/t/white-balance-offset-for-ir-work/1045/1

**Comment by Beep6581** [comment]
Closing this, see #3221

**Comment by mzuther** [comment]
Hey Beep6581,

I was about to open a feature request, but I think my idea fits here. How about adding a checkbox (or button) "Limit range" to the white balance dialog? When activated (possibly by default), the range of the following sliders would be limited:

* Temperature: 5000 to 8000 (or the like)
* Tint: 0.8 to 1.2
* Blue/Red equalizer: 0.8 to 1.2 (I don't use this too often, so the best range might be different)

It would be a good idea to add a history entry in case the checkbox is clicked, because this might lead extreme slider settings to be "clipped" to the new limits.

Additional task for the ambitious coder: add three checkboxes / buttons in a row: "Limit Temperature", "Limit Tint", "Limit Blue/Red"... :)

All the best,

Martin

**Comment by Thanatomanic** [comment]
Closing, can be taken up by #4617.
