### ISSUE TITLE
Perceptual curve problem with blues

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#2889]
AsdiscussedinIRC:P
http://filebin.net/eapljeucg3

**Comment by atorger** [comment]
I'll have a look hopefully soon. I think the reason is that the extreme blue gets pushed out of gamut. Extreme blue clipping to black is a common problem when CIE XYZ coordinates get negative and clipped, and I guess this issue is related. The "reference" implementation for the perceptual curve is in the DCamProf profiler, so I'll try to reproduce it there first.
