### ISSUE TITLE
Tone curve values > 1 or > 100

### ISSUE THREAD

**Issue by paulmatthijsse** [Beep6581/RawTherapee#2892]
Hello, I noticed two things regarding tone curves. 
1. In Exposure section, select tone curve 1, select right upper node, delete value in O field (so make it empty), click on the I field on the left --> crash. Nobody will repeat this under normal circumstances, so not a big deal.
2. The following applies to the curves in the wavelet section as well. One can drag the nodes with the mouse to values of 1 or 100, meaning max. When a node is selected (right click), one can use the input fields to enter values greater than 1 or 100, until 2 or 200. The curve moves, the image changes, but the node is invisible because it is outside of the curve graph. Is that supposed to be an 'expert mode'?

**Comment by Beep6581** [comment]
Hey

1 was fixed yesterday.
2 seems to apply to all curves, the limit is 200 (or 2 for flat curves) instead of 100 (or 1).

**Comment by Beep6581** [comment]
This patch fixes the issue: https://gist.github.com/f304a28474f1cf015cad

@Hombre57 I guess you may know, what was the purpose of " + axisAdjusters.at(i)->rangeUpperBound"? I tried a bunch of diagonal and flat curves and they all are broken with it and work  correctly without it.

**Comment by Hombre57** [comment]
The range upper and lower bound are the range of the spin buttons when editing points, because all points are in fact set in the 0-1 range internally, it's better to use something like 0-100 for the user. The range might also be -100 <-> +100, or anything that the developer want to set for the purpose of the curve.

The correct fix is to replace rangeUpperBound by rangeLowerBound in the 2 lines that you've modified.
