### ISSUE TITLE
Gtk3 branch, processing settings are lost, something to do with snapshots

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#2914]
1- Open a photo, make some changes, e.g. set a crop, take a snapshot.
2- Open another photo, take a few snapshots (you don't need to change anything), click on any snapshot, e.g. the middle one.
3- Open the first photo again. At first I see the correct preview, but RT straight away starts updating the preview and when it's done the settings are lost.

Branch: gtk3
Version: 4.2.376
Changeset: a4f7864f81e6cce8b2647f26ec053ecb55bbb74f

**Comment by Hombre57** [comment]
I reproduced the error, but I guess that it's not specific to branch Gtk3.

**Comment by heckflosse** [comment]
I could not reproduce it using gtk2

**Comment by Beep6581** [comment]
Cannot reproduce with Gtk2 branch.

**Comment by adamreichold** [comment]
I think the [branch](https://github.com/adamreichold/RawTherapee/tree/fix-snapshot-selection-on-photo-load) should fix as the problem seems to be that changing the image will clear the snapshot list and hence change the selected snapshot, so that the snapshot change handler will insert the processing parameters from the old image into the new image's history.

I just blocked the snapshot change signal as well as the history change signal in the parameter change handler to prevent this from happening. Could there be a case when that handler legitimately selects a snapshot?

**Comment by Beep6581** [comment]
Fix confirmed, will merge in 24 hours if no objections.

**Comment by Hombre57** [comment]
> Could there be a case when that handler legitimately selects a snapshot?

No.

Can be committed for me too.

**Comment by Beep6581** [comment]
Merged, thank you.
