### ISSUE TITLE
missing (or misplaced) .png files

### ISSUE THREAD

**Issue by mjskier** [Beep6581/RawTherapee#2937]
I just installed and tried to play with rawtherapee on a Linux 13.2 machine.
With 4.2.380-34.1.x86_64, a lot of .png are not in the /usr/share/rawtherapee/images directory as expected, but in some lower level directories (like images/Light/actions, images/Dark/actions...) which causes rawtherapee to abort at startup.

miko@linux-48hs:~> rawtherapee /tmp
no mmap
no mmap
RawTherapee, version 4.2.380
WARNING: closing this window will close RawTherapee!

"expanderInconsistent.png" not found!
terminate called after throwing an instance of 'Glib::FileError'
Aborted
miko@linux-48hs:~> cd /usr/share/rawtherapee/
miko@linux-48hs:/usr/share/rawtherapee> find . -name expanderInconsistent.png
./images/Light/actions/expanderInconsistent.png
./images/Dark/actions/expanderInconsistent.png

**Comment by Beep6581** [comment]
I ran into this two days ago for the first time. The reason is that something cleared our Theme= line in the options file, but I don't know what. Have you tried the Gtk3 branch and then the report above is with the Gtk+ 2 branch?

Anyway this patch fixes it
https://bpaste.net/show/7be25429914f
@Hombre57 ok with you to commit to master?

mjskier to continue using RT, just delete the Theme= line from your options file.
~/.config/RawTherapee*/options

**Comment by mjskier** [comment]
Thanks for the quick reply. I'll give it a try when I get back home tuesday.
At least now I know where the configuration file is (I was looking for a
-/.raw*)

Bruno
