### ISSUE TITLE
Problems with colors from some colors

### ISSUE THREAD

**Issue by blandyna** [Beep6581/RawTherapee#2967]
Dear all,

I'm using Ubuntu 14.10 and RawTherapee from PPA.

I have some problems with colors:

1. The Saving from my Nikon D700 and D7100 has to much pink color.  This problem comes with the last update.
2. The view of the RAW file from FujiFilm X30 are wrong. The colors are completly bad and not correctable. The view ist extremly dark. RawTherapee crashed on some of the files.
3. The view of the RAW file from Lumix G70 are completly wrong - the view is blue-gree and not correctable.

Best regards
Blandyna

**Comment by Beep6581** [comment]
Hello

You haven't given the RawTherapee version nor provided the raw files for us to reproduce the problem on.
Please read http://rawpedia.rawtherapee.com/How_to_write_useful_bug_reports
Then upload the raw files + contents of the "Preferences > About > Version" + screenshots + whatever else the link above asks for, and open one issue per problem, don't mix them all in one issue as you have done.

Furthermore, make sure you have read this
http://rawpedia.rawtherapee.com/The_Image_Editor_Tab#Eek.21_My_Raw_Photo_Looks_Different_than_the_Camera_JPEG
and that RawTherapee and your external image viewer are both set to use the same monitor profile.

Closing this.

**Comment by Lucas-naceri** [comment]
Dear all,

I'm using Ubuntu 14.10 and RawTherapee from PPA.

I have some problems with colors:

The Saving from my Nikon D700 and D7100 has to much pink color. This problem comes with the last update.
The view of the RAW file from FujiFilm X30 are wrong. The colors are completly bad and not correctable. The view ist extremly dark. RawTherapee crashed on some of the files.
The view of the RAW file from Lumix G70 are completly wrong - the view is blue-green and not correctable.
Best regards
Blandyna

**Comment by Beep6581** [comment]
Why have you posted the same thing from two different accounts?
