### ISSUE TITLE
Wrong rendering of highlights

### ISSUE THREAD

**Issue by heckflosse** [Beep6581/RawTherapee#2972]
from here: http://rawtherapee.com/oldforum/viewtopic.php?f=1&t=6309
change causing issue: https://code.google.com/p/rawtherapee/source/detail?r=de930#
@atorger : Anders, could you take a look at this Issue?

Ingo

**Comment by iliasg** [comment]
With new measure at raw values I detect the WL of the file with colored highlights is 4094. (All other E-M1 files I checked had a WL of 4095). Even this slight change of WL (4094 vs 4095) solves the problem .. 

camconst.json item for E-M1, WL set at 4080 to be safe on larger deviations

    { // Quality b, missing per ISO samples
        "make_model": "OLYMPUS E-M1",
        "dcraw_matrix": [ 7687,-1984,-606,-4327,11928,2721,-1381,2339,6452 ], // dng d65
        "ranges": { "white": 4080 } // nominal 4095-4094, spread with some settings as long exposure
    },

The above will be included in a maijor update I am readying for the next days ..

**Comment by iliasg** [comment]
Magenta highlights fixed with updated camconst.json. https://raw.githubusercontent.com/Beep6581/RawTherapee/d0cef55aada8e51321d44982a2a8ca258eaa6139/rtengine/camconst.json

link with sample at old RT forum http://rawtherapee.com/oldforum/viewtopic.php?f=3&t=6309#p44131 

@atorger Anders should we expect any changes at highlight clipping before tagging as fixed ?
http://rawtherapee.com/oldforum/viewtopic.php?f=3&t=6309#p44150

**Comment by atorger** [comment]
I have not much time to contribute. I know about one clipping to purple issue though, not necessarily the one reported here though; 

some of the curves we have, like the perceptual and luminance, will not naturally roll off to the whitepoint (1,1,1), but instead very bright saturated colors will have some but not all channels way above 1.0 and then when clipped the color will shift. I've dealt with this in my own DCamProf camera profiling project by having a special clipping function. At some point I should port that over to RawTherapee.
