### ISSUE TITLE
OS X compilation instructions

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#3003]
If you know how to compile RawTherapee for OS X 10.10 and 10.11, please update the compilation instructions:
http://rawpedia.rawtherapee.com/OS_X
Or describe it here and I'll move it to RawPedia.

For reference and lack of better place to post this, OS X .app application bundle build structure:
https://developer.apple.com/library/mac/documentation/CoreFoundation/Conceptual/CFBundles/BundleTypes/BundleTypes.html

**Comment by Beep6581** [comment]
Ref:
https://github.com/Beep6581/RawTherapee/issues/2530#issuecomment-130048597

**Comment by helmi03** [comment]
I only have OS X 10.11 El Capitan machine now, so the clang instruction still same as https://github.com/Beep6581/RawTherapee/pull/2898/files (not sure for os x < 10.10, since I had to compile using clang because gcc build not working on my Yosemite).

Except that for RawTherapee_OSX_10.11_64_4.2.521, https://drive.google.com/open?id=0B81lBx1OzJMsREJoaGdGMnFrN3c, I use clang-3.7 and libomp from macports instead of custom build.

Maybe this is still needed https://github.com/Gui13/linphone/blob/master/README.macos.md#libiconv-hack, based on my previous comment https://github.com/Beep6581/RawTherapee/issues/2713#issuecomment-130066140

**Comment by Beep6581** [comment]
Thank you, I added it to the site.

I don't remember what the stack backtrace was for, could you write a bug report if its still valid?
http://rawpedia.rawtherapee.com/How_to_write_useful_bug_reports

As the instructions are still valid, I will close this issue.

**Comment by Beep6581** [comment]
@helmi03 I ported the guide to RawPedia, please take a look:
http://rawpedia.rawtherapee.com/OS_X

**Comment by Beep6581** [comment]
@heckflosse @adamreichold could you take a look at the patch from http://rawtherapee.com/forum/viewtopic.php?f=1&t=1910&start=2910#p44395 and comment whether it would be fine to automate that with `#if defined(__APPLE__)` or some other solution?

@helmi03 do you still need to use the patch to rtdata/osx/macosx_bundle.sh from http://rawtherapee.com/forum/viewtopic.php?p=44395#p44395 ? If yes, we should update it on our side, no?

**Comment by helmi03** [comment]
@Beep6581 yes, I have to patch rtdata/osx/macosx_bundle.sh. If not patch, an error message popup displayed when run the installed app.
Updated macport packages on my machine, and that patch required for new version pango-querymodules 1.38. Should be an if statement for patch this version only, but I struggle to get correct code.

**Comment by Beep6581** [comment]
1. Do I understand correctly that you get pango from Homebrew, and pango-1.38 no longer ships pango-querymodules, therefore you need a way in a shell script to either check which version of pango is installed or to check whether pango-querymodules exists?
2. Can people using 10.10 or older also use the latest version of homebrew which includes pango-1.38?

**Comment by Beep6581** [comment]
@helmi03 please paste the output of:
`brew list --versions pango`

**Comment by adamreichold** [comment]
@Beep6581 The definition `_RT_NESTED_OPENMP` is already specific to Clang and just equals `_OPENMP` for other compilers, i.e. GCC. So I don't think it would be necessary to add any extra conditional compilation there, we could merge it as it is. But it seems abuse of notation since this does not seem to be nesting in the OpenMP sense of the term.

What I find more interesting is why that particular piece of code fails as Clang 3.7 should fully support OpenMP 3.1 at least. Hence a separate issue with the stack trace (of all threads) and maybe the values of locals should be interesting. Maybe the changes from Google Code issue 409 have something to do with this? But I have a hard time following the various code path w.r.t. the halo-control and edges-only parameters and would defer to @heckflosse as to what is happening exactly here.

@heckflosse Something I found puzzling when reading the code is seeing something like
````
float** buffer = new float*[H];
for(int i=0; i < H; ++i)
    buffer[i] = new float[W];
````
several times, where I would naively expect
````
float* buffer = new float[H * W];
````
to get a contiguous block of memory. Can you elaborate on why it is done that way?

**Comment by Beep6581** [comment]
@helmi03 I just committed a patch which should detect the pango version and not use pango-querymodules for versions older than 1.38.0. I don't have Homebrew or OS X so it's untested - please test and report.

@adamreichold my commit closed the issue, but if you want to use _RT_NESTED_OPENMP unconditionally, or, even better, find and fix the OpenMP issue with Clang, feel free to re-open it.

**Comment by adamreichold** [comment]
@Beep6581 I think a separate bug report by @helmi03 on the issue, including the stack traces would be the best way to go forward with this.

**Comment by Beep6581** [comment]
@helmi03 please confirm that you received the message about opening a new issue with a stack backtrace of the segfault which happens when you compile without this:
```
-#ifdef _OPENMP
+#ifdef _RT_NESTED_OPENMP
```
