### ISSUE TITLE
Wrong crop-factor for Fuji X100 in EXIF

### ISSUE THREAD

**Issue by klayman** [Beep6581/RawTherapee#3047]
Fuji X100 is an APS-C camera (~1.5 crop factor). And this is stated in the .RAF EXIF info:
```
Scale Factor To 35 mm Equivalent: 1.5
Field Of View                   : 54.2 deg
Focal Length                    : 23.0 mm (35 mm equivalent: 35.2 mm)
```
However, converted files have wrong values:
```
Scale Factor To 35 mm Equivalent: 0.8
Field Of View                   : 90.7 deg
Focal Length                    : 23.0 mm (35 mm equivalent: 17.8 mm)
```
The problem also exists in Darktable, as well as in the proprietary Silkypix (bundled with camera), but the crop factor is set correctly in out-of-camera jpgs.

As these values are used as an initial approximation in Hugin panorama stitcher, it would be nice to have the correct field of view out of the box.

**Comment by Beep6581** [comment]
Please upload a sample file to http://filebin.net/ and link it here.

**Comment by klayman** [comment]
Here it is: http://filebin.net/9h16dke3b3

**Comment by Beep6581** [comment]
This is not a problem in RawTherapee nor darktable or anything else. Neither the raw nor the JPEG contain a crop/scale factor. The value you see is calculated by exiv2. Go to exiv2's bugtracker, open an issue with the raw file, and ask them how exiv2 calculates it.
http://dev.exiv2.org/projects/exiv2/issues

Closing.

**Comment by klayman** [comment]
Ok. But are you sure this value is obtained through exiv2? I don't see anything similar in `exiv2 -pa` output.

**Comment by Beep6581** [comment]
You're right, exiv2 doesn't list composite tags, exiftool does.
http://www.sno.phy.queensu.ca/~phil/exiftool/
https://rt.cpan.org/Public/Dist/Display.html?Name=Image-ExifTool

http://owl.phy.queensu.ca/~phil/exiftool/TagNames/Composite.html
This page states for `ScaleFactor35efl`
> (this value and any derived values may be incorrect if the image has been resized)

exiftool shows this from your photo:
```
-File:ImageWidth=2176
-File:ImageHeight=1448
-EXIF:FocalLength=23.0 mm
-EXIF:ExifImageWidth=2176
-EXIF:ExifImageHeight=1448
-EXIF:FocalPlaneXResolution=924
-EXIF:FocalPlaneYResolution=924
-EXIF:FocalPlaneResolutionUnit=cm
-MakerNotes:RawImageWidth=4310
-MakerNotes:RawImageHeight=2870
-RAF:RawImageFullSize=4448x2870
-RAF:RawImageFullWidth=4448
-RAF:RawImageFullHeight=2870
-Composite:ImageSize=2176x1448
-Composite:FocalLength35efl=23.0 mm (35 mm equivalent: 35.2 mm)
```

The Exif data in the image does not match the makernotes. The makernotes are usually more reliable in such a case. This camera has a 12.3 megapixel sensor according to the specs, which is inline with the resolution reported by RawTherapee and with the resolution contained in the makernotes and the RAF tag. Your camera has a 3:2 shooting mode, and one of the three resolutions available in that mode is 2176 x 1448, so now it is clear where the resolution in the Exif data comes from.

Why is the scale factor different? The scale factor is not a metadata tag in the image file, instead it is a composite tag calculated from other tags. In this case, I think it is calculated using FocalPlaneXResolution. 

The camera's sensor has a size of 23.6mm x 15.8mm (though this info is not in the metadata embedded in the image, I got it from the specs).
2176(px) / 2.36(cm) = 922
1448(px) / 1.58(cm) = 916
That's close enough to the reported 924.
924*2.36=2180.64, but even 2180 is not divisible by 8, but 2176 is.

The FocalPlane_Resolution tags in the raw image do not describe the raw image but the embedded JPEG image. These tags are preserved in the image saved from RawTherapee and from other software, and then when you examine the saved image, the composite scale factor is calculated based on wrong data.

What to do about it?
I don't think RawTherapee or any other software can be expected to fix this for you since the raw image does not contain the sensor's dimensions.
* The simplest solution is to switch your camera from 3:2 mode to the full raw mode whatever its called.
* To fix images already taken in the 3:2 mode, you could fix the FocalPlane_Resolution tags in the saved JPEGs:
`exiftool -P -overwrite_original_in_place -EXIF:FocalPlaneXResolution=1816 -EXIF:FocalPlaneYResolution=1816 *.jpg`

**Comment by klayman** [comment]
The thing is - there are no other raw modes for Fuji X100. Full raw only.

And 2176 x 1448 is just the size of the embedded jpg preview, so the "makernotes" values are the actual size indeed. RT-converted files have a bit smaller size of 4302 x 2862 regardless of demosaicing method.

Is it possible to obtain the metadata not from the `File:ImageWidth` but from the `MakerNotes:RawImageWidth`, which translates to the `Raw Image Width` in `exiftool -a -u -g1` output, and save it to the converted file EXIF?
