### ISSUE TITLE
Rawtherapee Project - Git - etc.

### ISSUE THREAD

**Issue by Desmis** [Beep6581/RawTherapee#3058]
Bonjour à tous, et à nouveau excusez mon mauvais anglais...donc pour éviter des incompréhensions je vais m'exprimer en français. Si Hombre, ou quelqu'un d'autre maîtrisant les 2 langues peut me traduire se serait bien.

Je dois d'abord vous demander à tous, notamment à @adamreichold, de m'excuser pour les événements d'hier (3 décembre)....C'est à dire ne pas avoir compris ce que tu demandais !
Mais, j'ai des circonstances atténuantes. Mon anglais étant mauvais, et ma compréhension de « Git » très faible – je suis beaucoup plus à l'aise pour comprendre les formules de la mécanique quantique ou de la relativité générale – m'amènent à faire des bêtises.

Lorsque Hombre me dit (issue3057) « ok, mais il y a eu une demande attachée au PR lui-même », c'est un jargon quasi incompréhensible pour moi. C'est quoi un PR  (Pull Request), bien sûr je sais traduire, mais cela n'apporte rien, donc à quoi cela sert, quand s'en servir? Bien sûr j'ai vu ce bouton vert dans GitHub, et je l'ai même actionné par curiosité...d'où la remarque de DrSlony en issue3055.

Mon propos va être plus général. Depuis le mois d’août, nous avons faits plusieurs migrations, l'une imposée du fait de la fermeture de « Google code », (rappel j'ai été hospitalisé à cette période, et la transition a été difficile) et d'autres sont venues ensuite. 
Certes je n'ai rien contre le changement, bien au contraire, et j'apprécie toutes les nouveautés récentes, mais elles se sont produites, à chaque fois, lors des mes absences : 15 jours début décembre à l'île Maurice , 12 jours fin décembre dans ma famille...(changement vers MSY2)
Et à chaque fois je suis dans l'incompréhension (ou la difficulté) de Git  où comme je l'ai déjà dit l'essentiel est caché dans le détail.  De plus l'architecture avec GitHub est loin d'être évidente...
Il me semble que ces derniers changements étaient dus: a) à une « modernisation du code » (je n'ai rien contre, mais cela a rendu mes branches totalement inopérantes), et b) à une évolution vers GTK3. Pour ce dernier point au delà de passer de 2 à 3...quels sont les finalités et objectifs, que permet de plus GTK3 ?

Ces remarques, m’amènent de manière générale à parler du projet. Certes il est très bien d'avoir chacun son autonomie...c'est le propre du développement libre, mais parfois j'ai le sentiment que les priorités de chacun sont différentes et ou chaque développeur travaille pour son clocher, jouant par moment au « chef de projet »...Il y a même dans certains cas une certaine forme de myopie cognitive...

J'en veux pour témoignage une vielle affaire qui a failli me faire quitter le projet il y a 2 - 3 ans – l’algorithme de Tone-mapping - : j'évoquais qu'il ne fonctionnait pas comme il devrait...il m'a été gentiment dit que tout allait bien...puis ensuite après quelques mois...effectivement cela ne fonctionne pas bien. Certes des améliorations ont été apportées à l'algorithme, mais il est encore insuffisant...

Je citerais un deuxième exemple, la branche « locallab »...J'ai bien compris, qu'on ne pouvait la fusionner comme cela, car nous n'avons qu'un point de contrôle et cela amènera à terme des incompatibilités . Mais le fait d'avoir des points contrôlables à la souris (peut être avec GTK3?) et des calques (??) ne résout en rien le problème de ce qui se passe à l'intérieur. Comment fait-on les transitions ? Comment discerner une surface continue d'une variation ? Etc. Ce sont ces aspects qui sont dans « locallab » et qui me semblent essentiels (bien sûr ils sont à compléter, à travailler je suis encore loin des ex U-point de NX2 arrêté). Mais maintenant mettre à jour « locallab » avec tous les changements intervenus me semble se rapprocher du parcours du combattant, voire quasi impossible:)

En conclusion (provisoire) :
*il me semble manquer dans notre projet, une méta-règle (au sens de la régulation sociale - une règle du jeu), qui permettrait à chacun d'avoir des marges d'autonomie contrôlées, mais ce n'est pas une mince affaire à construire !
*il serait bon d'avoir une meilleure  communication interne, ne faisant pas fi des différences de cultures, d'ages et de langues (nous sommes chacun dans ce projet pour des raisons propres, mais nous devons travailler ensemble)
*ma compréhension de Git va progresser, pas ou peu mon anglais (j'ai été formé..si on peut appeler cela, dans les années 1950 où personne ne le parlait – mes parents parlaient le flamand, pas de TV ou peu, pas de net,...)
*excusez-moi encore pour ma conduite, même si j'ai des circonstances atténuantes 

Jacques

**Comment by paulmatthijsse** [comment]
Hello, following is a short summary of Jacques' post.

First of all I want to apologize to @adamreichold for the things that happened yesterday (December 3). I did not understand what you asked me, due to my bad English and a bad understanding of Git. For me it's much easier to understand formulae in the world of quantum mechanics or relativity theory...

Third alinea (issue 3057): this is a jargon quasi non-understandable to me 

[Following are some examples of why Jacques has some problems with the way the RT team works]

- Things change quite fast: googlecode > github, MSY2, GTK3, what are the goals of this, are there any goals for this?
- Of course it is a good thing that every developer works in an autonome way, but sometimes I have the sentiment that the priorities of the different developers are not aligned
- That means that the branch I'm working on now, locallab, can only be updated in a nearly impossible way! 

Conclusion 
- it seems to me that we need in our project a meta rule (in the sense of social regulation) that gives each developer the margin to operate autonomously within certain boundaries - this is not easy to construct!
- we need a better internal communication to overcome cultural, age and language problems
- I had my education in the 50s and my parents spoke only Flamish, so English is difficult for me 
- excuse me one more time for my behaviour, even when that was due to certain circumstances.

Jacques

**Comment by Hombre57** [comment]
About the Pull Request:

Some developers that do not have commit right can still "fork" the project (i.e. create a clone on their own account) to patch it, and when it's ready, create a Pull Request, i.e. a patch that is created by differentiating the fork to one of the main branch (e.g. master, but it could be gtk3 or any other HEAD). This patch would be stored online, with it's own ID and comment page. When creating the Pull Request, you can add a title, then after creation, add comments to the generated Pull Request thread. This kind of thread is very convenient, because we can add comments directly inside the patch listing, to discuss technical issue.

I'm not sure of that, but I think that pull request automatically evolve to stay up to date with commits added afterwards.

Then when everything is ready, a developer with commit rights will click on the Merge button to merge the PR to the target branch (the one selected when creating the PR).

For developer having commit right, the problem would be almost the same : we could create a Pull Request to comment it directly, then decide to merge it to the target branch either by using the PR's MERGE button, or use your local Git commands to merge, commit and push to upstream (i.e. on the remote server). I'd recommend you to use a GUI to do that.

**Comment by adamreichold** [comment]
I would just like add to one more aspect to @Hombre57's explanation of pull requests:
The style of using independent forks and pull requests does IMHO provide one way of at least partially solving the posed problem of autonomy versus central direction: Developers can work independently in their forks and on any branches they like. When they feel their work is ready for review, they can submit a pull request. (If the original project has moved considerably in the mean time, Git's rebase and merge facilities coupled with a helpful frontend like [Meld](http://meldmerge.org/) usually make merged changes relatively painless.)
This means that very few developers need commit access to the main repository. Those developers that do have such access, can then act as curators taking care of the main directions for development and ensuring that the various contributions fit together and do not interfere which each other.

**Comment by adamreichold** [comment]
Concerning MSYS2, I don't think anybody mandated that we will anybody has to use MSYS2 from now on to build RT on Windows. Basically, there generally knowledge was that there is no recent version of the GCC tool chain available on `win32` systems. Then we found out that MSYS2 actually does provide a very recent (last week saw it update from GCC 5.2 to 5.3) version of these tools and libraries. It also comparatively painless to install and configure and hence it was relatively easy to begin writing up some documentation in RawPedia. I don't much more has happened here besides people trying that out and finding various deficiencies in either the RT code base or its documentation.
Since we only increased the mandated compiler version to GCC 4.9, everybody is still free to use any GCC-based tool chain on Windows that fulfils this requirement. (That change itself is to have support for OpenMP 4.0 and C++11, both of which provide various evolutionary improvements of technologies heavily used by RT and provide various to modernize the code case to make it more maintainable and also more accessible.)

**Comment by Hombre57** [comment]
And for the Gtk3 update, it has been commonly decided to either move to Qt (and that's a lot of changes) or move to Gtk3. No time frame has been given, but the actual Gtk2 library is now very old on Windows (V2.24 if few years old). Of course, you shouldn't change something that is working, but with OS evolving (we are at Win10 now), we must keep our dependencies up-to-date as well on a regular basis. Actually, we support both Gtk2 and Gtk3, but the plan is to officially switch to Gtk3 once it has been adopted by the Linux community, which might be in the first half of 2016 ( @Beep6581 : correct me if I'm wrong ). There is still a lot of job to do to suppress deprecated functions, but it's already in a usable state now, and I'd suggest that all new major feature be done in the Gtk3 branch only (?)

**Comment by gaaned92** [comment]
Regarding GTK3 and 32 bits Windows : GTK3 can be build on WXP, but due to the use of DWMAPI.dll, it cannot be run on XP. It should be ok on vista 32.
I think that devs should, at one point, give up compatibility with very old systems like XP and go ahead with GTK3 .

**Comment by Beep6581** [comment]
@Hombre57 that sounds correct, see http://distrowatch.com/search.php?pkg=gtk%2B&pkgver=3.16&distrorange=InAny#pkgsearch

Windows XP extended support ended in 2014.

**Comment by Hombre57** [comment]
> Je citerais un deuxième exemple, la branche « locallab »...J'ai bien compris, qu'on ne pouvait la fusionner comme cela, car nous n'avons qu'un point de contrôle et cela amènera à terme des incompatibilités . Mais le fait d'avoir des points contrôlables à la souris (peut être avec GTK3?) et des calques (??) ne résout en rien le problème de ce qui se passe à l'intérieur. Comment fait-on les transitions ? Comment discerner une surface continue d'une variation ? Etc. Ce sont ces aspects qui sont dans « locallab » et qui me semblent essentiels (bien sûr ils sont à compléter, à travailler je suis encore loin des ex U-point de NX2 arrêté). Mais maintenant mettre à jour « locallab » avec tous les changements intervenus me semble se rapprocher du parcours du combattant, voire quasi impossible:)

In English :
> I'll take a second example, the « locallab » branch... I've well understood that we couldn't merge it as is, because we only have 1 control point and and in the end, it will result in incompatibilities. But the fact of having control points editable by mouse (maybe with Gtk3?) and layers (??) does not answer to what's behind. How do we make transitions ? How do we differentiate a continuous surface from a variable surface ? Etc. It is aspects that are in « locallab » and that seem to be essential (of course they have to be completed and reworked, I'm still far from the former NX2's U-point). But updating « locallab » to the current master is now next to impossible :)

Well, this is a good example of what we should avoid : starting a new development on your own that is touching a very (I mean VERY) big and overdue feature. Talking about ways to handle that in RT BEFORE starting to code it is more appropriate, because we indeed have to commonly figure out how to handle the pipeline and the GUI to have such a great feature. That's not the issue to talk about it, but yes, we could differentiate 2 different way of making local things :
  1. Having layers + fusion filter
  2. In a single layer, applying a GUI parameter heterogeneously.
If I understand correctly, you started point 2, without taking care of how to handle that so that other tool will benefit such evolution, or in other words, defining a GUI API + something standard in the pipeline. We can't just make brute force coding, i.e. copy/paste a bunch of widgets to other tools, we can't maintain this.

For your reference, it's 2 months now that I'm trying (on a very spare basis, I must admit) that I'm trying to make modification on how to handle widgets in the preview, and I think I finally found something doable in the code that will enable more widgets  in the preview.

I know that DrSlony and maybe Michael gave you a "go" to work on this evolution, but I'm still thinking it's too early.

> Ces remarques, m’amènent de manière générale à parler du projet. Certes il est très bien d'avoir chacun son autonomie...c'est le propre du développement libre, mais parfois j'ai le sentiment que les priorités de chacun sont différentes et ou chaque développeur travaille pour son clocher, jouant par moment au « chef de projet »...Il y a même dans certains cas une certaine forme de myopie cognitive...

In English :
> Those remarks bring me to talk about the project. Of course it's good to all have our autonomy... it's what FOSS is all about, but I sometimes have the feeling that everyone has his own priorities and where each developer work for his "own churche", playing sometime to the « project manager »... There is even in some case a form of cognitive myopia.

Yes, defining priorities is difficult when everyone is free to do whatever he wants. But there's a difference between :
  1. priorities between totally independent features,
  2. technical priorities, where you have to code stage B before being able to code stage C properly, particularly in big features.

I don't think anyone stopped a developer from doing what he's willing to do in situation 1. But in situation 2, it's another subject and I don't understand what is shocking in explaining what "should be" (notice the double quotes ;) ) the successive steps to achieve a goal. And I don't see explaining that as being a « project manager », but rather to avoid loosing time to refactor something that has been initially done as a hack, a functional one but still a hack when what we need is a framework.

J'essaie d'expliquer les choses avec respect, j'espère que ce sera compris comme tel, mais puisque tu demandes des explications... Mon anglais est-il clair pour toi ? Sinon je traduirais.

**Comment by Desmis** [comment]
Ton anglais est suffisamment francisé pour que je le comprenne.

Quelques explications de fond sur mes propos (en français) :
*lorsque je parle de « jouer au chef de projet », je ne vise personne particulièrement, mais chaque développeur y compris moi-même

*lorsque je parle de « myopie cognitive » (pour éviter de parler d'aveuglement), c'est la même chose. Pour illustrer mon propos je prendrais en exemple A.Einstein, homme que j'admire qui a fait des choses considérables, mais qui a fait preuve de myopie cognitive sur des points qui gênaient ses théories. On peut citer la négation des trous noirs et de l'expansion de l'univers (G.Lemaître) ou encore la conception aléatoire de la mécanique quantique (Heisenberg) « Dieu ne joue pas au dès » disait Einstein...L'avenir proche a donné raison aux 2 personnes évoquées.

*Ces 2 remarques m'amènent à formuler ce qu'il y a en conclusion. En effet je ne pense pas que le travail en groupe puisse se contenter – quelque soit les outils – d'échanges via le net. L'incompréhension due à la langue, due à l'écrit, due aux non-dits, due à l'absence de dialogues,... peut amener des conflits (voire par exemple la guerre froide et ce qui se passe actuellement dans le monde). Mais bien sûr on n'en est pas là ! Mais il me semble que des réunions physiques seraient une bonne chose et permettraient de mieux se comprendre, de discuter des incompréhensions.... Je regrette toujours que nous n'ayons pu nous voir il y a quelques temps lors de ton passage en Provence. J'en profite pour inviter chacun des membres de l'équipe projet (y compris toi) à me contacter s'il passe en Provence, nous pourrons échanger autour d'un verre ou d'un repas.

*A propos de la communication interne, je n'ai jamais tant appris que depuis 3 jours. En 3 jours, par vos apports, et mes recherches sur le net (on peut rechercher si on est mis sur une piste), m'ont fait plus progresser qu'en 3 mois. Pour reprendre les propos d'un chercheur : "il faut profiter des événements (incidents, erreurs...) pour apprendre" (individuellement et collectivement) !

*Certes mes propos étaient un peu provocateur (c'était voulu), déclenchant un conflit (petit), mais aboutissant au moins partiellement à une amélioration. La régulation sociale que je cite, comporte 3 phases : « le conflit, la crise », « la négociation », « la règle ». Cette règle ne fonctionne pas en "tout noir" ou "tout blanc", ou pire en "tout gris", mais en une construction (on peut parler de congruence) d'assemblages de règles noires (formelles) et de de règles blanches (autonomes).

Donc je reformule mes conclusions partielles :
*il me semble manquer dans notre projet, une méta-règle (au sens de la régulation sociale - une règle du jeu), qui permettrait à chacun d'avoir des marges d'autonomie contrôlées, mais ce n'est pas une mince affaire à construire !
*il serait bon d'avoir une meilleure communication interne, ne faisant pas fi des différences de cultures, d'ages et de langues (nous sommes chacun dans ce projet pour des raisons propres, mais nous devons travailler ensemble)

**Comment by Beep6581** [comment]
Anything to do here?

**Comment by Desmis** [comment]
These conclusions remain valid. 

No member of RT'project is personally targeted. 

But I think our project is to progress, perhaps with the addition of good technicians (we are few), but especially by two points I mentioned in conclusion.

Do free development of other groups are like us (Gimp, etc.), I think so to see the "external" comments that I read here and there...and it's a shame

Now, following the incident early this year (Retinex merge the branch), this incident really touched me, I would not do more "merge" and let another member assure me...(the history of the case required a feedback)

Conclusion (excuse my bad english)
* It seems to me, to be missing in our project, a meta-rule (in the sense of social regulation - a rule of the game), which allow everyone to have controlled margins of autonomy, but it is not an easy task to to build !
* it would be nice to have better internal communication, not ignoring the differences of cultures, ages and languages (we are all in this project for their own reasons, but we must work together)

If no other comment...you can close :)
