### ISSUE TITLE
Merge master into gtk3

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#3065]
With the recent numerous changes I feel I'm not the right person to perform this "weekly" merge of master into gtk3, especially since it's been a few weeks. @adamreichold @Hombre57 could you do it?

**Comment by adamreichold** [comment]
@Beep6581 I will look into it and present the conflict resolution as a pull request.

**Comment by Hombre57** [comment]
Merging regularly is mandatory but time consuming, considering the quite big change in the code base. Why not making a last 4.2 "stable" version asap then drop it completely ? I don't think it will be a problem if the next stable release will be in 3 months.

**Comment by adamreichold** [comment]
PR #3066 is the result of the merge. Looks expect for the `PopUpCommon` class which should be reviewed since it had significant incompatible changes.

Concerning moving to Gtk+ 3 now, I think it would the right decision from a technical point of view if we can provide appropriate platform support, i.e. reach all users we want to reach. But I also think that there is still much to do in the `gtk3` branch w.r.t. to cleaning up the code and removing uses of deprecated functionality, e.g. the `gtk_thread_enter/gtk_thread_leave` looks like a huge amount of work at a first glance. So IMHO, if we switch and intend to release something based on `gtk3` in three months or a similar time frame, I think we should freeze the current feature set and concentrate on bug fixes, performance and maintainability until then.

**Comment by Hombre57** [comment]
We're that far from a stable Gtk3 branch ?

See also my comment in PR #3066

**Comment by Hombre57** [comment]
@adamreichold I've have some difficulties to pull the changes into my local repo. I've done the steps explained at the bottom of the PR, but can't I don't see conflicts anywhere. I've checked the PopupCommon class. All that I've added is the `void PopUpCommon::setItemSensitivity (int index, bool isSensitive)` function which is in your branch/PR, the rest is your work. So from my point of view on this file, I see my changes and would say it's ok.

**Comment by Hombre57** [comment]
`gtk_thread_enter/gtk_thread_leave` are deprecated for now, but not deleted yet from the API. Do we have to suppress them before the first Release ?

**Comment by Beep6581** [comment]
The merge seems to be working well, thank you!

There is one issue with the monitor profile/intent box, it takes up too much space and is centered.
![scrot_2016-01-07 105126](https://cloud.githubusercontent.com/assets/5844619/12167504/c10a39d2-b52c-11e5-9a29-87fb100062b1.png)

I managed to get it like this:
![Uploading scrot_2016-01-07 104637.png…]()
using this patch:
```
diff --git a/rtgui/editorpanel.cc b/rtgui/editorpanel.cc
index 5f335f6..1dd44c7 100644
--- a/rtgui/editorpanel.cc
+++ b/rtgui/editorpanel.cc
@@ -400,9 +400,15 @@ EditorPanel::EditorPanel (FilePanel* filePanel)
     }
 
     statusBox->pack_start (*progressLabel);
-    iops->pack_start (*statusBox, Gtk::PACK_EXPAND_PADDING, 2);
+    iops->pack_start (*statusBox, Gtk::PACK_SHRINK, 2);
     iops->pack_start (*Gtk::manage(new Gtk::VSeparator()), Gtk::PACK_SHRINK, 1);
 
+    // Monitor profile and intent buttons
+    Gtk::HBox *monitorBox = Gtk::manage (new Gtk::HBox());
+    monitorProfile.reset (new MonitorProfileSelector (ipc));
+    monitorProfile->pack_end_in (monitorBox);
+    iops->pack_start (*monitorBox, Gtk::PACK_SHRINK, 0);
+
     // tbRightPanel_1
     iops->pack_end (*tbRightPanel_1, Gtk::PACK_SHRINK, 0);
 
@@ -453,10 +459,6 @@ EditorPanel::EditorPanel (FilePanel* filePanel)
 
     iops->pack_end (*Gtk::manage(new Gtk::VSeparator()), Gtk::PACK_SHRINK, 0);
 
-    // Monitor profile buttons
-    monitorProfile.reset (new MonitorProfileSelector (ipc));
-    monitorProfile->pack_end_in (iops);
-
     editbox->pack_start (*Gtk::manage(new Gtk::HSeparator()), Gtk::PACK_SHRINK, 0);
     editbox->pack_start (*iops, Gtk::PACK_SHRINK, 0);
     editbox->show_all ();
```
But I can't figure out how to get them to attach to the right end instead of floating there in the middle. If you check with Gtk+ Inspector or by adding borders around the box with CSS, you will see that the monitorBox does not have any empty space, it contains just those two widgets, so it must be iops which is doing that. I suspect this has something to do with the custom way in which the monitor profile and intent widgets are handled, but I don't pretend to understand why pack_end_in is needed or how to make it not add that empty space.

**Comment by Hombre57** [comment]
I'll solve this when back home tonight.

**Comment by adamreichold** [comment]
@Hombre57 The pull request is already the result of merging and resolving the conflicts, so it should be enough to just check it out as you already did. Concerning the above layout issue in the editor panel, I would suggest we merge the PR first if that is the only issue and you fix this on the `gtk3` branch afterwards? (Otherwise, I suspect it will become a back and forth of patches...)

**Comment by adamreichold** [comment]
Concerning whether `gtk3` is stable, it does not have seen widespread use, so I do expect bugs when more people try it out. And the UI feels somewhat slower on my system. I also suspect that we could probably make better use of Gtk+ 3 API which work differently from what we are used to in Gtk+ 2. Concerning `gtk_thread_enter/gtk_thread_leave`, there surely are reasons why this was deprecated (I guess it is related performance), so I do think we should remove it ASAP if `gtk3` is to become the new mainline.

**Comment by heckflosse** [comment]
I confirm the impression that gtk3 UI feels slower than gtk2 UI on my Sabayon laptop.

**Comment by Hombre57** [comment]
@adamreichold Then please commit.
