### ISSUE TITLE
File Save Dialog switches into background - GTK+ 3

### ISSUE THREAD

**Issue by TooWaBoo** [Beep6581/RawTherapee#3075]
Clicking on the button "Save current picture" opens the file dialog window in foreground and switches immediately into the background.

cu TooWaBoo

**Comment by Beep6581** [comment]
This seems to depend on the window manager, at least in Linux. I had the problem long ago in some WM, now I use Awesome and Plasma and it works fine there. Which OS are you on?

**Comment by TooWaBoo** [comment]
@Beep6581 
Windows 10 x64

**Comment by sguyader** [comment]
Ive seen this too, also with the preferences window. But it's not occurring every time.

**Comment by adamreichold** [comment]
@Beep6581 I can currently not reproduce this on Linux using `xfwm4`, but I think the Gtk+ warnings
````
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
````
might be related? Does the following patch
````
diff --git a/rtgui/preferences.cc b/rtgui/preferences.cc
index 84625bd..124cd37 100644
--- a/rtgui/preferences.cc
+++ b/rtgui/preferences.cc
@@ -36,13 +36,13 @@ extern Glib::ustring argv0;
 extern Glib::RefPtr<Gtk::CssProvider> cssForced;
 Glib::RefPtr<Gtk::CssProvider> css;
 
-Preferences::Preferences  (RTWindow *rtwindow) : rprofiles(NULL), iprofiles(NULL), parent(rtwindow)
+Preferences::Preferences  (RTWindow *rtwindow)
+    : Gtk::Dialog (M("MAIN_BUTTON_PREFERENCES"), *rtwindow, true)
+    , rprofiles (nullptr)
+    , iprofiles (nullptr)
+    , parent (rtwindow)
+    , splash (nullptr)
 {
-
-    splash = NULL;
-
-    set_title (M("MAIN_BUTTON_PREFERENCES"));
-
     moptions.copyFrom (&options);
 
     /*
@@ -96,7 +96,6 @@ Preferences::Preferences  (RTWindow *rtwindow) : rprofiles(NULL), iprofiles(NULL
     fillPreferences ();
 
     show_all_children ();
-    set_modal (true);
 }
 
 
````
help for people who can reproduce this? For me, it does remove the message at least...

**Comment by sguyader** [comment]
I wanted to try your patch, but there's an error applying it, I think the version you based it on is not the current one. Should I revert to the older version you used, or will update your patch? The current changeset is d460f5eae18a10b1e6593c9edd8de39333c32132.

**Comment by Beep6581** [comment]
@adamreichold good way of reproducing the problem on environments which are susceptible to it is by editing the options file, change `RawDefault` to anything which doesn't exist, and start RT. A modal window pops up informing you that the default raw profile is missing. On some systems, this modal window appears below the main RT window, and so the user thinks that RawTherapee is frozen because nothing can be clicked.

I tried reproducing it this way in [Awesome](https://en.wikipedia.org/wiki/Awesome_(window_manager)) but it works correctly here. I saw this issue last under KDE4.

**Comment by adamreichold** [comment]
@sguyader The patch applies cleanly to the latest `gtk3` code here, but since copying patches by hand is always error prone, I created [this branch](https://github.com/adamreichold/RawTherapee/tree/fix-preferences-dialog) which contains this as a commit. Maybe you could try that? Thanks! (Note that it changes only the preferences dialog.)

**Comment by sguyader** [comment]
@adamreichold i compiled your branch, when I ran RT the preferences or File save windows stayed on top of the main window, but the bug appeared randomly in the unpatched builds. However, I still saw occurrences of the `Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.` message.

**Comment by adamreichold** [comment]
@sguyader As indicated I did not yet touch the file save dialog, but only the preferences dialog. Did you get the warning when opening the preferences dialog?

**Comment by sguyader** [comment]
I probably didn't express myself correctly, non I didn't get the message anymore when opening the Preferences dialog window, and this window pushed behind the main RT window, so this part is fixed. I just wanted to say, in addition, that the message appeared on the yet-non-fixed File save window (the message appeared only when opening this dialog) which is pushed behind the window when opened first. If you fix this, I think it would be good to commit the change quickly, to improve the usability of the Gtk3 builds.

**Comment by adamreichold** [comment]
@sguyader I hopefully fixed the partial-paste (from the file browser or the profile panel) and the save-as (from the editor window) dialogs and updated the branch. Do you still get the warning anywhere?

**Comment by Beep6581** [comment]
I couldn't reproduce the problem on my current system, but I can confirm that the branch doesn't break anything either - compiles and runs correctly.

**Comment by sguyader** [comment]
@adamreichold I will test in a couple hours, it's carnival time here in the
Caribbean ;)

**Comment by TooWaBoo** [comment]
@sguyader 
This is no excuse :-)

**Comment by sguyader** [comment]
@adamreichold it looks like your fix is good, I don't see the message anymore, and the dialog windows stay in front of the main window. The following image sows that it works, and gives me, I think, the excuse of going to carnival instead of staying home testing RT patches...
![Imgur](http://i.imgur.com/EJ1IRXl.jpg)

**Comment by adamreichold** [comment]
@Beep6581 Are other tests still pending or should I merge then?

**Comment by Beep6581** [comment]
It's been over 24 hours, two have tested, so push and see who shouts :)
