### ISSUE TITLE
Slow response new Gtk3 4.2.643

### ISSUE THREAD

**Issue by EdwardKiefer** [Beep6581/RawTherapee#3077]
I installed latest non Gtk3 build 4.2.582 just for reference , RT startup's in like 4-5sec and once in GUI a pic loads in like 2 sec .
Now I tried 2x installing the latest GTk3 4.2.643 and each time it takes like 20sec to startup and each pic once in GUI takes like 10sec to load .
So today I retry and use debug version , I get same time results but have a bunch of same errors in console . here copy/paste of same error many times .

<rawtherapee.exe:4200>: Gtk-warning **: failed to fetch network location: error opening directory 'C:\program Files\Rawtherapee-4.2.643\network:': No such file or directory..

Hoe that helps , FWIW I only have one HD C:\ , not sure whats going on with network part at end of path in error message.

System= Win7 64bit Pro, i5-3570k, 8gig memory, GTX970 ,1 WD black 500g HD.

**Comment by TooWaBoo** [comment]
Goto <b>C:\Users\*User*\AppData\Local\RawTherapee</b> and open the file "option" in a text editer.
Search for "network". Maybe there is wrong path for an external file or folder.

cu TooWaBoo

**Comment by EdwardKiefer** [comment]
nothing comes up with network , I checked each line even .
here are some paths, I will post here.
[general]
StartupPath=C:\\Users\\Ed\\Pictures\\2015_08_06
DarkFramesPath=C:\\Program Files
FlatFieldsPath=C:\\Program Files

[External Editor]
EditorKind=1
GimpDir=C:\\Program Files\\RawTherapee-4.2.146
PhotoshopDir=C:\\Program Files\\RawTherapee-4.2.146


[File Browser]
RecentFolders=C:\\Users\\Ed\\Pictures\\2015_08_06;C:\\Users\\Ed\\Pictures\\2015_08_02;C:\\Users\\Ed\\Pictures\\2015_09_27;C:\\Users\\Ed\\Pictures\\2015_09_21;C:\\Users\\Ed\\Pictures\\2015_05_10;C:\\Users\\Ed\\Pictures\\2015_03_02;C:\\Users\\Ed\\Pictures\\2014_11_02;C:\\Users\\Ed\\Pictures\\2014_08_13;C:\\Users\\Ed\\Pictures\\2014_08_05;C:\\Users\\Ed\\Pictures\\2014_07_29;C:\\Users\\Ed\\Pictures\\2014_07_31;C:\\Users\\Ed\\Pictures\\2015_05_11;C:\\Users\\Ed\\Pictures\\2015_05_25;C:\\Users\\Ed\\Pictures\\2015_06_13;C:\\Users\\Ed\\Pictures\\2015_07_27;
[output]
LastSaveAsPath=C:\\Users\\Ed\\Desktop


[Profiles]
LoadSaveProfilePath=C:\\Users\\Ed\\AppData\\Local\\RawTherapee\\profiles
RawDefault=${G}\\Default
CustomProfileBuilderPath=
CustomProfileBuilderKeys=0

[Color Management]
ICCDirectory=C:\\Windows\\System32\\spool\\drivers\\color
ClutsDirectory=C:\\Program Files

[Dialogs]
LastIccDir=C:\\Windows\\System32\\spool\\drivers\\color
LastDarkframeDir=\\
LastFlatfieldDir=\\
LastRgbCurvesDir=C:\\Users\\Ed\\AppData\\Local\\RawTherapee\\profiles
LastLabCurvesDir=C:\\Users\\Ed\\AppData\\Local\\RawTherapee\\profiles
LastRetinexDir=C:\\Users\\Ed\\AppData\\Local\\RawTherapee\\profiles
LastDenoiseCurvesDir=C:\\Users\\Ed\\AppData\\Local\\RawTherapee\\profiles
LastWaveletCurvesDir=C:\\Users\\Ed\\AppData\\Local\\RawTherapee\\profiles
LastPFCurvesDir=C:\\Users\\Ed\\AppData\\Local\\RawTherapee\\profiles
LastHsvCurvesDir=C:\\Users\\Ed\\AppData\\Local\\RawTherapee\\profiles
LastBWCurvesDir=C:\\Users\\Ed\\AppData\\Local\\RawTherapee\\profiles
LastToneCurvesDir=C:\\Users\\Ed\\AppData\\Local\\RawTherapee\\profiles
LastVibranceCurvesDir=C:\\Users\\Ed\\AppData\\Local\\RawTherapee\\profiles
LastProfilingReferenceDir=C:\\Users\\Ed\\AppData\\Local\\RawTherapee\\profiles

**Comment by TooWaBoo** [comment]
Hmmm, maybe it's something in your registry. You can use a Reg.Cleaner or regedit to search for outdated entries.

**Comment by heckflosse** [comment]
There's nothing related to RT in registry

**Comment by TooWaBoo** [comment]
My last idea: Check the file "bookmarks" in <b>C:\Users\ [Username] \AppData\Local\gtk-3.0.

**Comment by EdwardKiefer** [comment]
I checked registry, didn't see anything .
On the C:\Users\ [Username] \AppData\Local\gtk-3.0
that folder is empty

**Comment by Beep6581** [comment]
And what if you delete or rename the options file while RT is closed, is it still slow the next time you run it?

**Comment by EdwardKiefer** [comment]
that fixed it, started super fast now, 
Now before I had mult tabed editing option on , I am going to slowly change preference and then compare the two files.
Maybe I will find differeance .

**Comment by EdwardKiefer** [comment]
Ok, compared the files, but don't see any bad settings (have new gtk3 build same preferences), other than theme which old was 21 gray-gray there pretty close.
But I think I know what happened , before installing this version I had a folder with no pictures "2015_05_11" so I manually deleted that from picture library .
Now in the old option file that folder is listed in resent veiwed picture paths .

RecentFolders=C:\\Users\\Ed\\Pictures\\2015_08_06;C:\\Users\\Ed\\Pictures\\2015_08_02;C:\\Users\\Ed\\Pictures\\2015_09_27;C:\\Users\\Ed\\Pictures\\2015_09_21;C:\\Users\\Ed\\Pictures\\2015_05_10;C:\\Users\\Ed\\Pictures\\2015_03_02;C:\\Users\\Ed\\Pictures\\2014_11_02;C:\\Users\\Ed\\Pictures\\2014_08_13;C:\\Users\\Ed\\Pictures\\2014_08_05;C:\\Users\\Ed\\Pictures\\2014_07_29;C:\\Users\\Ed\\Pictures\\2014_07_31;C:\\Users\\Ed\\Pictures\\2015_05_11;C:\\Users\\Ed\\Pictures\\2015_05_25;C:\\Users\\Ed\\Pictures\\2015_06_13;C:\\Users\\Ed\\Pictures\\2015_07_27;

So maybe its trying an find that folder but not there anymore, funny thing the old non gtk3 version worked fine (not as fast as now ) , so not 100% sure .

**Comment by Beep6581** [comment]
@EdwardKiefer did you delete the old options file or rename it? If you still have it, please upload it.

**Comment by EdwardKiefer** [comment]
I renamed them so I have 2 now. what I don't have is the option with new gt3 build that was slow, I have old option but the last was the 4.2.582 .
So I can set the old option, then reinstall 4.2.642 and then I have all 3 (good clean 642, old with 582 and old with 642).

**Comment by Beep6581** [comment]
Both files lead to RT opening as fast as it normally does here, Linux. Cannot reproduce.

**Comment by EdwardKiefer** [comment]
must be a windows thing, its 100% reproducible here

**Comment by TooWaBoo** [comment]
@EdwardKiefer 
I've testet your corrupt option file and RT takes forever to start. After 3 minuntes I had to kill RT.
The CPU was on 23% all the time.

**Comment by EdwardKiefer** [comment]
Ok, funny how older version work.
but good someone else can reproduce so if it come up again, we know problem.

**Comment by Hombre57** [comment]
Is this slow response time happening when switching from one version to another, then restarting RT is fast, or is it on each start of a single version ?

I'm asking because I can see a major difference in the 2 provided options file : MaxPreviewHeight=250 in one file and =400 in the second one.

It means that when switching from one version to the other, RT has to reprocess all thumbnails to the new size. This is a weakness in RT's logic, because in such situation, I'm not sure that it can do it as a background task, but as a blocking task.

Second possible culprit that I can imagine : `LastDarkframeDir=\\` and `LastFlatfieldDir=\\` in one file, and empty in the other one. I don't know how RT react with this kind of path...

**Comment by EdwardKiefer** [comment]
Hombre , no its slow starting and loading pics ever time, no matter how many restarts on new gtk3 version .

**Comment by EdwardKiefer** [comment]
found it.
It was this one that fixes it

ClutsDirectory=C:\\Program Files\\RawTherapee-4.2.642\\cluts

**Comment by heckflosse** [comment]
It's ClutsDirectory=C:\\Program Files in your options file. The folder is scanned recursively to find clut files.

**Comment by heckflosse** [comment]
you've been faster :-)

**Comment by EdwardKiefer** [comment]
ok, not sure what you can do about it.
I can say I don't edit the option file, but I do a lot of updates, when one is available and that is over last 2-3yrs on this system .

**Comment by heckflosse** [comment]
btw: Nice way to crash rt at startup: Set  
ClutsDirectory=
in options file...

**Comment by heckflosse** [comment]
As we don't ship clut files per default we should create an empty clut folder somewhere and let the entry in options file point to it to avoid the crashes and slowdowns. Furthermore (to avoid the crashes) we should check the clut folder in options file.

**Comment by EdwardKiefer** [comment]
Ok, sounds like a plan :)

**Comment by Beep6581** [comment]
Um, wouldn't it be better to not ship an empty CLUTs folder, and to have `ClutsDirectory=` empty until the user changes it? Because consider the vastly different cross-platform installation procedures. Perhaps users on Windows would put CLUTs into some RT subfolder, but not on Linux, where the binary is installed into /usr/bin and the docs, credits, licence and possibly icons to /usr/share, and the most likely place for the CLUTs is somewhere in the user's home folder. If an empty ClutsDirectory= is not good for some reason (why?) then this empty CLUTs folder workaround would need to be created only in Windows.

**Comment by heckflosse** [comment]
@Beep6581 yes, allowing ClutsDirectory= without crash should be enough

**Comment by adamreichold** [comment]
@Beep6581 @heckflosse I could try to work this out, i.e.
* Make sure a non-accessible ClutsDirectory does not crash the program.
* Put an upper bound on the number of directories that will be scanned.

Any suggestions for the maximum number we should allow? Do we prefer depth-first or breadth-first search?

**Comment by adamreichold** [comment]
(Personally, I'd suggest breadth-first search and a limit of search two or three levels deep.)

**Comment by EdwardKiefer** [comment]
I noticed something, using ProcessExplorer , I was trying to see if I saw anything in there when the problem was happening .
But one thing I noticed on both old version an gtk3 version , It looks to me RT is searching all over the place , looks like it just going through everything in program files\xxxx .
Maybe its searching for images with profiles or might be normal, but looks odd .

**Comment by Beep6581** [comment]
@adamreichold our HaldCLUT bundle contains just under 400 files. How about capping it to the first 500 or 1000 compatible results?

**Comment by adamreichold** [comment]
@Beep6581 I would prefer to limit the number of directories searched since for example `C:\Program Files` might contain no CLUT files but a lot of directories to scan.

**Comment by Beep6581** [comment]
We ship 14, so maybe 30?
As a user I would want to get feedback when I hit this barrier, even failing/refusing to set the folder is perfectly acceptable as it would force me to re-think what I'm doing if I had more than the folder limit in that directory.

**Comment by adamreichold** [comment]
We can I actually get the CLUT bundle for testing?

**Comment by sguyader** [comment]
The bundle is [here](http://rawtherapee.com/shared/HaldCLUT.zip), the link is presented in Rawpedia's [Film simulation category](http://50.87.144.65/~rt/w/index.php?title=Film_Simulation).

**Comment by Beep6581** [comment]
I have 80-something more for inclusion from sTi, but that got stalled some months ago.

**Comment by adamreichold** [comment]
Ok, so [here](https://github.com/adamreichold/RawTherapee/tree/fix-cluts-dir-listing) is a branch that should fix the crash on an empty setting and also limit the search for CLUT files to
* maximum recursion depth of 4
* maximum number of directories to 128
* maximum number of files to 4096.

If any of these limits is reached, the model is cleared and the same message displayed as if no CLUT files were found, i.e. the advice to check the settings. If deemed appropriate we could of course also use a separate and more specific message.

**Comment by Beep6581** [comment]
I tested by creating separately 5000 files and 5000 directories, in each case the Film Simulation combobox was reset with the generic message, good. But in each case it took 15 seconds to start RawTherapee with no indication as to what took so long. I think there is a messaging mechanism of some sort (because I nagged for one several times before), e.g. the message window which pops up when the default profile for raw or non-raw photos is missing. Could you use that to notify the user of the problem?

**Comment by adamreichold** [comment]
@Beep6581 I will have to think about that: The problem is that the CLUT files are loaded during the construction of the GUI, hence I cannot just stop and display some GUI element as I am blocking the event loop by already doing the searching there.
One proper solution would probably be to run the search on a separate thread and pushing events into the Gtk+ event loop, but that sounds like a lot of work considering the impact.
Another thing I could try is to mimic what browsers do why synchronous JavaScript that takes a lot of time to execute: After some timeout, I could stop searching and ask the user (using a modal dialog) if I should continue loading CLUT files until the timeout is reached again or stop at this point with the CLUT already loaded.
(In any case, we would need to define some timeout after which I will start to display that message.)

**Comment by heckflosse** [comment]
@adamreichold 'The CLUT files are loaded during the construction of the GUI'? Do you mean 'searched' instead of 'loaded'? IIRC they are loaded on demand...

**Comment by adamreichold** [comment]
@Beep6581 Yes, I mean searched.

**Comment by adamreichold** [comment]
Sorry, I obviously meant to write @heckflosse...

**Comment by adamreichold** [comment]
@Beep6581 I updated the branch with a simple implementation of the confirm-to-continue scheme using a message box, asking for confirmation every 5 seconds. It isn't particularly nice since the dialog will freeze if you ask to continue (as the event loop is blocked again), but I'd say it is actually simpler than trying to find proper limits for the various directory and file counts.

**Comment by Beep6581** [comment]
That's an improvement, but we don't want to nag the user every 5 seconds on every startup - we just need the user to know of the problem and to fix it. How about showing a popup only once after loading takes more than 5 or 10 seconds with the message, "The Film Simulation HaldCLUT folder you pointed RawTherapee to is taking too long to load. Reduce the number of files in that folder or point RawTherapee to an empty one instead.\n\nSee Preferences > Image Processing > Film Simulation"

**Comment by adamreichold** [comment]
@Beep6581 I updated the branch as per your suggestion including the exact wording as the new translation table entry `TP_FILMSIMULATION_SLOWPARSEDIR` which is currently set to the exact wording above.
