### ISSUE TITLE
All File format options in Queue tab are shown

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#3083]
All of the "File format" options in the Queue tab are shown when I open the tab. Only the ones relevant to the chosen output format should be shown.
![scrot_2016-01-11 003100](https://cloud.githubusercontent.com/assets/5844619/12224840/82b8fea4-b7fa-11e5-8654-cf59c4db8002.png)

It fixes itself when I trigger a file format combobox event
![scrot_2016-01-11 003125](https://cloud.githubusercontent.com/assets/5844619/12224842/9853044e-b7fa-11e5-8012-187d14b50d0f.png)

**Comment by Hombre57** [comment]
Yes, that something that I forgot to fix. I've already investigated at the time of the port, but I don't know why it shows everything at first, I wouldn't mind some help from @adamreichold

**Comment by adamreichold** [comment]
@Hombre57 I think the reason is that `RTWindow::RTWindow` calls `Gtk::Widget::show_all` after the initial show/hide combination for the save format panel is done, thereby recursively showing all child widgets (again) including those format options that should be hidden. The [branch](https://github.com/adamreichold/RawTherapee/tree/fix-batch-save-format-visibility) tries to fix this by delaying the initialization of the save format until after that call to `Gtk::Widget::show_all`. Could you have a look at it to determine if you agree with the interpretation?

More generally speaking, I think the way we are currently doing initialization by using constructors to instantiate the object graph, set up UI properties according to the current program state and finally calling `Gtk::Widget::show_all` over and over again is somewhat flawed. IMHO the constructors should only be used to instantiate the widget graph. Then `Gtk::Widget::show_all` should be called in a single place, probably in the main function to recursively show all widgets beginning with the main window. Then setting up the UI properties according to the current (i.e. the initial) program state should be done using the same setters that will be used to change the state later on. This should remove a lot of code duplication and automatically ensure that dependent state is properly set up as events propagate in the same way as they do during normal program execution. (Repeatedly calling `show_all` at various levels of the widget hierarchy which are then traversed recursively each time is probably also not beneficial for our start-up time.)

**Comment by Hombre57** [comment]
Yes, it looks correct. It also build and run fine.

You're right, there's room for a lot of optimization almost everywhere. That's why we talked about a complete rewrite of the code some times ago, but that's a long, very long road, so IMHO, maybe we should "refactor" things here and there, sometimes with big patch to move to a better code, better organized, but this is a long road too. At least, we'll have a working RT while "rewriting the code".

**Comment by Hombre57** [comment]
Oh, and thanks for the fix ! ;)

**Comment by adamreichold** [comment]
@Hombre57 I agree with refactoring a working program to make it a working program with better code. Even though that this will be probably be the longer road in the end, but we can do it piece by piece which fits better with spare time work. Concerning this particular issue, beginning to remove unnecessary calls to `show_all` should be straight forward if tedious.

In the longer run, generally disentangling the interfaces resp. headers to reduce build times and make it easier to refactor would probably also be a net win. Also separating the custom widgets and and having an `rtcommon` library to gather reuseable stuff to simplify the dependencies between `rtengine` and `rtgui` sound interesting to me. But probably the most pressing large-scale issue IMHO is how we will proceed w.r.t. the Gtk+-2 and -3 based implementations. As said before, I would personally argue for going over to Gtk+-3 ASAP but forcing ourselves to spend a significant amount of time on maintenance only.

**Comment by Hombre57** [comment]
+1000
