### ISSUE TITLE
Disable crop adjustment over thumbnail

### ISSUE THREAD

**Issue by TooWaBoo** [Beep6581/RawTherapee#3087]
When an image is open and crop ist activated, it is possible to change the crop in the thumbnail like in the image.
1. Open an image
2. Activate the Crop tool
3. Go back to the thumbnail and try to crop the image.

It happend to me a couple of times that I changed the crop by double clicking a thumbnail.

RT 4.2.670 Gtk3, Win 10 x64

**Comment by heckflosse** [comment]
It's a feature. It's also possible when the image is not open. But I admit that it's a bit annoying that it can happen at a double click...

**Comment by TooWaBoo** [comment]
It doesn't make sense to me. How can I set a crop in the small image?
Try rhis:
1. Move the mouse on the thumbnail until the pointer changes to the crop symbol
2. Doubleclick
3. The pointer now stays with the crop symbol
4. Go to the file browser and move the mouse arround on the screen

You will see, that it changes the crop in the image and you have to click in the thumbnail to stop it.

**Comment by Beep6581** [comment]
It can also cause disaster if you select several photos which have been tweaked and accidentally manipulate the crop in one of the images (e.g. you wanted to select it, but you happened to click it on the crop's edge) - then they all lose their tweaks. I am strongly in favor of getting rid of this feature.

**Comment by heckflosse** [comment]
:+1: to remove this feature

**Comment by sguyader** [comment]
I agree to remove it.

**Comment by heckflosse** [comment]
You can also select a lot of thumbs in file browser and then apply the same crop to all with the crop tool. But I see no sense in doing this

**Comment by adamreichold** [comment]
Just talked with this with someone doing this for a living: She does consider that feature rather useful when long sequences with the same perspective were shot, e.g. when using a tripod and a stationary motif, to apply a uniform crop to a selection of images. Of course, it could also be done using the editor and then partial paste, so this would stay possible even if it is removed from the thumbnail browser, but it would probably be a bit less efficient. She also agrees that this feels like it rather belongs into the editor.

**Comment by TooWaBoo** [comment]
If it's usefull for others, then I suggest add a checkbox to the preferences to switch it on or of.

**Comment by adamreichold** [comment]
(Independently of whether it is useful to do this in the file manager or now, the interactions that somehow "bleed over" from the editor into this perspective are definitely not useful.)

**Comment by adamreichold** [comment]
Having my developers hat back on, I would argue against a user-configurable setting: It will see even less testing this way and probably make the code even more complicated since we have to keep the function and make it possible to disable it. So this opens the possibility for even more strange interaction bugs. I would rather suggest doing some "trading", i.e. making it simple and fast to copy out a crop from the editor to a number of images selected in the file browser should be enough to cover the relevant use cases. The problematic thing of actually having the crop tool available in the file manager could then be removed.

**Comment by Beep6581** [comment]
I shoot concerts, panoramas (bracket stacks) and macro (focus-stacks), each involve often hundreds of shots, and I have never seen a need for this. You can't make a crop based on a small thumbnail anyway, that's what the Editor tab is for, and when it comes to sequences that's what copypasta of profiles is for.

I am also against having this as a user-configurable setting. While I generally am very much for user-configurable settings, this particular one is best removed because it is simply dangerous, and removing it simplifies things.

**Comment by michaelezra** [comment]
My 2c... I regularly copy profile from one thumbnail to many and then quickly reposition the crop in the file browser. This is useful for creating fast draft output to normalize appearance of images that were shot similarly, but not exactly the same. E.g. portrait session, when hand-holding the camera. When showing to the client, normalized output is preferred as it simplifies selection of better candidates. Having ability to do this in the file browser is useful as one can refer to the adjacent thumbnails in the same size and is faster than in editor as image does not need to be opened.

**Comment by michaelezra** [comment]
I suppose, if crop adjustment over thumbnails is enabled only when Ctrl key is pressed, this would work for everyone. Crop re-positioning already requires Shift key, so the danger of its accidental use is mitigated. Explanation of thumbnail cropping can be given in a tool tip. What do you guys thing?

**Comment by TooWaBoo** [comment]
<--- REMINDER --->
This function still drive me nuts

**Comment by Hombre57** [comment]
@TooWaBoo @michaelezra I don't modify the crop from thumbnails neither but can understand that some people find this useful, like @michaelezra. So we could use the middle mouse button to move the crop and avoid mistake ? How would that fit when using a pen device ? Please vote on using middle mouse button OR removing that feature completely.

**Comment by TooWaBoo** [comment]
I vote for removing, but I can live with the middle mouse button.

**Comment by Beep6581** [comment]
One must press Shift to pan the crop. Making Shift required to resize a crop would be a good safeguard too. Removing, middle or shift all have my equal vote.

**Comment by TooWaBoo** [comment]
@Beep6581 
Shift and Ctrl are used to select a bunch of thumbnails and then it could happen that you apply the crop to all selected images.

**Comment by Beep6581** [comment]
@TooWaBoo good point.
Then I vote in order of preference:
1. Remove it.
2. Checkbox to enable/disable thumb crop manipulation.
3. Middle-click.

**Comment by Kildor** [comment]
> Checkbox to enable/disable thumb crop manipulation.
This one. It is usefull feature for fast changing of crop. If someone doesn't need it, he can just not to switch it on.

**Comment by TooWaBoo** [comment]
Anything new?
I disabled this "feature bug" for myself quick and dirty but I would appreciate it if this gets fixed.

filebrowserentry.cc
![filebrowserentry cc](https://cloud.githubusercontent.com/assets/13800920/24154031/58e7d2e6-0e50-11e7-8e5f-4e11127293bb.png)

**Comment by agriggio** [comment]
Ok, so, using my recently-acquired superpowers :-), I went ahead and pushed (what I consider to be) a "proper" fix for this. No custom preferences, no middle-click. I simply extended the behaviour slightly so that it is possible to not have any active tool in the file browser (see screenshot). If you have the hand tool active, the behaviour is the same as before (i.e. you can change the crop). If no tool is active, then you can change nothing. By default, no tool is active. Opinions?
![no-active-tool](https://cloud.githubusercontent.com/assets/11982086/24199216/016ee5ea-0f09-11e7-9b63-cf11f5a1ac21.png)

**Comment by TooWaBoo** [comment]
@agriggio 

This is a great solution. 🥇 👍 
Thanks.

**Comment by sguyader** [comment]
I vote for @agriggio 's solution. It happens to me to use modify the crop on thumbnails.

**Comment by TooWaBoo** [comment]
@sguyader 

It's already done in branch dev. 😁 
Works perfect.

**Comment by Beep6581** [comment]
@agriggio I confirm that your solution works, and it seems clean and simple. +1

**Comment by agriggio** [comment]
ok, then we can close this, can't we?

**Comment by TooWaBoo** [comment]
Yes, we can. I close it.

**Comment by Beep6581** [comment]
@agriggio please include a description of what the patch actually does in the commit message, as "candidate fix for #3087" will require time to open issue 3087 in a browser and figure out what the committed solution was when it comes time to making a changelog or just browsing/grepping the log in general.

**Comment by agriggio** [comment]
@Beep6581 sorry about that. I'll take this into account in the future :disappointed:
