### ISSUE TITLE
Latest CMakeLists.txt stating that "Building requires using GCC version 4.9 or higher" is plain false

### ISSUE THREAD

**Issue by pmo-19** [Beep6581/RawTherapee#3095]
Lines 20/22 of CMakeLists.txt modified last Jan. 8th states that if GNU compiler is used it should be 4.9 or higher.
This statement is false.
I have patched these lines to replace 4.9 by 4.8 used on my system Ubuntu Trusty 14.04 and it is working fine right now ...
If you want to check by yourself you should have a look at my PPA which builds a daily git version of RawTherapee for Ubuntu Trusty, Vivid and Wily (the last 3 supported versions of Ubuntu). Here is the link:
https://launchpad.net/~anton+/+archive/ubuntu/photo-video-apps
Check patch 04-gcc-version.patch

Here is the dump of the About --> Version
Branch: master
Version: 4.2.601
Changeset: 5ff270bf51d16a13147f1849fff0936ce528530f
Compiler: gcc-4 4.8.4
Processor: x86_64
System: Linux
Bit depth: 64 bits
Gtkmm: V2.24.4
Build type: Release
Build flags: -g -O3 -fPIE -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2  -std=gnu++11  -Werror=unused-label -fopenmp -Werror=unknown-pragmas -O3 -DNDEBUG
Link flags:  -Wl,-Bsymbolic-functions -fPIE -pie -Wl,-z,relro -Wl,-z,now -Wl,--as-needed
OpenMP support: ON
MMAP support: ON

**Comment by adamreichold** [comment]
@pmo-19 The statement in the build system does imply that it is not possible to build RT with earlier versions of GCC, it means the it is not supported any more since the project aims to make use of features found only in these newer versions. Of course, you can always patch and build with other compiler versions, it is just that there are no guarantees that this will continue to work, e.g. as soon as we make use of an OpenMP-4.0-specific feature.

**Comment by pmo-19** [comment]
I thought you would move on CMakeLists.txt only when you actually use the new features of GCC 4.9 ?
I thought as well that the spate of new translation po files were the prelude of a coming stable version e.g. 4.3 ?

**Comment by adamreichold** [comment]
@pmo-19 The idea behind requiring GCC 4.9 now and not the lowest version which would actually build was to have this breakage once and stick to that version for some time instead of repeatedly breaking builds as we incrementally increase the GCC version to where we'd like it to be.
Admittedly, this started out as a warning in the build system but then people had FTBS with GCC 4.7 which are clear indication what the problem was as automatic builds systems (Launchpad, OBS) usually ignore such warnings. A compromise could be to warn about anything lower than 4.9 as it is considered unsupported and fail with everything lower than 4.8 as it definitely does not build using 4.7?

**Comment by pmo-19** [comment]
Well, the current situation is already causing FTBFS with GCC 4.8. I think your suggestion of a Warning (may be in capital letters) set in CMakeLists.txt would be better. Anyone looking for a cause in a FTBFS is looking at the log I believe ... If the warning is clearly visible (may be underlined with underscores) then it's easier to get around. I mean in Launchpad it's easy to add a dependence to another PPA like the official Ubuntu PPA build for all GCC versions.

**Comment by adamreichold** [comment]
@pmo-19 The warning for <4.9 and error for <4.8 should be simple to implement, but since that is a policy decision, I would defer to @Beep6581 for that. In any case, I would be glad if you could build using >=4.9 where this is packaged for the distribution (as @mbajor did for example with OpenSUSE).

**Comment by Beep6581** [comment]
@adamreichold relatively, I don't know anything about code, but I can comment on the logic and manpower requirement. The recent changes and cleanup already require minimum GCC-4.8, and you wrote that soon it will require features present only from 4.9 onward, so I see little sense in putting effort to momentarily support GCC-4.8 only to undo it again in the near future. By the time we release the next stable version of RT (I'm counting on three months, as per your comment in another issue), I understand that 4.9 will be required in theory as well as in practice. If my understanding is correct, I'd leave it as it is to ~~encourage~~ enforce testing on a version of GCC which is of interest to us, instead of enabling 4.8 which won't work with the next stable RT, and only lead to more bug reports, ones valid only for 4.8.

Furthermore installing GCC-4.9 is possible in Ubuntu 14.04 and easy to do as explained here http://askubuntu.com/questions/466651/how-do-i-use-the-latest-gcc-4-9-on-ubuntu-14-04

**Comment by adamreichold** [comment]
@Beep6581 Your understanding is correct AFAIU (although it was @Hombre57 who brought up a three month time frame in #3065 for polishing `gtk3` ;-)), so I think we should close this and ask the reporter to build using GCC 4.9?

**Comment by Beep6581** [comment]
I think so. I'll do so :)
