### ISSUE TITLE
Bundle gdb.exe with Debug builds

### ISSUE THREAD

**Issue by sguyader** [Beep6581/RawTherapee#3098]
When a user reports a crash, generally we ask that user to try reproducing the crash with a Debug build and paste here the result of the backtrace. However, simple users easily geel discouraged because not only they have to install a new (debug) build, but also they're asked to install the whole tdm-gcc bundle just to be able to run the gdb.exe found in it.
With the help of @gaaned92, we found an easier solution by simply downloading a standalone gbd executable found  [here](http://www.equation.com/servlet/equation.cmd?fa=gdb) and which seems to work. Both 32 and 64 builds are provided, gaaned92 tried the 32 bits one in Windows XP with success.
I suggest we ask package maintainers for the Windows platform who make Debug builds, to add the relevant gdb.exe file in their bundle. @adamreichold, if we all agree with this, this information should be added in the Windows compilation section in Rawpedia.

**Comment by Beep6581** [comment]
@sguyader if you open a RawPedia account let me know here so I can give you edit permissions.

**Comment by sguyader** [comment]
Well I'm not sure if I can write a clear and grammatically correct article on Rawpedia. If I write something, someone will need to edit it.

**Comment by heckflosse** [comment]
@sguyader I am quite sure you can do it (at least not worse than me) :)

Ingo

**Comment by sguyader** [comment]
OK, so I'll give it a shot!

**Comment by sguyader** [comment]
By the way, I think gdb.exe is released under a GPL license, shouldn't we
say something about it when we distribute the copy in the debug bundles?

**Comment by sguyader** [comment]
@Beep6581 in which section should I add this information in the Windows compiling section? I saw in the Troubleshooting section that it is said gdb.exe should generally be provided with debug builds.
Regarding the license, gdb.exe is released under GNU GPL lincense, I still don't know how to give that information in the RT debug bundles. I think we should at least give the adress of the GNU GDB website where source code can be downloaded (http://www.gnu.org/software/gdb/).

**Comment by Beep6581** [comment]
@sguyader I would put it in a new "Creating a distributable package" section, and check the other sections whether they contain any info which would belong in this new section better. I would start the section off by describing how to create a distributable release build package, and end it with a paragraph on the debuild build package requirements.

As for the licencing situation, it's best to get in touch with the GDB people and ask. The reason is that Wikipedia says GDB is GPL, [this COPYING file](https://sourceware.org/git/gitweb.cgi?p=binutils-gdb.git;a=blob;f=COPYING;hb=HEAD) is GPLv2 and [this COPYING3 file](http://sourceware.org/git/gitweb.cgi?p=binutils-gdb.git;a=blob;f=COPYING3;hb=HEAD) is GPLv3, furthermore their website shows nothing when I ctrl+f for "gpl" or "licen", so who knows what the situation really is.
Finally, every time you run GDB this gets printed:
> Copyright (C) 2011 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

Including source code is also not necessary if we haven't changed it. A link to their homepage should do.

**Comment by sguyader** [comment]
@Beep6581 ok, I started writing something about including gdb in Debug builds. I also registered an account on Rawpedia.

**Comment by Beep6581** [comment]
I gave you edit permissions.

**Comment by sguyader** [comment]
OK thanks, I'll post a first version within the following hour.

**Comment by sguyader** [comment]
@Beep6581 [here](http://50.87.144.65/~rt/w/index.php?title=Windows#Creating_a_distributable_package) is my first contribution. I haven't seen the need to move content from other sections over there, but of course feel free to propose or edit.

**Comment by Beep6581** [comment]
@sguyader looks great! Thank you for the contribution.
