### ISSUE TITLE
Sony α35 SLT-A35 camconst.json support

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#3112]
http://filebin.net/r9qmssj36x
From https://discuss.pixls.us/t/adding-support-for-new-raw-formats-sony-slt-a35/704

**Comment by iliasg** [comment]
Thanks for the effort and the data supplied.
All files at all ISOs and with both NR/no_NR or wide aperture, clip consistently at 16372 so I think we have nothing to change in RT as we use 16300 as safety clipping point .. 
(we just clip the above 16300 values which is negligible (0.007 stops) and in fact  there are only 3 levels there because Sony use 1/32 levels at the top highlight region).

**Comment by Beep6581** [comment]
Already supported, nothing to do - closing.
