### ISSUE TITLE
Post resize LR sharpening corrupts bottom rows of pixels in saved image when radius < 0.6

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#3128]
Sometimes Retinex makes the bottom few rows of pixels either completely black, or as in this case black with a purple line running through it.
http://filebin.net/mlhwzq7hg9
http://rawtherapee.com/shared/test_images/amsterdam.pef

It doesn't happen with all images. I haven't noticed any pattern for how to predict which image it will happen in, but when you find an image it happens in it will do that every time you save. Not visible in the preview at any zoom level.

**Comment by Desmis** [comment]
Hello DrSlony
I have tried pp3
If you deselect  "Resize" in "Transform panel", all is good :)
I think this bug appears, because Retinex is in Process beginning and Resize is not concerned with Preview
:)

**Comment by heckflosse** [comment]
I'll take a look

**Comment by Desmis** [comment]
Ingo
I am impressed by the reaction rate and efficiency :)

**Comment by heckflosse** [comment]
Jacques, this one was easy: You gave the hint with disabling resize. Then I detected that RL-Post-Resize sharpening was enabled. I tried with different radius values (because there are different algorithms for different radius) and detected that it only happens when radius < 0.6 
Then I detected that it didn't happen when damping was > 0, so the only possible candidate for this bug was gauss3x3div :)

Ingo

**Comment by Desmis** [comment]
Thank you for explanation :)
