### ISSUE TITLE
DCP tone curves applied before exposure adjustments

### ISSUE THREAD

**Issue by rogerswb** [Beep6581/RawTherapee#3133]
When using a DCP tone curve, the curve is applied prior to exposure adjustment (during application of color management, actually), rather than at the same time as user defined tone curves and results in exposure adjustments being roughly linear.  This also makes the tone curve almost completely unusable with exposure adjustments.  It appears that the application of the curve should be removed from DCPProfile::Apply and added somewhere after exposure adjustments are made in ImProcFunctions::rgbProc.  If no exposure adjustments are made, photos appear as expected.

I've made some corrections to an older version (4.2.0, I think) which seemed to work properly and wouldn't be too hard to adapt for the current version, and I'd be glad to make these changes myself, but I'm pretty sure that my fix is not the preferred way to get the curve data.  I know that the DCP tone curve needs to be retained beyond when it's applied in the color correction process, and I know it would need to be stored in a ProcParams object, but I don't seem to understand how that data persists (due to partial profiles, I think) and was unable to make this approach work.  

Instead, my fix involved reloading the DCP profile inside rgbProc based on the profile listed in ProcParams::icm.input.  Unfortunately, this means the profile is reloaded every time a thumbnail is rendered or any change to the profile is made.  I'm open to suggestions if anyone has any.

Also, if fast export bypasses color management corrections, then this issue may also be related to issue #2882.

**Comment by Beep6581** [comment]
@rogerswb hey, have you checked master to make sure what you're asking for isn't already the case? 4.2.0 is a year old.

@atorger I have some questions too, related to the above:
1. Scene-referred adjustments should take part before exposure compensation, and output-referred after, correct?
2. Is the DCP curve output-referred? I would guess that it is - its there only to give a look - but then I also read in one of your comments, "If the profile is specifically designed for a curve then colors wouldn't match when used with a linear curve".
3. If I add a curve to the DCP using dcamprof, "`make-dcp (...) -t acr (...)`", is this curve added as just an extra, or is that profile then "specifically designed for a curve", and so if I don't use it then the colors will be off?

**Comment by atorger** [comment]
1. Yes that is correct, at least in the context of DNG profiles.

2. DCP looktable and curve are output-referred, designed to apply a look.

Note however that DNG profiles these days are rarely designed purely like a colorimetric base profile (scene referred) with a output-referred look on top via curve and looktable. To avoid clipping of high saturation colors the base LUT (HueSatMap) may only be used to compress the color gamut to fit within ProPhoto, and then it's stretched back out with the looktable. You can see that in many profiles, and DCamProf does like that per default (you can do it the "pure" way too if you like by using the -E parameter, with the drawback of clipping). It's a bit of a mess really, and if Adobe designed DNG profile format today I think it would look otherwise. But it is the way it is...

3. If you add a curve using DCamProf the looktable (not the huesatmap) is specifically adapted to match the curve. If you don't have any custom look operators the purpose of the looktable is to counteract the effects of the curve (that is do what RT's perceptual curve does, a bit more refined), add gamut compression (if active) and stretch HueSatMap-compressed colors back in gamut (if needed). If you disable the curve, you always need to disable the looktable as well to get sane color, but you can't get sane color if the huesatmap have done clip-avoidance gamut compression. In that case the only way to get sane color is to have all elements enabled. Oh well, the compressed (desaturated) color of the HueSatMap is as correct as it can be while fitting all colors within ProPhoto and can actually be a good starting point to handle artificial light scenes. Clip problems typically occur in narrow band artificial light scenes where strange crazy gamut colors can be generated.

If you want the "pure" profile type with a true colorimetric base profile, and a look added on top you use the "-E" parameter to make-dcp. In the earlier versions this was default but Adobe has stopped making profiles that way, and I noted that the clipping issues are so large that for an robust all-around profile you need to do it the clip-avoidance way so I made it the default.

**Comment by atorger** [comment]
@rogerswb if the DCP tone curve is not applied after exposure correction than something has broken, because it was that last time I checked, I left it that way. It has been quite a while since I looked into the code though so maybe something has broken? Are you sure it's that way? Note that DNG profiles are applied in two stages, first one scene-referred pass with huesatmap which is before exposure correction, and then a second output-referred pass with the looktable and curve, which should be after exposure correction. In older versions of RT everything was applied in the first pass, but that's many versions ago.

The DCP handling should be made according to the DNG specification.

**Comment by rogerswb** [comment]
Well, I did check master before posting, but, rather embarrassingly, I didn't dig into it deeply enough before posting.  I saw DCPProfile::Apply being called in RawImageSource::colorSpaceConversion and jumped to conclusions based on what I'd seen in the old code.  I went back over it in depth just now and realized that I didn't notice the useToneCurve parameter being set to false (which wasn't the case in the older code) thereby eliminating the early curve application, and I also didn't notice the second stage being called in ImProcFunctions::rgbProc.  I'd used a more recent version a bit back and honestly thought it exhibited the same behavior, but I just built master, and it functions as expected.

This does bring up another question though: is there ever a situation where the DCP tone curve should be applied prior to exposure/in the first stage of applying the profile?  From what I little I understand of the DCP spec, and from what I understand of your brief description, it shouldn't be done.  However, it is possible to do so if DCPProfile::Apply is called with useToneCurve set to true.  I've briefly searched the source and haven't found where this actually happens, but if it shouldn't ever be applied in stage 1, then for the sake of clarity and to prevent the possibility of it happening, references to the tone curve should probably be removed from DCPProfile::Apply altogether.

Thanks for such a quick response despite the fact that this was a bogus issue!

**Comment by atorger** [comment]
It's understandable, it's indeed confusing. I've cleaned up the DCP code in stages as the function has changed to align with the DNG specification, but the tone curve parameter has stayed. Yes it should be removed preferably as the tone curve should never be applied in that step. RawTherapee is an old code base and there's some things here and there that is in need of cleaning up and simplified, and some dead code here and there. As people jump in and out of the project (me included) it can degenerate a little like that. It's no big crisis though, I've seen much worse code bases than this :-).

To really clean up stuff one needs a bit longer term involvement. When I do patches now I put most effort in "not breaking stuff that works" and thus generally modify as little as possible, which I think is a good strategy for us seldom-contributors, but has some drawbacks in that one can end up with dead code and dead parameters like that.

**Comment by Beep6581** [comment]
@atorger thank you for that explanation, it was clear and very informative :+1: 

I'll close.
