### ISSUE TITLE
Magenta Hue with propagation color method

### ISSUE THREAD

**Issue by olivier1981** [Beep6581/RawTherapee#3135]
Hi Everybody!
I don't want to submit a new wished feature, but I would like to see an improvement in the Color Propagation highlight reconstruction method.
Indeed, for some photos, when you try to recoverer highlighted clouds it appears a magenta hue in the sky. Beside this recovery function is very powerful, this issue makes it unusable... 
As an example, see the attached .NEF file:
https://drive.google.com/file/d/0B2qmLiaNNMJAOWZkUDRqME56b2M/view?usp=sharing

and the .pp3:
https://drive.google.com/file/d/0B2qmLiaNNMJAVWpISWh6UDBRN28/view?usp=sharing

I put below the jpg file with blue circles around the magenta area:
![sans titre](https://cloud.githubusercontent.com/assets/17065421/12815716/5b72e70e-cb48-11e5-9d87-3cbcbf80d170.jpg)

Is it a known issue? Would it be hard to correct it?
Thanks in advance,
olivier

**Comment by raceviper13** [comment]
I see this issue with my Nikon D5100 as well.  This is particularly evident enabling Flat Frame for vignetting correction with an extreme highlight reconstruction.  Generally the sky can start to become ery pink in areas (pink plus your blue sky is magenta, i guess.) This problem used to be substantially worse, but has received some good attention and is now usable.  However, there is still some work that can be done.  I think that a lot of work was done with other cameras to fix this, but is not entirely fixed with all cameras.

**Comment by heckflosse** [comment]
@raceviper13 When you work whit 'Flat fields' did you try to enable 'Automatic Clip Control' in 'Flat Field Correction'? At least this avoids clipped areas by applying the Flat Field. If the image has clipped highlights before 'Flat Field' it doesn't help.

**Comment by raceviper13** [comment]
@heckflosse usually i am working with clipped highlights prior to applying the flat field.  i will try to remember to look for an example of this sometime.

**Comment by Beep6581** [comment]
The discoloration might appear magenta to a viewer due to the surrounding color, but if you examine it its actually not - e.g. R=86% G=88% B=94%. So there is no magenta coloration problem here, simply a very clipped area which is so huge that color propagation fails to satisfyingly reconstruct. I'd close this issue unless someone wants to play.

**Comment by heckflosse** [comment]
Another point: Colour propagation works quite good when one channel is clipped. When two channels are clipped it often fails. When all three cannels are clipped it fails. In your example file (look at the raw histogram) two channels are clipped.

**Comment by adamreichold** [comment]
@Beep6581 To close or not to close?
