### ISSUE TITLE
"Move to trash" keyboard shortcut doesn't work in OS X 10.11.3

### ISSUE THREAD

**Issue by asvc** [Beep6581/RawTherapee#3141]
_RT version 4.2.521
Changeset: 1650333b2a911e21c2e59bdf889005bff872bf9e
Compiler: clang-mp-3 3.7.0
Gtkmm: V2.24.4
OS X 10.11.3_

Pressing "delete" button on the keyboard while photo is selected in the file browser does nothing.
However, this menu item is labeled with "delete" symbol which is quite confusing:
<img width="539" alt="screen shot 2016-02-08 at 13 17 25" src="https://cloud.githubusercontent.com/assets/300146/12878889/9362c018-cdf9-11e5-824f-3a46224e8ad5.png">

**Comment by asvc** [comment]
Not sure it will help, but here is what returns to the terminal after launch:
```
./rawtherapee
2016-02-08 16:25:36.173 rawtherapee-bin[1648:107725] *** WARNING: Method userSpaceScaleFactor in class NSView is deprecated on 10.7 and later. It should not be used in new applications. Use convertRectToBacking: instead. 

(rawtherapee-bin:1648): GLib-GObject-WARNING **: invalid cast from 'GtkMenuBar' to 'GtkWindow'

(rawtherapee-bin:1648): Gtk-CRITICAL **: gtk_window_add_accel_group: assertion 'GTK_IS_WINDOW (window)' failed
```

**Comment by asvc** [comment]
Kind of sorted, pressing "Fn+Delete" does the trick.

**Comment by Beep6581** [comment]
In OS X apparently Fn+Delete is used to delete text in front of the caret.
The easiest solution would be to change the shortcut key description, but it would be better if we kept that as it is and instead made the actual shortcut work on just "Delete", not "Fn+Delete".

**Comment by ion12** [comment]
The thing is that the Macbook keyboard only has a dedicated "Backspace" button, "Fn+Backspace" is in fact the "Delete" button. This is not an OS X issue, and Macbook users need to get adjusted to that system-wide.
I can confirm that with an external full sized keyboard, with a dedicated "Delete" button, everything works as expected, just like in any other OS.
IMO better to just leave things as they are. If you do want to change the short-cut on OS X to "Backspace", icon should be adjusted as well, from ⌫ to ← 
otherwise it could be more confusing than helpful.

**Comment by Beep6581** [comment]
I love it when problems solve themselves ;)
