### ISSUE TITLE
Retinex, fix some issues and clean code

### ISSUE THREAD

**Issue by heckflosse** [Beep6581/RawTherapee#3143]
I've pushed [a branch to fix retinex Issues and to clean retinex code](https://github.com/Beep6581/RawTherapee/tree/retinex_fix)
@Desmis Jacques, I opened this issue to not hijack your 'newwavelet' branch issue. Please continue discussions of retinex changes to master branch here. It was my fault that I hijacked your issue ;-)

I'll post some additional cleanups tomorrow.

Ingo

**Comment by Desmis** [comment]
@heckflosse 
Hello Ingo
You're one of the people who work at night, not me ...:)
For me no problem with "hijacked other issue"...the key is to have a debate on the subject. And "new wavelet" is also affected by this change !

I tested your new method for "iterative Gaussian blur" (it is a well known problem since the launch of Retinex, and the desire to have very large sigma values - we can say "huge values").

No artifacts generate by this modification :)
What seems clear is that the settings are changed when using mask! it's obvious..

The new method is more deeply on "transmission map".
I think it is better now...to confirm on others images.

Good work.
Thank you

Jacques

**Comment by Desmis** [comment]
@heckflosse 
@paulmatthijsse

When you have completed the next commit, I propose (following Paul's remark) to replace "gain" and "offset" by a curve (flat) ... of course I hope that this will improve the interface and understanding (??). Do you agree ?
:)

**Comment by heckflosse** [comment]
@Desmis 
I had to look what offset is in gui (it's brightness) ;-) Yes, that may improve the interface. Hard to say without trying it. But we'll lose backwards compatibility then, don't we?

Ingo

**Comment by Beep6581** [comment]
As we haven't had a stable release with Retinex yet, backwards compatibility is not a concern.

**Comment by heckflosse** [comment]
@Desmis 
Jacques, if you agree, I'll merge retinex_fix now and continue with cleanup after your modifications

Ingo

**Comment by Desmis** [comment]
@heckflosse 
Ingo, no problem you can merge

I'll replace "gain + offset" actually a function of type NewLum= a*gain*(transm(i,j)-mini) + offset
by NewLum = a*curvegain[transm(i,j)-mini], with in abscissa Transmission_map(i,j) and for Y , gain

I must first changed GUI, then MSR...I hope this w'ill work.
Perhaps I w'll used a combobox with "curve : slider"
:)
Jacques

**Comment by heckflosse** [comment]
Merged

**Comment by Desmis** [comment]
Ok, thank you :)

**Comment by heckflosse** [comment]
Oups, forgot to remove BENCHMARK and BENCHFUN. Jacques, can you remove them with your next commit, please?

**Comment by Desmis** [comment]
No problem :)

**Comment by heckflosse** [comment]
@Desmis Jacques, there is [this loop](https://github.com/Beep6581/RawTherapee/blob/master/rtengine/rawimagesource.cc#L2453) in rawimagesource.cc wich needs a lot of processing time after calling MSR function (about 560 ms for a D800 NEF). I'll include a speedup for this loop (using SSE and some line buffers to precalculate the expensive stuff) which reduces processing time of this loop to about 240 ms at my machine.

Ingo

**Comment by Desmis** [comment]
No problem, see my comment on #3146 
:)

**Comment by heckflosse** [comment]
Closing this one to continue in #3146
