### ISSUE TITLE
16 bit TIFF files limited to 3000x3000

### ISSUE THREAD

**Issue by wooac** [Beep6581/RawTherapee#3212]
I'm trying to convert a 6000x4000 Sony ARW file to a 16-bit TIFF with the fast exporter and the file size appears to be limited to 3000x3000.    It would be useful if this was user settable in preferences.

**Comment by Beep6581** [comment]
@michaelezra hey, any reason there is a limit there at all?
Shall we change it to 10000 w/h?
https://bpaste.net/show/ab677fcefaa4

**Comment by heckflosse** [comment]
@Beep6581 :+1:

**Comment by sguyader** [comment]
If 50 megapixel cameras become more frequent (resolution of about 8700×5800) and with the spread of sensor pixel shifting technology, maybe we should push the limit above 10000x10000?

**Comment by heckflosse** [comment]
The limit is only for 'fast export'. Though I admit, that the current limit of 3000 is too low I see no value increasing it to 10000 (who wants to 'fast export an image of that size?) On the other side, it doesn't hurt to unlimit it....

**Comment by Beep6581** [comment]
I don't use fast export so it makes no difference to me. I don't see a point limiting this though. If a camera shoots 6000px wide shots it's not like downscaling to 3000px will be any faster than downscaling to 5000px, and if someone needs to do that then their need is more important.

Shall we set it to 10000?

**Comment by heckflosse** [comment]
@Beep6581 :+1:

**Comment by michaelezra** [comment]
The original purpose of fast export was to allow quicker exporting of lower resolution image "previews", which are normally files limited to resolution of the display. For that use case 3000px is still generous, although could be increased to 4K or 8K... A resolution limit to fast export was imposed to enforce a higher quality fast export output as during downscaling appearance various artifacts gets minimized (e.g. noise if noise reduction is suppressed, aliasing if faster demosaic method gets selected, etc). Otherwise there is no reason limit resolution.
