### ISSUE TITLE
New DCP camera profile for Sony a6000 (ILCE-6000)

### ISSUE THREAD

**Issue by abrodkin** [Beep6581/RawTherapee#3220]
Hi,

With help of DCamProf and automated script found here (https://discuss.pixls.us/t/easily-generate-dcp-profiles-using-dcamprof-and-this-bash-script/897) I was able to create dual illuminant (daylight/tungsten) .dcp profile for Sony a6000 (ILCE-6000) camera.

Both .ARW files (DSC00481.ARW - daylight, DSC00535.ARW - tungsten) and resulting "Sony ILCE-6000.dcp" are available here http://filebin.net/o6ahb50ro6.

Note that .dcp filename was modified by filebin with substitution of "space" with "underline".
But only "Sony ILCE-6000.dcp"  gets automatically recognized by RawTherapee as a profile for the camera.

**Comment by Beep6581** [comment]
Sorry, could you upload those raw files again please @abrodkin ?

**Comment by abrodkin** [comment]
Reuploaded raw files in the same one filebin tag, so the same link is now valid again.
Let me know if there're any problems with those shots - while I still have cc24 target I may redo something.

**Comment by Beep6581** [comment]
@abrodkin thanks for the quick response! :)

**Comment by Beep6581** [comment]
In both photos the tint value is quite low. In tungsten it's 0.78 and in daylight its 0.83. Could you confirm that the daylight photo had no reflective walls or cars nearby and that you were holding the chart in such a direction that reflected light would not be a problem, and can you confirm that the tungsten shot was taken with a real, clear tungsten lightbulb also in a place where reflected colorful light is not a problem?

**Comment by abrodkin** [comment]
Well as for daylight shot I'm pretty sure it should be OK. I took it in a quite large and open space between buildings with pretty low chances anything colorful to affect the shot (among other things almost everything around was covered with white snow).

As for tungsten I took it on my kitchen - that's the only place where I found a real tungsten bulb (we use "energy-saving" bulbs almost everywhere these days) and it was not super bright (~60W) so I had a hope that walls (which in that case were ~1.5 away from the target) won't impact a lot.

If you think tungsten shot is a no go I'll try to get another shot in better conditions.

**Comment by abrodkin** [comment]
BTW for daylight shot I had my target turned ~45% to the sky (it was pretty cloudy that day, so definitely no direct sunshine). Is that OK?

**Comment by Beep6581** [comment]
They might be fine, because those values aren't conclusive and depend on other stuff, I just wanted to get confirmation. I'll make the DCP soon, today, then we will see the delta E.

"They say" that you're supposed to take them on clear sunny days in the middle of summer bla bla, but in my (admittedly limited) experience this doesn't make much difference, I took ones at midday on overcast days that were identical to clear sky ones, and I took basement shots that were identical to bathroom ones.

I also wonder whether shooting tungsten is the Right Thing To Do nowadays considering compact fluorescent lamps are everywhere... maybe the standard and software should be updated. But then again I suppose CFLs differ more one from another than tungsten bulbs. Then again I don't have a spectrophotometer so I can only guess.

**Comment by abrodkin** [comment]
That all makes sense indeed.

Again I'm pretty sure daylight is a good profile because that one I use in both Raw Therapee and in Darktable as my main color profile for Sony a6000 and results I'm seeing are very satisfying. Still as well as you I don't own precise color metering tools and not even trying to get 100% color accuracy caring more about what looks pleasant to my eyes :)

Tungsten profile I don't use much mostly because I tend to shoot during the day so it might not be as good as the one for daylight. But given results are still visually better than with standard color matrix I'd vote for adding that dual illuminant profile in Raw Therapee. And once there're complaints and better raw shots provided we may get a better profile IMHO.

**Comment by Beep6581** [comment]
Strangely high DE values! But your X-Rite Passport appears to be in great condition. Could it be the winter sun? Or perhaps a new kind of pigment on the color target, if yours is very new? @iliasg what do you think?

[Sony ILCE-6000.dcp.txt](https://github.com/Beep6581/RawTherapee/files/232734/Sony.ILCE-6000.dcp.txt)

**Comment by abrodkin** [comment]
I took another daylight shot this weekend in completely different environment again close to noon and with quite low amount of clouds (which happens not that often in St. Petersburg).
That's the link to that new shot - http://filebin.net/o6ahb50ro6/DSC01408.ARW

I'm wondering if you'll see any significant difference with the previous one.

**Comment by Beep6581** [comment]
This one has lower DE and no glare. Could you update the tungsten shot too? It has glare.
[Sony.ILCE-6000 2016-04-29.dcp.txt](https://github.com/Beep6581/RawTherapee/files/243246/Sony.ILCE-6000.2016-04-29.dcp.txt)

**Comment by abrodkin** [comment]
@Beep6581 Thanks for pinging me. Let me try to get hold of a bright tungsten bulb and do a couple of shots shortly. Are there any deadlines for this to be done? Like release is pending etc?

**Comment by iliasg** [comment]
@abrodkin
I don't have the last sample (01408.arw) as the link expired .. can you make it available ? 

To get less veiling flare (glare) on your shot, you have to 
- take care of any light facing the lens even if it's out of the frame.
- set a scene where the surrounding background of color checker is as dark and neutral as it gets. The first shot you provided (00481) had a bright bacground which got spread all over the frame skewing the measures especially on the dark patches. Maybe there existed a light facing the lens 
- fold back the second page of passport .. it has bright patches which increase the glare on cc24 patches

On the second shot (00535.arw) 
- I see shades at the low regions of the patches as if the light was coming at a large angle. Please take care so that the light is not so far of perpendicular.
- I see there is motion blur !! 
- I see softness and CA which usually come from OOF shots

It doen't help if  you blur the shot .. it skews the measures by spreading the point/line defects (dirt/scratches locally damaged patches) and make removing outliers difficult. Any sane profile builder should remove outliers easilly if they are not blured.

A well exposed shot makes measures more accurate. The 00481.arw was more than 2/3 stops underexposed while the 00535.arw was 1 1/3 underexposed. Please use as referece gray the D4 patch i.e the third darkest from the grey patches (spot measure on it). Because your a6000 possibly underexposes the use of -1/3, 0, +1/3 bracketing will help a bit more ;)

The largest the patches are on the frame the better for accurate measures provided that we don't fall on lens CA and color cast cases. On the 0481.arw the cc24 patches were too small. Generally a 1/3 of width/height coverage is a good rule of thumb (nicelly applied on 00535.arw ;) ) but depending on the lens it can be even larger for good lenses.

**Comment by iliasg** [comment]
@Beep6581 
> "Could you update the tungsten shot too? It has glare.
Sony.ILCE-6000 2016-04-29.dcp.txt"

This does not look like glare but uneven lighting .. if we compare the dark grey D6 with the mid greys D3,D4,D5 the ratios are close to perfect .. D2 starts to deviate (a bit lower) and D1 even lower .. as if the light source was closer to the dark patches ..

**Comment by Beep6581** [comment]
> This does not look like glare but uneven lighting ..

If you say so, I don't remember :)

**Comment by abrodkin** [comment]
@Beep6581 So finally I took another CC24 shot with incandescent bulb. I uploaded it to: https://filebin.net/7c5p8o58hq7bv6sz (see 2017-01-04-A2856-incandescent.arw).

Please take a look at it and let me know if that one is good enough. I tried to make sure LAB values of gray patches are as close as possible to those from http://xritephoto.com/ph_product_overview.aspx?ID=824&Action=Support&SupportID=5159

@iliasg I put 2016-04-24-D65-daylight.arw (renamed DSC01408.ARW) to the same filebin URL.

**Comment by Beep6581** [comment]
Much better DE. The tungsten photo was shot at f/3.5, if you feel like it you could re-shoot at f/8, but I don't expect to see much difference - I'm happy to commit this.

DCP + log:
https://filebin.net/c6zc3eijjba46uyv

Ping @iliasg

**Comment by abrodkin** [comment]
@Beep6581 Well I may indeed try to do another shot even though it is not that simple - I need to go visit that location that (a) has bright tungsten bulb and (b) empty room with almost grey walls... and do it in the evening so no other light source is involved. Also note the lens I used is 50 F1.8 that means 3.5 is already 2 full F-stops away and there's barely any kind of distortion, CA or vignetting could be expected.

That said if existing StdA shot is good enough I'd prefer to keep it.

I'm actually more worried about daylight profile. I was playing with .ICC profiles generated from both shots and profile made of StdA shot looks much better on different pictures compared to one from daylight shot. But that might be as well a matter of taste or lighting conditions of shots I way playing with.

**Comment by Beep6581** [comment]
> I was playing with .ICC profiles generated from both shots and profile made of StdA shot looks much better on different pictures compared to one from daylight shot. But that might be as well a matter of taste or lighting conditions of shots I way playing with.

No problems popped out at me while creating the DCP. As for "looks much better", yes it could be as you wrote, including the effects of your monitor profile, and besides, these are supposed to make colors accurate, not nice.

If you manage to take new shots then we'll take a look at them. I'll commit this one in the meanwhile as it seems good enough and there were no objections..
