### ISSUE TITLE
Canon 700D: overburned pixels are purple colored

### ISSUE THREAD

**Issue by lubernac** [Beep6581/RawTherapee#3248]
Rawtherapee 4.2.905
Win 7 64bit

Overexposed areas (burned) look purple when trying to recover them.

A raw with this issue is here: http://filebin.net/ieopckqlmx

Regards
Luca

**Comment by iliasg** [comment]
Hi lubernac

To correct this we need to fill camconst.json with 700D data. Can you provide very overexposed shots (i.e at +5EV or more so that all pixels are "burned") at all ISOs (integer and intermediate). 
Shoot a featureless homogeneous surface, completelly out of focus at f/4.0 or closer (f/5.6, f/8.0)
We need 
a) a set at normal shutter speed (less than 1 sec) and 
b) a set at the longer possible (30sec) with Long Exposure Noise Reduction set to ON 
If this is too much just upload the b) ..
c) a set of overexposed shots at ISO160 and at normal speed (less than 1sec) with all the available fstops wider than f/3.5 
  
If not we can safelly guess that D650 and D700 share the same sensor and the simple change you can try in your camconst.json file is 

change 
`        "make_model": [ "Canon EOS 650D", "Canon EOS Rebel T4i" ],
`
to
       ` "make_model": [ "Canon EOS 650D", "Canon EOS Rebel T4i", "Canon EOS 700D", "Canon EOS Rebel T5i" ],

`

**Comment by RawConvert** [comment]
@lubernac , be careful what you edit camconst with, Notepad is no good, Notepad++ works, see my post today in the forum...    Andrew

**Comment by Beep6581** [comment]
@lubernac when you upload the files, paste the link in this issue.
As it's already been two weeks without a word, I'm closing this issue, but if you provide the files we'll re-open it.
