### ISSUE TITLE
visible xtrans pattern

### ISSUE THREAD

**Issue by heckflosse** [Beep6581/RawTherapee#3267]
[Here](http://filebin.net/78dyk2lc0e) is an xtrans file which shows a strange pattern in the bright region at the top. First I thought it was caused by the 3-pass xtrans demosaic, but it also appears when I choose fast (bilinear) interpolation.
@iliasg Can you take a look, please? I've no clue what can cause the pattern.

**Comment by iliasg** [comment]
@heckflosse Hi Ingo, it's present at the raw data before demosaic !! A 6X6 pattern .. sadly there is no consistency between horizontal (dark lines are on the 2X2 green groups) and vertical (dark lines are on solitary green pixels).

We see (sometimes) some strange effects when we have strong oblique light (I remember a green imbalance resulting to maze artifacts with a sony (Bayer) at the old forum) ..
http://rawtherapee.com/oldforum/viewtopic.php?f=3&t=6143&p=42813&hilit=maze#p42813
These effects are possibly coming from optical crosstalk .. but this would be logical to give a denser than 6X6 pattern.

BTW the X-100T is among the Fuji models which suffer from aliasing at the Dpreview studio samples ;) . And it (horizontal and vertical structures on x-trans raw) is a phenomenon which has been detected many times .. I called them "candles" at our older discussion .. but it's not only me ..
 http://rawtherapee.com/oldforum/viewtopic.php?f=2&t=4081&p=32806&hilit=maze#p32806
I think it's possible that there is a systematic imbalance in these raw data and a line by line analysis (mean and stdev .per row and per channel) could help to detect if this is happening 
 I asked (and received) some flat fields from Seb but found nothing .. maybe because his X-T1 and X-T10  are different (do not suffer from aliasing at Dpreview studio shots)

**Comment by heckflosse** [comment]
@iliasg Hi Ilias, I uploaded a zip with some flat field shots from X-100T to the filebin link from above.

**Comment by iliasg** [comment]
@heckflosse  At a first try I couldn't detect anything .. but I worked by picking lines by hand .. I have no automated tools for this
