### ISSUE TITLE
"No profile" in Color Management - Input Profile distort non-raw files (both tiff and jpg)

### ISSUE THREAD

**Issue by geoderix** [Beep6581/RawTherapee#3284]
If I choose "No profile" in Color Management - Input Profile than the original image is distorted - histogram shifted to the right and compressed.The image will become bright and nasty white. This is observed for both TIFF and JPG.

Rawtherapee 4.2.830 (win, 32-bit).

Thank you!

**Comment by geoderix** [comment]
If I understand correctly, the option "No Profile" always means that the input image has a gamma value of 1.0. That is, the input image is applied to a gamma value, which is contained in the selected workspace profile.
It is easy to check - if the input image (tiff or jpeg) will have a gamma value of 1.0 (for example, obtained by Rawtherapee function "Save Reference Image for Profiling"), that after conversion into the workspace, the output image will have an acceptable appearance.
Thus, it would be nice if for non-raw files (most of which have already adjusted to the gamma value ~ 2.2), did not apply the value of the workspace gamma
The ideal solution as it seems to me - to add the gamma slider for adjust gamma values that applied to the input image in "No profile" section instead of always using the workspace profile gamma. Setting the gamma value of the input image could be used for raw files in some cases.
I hope that this is not technically difficult to implement.
Thank you!

**Comment by Beep6581** [comment]
@geoderix hey. Could you explain why you need this?

**Comment by geoderix** [comment]
Personally for me
- for raw file - often I see the result that if the image has a saturated color (yellow especially but not only), the transformation into the working color space and then to the color space of the output occurs clipping colors in one or two channels (often in the blue channel, a few less in the red). I do not know it's a bad job LCMS or the problem in something else (an image derived using the function "Save Reference Image for Profiling" does not have these problems). In any case, I can get the image without clipping when using the "No Profile" and choose the less wide workspace, and then slightly increase color saturation.
- for non-raw files - RawTherapee perfectly suited to work with such images - color correction, noise reduction, correction of the tonal range, and so on. Most non-raw images do not have embedded color profiles, some have bad quality embedded color profile. In any case, be able to impose the color values of the input images directly to the selected color of the space - it's a good opportunity. It is often easier to correct bit image than to mess with color spaces and profiles.

In both cases, the presence of the gamma adjustment slider - it would be perfect.

And finally, if the button is present, it should do something useful. Many people use RawTherape to work with a non-raw images.

Thank you!

**Comment by Beep6581** [comment]
1. Completely bypassing the input color profile because otherwise some colors clip is a very bad idea! Use an input color profile to get correct colors, then use RT's tools to bring colors which are out of gamut back into gamut.
Is your monitor color-managed? Is RT and your image viewing program set up to use the monitor color profile? Does your monitor color profile use gamut compression so that the sRGB gamut can fit within the gamut of your monitor? Answering "no" to any of these may mean that you think colors are clipped when they are not.
Easy solution even if you don't use color management: use the CC or CH curve to prevent clipping.
2. RawTherapee works fine with non-raw files. Most non-raw images are in the sRGB space. Some have a color profile, some don't. "Use embedded, if possible" will use the profile embedded in the image if it has one, otherwise it will assume the image is in sRGB space, which is usually correct.
3. "some have bad quality embedded color profile"
Then assign a correct one - use "Custom" and point RT to the profile you want, e.g. to `RT_sRGB.icm`.
Here's a sample file with an incorrect profile applied:
http://www105.zippyshare.com/d/cwzHegfD/8454773/tracteur_i-useembedded_o-NoICM_a-swapped.tif

Will close this unless someone demonstrates a valid need for a gamut adjustment when not using an input profile.

**Comment by geoderix** [comment]
I'm starting to think that your mission is to close as many bugs for any reason. However, problems remain. I imagine ostrich head in the sand. Sorry.
1. There is a problem in the color conversion. Therefore, a large number of images present clipping colors. This problem no one wants to solve. But a lot of talk about the color profile, bit depth conversions, wide working space and blah blah blah. And I think that for raw converter clipping problem is one of the most important. Who needs images permanently clipping blue channel? The histogram shows the clipping - I do not understand how the monitor calibration can affect this. Sorry, this is blah blah blah.
2. I found it strange that you do not want to make it work even better and had more opportunities.
3. It is not always possible - to find the correct profile. Or are you willing to help look for the correct profile?
Would it be better if I start to describe the problem in the forum? Here you do not agree even with the obvious things. Again, I imagined an ostrich with his head in the sand.
Sorry.
Thank you.

**Comment by Beep6581** [comment]
Indeed. There are currently still 433 opened issues, and it took many hours to go through the first half. There can be countless opened quasi-valid issues, but keeping them open doesn't help anyone, it makes a mess. I want to close issues which, like this one, have not been demonstrated to be useful. You haven't supplied a single file to demonstrate the problem, and you act annoyed at me for asking you to convince us why we should spend time coding this for you. At first I was in favor of adding a gamma control (I can code the UI part at least), but it turns out the reasons for requesting it are invalid, or have not yet been demonstrated to being valid, and your "blah blah blah sorry thank you" attitude does not help your case.

**Comment by geoderix** [comment]
I'm not annoyed. I just do not understand why open bug-tracker, if you do not pay attention to the reactions of users. I'm not going to prove anything to you. I do not need your favors. You are not Godfather. You do not look like a Godfather. If you do not want to do, do not do.
And I still believe that my proposal necessary and useful. They significantly extend the capabilities of RawTherapee. But none of my arguments will not affect you. Why should I even try to persuade you to correct obviously wrong logic of the program? Why re-apply 2.2 gamma to non-raw images? For what? You are in a bad mood. Constantly.
What about clipping? Nothing to say? It would be better to fix the problems with the conversion of color space. There's a lot of problems. Not only clipping. Instead of doing great blah blah blah.

As always - sorry and thank you.

**Comment by heckflosse** [comment]
@geoderix I doesn't matter whether you are annoyed or not. Also it doesn't matter if someone (not only Beep6581, also me) had the impression whether you are annoyed or not. But your "blah..." "Godfather..." "bad mood" comments are really not acceptable.
We work hard to improve RawTherapee and are open for constructive criticism. If you're not willing to 'prove' your Issue with an example, then that's not constructive.
And if you continue with "blah..." and "Godfather..." I will block you from this repository as fast as you can read [G. General Conditions 8](https://help.github.com/articles/github-terms-of-service/)

Ingo

**Comment by geoderix** [comment]
@heckflosse Maybe I got a little excited. Sorry.
However, I described in detail the problem. I proposed a solution. I explained where the error. In response Beep6581 demanded some files and closed the bug only because of hostility towards me. And because he believes that it is unnecessary to me. And what files can be useful for what I have described?
And this is not the first time Beep6581 closes bugs without explanation. It seems that Beep6581 more interested in a small number of bugs than the quality of the program.
Nothing personal.
Thank you!
