### ISSUE TITLE
General speedup with first scaling down and then processing

### ISSUE THREAD

**Issue by NextTherapist** [Beep6581/RawTherapee#3287]
RT needs about the same time to process the whole resolution of an image compared to a very small downscaled version. 

Would it be possible to accelerate most of daily use (small web images) with the sequence 
1. scaling down the raw image, 
2. process the result of 1.?

**Comment by Beep6581** [comment]
RT processes the resolution of the image you see in the preview for most tools (example exception: Retinex).
See:
http://rawpedia.rawtherapee.com/Tone_Mapping#Getting_the_preview_to_match_the_saved_image
Point 10: http://rawpedia.rawtherapee.com/Getting_Started#Advanced

Closing.

**Comment by NextTherapist** [comment]
@Beep6581 
Don't understand your citation of point 10: I can accelerate processing of most tools by using a smaller preview. Ok, but I cannot accelerate the end processing if I only want a small sized output image? 
When I only need a 400x300 px output jpg, I have to wait the same time as if I want a full-sized output...

**Comment by Beep6581** [comment]
@NextTherapist resizing is always done at the end of the processing pipeline. Some tools are size-dependent. If resizing happened first, you would need to re-adjust the size-dependent tools if you changes the output size, e.g. if you targetted skin wrinkles using Wavelets and if resizing changed the input image, you would need to re-adjust the Wavelet tool after resizing the image so that it would target the now much smaller wrinkles. That would not be usable.

**Comment by NextTherapist** [comment]
Oh. Ok, a pity.
