### ISSUE TITLE
dcraw 9.27

### ISSUE THREAD

**Issue by heckflosse** [Beep6581/RawTherapee#3302]
I just created [a branch with an update to dcraw 9.27](https://github.com/Beep6581/RawTherapee/tree/dcrawupdate). Happy testing :)

**Comment by sguyader** [comment]
I've just made Windows 64 builds for more testers: http://filebin.net/6zvihkawa2

**Comment by heckflosse** [comment]
@sguyader Sébastien, great, thank you!

**Comment by iliasg** [comment]
@pi99y the main difference is support for new models .. although most of them are covered by the updated camconst.json 
Issues waiting the new Dcraw ..
https://github.com/Beep6581/RawTherapee/issues/2814
https://github.com/Beep6581/RawTherapee/issues/3229 do we still need libraw's code ? 
https://github.com/Beep6581/RawTherapee/issues/3000

We also have to check the behavior on Sony ARW files (compressed and uncompressed) because of some changes regarding ARW Black Level in Dcraw 9.27 (although I think we will be fine ..) 

Check for compatibility with the Fuji firmware 4.0 patch https://github.com/Beep6581/RawTherapee/issues/3137

**Comment by heckflosse** [comment]
@iliasg I added the [absolute black levels](https://github.com/Beep6581/RawTherapee/commit/f86a0811aae311739615530976b3180b02c82ffd) to dcrawupdate branch

**Comment by iliasg** [comment]
@heckflosse OK thanks, nice to have this option
Tomorrow I will update camconst.json manual with the related info together with some more changes ..

BTW merging Dcraw 9.27 fixed the issue of wrongly detected BL for some NEFs ..

**Comment by heckflosse** [comment]
@iliasg and everyone else: Please tell me when you think I can merge dcrawupdate branch into master.

**Comment by iliasg** [comment]
@heckflosse I think you can merge without waiting for updated camconst.json (it's almost ready and I will upload it tomorrow)

**Comment by heckflosse** [comment]
@iliasg ok, I'll make the new dcraw.patch file and merge soon

**Comment by heckflosse** [comment]
I just merged 'dcrawupdate' into 'master'
