### ISSUE TITLE
Highlight recovery with color propagation enhancing purple fringing

### ISSUE THREAD

**Issue by pi99y** [Beep6581/RawTherapee#3311]
Hi,
firstly, let me say that RT is pretty awsome as it is, especially in recovering different kinds of detail.

However, mostly on pictures with sun reflecting off water I see the color propagation grabing the wrong detail (purple fringing) and so filling it with wrong - purple color.

![color_recovery](https://cloud.githubusercontent.com/assets/10639257/15565577/ed1e32a0-231b-11e6-824b-597efc44f423.jpg)
- I know that I can use luminance recovery (but that seems to recover far less - comparing with desaturated color propagation result: the color recovery has more recovered detail for example)
- I have false color supression at maximum setting
- I am unable to reduce the said fringing with "defirnge tool"
  Also, if I would be able to defringe the image with the defringe tool, should it be applied before highlight recovery so that the color propagation doesn't get the wrong colors to work with? Or is it allready so?

Here's the problematic raw: http://filebin.net/gvja68xqcs
Fujifilm X-trans

Improving this would make RT stand out even more and it's already no. 1
Thanks.

**Comment by Beep6581** [comment]
There are several issues here:

Always use the Neutral profile when assessing a problem. Here when you apply Neutral you see straight away that areas which should be clipped white are purple. Setting "Raw White Points > White-point correction" to 1.01 fixes that. @iliasg specializes in finding correct white and black levels, maybe he could help find the right values for camconst.json.

Second, after the clipped areas are turned white, you still see purple fringing on the periphery of each area. This is fixed by setting "False color suppression steps" = 1 and enabling Defringe.

Last, don't use color propagation on such images. By definition it propagates colors into clipped areas, and we know the colors it propagates from, the periphery of each clipped area, suffer from purple fringing.

![scrot_2016-05-26 105148](https://cloud.githubusercontent.com/assets/5844619/15569189/33ec12c4-2330-11e6-8dc5-29552c020469.png)

Issue remains open to investigate the raw white/black levels.

**Comment by iliasg** [comment]
>Here when you apply Neutral you see straight away that areas which should be clipped white are >purple. Setting "Raw White Points > White-point correction" to 1.01 fixes that. @iliasg specializes in >finding correct white and black levels, maybe he could help find the right values for camconst.json

 It's the same problem coming up after RT changed behavior at highlights, here the white clips at 4094 instead of 4095 and it shows .. (it was not  with the old behavior ).
I'll include X-pro-1 at the next camconst.json update setting white level at 4080 for safety. Anyone who wants to test please insert in camconst.json

```
	{ // Quality B
        "make_model": "FUJIFILM X-PRO1",
        "dcraw_matrix": [ 10413,-3996,-993,-3721,11640,2361,-733,1540,6011 ], // DNG_v9.4 D65
        "ranges": { "white": 4080 }
    },
```
BTW I think that if we could make RAW autoCA to work with X-trans (or "Bayerize" x-trans ;) ..) it would help a lot on these frings.

**Comment by pi99y** [comment]
Thanks for the tips on how to aproach such images, I'll testi it right away. And thanks for tweaking the x-pro1 profile. Great!
