### ISSUE TITLE
Add sorting to file browser

### ISSUE THREAD

**Issue by derlu** [Beep6581/RawTherapee#3317]
I'm very happy with rawtherapee, but when I browse images in a directory with many images sometimes it is difficul to find the right one, specially because my RAW files came from different sources and don't have consistent numbering.
If RT had an option to sort the thumbnails by Date, it would make it far more easier to find the images one is looking for. Most users may only want to process the newer images, since the previous ones, most probably were already processed.
Adding a sort button to open a pop-up menu with different sorting options (as DarkTable and ASP have), and offering the option to sort in Ascending or Descensing mode as well would be a really useful feature.

**Comment by morosakubek** [comment]
Yes, it would be very useful.

**Comment by andreas-alexander-42** [comment]
I would like to see that, too. I need sorting by capture date (asc/desc). Hope this is coming soon

**Comment by VitorFrost** [comment]
I wold really appreciate it, because I shoot with two cameras!

**Comment by nikonshooter** [comment]
I would also like the ability to sort thumbnails by date/time.

**Comment by vlnik-belyaev** [comment]
It definitely hurts me because I shoot with two cameras. Also I often reprocess new jpeg versions of the shot inside the body. Those versions share nothing but the time of capture, so  there is no convenient way to compare and to keep best one

**Comment by cogitech2** [comment]
4 years later... I can't find any sort options in the the file browser. Really, really need to be able to sort by date/time!

**Comment by TheRealHerisson** [comment]
This is invaluable. Please can someone reconsider this please?

**Comment by simohno** [comment]
I agree, this would add value to RawTherapee.
Apart from sorting, I also suggested, towards the way of having a "perfect" software, some other improvements concerning the navigator
[in another issue](https://github.com/Beep6581/RawTherapee/issues/5915)

**Comment by maderios** [comment]
I can't use file browser because there is no option to sort files. It's really bad. So, I have to use Digikam to sort, search images and open them in Rawtherapee.

**Comment by atomicflag** [comment]
@maderios Same. Honestly after I started using Digikam in my workflow I'm not so sure I need sorting in RT. I mean, it'd still be nice to have as a feature but Digikam is so much better at managing photo albums than RT or even Darktable, IMO. Digikam for managing photos, Rawtherapee for developing raw files works quite well for me.

**Comment by Thanatomanic** [comment]
While I'm sympathetic to everybody's cause and would like sorting in the file browser myself as well, there's no point bumping this issue. Also, I hope you understand that when you say you've already found a good workflow with Digikam, the incentive for somebody to invest time and effort to recreate the same functionality in RawTherepee is not very large?

**Comment by maderios** [comment]
@Thanatomanic Thanks for your answer. I know developing new function in file browser takes time but what is the purpose of a file manager without a sorting function? When i want to edit raws, I have to launch two softwares Digikam (or other file manager) and RawTherapee but I just need one: RawTherapee.

**Comment by cogitech2** [comment]
Indeed.

Not to mention that the digikam solution does not work for everybody. I have a massive library of raw files and digikam chokes and locks up every time I try to build an initial db, therefore it is useless to me.

My solution thus far has been to use a another full-featured RAW application and forget about RT. It is too bad, though, because I like every other aspect of RT.

Sent with [ProtonMail](https://protonmail.com/) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by maderios** [comment]
@cogitech2 This doesn't concern RawTherapee but you may report your issue here: digikam-users@kde.org. Devs give you answer.

**Comment by atomicflag** [comment]
@Thanatomanic 

> Also, I hope you understand that when you say you've already found a good workflow with Digikam, the incentive for somebody to invest time and effort to recreate the same functionality in RawTherepee is not very large?

Well, I do, that was my intention.

Since this issue is for discussing a new feature, I think it's reasonable to discuss whether this new feature belongs in RT or should be delegated to some other software. Please don't take this the wrong way, I don't mean to be rude or sound entitled, I'm simply providing additional (and hopefully meaningful) input.

RT is certainly lacking in features when it comes to file browsing, but at the same time the README clearly states that "RawTherapee is not aimed at being an inclusive all-in-one program". When I first started using RT I saw it as a DT/Lightroom replacement (and was quite disappointed when it fell short in so many ways), but now I see it more as a dedicated RAW processing tool, which frankly makes much more sense.

Maybe the problem is that people expect RT to have feature parity with Lightroom/DT/Digikam when it's not really the goal of RT? Or maybe RT *should* pivot to becoming an "all-in-one" program? Even if RT adds sorting, there's still a few of features missing from RT's file browser, features that would necessitate some users to use other software. (Timeline, uploading, archiving, finding duplicates, etc.) Should RT eventually adopt these features too?

Still, I agree that a file browser w/o sorting is limited in its usefulness. I wouldn't go so far as to say that it's completely useless, just slightly inconvenient, considering that even OS file selection dialog has sorting. However, circling back to your original question, yes, I think there are more important issues out there.

Just my 2c :slightly_smiling_face:

**Comment by cogitech2** [comment]
As discussed, sorting by date/time stamp (from exif) is a fundamentally essential feature for anyone who shoots events with multiple cameras. Using separate software is not a practical solution in this scenario.

To be specific, here is an example. 2 people shoot a wedding with 2 cameras each. A wedding (like most events) is an event that only makes sense in chronological order. Therefore, before the shoot all cameras have their dates/times synchronised down to the second.

In order to maintain chronology of all images, they are all dumped into the same folder after the shoot. Then the workflow goes like this:

1. Open folder in RAW application
2. Sort by EXIF time/date stamp
3. cull bad images and/or select "keepers"
4. Apply corrections to "keepers"
5. Batch images out to JPEGs, web gallery, (or whatever) while maintaining chronology and renaming to sequential filenames (if desired).

Imagine doing this efficiently if you are forced to do the sorting in DigiKam and then individually open and process each RAW file and save it manually.

Terrible. Even if DigiKam could actually handle my RAW library, it would still be completely inappropriate for the task at hand.

As far as I know, RT is the only RAW application that does not have a "sort by date/time" feature (whether paid or FOSS it is irrelevant) and it should be a dead simple feature to implement.

Just my opinion - to me the application is wonderful, but useless to me without this feature.

Sent with [ProtonMail](https://protonmail.com/) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by Thanatomanic** [comment]
@cogitech2 @coffee-lord @maderios I'll be frank here: there's really no need to explain why this feature is useful, nor that you fail to understand why it's not part of the software. It's all clear, there's just somebody who needs to pick up the coding... 
If you can volunteer or know somebody who can, you're most welcome to contribute.

**Comment by atomicflag** [comment]
@cogitech2

> Even if DigiKam could actually handle my RAW library, it would still be completely inappropriate for the task at hand.

Is DigiKam completely inappropriate? My workflow is very similar to what you described. I do steps 1 thu 3 in DK, then I open the folder in RT, do processing (copy/paste processing profiles as needed), export high-res JPEGs, switch back to DK, do some final touch-ups and upload to flickr/downsize for web from within DK. I do have 2 cameras. I don't see any issues with using 2 programs, other than maybe wasting a few seconds switching back and forth 1 time.

Granted, I don't typically need to see RAWs in chronological order in RT during step 4, but if I did, I would've renamed photos to sequential filenames before I did step 4. Would it save me much time if RT had sorting? Well it would've saved a few clicks sure, but I'm still not convinced that RT *is* the right tool to do all 5 steps, at least not in its current form. DK can import pictures directly from camera/SD (with per-camera rules), cull blurry photos automatically, show (and filter by) the geographical location of the shoot and so much more. The only step that DK isn't ideal for is step 4, the rest are pretty much it's forte.

I doubt that RT will ever be as good at photo management as DK (or it's commercial alternatives). I'm also not sure that RT *should* have photo management capabilities beyond what it already has. Let me put it this way: if lack of sorting in RT is the only thing that prevents you from using RT full time then you might be missing out on some great features that software such as DK has. Being able to sort is a tip of the missing iceberg in RT, adding it would alleviate one pain point but there's still a lot to be desired beyond simple sorting.

If sorting is all that you need and you really don't need or want anything else - that's completely understandable too. What I said earlier doesn't really apply in this case at all. Sorry if I caused any confusion.

**Comment by Arumes** [comment]
@Thanatomanic I read your comment that there's no need to explain, but because most requesters say they want sorting options because they use multiple cameras, I still think my explanation has some value:

It doesn't even require usage of multiple cameras to be useful. Olympus cameras have a strange file naming convention, which means alphabetical sorting is different from sorting by date. Olympus filenames start with a P followed by the MONTH. So even with a single camera my images are in the wrong order, with images from (for example) 2019, 2020, 2021 all mixed up. So I agree with the other requests, sorting options are essential for a good workflow.

Sadly I haven't done any serious coding for about 20 years. I switched from programming to photography...

**Comment by fatso83** [comment]
For someone searching for this, know that the work has been done in  #6449 and is pending merge (not sure if it has gone out of view or what), so high probs of this landing in some future release.
