### ISSUE TITLE
Posterization, clipping and phantom circuits as result of Retinex function

### ISSUE THREAD

**Issue by geoderix** [Beep6581/RawTherapee#3348]
[This one](http://img.photographyblog.com/reviews/pentax_ks2/sample_images/pentax_ks2_01.pef) is Pentax KS-2 raw file from [here](http://www.photographyblog.com/reviews/pentax_ks2_review/sample_images/). And [this one](http://img.photographyblog.com/reviews/pentax_k1/sample_images/pentax_k1_30.dng) is Pentax K-1 raw file from [here](http://www.photographyblog.com/reviews/pentax_k1_review/sample_images/).
Here are the results with default RawTherapee's setting only with enable Retinex with default setting: [Pentax KS-2](http://imgur.com/ZWnsAYg) with [pp3](https://filebin.net/f1gucyf4opqzt4fh) and [Pentax K-1](http://imgur.com/BijS3kD) with [pp3](https://filebin.net/0ou9dl7qgyxsoee6).
Areas in which visible problems I identified with a red marker.
Thank you!

**Comment by heckflosse** [comment]
@geoderix For first and third link I get a 403 (forbidden). Can you please tell us the names of the files in the 'from here' links to allow us reproducing the problem!

**Comment by geoderix** [comment]
pentax_ks2_01.pef
pentax_k1_30.dng

**Comment by heckflosse** [comment]
@geoderix Ok, thank you! For pentax_ks2_02.pef you can get rid off the 'phantom circuits' by using 'Retinex Transmission map'. Just lower the peak point of the curve.
Now looking at pentax_k1_30.dng...

**Comment by heckflosse** [comment]
@geoderix For pentax_k1_30.dng raise the right point of retinex 'gain transmission' curve'

**Comment by geoderix** [comment]
For pentax_ks2_01.pef yes, it works.
For pentax_k1_30.dng - no result. I can not understand how it works. And pink roof remains.
Are you planning to write documentation for the Retinex?

**Comment by heckflosse** [comment]
@geoderix Here's a [screenshot](https://filebin.net/r5gaut32hpz1za90/retinex_case2.png) for pentax_k1_30.dng
About the documentation: There already is a french documentation iirc. But we still have to translate it...

**Comment by geoderix** [comment]
@heckflosse Thank for screenshot. It is work. Retinex - powerful stuff. I am impressed.
It is hard to understand without documentation - a lot of options, but their meaning is not clear.
Thank you!

**Comment by Beep6581** [comment]
> Are you planning to write documentation for the Retinex?

http://rawpedia.rawtherapee.com/Retinex/fr

**Comment by Krzysiu** [comment]
I was writting a new bug report, but it seems to be the same problem. Original links don't work, so I'm not sure if there's some way to get rid of it and if the problem is the same as mine. Here's my report:

Hey! Maybe it's supposed to be like that, i.e. natural effect or wrong combination, but sometimes Retinex causes white, overexposed part of the picture, to be pink. I'm using one camera, i.e. Canon EOS 50D, but as far as I remember it was the same with Konica Minolta A200. 

I don't know exact steps to reproduce it. I just know it happens with Retinex when there are overexposed parts. Changing Retinex method helps, but very rarely and there's no single setting which could help. Sometimes it's some combination, sometimes other.

My system is Windows 7 64 bit, RT version is the stable 5.3, but it happens since version 4. I've tried it on laptop with Linux Mint, everything is different there, but it still happens, so it seems to be platform independent.

Preview: https://imgur.com/a/2d1W4
Photo: http://up.krzysiu.net/RjrA3PRL9p/IMG_6541.CR2
Profile: http://up.krzysiu.net/lvogEoQRyq/IMG_6541.CR2.pp3

**Comment by Beep6581** [comment]
Magenta highlights when using Retinex: https://github.com/Beep6581/RawTherapee/issues/2833#issuecomment-145528569

> With last commite + push ;
> I add 2 methods (Low, Uniform, High, ==>highlight, highlight more) to try to solve "magenta" problem
>
> It is very hard to solve  :
> 1) we use Raw values, with no RGB conversion, no profil...Datas can be out of all !
> 2) for some Images (ex: Amsterdam), datas of sky are already out without Retinex, but seems goods because luminance is at 100...but they are wrong..
> 3) etc.
>
> First method :
> - change algo high, you need probably to change settings (Neighboring pixels) and also increase Raw White-point, while acts on slider "highlight threshold"
>
> Second method
> - as first, more action on RGB channels (Red = master ==> action if red < 100)
> - it is very very empirical, but with some images, can help to solve
>
> But in some image, first and second fails...No miracle :)
