### ISSUE TITLE
RE: VERSION ENDING 936 CRASHES

### ISSUE THREAD

**Issue by sarak3098** [Beep6581/RawTherapee#3431]
When I select all to convert to jpeg to a folder, the software prompts a popup.box the server isn't working and has crshed 

Please sort ir out Asap

**Comment by Floessie** [comment]
First of all: Mind your wording! Noone wants to be shouted on with ALL CAPITAL letters in the header. Noone wants to be stressed by a "Asap". Try to be kind! Bear that in mind if you want people to cooperate.

Now for your problem: You didn't provide any useful data, except "936" which makes me think, you are using the Windows XP version from June, 11th. Please note, that we've fixed some crashed since then, and if you want to report something new, you should use the lastest master branch. So it's likely we've already sorted "ir out".

Instead of pushing us with an unspecific crash, you could have asked for a newer XP version to countercheck if your crash is still present. If so, you could have read "[How to write useful bug reports](http://50.87.144.65/~rt/w/index.php?title=How_to_write_useful_bug_reports)" and provided us with useful information.

Please do so next time. Thanks!

**Comment by sarak3098** [comment]
To whom it may concern

My apologies for that in regards to the firmware I am sorry if I didn't
give the full kernel of the version bt I have windows vista and that's the
latest one

I have stopped using rawtherapee as it is severely slow

**Comment by Floessie** [comment]
> My apologies for that in regards to the firmware I am sorry if I didn't give the full kernel of the version bt I have windows vista and that's the latest one

Apologies accepted. ;) We are kind people willing to help.

> I have stopped using rawtherapee as it is severely slow

Could it be, that you've accidentally downloaded the "debug" instead of the "fast" version? Now that you are actually running Vista, why not give "RT 4.2.1148 for Windows Vista/7/8/10 64-bit - fast" on the download page a try. It's the third item from top.

And please report back, if that fixes your problem, so that we can close the issue or investigate further. Thanks.

**Comment by sarak3098** [comment]
My vista is 32bit for some reason 64bit rate don't work as I checked the
firmware

**Comment by Floessie** [comment]
If you have a 32bit OS a 64bit application will obviously not work.

So, let's ask our project leader:
@Beep6581 Would it be possible to update the Windows XP version or provide @sarak3098 with such a version for testing purposes?

**Comment by Beep6581** [comment]
I don't see sense supporting a 32-bit Vista... but @gaaned92 if you feel like making a new Windows XP 32-bit build, we would appreciate it and I will of course update the build on our website.

As @sarak3098 hasn't provided any useful information whatsoever, and has in fact stopped using RT, I will sort this out ASAP by closing it.

**Comment by heckflosse** [comment]
`Please sort ir out Asap`
I thought 'Asap' is your forname :grin:

**Comment by sarak3098** [comment]
Hi there as I havs thewibdows vista should I download this version
http://rawtherapee.com/releases_head/windows/RawTherapee_WinVista_64_Gtk3_Release_4.2.1148.zip
