### ISSUE TITLE
Fix non-ASCII characters

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#3445]
There were issues in the past with files which used non-ASCII characters, because they weren't using the correct encoding. This issue is to find and convert such characters to ASCII.

**Comment by Beep6581** [comment]
`grep -rnP "[^\x00-\x7F]+" rtengine/* rtexif/* rtgui/*`

Useful: http://www.cogsci.ed.ac.uk/~richard/utf-8.cgi

**Comment by Floessie** [comment]
@Beep6581 IMHO those times are long gone. Today UTF-8 is the norm. I don't want to have my name spelled "Floessie" instead of the correct "Flössie", and I don't see umlauts or accents a problem for anyone using an OS more modern than DOS. And you can even use UTF-8 in code strings when your toolkit is UTF-8 aware. So, what are those issues you are referring to?

I strongly vote for reconsidering this!

**Comment by Beep6581** [comment]
@Floessie when I look at some of those characters in my console and vim, and even here in GitHub, instead of correct characters I see artifacts, for example in the "mus�e d'Orsay.." or in "Observer 2� x2, y2, z2". http://i.imgur.com/iLXRt7e.png
Other characters, like the "o" in your name, are displayed correctly. It is not a font issue.
Those characters caused issues in the very recent past (this year? last year the latest), for example grep would skip some files treating them as binary, and we spent an hour looking for a function that seemed to not exist. It would be great if we all used UTF8-capable editors, but we don't. I replaced them with ASCII equivalents just because its less work and less error prone.

If you feel strongly about having the umlaut in your name, we can do that.

**Comment by Floessie** [comment]
@Beep6581 Oh yes, I do. And I also do care about all those poor creatures on earth, that don't have fully ASCII compatible names and still want to have them in a comment.

The "�" in "mus�e d'Orsay.." is correctly rendered, as the UTF-8 "EF BF BD" sequence is code point U+FFFD (Replacement character). So literally all is fine UTF-8 except that someone failed to convert from another character encoding to UTF-8.

> Those characters caused issues in the very recent past (this year? last year the latest), for example grep would skip some files treating them as binary, and we spent an hour looking for a function that seemed to not exist. It would be great if we all used UTF8-capable editors, but we don't.

I doubt that there are still UTF-8-incapable editors in use. At least in non-US countries. And, well, spending an hour with ignoring grep's warnings about binary files (and without using `-a` in that case) to me seems like a weak argument. We could also switch back to C++98 because not all developers can read C++11 well.

:unamused: Fl**ö**ssie

**Comment by heckflosse** [comment]
@Beep6581 @Floessie iirc we had an issue in past with the ` ` in `#pragma omp` statements. But since we build using `-Werror=unknown-pragmas` at least the [invisible char](http://www.worldstart.com/the-invisible-character/) is not an issue anymore.

example:

without `-Werror=unknown-pragmas`
```
#pragma omp parallel
       ^this is an invisible char, not a space
```
will be silently ignored (at least with older gcc versions)

while 
```
#pragma omp parallel
       ^this is a space
```
works fine

I agree about having `ö` in comments should not be an issue

**Comment by Beep6581** [comment]
The other solution is that we allow all UTF-8 characters, and when someone's patch is found to cause text files to become treated as binary or characters to come out as "�" then they must reconfigure or change the software they use. Is that what you're suggesting?

**Comment by Floessie** [comment]
Exactly! :smile:

Then we could also change "mus�e d'Orsay.." to "musée d'Orsay.." or "N�" to "Nº", and everthing is fine if we obey to use UTF-8 (and not Latin-1 or other deprecated encodings). Should be doable. At least, we've already proven to have UTF-8-only code, as the "�" was in fact UTF-8. :wink:

**Comment by Beep6581** [comment]
Is this satisfactory?
https://gist.github.com/c7327285aa27a1e482fa9f33b2d108f2

I don't see a point replacing "Number" with "Nº", unless "Nº" means something different, in which case it would be better to explain the difference.

**Comment by Floessie** [comment]
> I don't see a point replacing "Number" with "Nº", unless "Nº" means something different, in which case it would be better to explain the difference.

You're right. It was just an example.

> Is this satisfactory?

Absolutely!

Mörgan and Ingö, you rock! :metal: 

Best
Flössie

**Comment by Floessie** [comment]
I came across a very well-written [page](http://utf8everywhere.org/#faq.literal) on UTF-8 that explains a lot. Just FYI, not to warm this old issue up.
