### ISSUE TITLE
Travis CI - Automatic build test of pull requests and new branches

### ISSUE THREAD

**Issue by heckflosse** [Beep6581/RawTherapee#3451]
@Beep6581 @Desmis @Floessie @Hombre57 @michaelezra 
What's your opinion on using [this](https://travis-ci.org/)?

Ingo

**Comment by Hombre57** [comment]
@heckflosse I don't understand what it is :confused:  What's the benefit of this ? How much time does it cost ?

**Comment by heckflosse** [comment]
@Hombre57 I don't know how much time it costs. I guess it will save some of our time because it detects build errors on other architectures or OS (like OSX) before we detect it.

**Comment by Hombre57** [comment]
Then yes, it should be useful, why not ?

**Comment by heckflosse** [comment]
@Hombre57 Have a look at the [CImg commits](https://github.com/dtschump/CImg/commits/master)

Each commit has a check (green or red) which tells you whether it built fine or not.

**Comment by Desmis** [comment]
I am not at all a "code specialist", but I think, if it is easy to use (for me), that we can go in this way :)

**Comment by Floessie** [comment]
I've not yet tried Travis, but I think CI is a really good idea! Nowadays it's often @mbajor who has to report build failures. Would be cool, to have that automated, and a lot of projects on GitHub make use of it. I recently found out, that my beloved [uncrustify](https://github.com/uncrustify/uncrustify) moved to GitHub and supports this, too.

@Desmis 
> I am not at all a "code specialist", but I think, if it is easy to use (for me), that we can go in this way :)

As I understand it, it's a web service, and we only have to add an appropriate `.travis.yml` configuration file to the base of our project (plus register RT somehow). It's not something you as a developer have to care about on your installation. It can be configured so that you get a mail alert, if something you committed doesn't build.

Best
Flössie

**Comment by heckflosse** [comment]
@Desmis We (maybe @Beep6581 and I) have to setup it once. Then it should work automatically.
Assume you commit some new stuff and forgot to add one source file. Then you can see a bit later that it didn't build.

**Comment by Beep6581** [comment]
I'll add it.

**Comment by Beep6581** [comment]
Quick guide to Travis:

- If your commit compiles, no email notifications.
- If your commit does not compile, you get a notification via email.
- See the build status by looking at:
  - the commit log on GitHub https://github.com/Beep6581/RawTherapee/commits/
  - the branch list on GitHub https://github.com/Beep6581/RawTherapee/branches
  - IRC http://rawpedia.rawtherapee.com/IRC https://i.imgur.com/JN8MuVa.png

**Comment by Floessie** [comment]
@Beep6581 
> Should I add -Wno-deprecated-declarations?

I'd say: Yes. At least for gtkmm-2.4 based branches. Did a quick check: We don't use `std::auto_ptr<>`.

Thanks for your efforts!

**Comment by Beep6581** [comment]
Done.
Ingo agreed to `-Wno-deprecated-declarations` and merging in IRC. Branch `travis` deleted (because its commit history is messy - the only way I know of to test the .travis.yml file is by committing a change).
Issue stays open for `gtk3` branch use.

**Comment by heckflosse** [comment]
I just pushed a [change](https://github.com/Beep6581/RawTherapee/commit/c7cf196ae15c11f8ff169da98626d76712eb6d52). Works fine :+1:
