### ISSUE TITLE
Tone curve histogram ignores DCP tone curve

### ISSUE THREAD

**Issue by pi99y** [Beep6581/RawTherapee#3512]
Hi,
the (background) histogram of the "Exposure > Tone curve" ignores the tone curve of the "Color management > DCP > tone curve" while the "main histogram" reflects the DCP's tone curve correctly.

I don't see how this could be a feature so I'm filing it as a bug.

![hitogramdcponoff](https://cloud.githubusercontent.com/assets/10639257/20552766/65cfff10-b14e-11e6-88db-8ff6fe9d4a67.jpg)

Current Ubuntu daily build, master, bc85236ee916dab71376252823e91e4934089171

**Comment by da-phil** [comment]
I already opened an [issue](https://github.com/Beep6581/RawTherapee/issues/3016) some time ago because of the very same reason, but the developers seem to desire this behavior although I agree with you, it's not intuitive because you need to see the "real" histogram as a "optical feedback" for tuning the tonecurve. I also want this histogram to reflect on all changes, otherwise tuning the tonecurve is more like guessing without proper feedback on the actual image state.

**Comment by heckflosse** [comment]
It's not possible to reflect all changes in tonecurve histogram. There are steps behind tonecurve which of course can not be reflected in the histogram before tonecurve. Nevertheless it should be possible to build the tonecurve histogram exactly before the tonecurve is applied. That would reflect dcp lookup table and some other stuff as well (Shadows/Highlights and Saturation for example which currently are also not reflected in tonecurve histogram though they are applied before tonecurve)
I'll see, what I can do

Ingo

**Comment by heckflosse** [comment]
I was wrong about Saturation. But for dcp lookup table and Shadows/Highlights I will create a new branch soon

**Comment by heckflosse** [comment]
@pi99y @da-phil Please test the histtonecurve branch

**Comment by heckflosse** [comment]
@da-phil Thanks for testing. Though I don't know if my changes will go into rt 5.0. At least they should go into rt 5.1

**Comment by heckflosse** [comment]
@Hombre57 and I agreed to merge this into master, which I just did :)

**Comment by Hombre57** [comment]
:+1:

**Comment by pi99y** [comment]
@da-phil @heckflosse That was fast! Great news guys, thank you!

**Comment by da-phil** [comment]
@heckflosse that's nice, thanks!
