### ISSUE TITLE
Pentax K1 file in APS-C mode has wrong raw crop

### ISSUE THREAD

**Issue by heckflosse** [Beep6581/RawTherapee#3519]
Pentax K1 files in APS-C mode have wrong raw crop. There's a coloured vertical line at right border.
[Pentax K1 APS-C file](https://filebin.net/9ckzonefrjvxi2cl)
The file is a pixelshift file. I don't know if that matters. The issue is reproducible in master branch which reads only the first frame of that file and also in pixelshift branch (tried with all 4 frames).

@iliasg Do you have an idea?

**Comment by iliasg** [comment]
A few things go wrong with this

- Dcraw.cc reads the size of the (full uncropped) raw_frame then applies raw_crop. 
In camconst.json we have defined only the FF raw crop so here we have
raw_size = 4832x3238
raw_crop in camconst.json is "raw_crop": [ 6, 18, 7376, 4932 ],
DNG raw_crop tag gives 18 0 3238 4832 (vertical first ) which is translated in camconst.json 
"raw_crop": [ 0, 18, 4832, 3220 ], in absolute size or [ 0, 18, 0, 0 ] in relative
RT (used to crash in such cases some time ago) but now just clips at the raw_size but looks like it missed the left_border (6) so tries to fill the 6 missing columns .. Demosaic cuts 4 of them and the remaining is 2 garbage columns at the right .. 

- Dcraw has no raw_crop data for K-1 

- The DNG raw crop tag should have higher priority than camconst.json if we (or Dcraw.c) has no related `adobe_coeff (make, model) `.. in dcraw.cc .. which is non existent in current dcraw.cc 
I thought that this is the case (DNG has higher priority) and this is the reason I used the same raw_crop as defined in DNG tags in order to both DNGs and PEFs have same size ..

- We have not the ability to use multiple raw frames for each model in camconst.json .. 
Dcraw uses the raw_frame size to define multiple raw crops i.e. if raw_size (width, height or both) is X then raw_crop is Y

I think the correct would be to add multiple frame support in camconst.json
The easy and dirty solution is to add in dcraw.cc the missing lines .. and remove raw_crop from camconst.json
```
if (width = 7392 && !strncmp(model,"K-1",3))
    { left_margin = 6; width  = 7376; top_margin = 18; }
if (width = 4832 && !strncmp(model,"K-1",3))
     top_margin = 18;

```

**Comment by Hombre57** [comment]
@iliasg When you say "multiple frame support", all frames from a single file have the same size, of course. This file has been shot in APS-C mode, hence the difference in size for all its sub-images.

**Comment by iliasg** [comment]
@Hombre57 it should be "multiple frame_size support" for each model (no relation with multiframe raw files like pixelshift) 
i.e support defining the raw_crop for both FF and APS-C in Pentax FFs or Nikon FFs which have up to 3 different crop modes (D810), Sony FF, Olympus normal and Hires modes (E-M5II has 16Mp and 64Mp raw sizes,). 
Up to now we either leave this on Dcraw if it supports the model (where the sizes are sometimes suboptimal) or for Sony FFs we use the relative raw_crop in camonst.json (i.e we only define the borders) as it happens that both FF & APS-C modes use the same borders.
With K-1 and Olympus the borders do not match and there is the problem ..

**Comment by Hombre57** [comment]
@iliasg Ok, I understand. Pentax K-1 has 3 crop mode in fact. If you don't mind, could you also have a look at the 1:1 crop ratio ?

https://filebin.net/mdlhop60w346dgs2/PENTAX_K-1_1-1Crop.PEF

**Comment by Hombre57** [comment]
As Ingo told me on IRC, that 1:1 raw file has a cropped jpeg embedded image but a Full Frame raw image, so there's no 3 real raw crop size. I should have opened that file in RT first instead of guessing... (I've never shot in this crop ratio)

**Comment by iliasg** [comment]
@heckflosse @Beep6581 
I think the code at
https://github.com/Beep6581/RawTherapee/issues/3519#issuecomment-264666406
should be commited or else I have to try with a bit different "raw_crop" in camconst.json to (not optimally) cover both FF and APS-C cases .. ;)

**Comment by heckflosse** [comment]
@Hombre57 Can you please supply an APS-C size PEF file? We need to solve the issue for DNG and PEF before pushing.

**Comment by Hombre57** [comment]
@heckflosse RT is crashing here so I can't check the shot size, however considering the file size it should be APS-C. Do not publish or share.

https://filebin.net/3m926h3eqidis75m

**Comment by heckflosse** [comment]
@Hombre57 Can you test [this patch](https://filebin.net/wsqk7i85uksgs0g5) with full and aps-c format pef and dng from k-1?

**Comment by Hombre57** [comment]
Sure.

**Comment by heckflosse** [comment]
@Hombre57 Great! If it works fine in your tests (here it works fine) I can push it for rt5 if there are no objections.

**Comment by Hombre57** [comment]
Yes, works fine with FF & APS-C PEF image, and for FF DNG image. I don't have APS-C DNG image but I guess it works fine too ;). +1 for committing.

**Comment by heckflosse** [comment]
I tested with APS-C DNG image I got from you. Also works fine. Will commit now. Thanks for testing :+1:

**Comment by heckflosse** [comment]
@Hombre57 Can you upload a raw file from K-1 shot in square mode? I want to test how auto distortion correction behaves for that case (comparing full size crop to square jpeg preview)

**Comment by Hombre57** [comment]
Here is a PEF file in 1:1 crop format https://filebin.net/wsqk7i85uksgs0g5 , but I don't know if lens correction was enabled. If not, I won't be able to take a new one until my K-1 come back from the repair service.

**Comment by heckflosse** [comment]
@Hombre57 Does not matter whether lens correction is enabled. I just want to try whether the autl lens correction algo does not crash in that case.

**Comment by heckflosse** [comment]
@Hombre57 Just tested. No crash, no correction, fine :)
