### ISSUE TITLE
Gtk+3.20 GUI Glitch

### ISSUE THREAD

**Issue by TooWaBoo** [Beep6581/RawTherapee#3531]
Combobox Method: min-width to high
Combobox Size: not right aligned
Label Size: To close to pipette button, to far from combobox

![1](https://cloud.githubusercontent.com/assets/13800920/21120573/4aaa7e3e-c0c8-11e6-874f-479c07e98f2d.png)

Wrong button is stretching

![unbenannt](https://cloud.githubusercontent.com/assets/13800920/21125637/7366f0ea-c0e7-11e6-87f3-dbfd3608a7ba.png)

**Comment by Beep6581** [comment]
The Processing Profiles combo had a problem where its collapsed size would assume the size of its largest containing item, but I confirm that this issue is fixed (just confirmed in gtk3-bugfix 3b3a14b). It seems like the White Balance Method combo has the same problem, its assuming the width of its widest element - `TP_WBALANCE_FLASH60;Standard, Canon, Pentax, Olympus`.

I also confirm that the curve type combo gets ellipsized even when the one to the left had plenty of free space.

**Comment by TooWaBoo** [comment]
I've add a \n to the menu and than it looks like this: :-) 
![unbenannt](https://cloud.githubusercontent.com/assets/13800920/21210477/adb7925a-c27b-11e6-8bb8-a0c3794f218b.png)

Maybe the problem affects only menus with submenus.

**Comment by Beep6581** [comment]
> Third side note : the curve's buttons does actually expand, making the optional accompanying widget shrink. Should we change the expand/shrink policy and on which basis (automatic or programmed) ?

The collapsed curve type combo shows only an icon, no label, so it does not need to expand, while the combo to the right with the label does.

**Comment by Hombre57** [comment]
Glitch fixed, can you confirm and close ?

**Comment by Hombre57** [comment]
I'm not using master anymore, but I should have fixed those bugs in master... Is there an easy way to port back ? Do we care ?

**Comment by Beep6581** [comment]
Great @Hombre57 I will test when I'm at my laptop later. You could cherry-pick it into master. A master's life is nearing an end, I only care in the sense that having similar code in both branches simplifies merging.
