### ISSUE TITLE
FEATURE REQUEST : GPS Set feature

### ISSUE THREAD

**Issue by stilicrafter** [Beep6581/RawTherapee#3576]
Hello.
I would realy love it , if it would be possible to place pictures at a virtual map , and then , when exported , the gps information are copied .
Or eaven better , GPX Files from GPS System could be added automaticaly.

(Sorry 4 bad English , German :) )
Thanks

**Comment by Beep6581** [comment]
RawTherapee does't handle that. Try digiKam.

**Comment by stilicrafter** [comment]
But DigiKam can only be used after the developement ( Raw --> Jpeg )
But some pictures i dont convert to Jpg , because only the best are converted , and i want to tag any picture .

**Comment by Beep6581** [comment]
digiKam can be used on raw and non-raw images, and it already includes a globe map feature. Point being RawTherapee's job is raw conversion, and this request is about digital asset management and would require much work which nobody has expressed any intention of doing. Of course anyone is free to take it up - this issue is closed, not deleted.
