### ISSUE TITLE
ISO steps 2/3 and 1 have same brightness (Canon 60D raw)

### ISSUE THREAD

**Issue by Blizzara** [Beep6581/RawTherapee#3611]
Hi,

After applying the "Neutral" profile and equal white balance, two CR2 files taken with different ISO settings (otherwise same settings) seem to have same brightness, both in preview and after exporting, when the ISO's are steps 2/3 and 1, e.g., 160 and 200. 

The change from 125 to 160 is about twice the change from 100 to 125, suggesting that the values are like 100 -> 125 -> 200 -> 200 -> ..

dcraw -W -T produced images where the brightness differs by the expected amount for all 100->125, 125->160 and 160->200.

Two example CR2's can be found at https://avo.kapsi.fi/ISO_160_200_ex.zip.

Tested with both rawtherapee-fresh and rawtherapee-unstable from dhor's PPA, so versions 4.2.380-1dhor\~wily and 1:4.3+git20170115-450~ubuntu16.10.1, on Ubuntu 16.10.

Please let me know if you'd need more information (or clearer description). Thanks!

**Comment by heckflosse** [comment]
> The change from 125 to 160 is about twice the change from 100 to 125, suggesting that the values are like 100 -> 125 -> 200 -> 200 -> ..

It's roughly the same change (1.28 to 1.25)

I think your issue is related to being Canon intermediate ISO settings not being real ISO settings. Have a look [here](https://github.com/Beep6581/RawTherapee/blob/master/rtengine/camconst.json#L646). Why are white levels different for intermediate ISO settings? Maybe @iliasg knows more...

Ingo

**Comment by Blizzara** [comment]
I was suspecting the intermediate ISO's, and I was ready to call it a "feature" of CR2, but when dcraw procuded different output I decided to ask. The white levels specified in camconst.json seem to be the reason - after setting the white level to same number for all ISO's for the 60D, the "Neutral" profile works as expected. Then setting the ISO160 photo's exposure compensation to 0.0 and ISO200's EC to -0.33 the photos again have almost the same brightness.

I guess that being intermediate ISO's, they probably do have different white levels, and RT probably allows better editing when it knows then. So just resetting the values in camconst.json is not a good solution... 

The reason I'm wondering about this is a timelapse taken with auto ISO. I'd like to calculate the brightness of each photo from somewhere (embedded preview, the photo extracted by dcraw, something), and currently the only solution is to first process the photos with RT, then calculate the brightess from the resulting images and from that calculate the EC values. That does work, but it's not very streamlined process.

**Comment by Beep6581** [comment]
@Blizzara are you J.B.?

**Comment by Blizzara** [comment]
@Beep6581 No, I'm not. But LapseStudio was something I've been looking for for ages, so I've been trying to fix / finalize it so that it would work (at least for me) :)

-Arttu

**Comment by iliasg** [comment]
@Blizzara 
Dcraw uses a single WL = 12279 for all ISOs which is only correct for ISOs 160-320-640 etc while it clips some highlights from ISOs 100 and 125 and a lot of highlights from ISOs200-250-400-...

RT with camconst.json uses the correct WL for each ISO so that we take no clipped highlights nor magenta highlight (which happens when we use a WL higher than the correct) 
So a change to a single WL is not acceptable.  

If you need to do any calculations with RT's WL keep in mind that the values at camconst.json are before Black Level subtraction .. to take the correct ratios you need to subtract 2048 from them i.e. for 100&125 is 13480-2048 for 160-320-640 etc is 12550-2048 and the rest 15200-2048 ..

**Comment by Blizzara** [comment]
@iliasg, makes sense. Would it be possible for RT to somehow compensate for the different white levels with for example some internal correction term to exposure compensation, using the ratios you mentioned?

**Comment by iliasg** [comment]
I don't think we can do something simple in the code .. any such try would either destroy linearity or clipp highlights :( .. and it's getting complex because we have to deal with different behaviour of each model ..

BTW I don't fully understand what you really need to calculate so that you cannot overcome the fact that ISO160 is same as ISO200 ..

**Comment by Blizzara** [comment]
@iliasg, ok :(

I want to calculate EC values that make all images in a timelapse series have similar brightness. There are a couple of different ways of calculating the brightness, the ones I've tried so far are:
1) calculate from the embedded preview using some formula
2) convert the CR2 to TIFF with dcraw and calculate from the TIFF using some formula
3) assume the scene has equal brightness through the series and calculate image brightness form EXIF data (Av,Tv,ISO): 
4) use RT to export photos with for example neutral profile and calculate from the exported images using some formula: works, but the process is most complicated of these

Currently 1) and 2) don't work, as the embedded preview and dcraw's export result in ISO200 giving more bright image than ISO160, resulting in EC of about 0 for ISO160 photo and -0.33 for the ISO200 photo. Due to the different white levels, in RT those images have now similar brightness when both have EC=0.

3) works with some "if (iso == 160) iso = 200;" trick. Apparently it should be a bit more complicated to compensate for all those different white levels, but this already gives quite good result.
4) works fine, but my impression is that RTs cli-usage is a bit limited so calling RT to first do the neutral images is not as easy as calling dcraw.

Still, sounds like my best bet is to go with 4). Thanks for all the answers! :)
-Arttu

**Comment by reggybe** [comment]
Hello,

The ISO settings of a camera are not always exact: ISO 200 can be 200 in reality, but can also be eg. 180. ISO 400 on the same camera can be 360 in reality. Look for your camera on www.dxomark.com. There is also a video on intermediate settings: google for 'RawDigger Case Studies - The Riddle of the Intermediate ISO Settings'.

Reggybe

**Comment by iliasg** [comment]
I thing it's better to stop using intermediate ISOs for this job .. you gain nothing because 
- ISO 125/250/500 etc are ISO100/200/400 multiplied by 1.25 after digitization .. there is no gain .. only loss of 1/3stop highlights
- ISO 160/320/640 etc are ISO 200/400/800 multiplied by 0.80 after digitization .. it's same as if you used ISO200/400/800 with +1/3 EV setting ..

For already existing shots you already found the way .. :)
I think you can find more reliable data than Av,Tv,ISO in exif for real scene brightness ..  (MesuredEV - MeasuredEV2 - maybe RawMeasuredRGGB if you manage to decode it's meaning)
