### ISSUE TITLE
Add support for RGB Indicator Bar for raw histogram mode

### ISSUE THREAD

**Issue by goblin** [Beep6581/RawTherapee#3624]
As per title, the RGB Indicator bar doesn't work when I select the RAW histogram. I'm on RT 4.2.448.

Also, it would be nice to be able to have both the RAW histogram and the output histogram on at the same time (with indicator bar jumping appropriately for each pixel under the cursor)

**Comment by goblin** [comment]
Also happens on 5.0

**Comment by Thanatomanic** [comment]
This is an old issue, but I will close it because:
1) It is unclear what the RGB indicator should show for a selected pixel. The underlying RAW values have been 'compromised' by the demosaicing process.
2) Combining the RAW and RGB histograms clutters the histogram big time. I also fail to see any practical advantage of showing them together.
