### ISSUE TITLE
5.0 install overwrote old version

### ISSUE THREAD

**Issue by Bobthearch** [Beep6581/RawTherapee#3629]
Version 5.0 - gtk3
Windows 7 64-bit.
Downloaded from here:  http://rawtherapee.com/releases_head/windows/RawTherapee_WinVista_64_5.0-gtk3_3.18_release.zip

Problem:  RawTherapee 5 installed into the folder "RawTherapee-4.2.880", which overwrote my previous install.  I just wanted to check out 5.0; I wasn't ready to replace the old version quite yet.

**Comment by Beep6581** [comment]
@sguyader does the installer not ask the user where to install to?

**Comment by Bobthearch** [comment]
It does not allow for a custom install location.
But even so I would have chosen the default installation anyway, never guessing the default location for RaawTherapee 5 would be **/Program Files/RawTherapee-4.2.880**

**Comment by gaaned92** [comment]
@Bobthearch You are right. As it is programmed now, the inno installer doesn't allow multiple installations.
When installing a new version, the installer search for an already installed SW with the same Appid.
As this happens, it installs in the same directory without warning.
I think we have to modify the installer as some users want to install a few versions simultaneously.

For the development builds(except 5.0) I provide for windows ([https://discuss.pixls.us/t/download-rawtherapee-builds-windows-macos-linux-appimage-other/2924/19](https://discuss.pixls.us/t/download-rawtherapee-builds-windows-macos-linux-appimage-other/2924/19) I modified the installer to avoid collisions.

**Comment by Bobthearch** [comment]
I don't think it would be necessary for regular small updates, but a major release like RT5 should be treated as an entirely new program.  
It also could be problematic for some users that the folder and software names don't match, ie having RT 5 installed in a folder labeled RT 4.
I don't see any major issues with RT5 that would make me want to roll back or use an older version, but no one can know that before installing and running the program.

**Comment by sguyader** [comment]
In the Innosetup script, if we add the line `DisableDirPage=no` in the setup part, then the installer always asks the user where they want to install Rawtherapee.

**Comment by sguyader** [comment]
In fact there are 4 setup options to check out:

`DisableDirPage=no`
`DisableProgramGroupPage=no`

So that both the installation folder and the program group name can be changed by the user.

`UsePreviousAppDir=no`
`UsePreviousGroup=no`

So that, if there is a previous version installed, the installer will use the correct names from the new version. If set to yes (or omitted) the installer will pick up the version name of the previous installation and propose this older version name for the new installation folder and program group names by default (in this case, if the user doesn't pay attention, it will override the older version and install the new one under the older named folder...)

**Comment by Hombre57** [comment]
Users need more guidance when installing a new Release build, as well as any Innosetup packed version, on :
1. what to do of the previous version
2. select new installation directory
3. warn about possible conflict with cache folder name and sidecar file when using 2 different versions !

Before taking action on this, I'd suggest to find a version naming first (issue #3628).

**Comment by Raoul-Kima** [comment]
Hi all.

I have the same issue. It seems the installation overwrote all my program settings of the old rawtherapee, and deleted all my custom processing profiles. Thank god my camera calibration profiles are still there! I think this issue deserves more priority, or at least the download page should have a warning till the issue can be resolved.

If anyone knows how to recover my profiles it would be great to hear about that. Is the new rawtherapee compatible with the old pp3 files?

The download page gave this version info:

Uploaded by DrSlony on 2017-01-24 10:52
Branch: gtk3
Release Type: Stable (recommended)
Commit: 7fe7c4f60f85b47bc1d24b2cfece43444028e3a6
Build Type: release
Processor: generic x86
Gtkmm Version: V3.18.0
Compiler: gcc 5.3.0
Build Flags: -m64 -mwin32 -mthreads -std=gnu++11 -mtune=generic -Werror=unused-label -fopenmp -Werror=unknown-pragmas -msse -msse2 -mwindows -fopenmp -Wno-aggressive-loop-optimizations -DNDEBUG -O3
Link Flags: -m64 -mwin32 -mthreads -static-libgcc -mtune=generic -mwindows -s -O3
OpenMP: Yes, Mmap: Yes


Build from sguyader
https://github.com/Beep6581/RawTherapee/issues/3300#issuecomment-274489836

**Comment by Beep6581** [comment]
This should be fixed in 5.0-r1, to be release within the next two days.
If @sguyader or @gaaned92 release a build before then you should test it and report back.

**Comment by Hombre57** [comment]
@Raoul-Kima You should be able to recover your old processing profiles by renaming the RawTherapee-_xxx_ folder name in your UserProfile\AppData\Local folder (or AppData\Roaming, I don't remember) or to keep safe, copy its content into the new cache folder.

See also here : http://rawpedia.rawtherapee.com/File_Paths

> Are they compatible

it depend on the version you were using before, but chances are that some tools does understand their parameters slightly differently. That's why we recommend to keep the previous install on disk and why this issue is critical.

Could someone remove the Windows build from the download page and replace it by a new one with the lately updated InnoSetup? AppId not being the same now, it will let the user choose where to install any new builds (as discussed in #3628).
