### ISSUE TITLE
LG Mobile LG-H850 (LG G5) raw support

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#3655]
For white levels
https://filebin.net/vaz6ovj5p66exgz9

From https://plus.google.com/u/0/b/106783532637761598368/+AndrewJens/posts/VarFNfXZhd2

**Comment by iliasg** [comment]
This file opens fine and without magenta cast .. the WL looks correct at 1023 (10bit file) .. but I have to dig a bit ..

magenta highlight is only visible in the in_DNG embbeded preview ;)

We only need to extract the full dcp profile because RT only read the colormatrix2 ..

**Comment by iliasg** [comment]
OK I see that there is a BIG spread from 503-1023 for Red and 750-1023 for Blue which is hidden with a "correct" WB but can show up with a different WB
I think this is a spread coming from Black Frame subtraction operated due to Long Exposure .. may be also vignette correction, as the coloration is at the center 
I think lowering the WL at 500 is too much. Also we cannot be sure if it's always same and not depended on camera's WB .. :(
Lets see what happens with normal exposures and decide .. if this coloration only gets visible at extrem/special cases we can leave it happen and suggest the user to control it with RAW White Point correction. 
![lg-h850](https://cloud.githubusercontent.com/assets/15012599/22529339/bbf8725a-e8df-11e6-81b5-032123801b60.png)

**Comment by iliasg** [comment]
The exported dcp profile .. no LUTs .. only dual illuminant matrices.
[LG-H850-dcp.zip](https://github.com/Beep6581/RawTherapee/files/746389/LG-H850-dcp.zip)

It uses inverse order of illuminants but I think RT recognizes this ..

**Comment by Beep6581** [comment]
One more file uploaded to the original filebin, there should be at least one more file to come.

**Comment by Beep6581** [comment]
Final file uploaded to original filebin. @iliasg what do we do?

**Comment by Beep6581** [comment]
Ping @iliasg

**Comment by iliasg** [comment]
I think that it's too much conservatism to cut 1 stop from highlights just because there is a rare case that we take magenta highlights (on long exposures and strange WB). I vote for being just slightly conservative and leave the users to correct rare cases with "White-point correction"
So for both LG smartphones  we need in camconst.json .. (feel free to interchange D65 with A matrix if it is valid that LG reports them inversely)
```
    { // Quality C
        "make_model": "LG mobile LG-H815",
        "dcraw_matrix": [ 5859,547,-1250,-6484,15547,547,-2422,5625,3906 ], // DNG D65
      //  "dcraw_matrix": [ 11563,-2891,-3203,-5313,15625,625,-781,2813,5625 ], // DNG A
        "ranges": { "white_max": 1000 }
    },
    { // Quality C,
        "make_model": "LG mobile LG-H850",
      //  "dcraw_matrix": [ 10000,-2188,-2813,-5156,15469,625,-703,2734,5078 ], // DNG A
        "dcraw_matrix": [ 5313,1016,-1172,-6250,15391,547,-2344,5547,3359 ], // DNG D65
        "ranges": { "white_max": 1000 } // exif 1023, spikes at 1012
    },
```
and in dcraw.cc to make RT not use the wrong illuminant from LG's exif data 
```
if (!strncmp(make, "LG", 2) && (!strncmp(model, "LG-H850",7) || !strncmp(model, "LG-H815",7))) 
adobe_coeff (make, model);
```

**Comment by Beep6581** [comment]
Done some time ago.

**Comment by heckflosse** [comment]
The "white_max" has to be "white". Also the changes to dcraw.cc have to be made. I will take this one.

**Comment by Beep6581** [comment]
Apologies, I don't remember why I was under the impression that these changes were already committed...
