### ISSUE TITLE
make macosx_bundle dylib location

### ISSUE THREAD

**Issue by Partha1b** [Beep6581/RawTherapee#3824]
When make macosx_bundle is executed, the dylibs are not relocated relative to the app location. For example, 
```
Parthas-MacBook-Pro:Frameworks partha$ otool -L /Applications/RawTherapee.app/Contents/Frameworks/libgmodule-2.0.0.dylib 
/Applications/RawTherapee.app/Contents/Frameworks/libgmodule-2.0.0.dylib:
	/Users/partha/local10.9/lib/libgmodule-2.0.0.dylib (compatibility version 5103.0.0, current version 5103.0.0)
	/Users/partha/local10.9/lib/libglib-2.0.0.dylib (compatibility version 5103.0.0, current version 5103.0.0)
	/Users/partha/local10.9/lib/libintl.8.dylib (compatibility version 10.0.0, current version 10.5.0)
	/Users/partha/local10.9/lib/libiconv.2.dylib (compatibility version 8.0.0, current version 8.1.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1238.0.0)
	/System/Library/Frameworks/Carbon.framework/Versions/A/Carbon (compatibility version 2.0.0, current version 157.0.0)
	/System/Library/Frameworks/Foundation.framework/Versions/C/Foundation (compatibility version 300.0.0, current version 1349.25.0)
Parthas-MacBook-Pro:Frameworks partha$ 
```
This would crash on startup for anyone but me. 🙂 

Since we are doing the following:
```
ln -sf "${app}" /tmp
```
suggested solution would be (replacing Lines 161-171):
```
#Fix the libnames within the app:
for files in `find "${CONTENTS}" -name "*dylib" -o -name "*.so"` "${CONTENTS}"/MacOS/rawtherapee-bin ; do
	# echo "$files"
	install_name_tool -id /tmp/RawTherapee.app/Contents/Frameworks/$files $files;
	for i in `otool -L $files |fgrep compatibility |cut -d\( -f1 | grep "${GTK_PREFIX}" | sort | uniq | sed -e 's|"${GTK_PREFIX}"/lib/||g'`; do 
	# echo "current file is $files and lib is $i"
		install_name_tool -change "${GTK_PREFIX}"/lib/$i /tmp/RawTherapee.app/Contents/Frameworks/$i $files;
	done; 
done;
```
or something similar?

**Comment by Beep6581** [comment]
Ping @ion12

@Partha1b could you explain what the script does? It's a loop in a loop using mac commands I don't have or know, but I wonder if it can be simplified - if you explain the expected result maybe I can help.

**Comment by Partha1b** [comment]
@Beep6581 Sure!
The first loop identifies all the dynamic libs (dylibs), shared objects (so) and of course the actual binary. 

For each of these files, we use otool to identify the dependencies in the second loop. For each of these dependencies, we relocate the lib from the original location to the location within the app using install_name_tool.

Note that this relocation only works if the number of characters in the length of the current location is less than the original. That's why we used ```headerpad_max_install_name``` in the previous bug to make sure we get the maximum headerpad allowed.

As an FYI, to avoid this above problem, I usually mount Frameworks to /tmp/lib or similar location in the MacOS script.

**Comment by Beep6581** [comment]
@Partha1b ok, concerning simplification of the script the only things I would consider changing without being able to see the output for myself are perhaps replacing `sort | uniq` with `sort -u` (why use two commands when you can use one), and perhaps `cut` and `sed` with Bash parameter expansion (why use external commands when Bash can do it), but it's also fine to leave it as-is and move on.

As for using `/tmp`, it seems a little dangerous to assume that `/tmp/whatever` is free. Wouldn't it be safer to use this?
```bash
tmpDir="$(mktemp -d /tmp/rt5-XXXX)" || exit
```

**Comment by Partha1b** [comment]
@Beep6581 Makes sense to me. 

[Edit] On second thought, if the tmp folder is created on the fly, you have to run otool on the fly. This would really slow down starting rt. Suggest we use what I do: Use /tmp/libRT. Highly unlikely that it would be taken.

The script snippet I provided was a suggestion based on what I use to make my app. 🙂 

I'll test it out to see if it actually works and let you know.

**Comment by Beep6581** [comment]
@Partha1b 

> On second thought, if the tmp folder is created on the fly, you have to run otool on the fly. This would really slow down starting rt.

Could you explain that? All my command does it ensure that the /tmp subfolder is unique and safe to use (which is not always the case, e.g. what if your script or RT crashes and leaves junk behind, and then you try to re-run it?), it takes no time at all. Where does the delay you speak of come from?

**Comment by Partha1b** [comment]
@Beep6581 Sure.

Let's say the app is soft linked to /tmp/temp.XXXX where XXXX is determined every time you run the app. However, the dynamic link libraries are not located in the same spot. This in turn means that you have to relocate the dylibs. This can only be done once you know what temp.XXX is. That means you have to run otool on the fly. This would delay the startup. 

At least that's my understanding of mktemp. Perhaps I am wrong.

**Comment by Partha1b** [comment]
@Beep6581 This snippet now works with macosx_bundle.sh
```
#Fix the libnames within the app:
for files in `find "${CONTENTS}" -name "*dylib" -o -name "*.so"` "${CONTENTS}"/MacOS/rawtherapee ; do
	name=`basename $files`
	install_name_tool -id /tmp/libRT/$name $files;
	for i in `otool -L $files |fgrep compatibility |cut -d\( -f1 | grep "${GTK_PREFIX}" | sort -u | sed -e 's|"${GTK_PREFIX}"/lib/||g'`; do 
	libname=`basename $i`
		install_name_tool -change "${GTK_PREFIX}"/lib/$libname /tmp/libRT/$libname $files;
	done; 
done;
```
Finally you'll notice that I have change the location of dylibs to /tmp/libRT. So, in executable_loader.in, we are going to need another line:
```
ln -sf /tmp/libRT
```

**Comment by Partha1b** [comment]
@Beep6581 As an aside, as per the wiki, RT crashes on startup due to libiconv issues. When I make RT myself, I don't have this crash, while I do with ```make macosx_bundle```.

Thought you should know. 

PS: I think it's unreasonable to ask users to patch libraries. 🙂

**Comment by Partha1b** [comment]
@Beep6581 Final issue, I think: 🙂 
I get the following errors:
```
ditto: can't get real path for source '/Users/partha/local10.9/share/mime'
/Users/partha/projects/src/graphics/RT/sources/dev/tools/osx/macosx_bundle.sh: line 150: /Users/partha/local10.9/bin/gtk-update-icon-cache-3.0: No such file or directory
```
I do have gtk-update-icon-cache.

**Comment by ion12** [comment]
@Partha1b while I follow what you are saying about install_name_tool/dylibs, I am not experiencing the issues you are reporting with my macports-based setup. Just pulled updated dev branch and it builds fine (other then an unrelated error from a `#pragma GCC diagnostic` introduced into 'dcraw.cc' which I will report separately) and runs fine on a second machine without all the libraries installed.

However I feel much more at ease anyway knowing that you are going through the source code and making sure all is optimal and correct. Once you and @Beep6581 push the changes to 'macosx_bundle.sh' and 'executable_loader.in' I can compile and test if it is working for the macports workflow as well.

@Partha1b Would be great to know that you also approve of the changes in 'CMakeLists.txt', I am a bit apprehensive of the way I resolved the relative paths for BUNDLE_BASE_INSTALL_DIR, BINDIR and DATADIR paths. It does seem work correctly but I would like to make sure that there isn't something I overlooked, or a more preferable/correct solution.
I still also think that DESKTOPDIR, ICONSDIR and APPDATADIR paths should have an APPLE specific setup. (?)

@Partha1b libiconv needs to be patched and installed manually prior to `make macosx_bundle`, and the same would go for the cairo patch if we add it. I completely agree it is problematic to expect casual users to perform these patches themeselves to correctly compile the odd test build. What is the alternative? @Beep6581?

One last small thing I noticed @Beep6581 , we are now testing for `if(UNIX OR WIN32)` (manpage install). Won't that **always** return TRUE making it redundant? Just curious.

**Comment by heckflosse** [comment]
@ion12 

> (other then an unrelated error from a  #pragma GCC diagnostic  introduced into 'dcraw.cc' which I will report separately) 

I will try to fix that as soon as possible (after you provided more informations)

Ingo

**Comment by ion12** [comment]
@heckflosse just opened the issue :)

**Comment by Partha1b** [comment]
@ion12 When you say, you are not experiencing the dylib issue, what do you mean? Since you are building for yourself, of course you will not experience the issue as the library locations would be specific to your installation. 🙂 

For example, please post the output of the following in your build folder:
```
otool -L RawTherapee.app/Contents/Frameworks/libgmodule-2.0.0.dylib
```
As regards the patch, I don't have the issue with libiconv when I produce the app using my setup. The problem only arises when I am using ```make macosx_bundle```

The problem with cairo is that the assertion only rears its ugly head for certain jpegs and in certain situations. So, I am not sure that the patch I did for my system would be universal though it does solve the issue we are experiencing.

Finally wrt macport, I don't know what compiler they use to produce their binaries. I don't know what patches they make to stock source code provided by gnome. So, I cannot comment on that at all. 

There are other build systems as well like homebrew, jhbuild, fink etc. who use different setup.

From my perspective I think it's reasonable to use the native clang compiler on a Mac as it's provided by Apple and would be available on all Macs with Xcode.

I think I did comment on 

> I still also think that DESKTOPDIR, ICONSDIR and APPDATADIR paths should have an APPLE specific setup. (?)

I agree. I commented on that issue (don't remember the issue number) and said that I would have them as subfolders of Resources/doc

Currently there is one final flaw that I have not addressed whereby a share folder is installed in MacOS. 

Did I miss anything?

**Comment by Beep6581** [comment]
@Partha1b I'm afraid I don't follow, not being a macOS user and not knowing your setup. Would be great if you could fork and open a PR with the required changes.

**Comment by ion12** [comment]
@Partha1b I did test the build on a second machine, but it is possible I incorrectly assumed it did not have a macports installation + matching dependencies. I don't have the machine available at the moment to double check but you are correct of course re - dylibs.

The old build scripts have been working more or less flawlessly for years before we started shifting the bundle structure around, I feel I am missing the same level of scrutinity that you have, so I echo @Beep6581 asking please fork and optimize the scripts according to what you know is correct, and I can help conform it to work with macports as well after (or homebrew if there is a convincing argument to switch workflow, although I personally prefer macports) if there are any discrepencies that arrise. I don't think fink and jhbuild are really relevant to our purpose. I'd like to continue this tomorrow as I am very done for tonight...

**Comment by Partha1b** [comment]
@Beep6581 OK, will try. I have to figure out how to fork. 🙂 

@ion12 Please don't misunderstand. I am not advocating any build system. I was merely pointing out that it's possible some user has a different build system etc.

I do my own builds using clang provided by Apple. I build all dylibs from scratch with gnome/gnu etc. provided sources.

Good night. 🙂

**Comment by ion12** [comment]
@Partha1b, thanks, I did not take your comments to be an advocation of one particular build system, and did not intend my comments to be taken as such either :)
I mentioned the old script working flawlessly before we started the restructure to explain why I think I was not diligent enough when confirming the build outside my own environment, as I was in a habit for years that what worked on my system worked for other users as well.

Obviously we can't expect or demand conformity of build setups, but the two most popular and easy to use systems are macports and homebrew, so I think the default build script should target one of them as the defacto build system to make building accesible for users of all skills, and I think it is sensible to assume that if someone is skilled enough to setup a customised build environment he would also be more capable of making small local adjustments to the script to suit his environment if necessary, and not the other way round.

As for clang - macports and homebrew both depend on xcode/CLT and as far as I know both use the Apple system-provided compiler to build their packages/ports.
But I have always used the latest stable compiler available from macports to compile RT itself. I think it is inadvisable to use the native system compiler for RT, Apple provides such infruriatingly outdated binaries, and RT contains OpenMP code for which support has been improved in more recent clang.

A minimum stable version of clang could be considered a prerequisit just as with any other dependency, whether you build it manually or through a port/brew. Just my 2 cents.
Latest stable version is clang 4.0.0 which was released last month, but probably best to stick with 3.9.1 for now until all previous issues are confirmed resolved?

I have no idea why you have the gtk-update-icon-cache issue, this is one of the issues I meant I was NOT seeing with macports. The libiconv discrepency could be maybe related to the different clang versions?

Very happy that you will fork and check the code :) I can then try and compile and if there are any conflicts left with macports we can resolve.

@Partha1b @Beep6581 If there is a desicion that the project would be better off replacing macports with homebrew as the default workflow I will make the switch as well, but perhaps this should be brought up in a wider forum, and it would need to be properly tested.

**Comment by Partha1b** [comment]
@ion12 & @Beep6581 
I think we're way off topic now discussing macports/homebrews etc. I am a wine person myself, preferring bordeaux. 🙂 

I am simply stating that I use Apple provided compiler, period. I think this make sense to me since it will be available for all Macs from the AppStore. 

Imagine if you are asking users on a Linux system to compile and use a specific compiler different from the one provided by the distribution. Great for hobbyist, not so practical for everyday user. 

The latest provided by Apple is:
```
Parthas-MacBook-Pro:std partha$ clang -v
Apple LLVM version 8.1.0 (clang-802.0.41)
Target: x86_64-apple-darwin16.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```
At the end of the day, we really want users to be processing images and not necessarily discussing the nitty gritties of a specific build system.

But if you want to officially state that you are using a build system that the user has to download and install prior to compiling RT, then I would not be able to do that.

Thanks,
Partha

**Comment by heckflosse** [comment]
@Partha1b @ion12 @Beep6581 

> At the end of the day, we really want users to be processing images

Absolutely. And we want them to do that fast. I did not follow your whole discussion from above. But we should ensure that the builds make best possible use of OpenMP code.

**Comment by Partha1b** [comment]
@heckflosse Thanks for comment. There is no openMP provided by Apple. 🙁

**Comment by heckflosse** [comment]
@Partha1b I know nothing about building rt on Apple. But I know that latest rt 4.x builds for Apple used OpenMP. And it would be good (maybe even a necessity) to use OpenMP also for rt 5.x builds.
Anything else would be a big step backwards (performance wise) for Apple users :(

**Comment by agriggio** [comment]
I agree with Ingo. if the official some complier doesn't support openmp, I
think we should consider alternatives. a "vanilla" recent clang should do

**Comment by ion12** [comment]
@Partha1b 
The casual user will NOT be compiling GTK and all the other dependencies of RT manually as you are doing. S/he will be looking for a simplified solution such as macports/brew that provide a package-manager-like experience, and for her/him using an up-to-date clang would be as simple as typing in
`sudo port install clang-3.9`
that's it. same as any other dependency.
And you do not need to download a particular build system. If you compile dependencies manually, you can compile manually a recent clang release just as you do with all your other dependencies.

Note that the current macports workflow was not designed by me, it was setup (I don't even know by whom) long before I started compiling RT several years ago so I have no particular allegience to it. It's just simple and accessible and it works.
Before Apple dropped support for GCC in 10.9, we used to compile with gcc, and even then we used a more up-to-date gcc from macports because of the OpenMP support and how outdated Apple's gcc was.
Apple ships severly outdated binaries. Period. I can't imagine why we would want to use an outdated compiler as the defacto suggestion.

I hope this clarifies better my meaning, wasn't trying to start a philosophical debate about compiling
:)

**Comment by Partha1b** [comment]
@Beep6581 and others, I don't know where this thread is going. When I was asked to provide Mac builds, I didn't realize that there are already others who were doing these builds. 

So, I don't think we need one more build, since we already have @ion12 and @agriggio volunteering and building mac builds and should be able to provide them.

Thanks,
Partha

**Comment by heckflosse** [comment]
@Partha1b 

> I don't know where this thread is going

I admit that I hijacked this thread. I did that because I read it and think it's important to provide the MacOS users with fast rt builds. It was clearly not my intention to advice you (or others) how to build rt for MacOS, because I now nothing about building rt for MacOS. For me usability (and this includes speed) of RT is important. If two persons make builds for MacOS and one build is fast (because it uses OpenMP for example) and the other build is slow, the slow build will not be used. Please don't take that wrong. I really appreciate your work building RT for MacOS!!!

Of course we don't need more than one build for MacOS, but that's not the point. In my opinion having two MacOS builders better satisfies the four-eyes principle even if only one of the builds will be used.

Ingo

**Comment by agriggio** [comment]
I agree with Ingo. sorry if my comment turned out harsher than I meant. I
just wanted to point out that having openmp is very important IMHO if we
care about Mac users. I personally don't use Macs, I have one at work and
with some effort (and begging :-) I can probably get the RT dependencies
installed, but I'd rather not do that. we have recently seen people
downgrading because of the lack of openmp in the latest Mac builds, it
seems to me this isn't a desirable outcome for anybody

**Comment by Beep6581** [comment]
> If there is a desicion that the project would be better off replacing macports with homebrew as the default workflow I will make the switch as well

@ion12 The decision is up to you.

At one point the RawTherapee compilation instructions tried to satisfy a range of possible scenarios using a range of possible tools. The end result was that none of the instructions worked and the guide was effectively of no use. I deleted the guide, started a new one, decided to eliminate all paths and explain just one, straightforward and easy to follow way of compiling RT, and that is what you see in http://rawpedia.rawtherapee.com/Linux
Anyone with no experience can start reading the guide from the top, on any Linux distro, just copy-paste some lines and end up with a well-working RT build. I would like the same for macOS. No if-else, just one straightward guide which is easy to follow and easy to maintain.

> I am simply stating that I use Apple provided compiler, period. I think this make sense to me since it will be available for all Macs from the AppStore.

It does make sense, but if the Apple-provided compiler is defective in some way, e.g. doesn't support OpenMP, then it's simply not an option.

> Imagine if you are asking users on a Linux system to compile and use a specific compiler different from the one provided by the distribution. Great for hobbyist, not so practical for everyday user.

@Partha1b  Compilation is not for everyday users, but it must be easy to do so that we as a project can ship working macOS builds, and currently we don't have working macOS builds. If the Apple-provided compiler is not an option then I don't see how using Homebrew is a problem - I read the Homebrew docs while updating OS X instructions in recent years and it seems so simple that using it should not be considered an obstacle. -- as @ion12 showed in the next comment.

> At the end of the day, we really want users to be processing images and not necessarily discussing the nitty gritties of a specific build system.

Absolutely, and currently they are not, because of the convoluted build process which results in unstable and slow builds, should someone succeed.

> I don't know where this thread is going.

@Partha1b what we're discussing is simplifying the macOS builds process so that you or anyone can do it without hassle.

> When I was asked to provide Mac builds, I didn't realize that there are already others who were doing these builds. So, I don't think we need one more build, since we already have @ion12 and @agriggio volunteering and building mac builds and should be able to provide them.

We did have a person making OS X builds [years ago](http://mattintosh.hatenablog.com/archive/category/RawTherapee), @mattintosh, but he disappeared. There was also @helmi03 whom I've also not head from in a long time.

We can't have a situation where only one person makes builds. If the person is on holiday, or ill, or has no time, it should be easy for anyone else to step up and help out.

I hope this clarifies the direction our efforts should head in.

**Comment by ion12** [comment]
Thanks to all for the comments and clarifications.

I have no interest in who is "doing the builds" just think that the builds distributed to end-users should be made from the build scripts included in the sources and in sync with rawpedia, so that it remains easy to continue to collaborate and contribute.

I've suggested some changes here
https://github.com/Beep6581/RawTherapee/pull/3829/commits/f8709ff0b6fcb837de244a4901e7623957848b77
that I think should resolve the remaining issues in this thread - other than the fact that it is still required to manually patch libiconv and libcairo prior to building, which I don't know how to solve.

I'm also bothered by the fact that I've changed `BUNDLE_BASE_INSTALL_DIR` for APPLE from `"${CMAKE_BINARY_DIR}/${CMAKE_BUILD_TYPE}"` to `"${CMAKE_BINARY_DIR}/${CMAKE_BUILD_TYPE}/MacOS"` to accomodate for the changes we've made to the location of the LIBDIR and DATADIR in the bundle.
It does seem to be working, but seems like an incorrect way (or at least an inelegant way) to resolve things, however my cmake knowledge is limited and I cannot figure out a better way.

@Partha1b I still think you are better suited to make the ultimate decisions and corrections for the build scripts, and hope you are willing to look at the code and fork and make your own pull request if necessary. 
I ended up making the pull request and attempts at changes only because you seemed not inclined to do so yourself, I tried to clarify that I am less experienced then you at compiling and I really don't know where the miscommunication is coming from - I'm only trying to help.
The macports vs. manual compiling of dependecies should not be fundementaly relevant to the `macosx_bundle.sh` and `executable_loader.in` scripts - as long as all the dependencies are met it shouldn't matter _how_ they are compiled.  `clang => 3.9.1` is not because of macports but because of RT's OpenMP requirements.

I only stress that we should make sure everything works with a macports/homebrew workflow because I think not many people would be willing to compile all the dependencies manually - as you are doing - without the aid of a package manager.

**Comment by Partha1b** [comment]
Hey @ion12 Sorry if I gave the impression that I am ignoring this thread. I was on vacation. We didn't want computers only cameras with us. 🙂 

I'll take the above under advisement and see what changes we need to make to allow people who want to, to do their own building.

As for providing prebuilt Mac binaries, I am assuming you and @agriggio will handle that.

Thanks,
Partha

**Comment by agriggio** [comment]
@Partha1b I think there was some misunderstanding (most likely caused by me, sorry) but I won't be able to provide Mac builds. I don't even have a Mac at home :-)

**Comment by ion12** [comment]
@Partha1b good to hear from you and hope you've had a great vacation :)
Looking forward for any corrections/improvements you might come up with.

I think during the last few years it was mostly @helmi03 and me who were testing and making builds for the Mac, on a voluntary basis as time allows.
There were periods were he was active and responsive and I wasn't, and vice versa.
Happy to continue making builds, but as you've said, real life is always intruding - and since there are not a lot of Mac users involved I hope you decide to continue being active, your contribution is very valuable :)

Ideally - If we can test together that the cmake files and included build scripts work regardless of how we compile the toolchain + dependencies, then it shouldn't really matter who provides the precompiled bundles themselves when @Beep6581 asks for a new build. Hope this makes sense.

**Comment by Beep6581** [comment]
Speaking of which, we still have no macOS OpenMP-enabled dev build. Would be great if someone could make one.

**Comment by Benitoite** [comment]
https://filebin.net/powjhrutt08eoi5g/RawTherapee_OSX_10.9_64_5.0-r1-gtk3-72-g29a72d15.zip
Here's a build using clang 3.9.1.  Made using rawpedia instructions with dependencies via macports, patch applied.  Here's the crash reported by the OS I get when launching it.

```
Process:               rawtherapee-bin [64350]
Path:                  /Applications/RawTherapee.app/Contents/MacOS/rawtherapee
Identifier:            com.rawtherapee.rawtherapee
Version:               ???
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           rawtherapee-bin [64350]
User ID:               501

Date/Time:             2017-04-28 23:28:44.730 -0700
OS Version:            Mac OS X 10.12.4 (16E195)
Report Version:        12
Anonymous UUID:        567E9ED4-5465-6075-F9A6-523A0FD4EEEA

Sleep/Wake UUID:       06B18D1D-CC80-40A7-93D4-F1C096DA60B7

Time Awake Since Boot: 720000 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x4] Symbol missing

Application Specific Information:
dyld: launch, loading dependent libraries
DYLD_LIBRARY_PATH=/Applications/RawTherapee.app/Contents/Frameworks

Dyld Error Message:
  Symbol not found: _iconv
  Referenced from: /System/Library/PrivateFrameworks/LanguageModeling.framework/Versions/A/LanguageModeling
  Expected in: /Applications/RawTherapee.app/Contents/Frameworks/libiconv.2.dylib
 in /System/Library/PrivateFrameworks/LanguageModeling.framework/Versions/A/LanguageModeling

```

**Comment by Benitoite** [comment]
Here is a build using clang 3.9.1: https://github.com/Beep6581/RawTherapee/issues/3847

**Comment by Benitoite** [comment]
Here is a working mac build with openmp enabled.
https://filebin.net/q9oh76kznl8rq5an/RawTherapee_OSX_10.9_64_5.0-r1-gtk3-475-g7553d86b.zip

```
Version: 5.0-r1-gtk3-475-g7553d86b
Branch: dev
Commit: 7553d86b
Commit date: 2017-04-29
Compiler: clang-mp-3 3.9.1
Processor: generic x86
System: Apple
Bit depth: 64 bits
Gtkmm: V3.16.0
Build type: release
Build flags: -arch x86_64 -std=c++11 -mtune=generic -Werror=unused-label -mmacosx-version-min=10.9 -flto -fopenmp=libomp -Werror=unknown-pragmas -Wall -Wno-unused-result -Wno-deprecated-declarations -O3 -DNDEBUG
Link flags:  -mtune=generic -headerpad_max_install_names -flto
OpenMP support: ON
MMAP support: ON
```

**Comment by Beep6581** [comment]
@Benitoite are you HIRAM in Discuss? Can someone confirm that the build works well?

**Comment by Benitoite** [comment]
Yep that was me...

**Comment by Partha1b** [comment]
@Benitoite & @Beep6581 Yes, I think it works. I don't know about "well", since I just downloaded and made sure it starts. I have not down any testing at all.
