### ISSUE TITLE
[feature suggestion] Single click to open folders and images

### ISSUE THREAD

**Issue by Eneen** [Beep6581/RawTherapee#3837]
It would be cool to have such option: "Single click opens" to change double click to single to:
- display pictures when clicked on folder from folder tree (file browser mode)
- open picture for editing when clicked on picture (file browser mode)
- change current picture when clicked on picture from strip (picture edit mode)

**Comment by Thanatomanic** [comment]
This would be a major change in the way RT behaves. 
- It would be impossible to do in the file browser, because it would pretty much prevent using the Inspector, Batch edit and Fast Export tools
- It would be possible from the filmstrip, but you can already use the F3/F4 keys to switch between images quickly.

Closing due to lack of interest and benefit.
