### ISSUE TITLE
Display "Filter" tab by default in File Browser

### ISSUE THREAD

**Issue by Hombre57** [Beep6581/RawTherapee#3843]
As discussed on IRC, I think that the Filter tab should be the default active one. Beginner would then be more prone to double click on a thumbnail and edit in an Editor tab than using the more complex Batch Editor tab.

**Comment by Hombre57** [comment]
Patch submitted in `filter-by-default` branch.

**Comment by Hombre57** [comment]
Should we add a tooltip over the "Develop" tab header saying "Batch edit files (expert users).", or change the label to "Batch develop" ? That would make that tab self-explanatory for those wondering about the difference with the Editor tab ?

[Edit]
... or preferably use "Batch edit" as new label ?

**Comment by agriggio** [comment]
:+1: to both your proposals

**Comment by Beep6581** [comment]
Branch looks good, and +1 to rename "Develop" to "Batch Edit".

**Comment by Hombre57** [comment]
@agriggio @heckflosse How do you translate those strings in your respective language ? @Beep6581 Is the current english version correct ?
```
Batch edit
Let's you edit multiple files at once (for experienced users). To use the standard editing process, double click on a thumbnail to open the image in an Editor tab.
```
The later one will be the tooltip.

**Comment by Beep6581** [comment]
@Hombre57 "Batch Edit", both capitalized, because it's a proper noun, the same as the other tab names.

Is the second part a tooltip?
Please avoid statements like "for experienced users" - everything is for users of a certain experience. A curve can be baffling to a user who has never used one. If enabling resizing on a bunch of images requires users to be truly experienced and warrants a warning, then I think we're doing something wrong.

So I would suggest either no tooltip, or "Allows you to change tool parameters for a selection of images."

The part about opening the image in the Editor tab is unnecessary and covered by the very first thing any RT user should read, http://rawpedia.rawtherapee.com/Getting_Started

**Comment by Hombre57** [comment]
@Beep6581 Ok, then no tooltip. I'll do that tomorrow, when I'll have the answer from @agriggio and @heckflosse for "Batch Edit".

**Comment by heckflosse** [comment]
@Hombre57 I don't care about german translation. @TooWaBoo does a very good job for the german language file  :+1:  and I don't want to chime into that.

**Comment by agriggio** [comment]
I also am not the right person for translating into Italian. Computer-related terms are usually translated pretty poorly and end up being uninitentionally funny (I'm thinking about "batch" here). FWIW, all my desktops are set to English for this very reason. But if you still want something, "Modifiche Batch" is the best I can think of -- anything else will sound strange, convoluted, laughable, or possibly all three :wink:

**Comment by Hombre57** [comment]
@heckflosse Ok, I'll commit without updating the German string.
@agriggio Thanks, I'll use your version.

**Comment by TooWaBoo** [comment]
@Hombre57 
A German translation could be "Hintergrundbearbeitung" or "Batchbearbeitung". I prefere "Batchbearbeitung"

**Comment by Beep6581** [comment]
:+1: for merge.

**Comment by Hombre57** [comment]
Merged.
