### ISSUE TITLE
Rename "Noise Reduction -> Quality" to "Strength"

### ISSUE THREAD

**Issue by agriggio** [Beep6581/RawTherapee#3854]
Rationale: "quality" is subjective -- and FWIW I almost always prefer "standard" over "high". I think "strength" is a more appropriate description here. It is also less confusing for users (e.g. search the pixls.us forum for questions about this).

Opinions?

**Comment by Beep6581** [comment]
RawPedia:

> Quality
"High" makes two noise reducing passes, each one with a different algorithm, for higher quality at the cost of processing time.
You can select in "Preferences > Performance & Quality" the number of levels for the wavelet:
No: no extra level
One level or two levels: add this number to the referenced one. This increases the processing time, but also improves the chromatic noise processing, mostly the ugly noise "packets"

How many wavelet levels are used when the extra levels combo is set to "no"?

The Luminance and Chrominance sliders already control the strength, changing this label to Strength wouldn't clarify things for me. How about "Double-pass" instead of "Strength"?

**Comment by agriggio** [comment]
> How about "Double-pass" instead of "Strength"?

That could do. But then, why is the selection partially in the preferences and partially in the pp3? What about "Number of passes", going from 1 to 3, and remove the entry in preferences?

**Comment by Beep6581** [comment]
Coming up with a good solution requires knowing for sure how this works, and the statement in RawPedia is too vague to give me certainty. It would need to be verified in the code.

> why is the selection partially in the preferences and partially in the pp3?

Exactly. Seems like a design issue which went unnoticed.
My suggestion is to see whether it works as advertised, specifically two things:
1. whether it does successfully remove "ugly noise packets" (I assume that means the very low frequency chroma noise),
2. and whether the selection of wavelet levels is really required, whether it makes a significant difference.
If it does work as advertised, we rename "Quality" to "Double-pass" and create a new combo with the number of wavelet levels used. Delete the option from Preferences.

> What about "Number of passes", going from 1 to 3, and remove the entry in preferences?

I too would prefer a single combo solution, but (assuming the RawPedia entry is correct) the widget in Preferences does not select the number of passes, but the number of wavelet levels used. The explanation in RawPedia seems to suggest that the number of wavelet levels used applies to each pass, so even in "standard quality" mode where there is only one pass the number of wavelet levels used has an influence on the result.

Let's do this for 5.2.

**Comment by agriggio** [comment]
can we resume this for 5.4? How about simply changing "Quality" to a generic "Level" (and adapting the tooltip accordingly)? 
"Quality" simply has a connotation that can just be misleading in this context...

**Comment by heckflosse** [comment]
@agriggio I agree. Additionally, iirc, we could get a strength adjuster for free, performance wise.
By strength adjuster I mean one, which blends before/after NR. There's an old issue about that too.

**Comment by agriggio** [comment]
@heckflosse that would also be interesting, but perhaps we can wait a little bit for it? I'm saying this just for the sake of having 5.4 out asap...

**Comment by heckflosse** [comment]
@agriggio 

> but perhaps we can wait a little bit for it?

absolutely! Just wanted to mention that I remember we could the strength (blending) slider for free (performance-wise). Though I have to dig out how...

**Comment by Beep6581** [comment]
In summary, to solve this issue:
1. Find out what the code actually does - documentation unclear. What do `smethod` and `nrwavlevel` do, how do they interact.
2. Either move wavelet level count from Preferences into the NR tool and PP3, or hard-code it and remove.
3. Rename the label accordingly.
4. Update the documentation.

**Comment by agriggio** [comment]
I'll take a look

**Comment by Beep6581** [comment]
`TP_DIRPYRDENOISE_METHOD11;Quality` = `smethod` = (`shal`|`shalbi`) = "shrink method"
Both quality settings run `WaveletDenoiseAll(AB|L)`, but quality "High" additionally runs `WaveletDenoiseAll_BiShrink(AB|L)` first.

Quality = High removes low frequency chroma noise very well.
![imgur-2017_12_30-13 13 45](https://user-images.githubusercontent.com/5844619/34454090-507f8304-ed63-11e7-9dfc-e4dc43ff0d3f.png)
![imgur-2017_12_30-13 13 52](https://user-images.githubusercontent.com/5844619/34454091-50a4feae-ed63-11e7-9a88-c7dd2dc475c1.png)

`PREFERENCES_WAVLEV;Increase wavelet level in quality 'high'` = `nrwavlevel` = `levwav` = (`0`|`1`|`2`)
Seems the level is dynamic, and it's capped to max 8: https://github.com/Beep6581/RawTherapee/blob/dev/rtengine/FTblockDN.cc#L1125
Since the user never really knows how many levels are being used, not sure exposing this is a good idea.

The differences between "no" and "two" are most visible in very noisy and dark areas. "two" kills low frequency chroma, though whether chroma of such a low frequency is detail or noise depends I suppose on the camera.

`nr crop m=lab q=high dl=standard l=no.jpg`
![nr crop m lab q high dl standard l no](https://user-images.githubusercontent.com/5844619/34454685-b21b7d68-ed70-11e7-8de7-0290389f8ab0.jpg)

`nr crop m=lab q=high dl=standard l=two.jpg`
![nr crop m lab q high dl standard l two](https://user-images.githubusercontent.com/5844619/34454686-b23d5262-ed70-11e7-8c8a-e8c0c1d2bfe3.jpg)

--edit
Woah, those images are supposed to be much darker. GIMP must have done something wrong with the profile when I used it for cropping.
____

Off-topic,
```c++
                            if (!memoryAllocationFailed) {
                                if (nrQuality == QUALITY_STANDARD) {
                                    if (!WaveletDenoiseAllAB(*Ldecomp, *adecomp, noisevarchrom, madL, noisevarab_r, useNoiseCCurve, autoch, denoiseMethodRgb)) { //enhance mode
                                        memoryAllocationFailed = true;
                                    }
                                } else { /*if (nrQuality==QUALITY_HIGH)*/
                                    if (!WaveletDenoiseAll_BiShrinkAB(*Ldecomp, *adecomp, noisevarchrom, madL, noisevarab_r, useNoiseCCurve, autoch, denoiseMethodRgb)) { //enhance mode
                                        memoryAllocationFailed = true;
                                    }

                                    if (!memoryAllocationFailed) {
                                        if (!WaveletDenoiseAllAB(*Ldecomp, *adecomp, noisevarchrom, madL, noisevarab_r, useNoiseCCurve, autoch, denoiseMethodRgb)) {
                                            memoryAllocationFailed = true;
                                        }
                                    }
                                }
                            }
```

Wouldn't it be more readable like this?
```c++
                            if (!memoryAllocationFailed) {
                                if (nrQuality == QUALITY_HIGH) {
                                    if (!WaveletDenoiseAll_BiShrinkAB(*Ldecomp, *adecomp, noisevarchrom, madL, noisevarab_r, useNoiseCCurve, autoch, denoiseMethodRgb)) { //enhance mode
                                        memoryAllocationFailed = true;
                                    }
                                }
                                if (!memoryAllocationFailed) {
                                    if (!WaveletDenoiseAllAB(*Ldecomp, *adecomp, noisevarchrom, madL, noisevarab_r, useNoiseCCurve, autoch, denoiseMethodRgb)) { //enhance mode
                                        memoryAllocationFailed = true;
                                    }
                                }
                            }

```

**Comment by agriggio** [comment]
@Beep6581 which is better quality?
![standard](https://user-images.githubusercontent.com/11982086/34454731-e1d25ada-ed71-11e7-8f50-89fe524cfb85.jpeg)
![high](https://user-images.githubusercontent.com/11982086/34454732-e56ca83a-ed71-11e7-93bd-379242363d05.jpeg)

**Comment by Beep6581** [comment]
@agriggio neither seems to have more noise than the other, #1 has more detail and #2 is nuked.
I wonder what the actual `levwav` difference is between the two (not the one in preferences, but the final computed value which was used) ...

**Comment by agriggio** [comment]
@Beep6581 right, so do you agree that "Quality" is a bad name in this case? 
Note: I agree with the rest of your points, but even if we don't know exactly the difference between Standard and High, calling it "Quality" is just misleading IMHO. "Level" is more neutral, and according to your analysis above, might also be more accurate.

**Comment by Beep6581** [comment]
@agriggio I agree that "quality" is an inappropriate name for `smethod`.

I haven't made up my mind on a better label yet.
"Level" is more appropriate for the `levwav` setting from Preferences.
What `smethod` does is choose between a single-method approach and a two-method approach, but those terms aren't super user-friendly either. Maybe it would be better to use a word which describes what they do, but... what do `WaveletDenoiseAllAB` and `WaveletDenoiseAll_BiShrinkAB` do in human terms?

Maybe "Conservative" and "Aggressive"?

**Comment by agriggio** [comment]
Well, I still think Level is good, but I'm fine also with "Strength" ;-)

**Comment by Beep6581** [comment]
@agriggio not sure I follow. Which one do you want to rename to "Level"?

If you want to rename "Quality" to "Level", that will conflict with `levwav` which, as you wrote above, should be moved, and which it appears should also be renamed from "number of passes" to "number of wavelet levels" or just "levels":
> why is the selection partially in the preferences and partially in the pp3? What about "Number of passes", going from 1 to 3, and remove the entry in preferences?

**Comment by agriggio** [comment]
I thought you wanted to kill the entry in preferences and have it hardcoded.
anyway, I just want quality to go away, whatever it takes :-)

**Comment by agriggio** [comment]
as agreed with @Beep6581 on IRC, we are settling for "mode" or "method" instead of "quality", with a renaming of the current "method" to "color space"

**Comment by Beep6581** [comment]
Reopened for docs.

**Comment by Beep6581** [comment]
Docs done http://rawpedia.rawtherapee.com/Noise_Reduction
Please open a new issue if something needs to be changed.
