### ISSUE TITLE
Make Preferences panel vertically scrollable

### ISSUE THREAD

**Issue by Stephan83c** [Beep6581/RawTherapee#3994]
Hello,

I have a laptop on linux and the preference windows is to big for my screen.
I can't clic on "OK" for validate, how can I validate ?

Maybe you should add a  scrollbar on this window. 

best regards.

Stéphan.

**Comment by Beep6581** [comment]
@Stephan83c 
1. Are you using RawTherapee 5.2?
2. Which desktop manager are you using? KDE Plasma for example allows you to alt+click a window to drag it around the screen.

**Comment by sguyader** [comment]
I have the problem on my low resolution laptop screen. Try this workaround: alt + left click anywhere on the preferences window and drag it towards the top: this allows to move freely any window where want, and to reveal the hidden bottom part and buttons.

**Comment by sguyader** [comment]
I have the problem on my low resolution laptop screen. Try this workaround: alt + left click anywhere on the preferences window and drag it towards the top: this allows to move freely any window where want, and to reveal the hidden bottom part and buttons.

**Comment by Stephan83c** [comment]
Thank you, it's working.

**Comment by afr-e** [comment]
`dev 5.4-641-g`c45c638ed on win10 from https://keybase.pub/gaaned92/RTW64NightlyBuilds/
Unfortunately, Windows doesn't have the `alt + left` trick. My workaround is to tab my way to the About-OK-Cancel row. I recall this wasn't a problem for me in `5.4-488...`.

**Comment by Beep6581** [comment]
I will try to do this when time permits, but if anyone wants to jump in, feel free.

**Comment by afr-e** [comment]
I took another look. It appears that

1. the padding is quite extreme
2. RT (or GTK3) ignores the space occupied by the Windows task bar and is obscured by it.

_Without the task bar. The tops of the 3 buttons are barely visible at the bottom._

![image](https://user-images.githubusercontent.com/42004791/43547874-8ba970f8-95aa-11e8-94d5-13bb0961b10e.png)

**Comment by Beep6581** [comment]
@afr-e please show a screenshot of your entire desktop, uncropped.

**Comment by afr-e** [comment]
Sure. With TooWaBlue, the padding is less but still too much.

_With task bar._

![image](https://user-images.githubusercontent.com/42004791/43549223-13597a36-95ae-11e8-9c10-f57684386396.png)

_Without task bar at bottom._

![image](https://user-images.githubusercontent.com/42004791/43549390-75ec1bfe-95ae-11e8-80b8-f5d8d5cea057.png)

_Default theme without task bar at bottom._

![image](https://user-images.githubusercontent.com/42004791/43549570-f2c45be6-95ae-11e8-9006-703774a1a729.png)

**Comment by afr-e** [comment]
**FYI**: I cannot resize the window vertically, nor does the position of the 3 buttons change when I shrink the font size. The padding increases instead!

**Update**: I just tried something different.

1. I unlocked the Windows task bar and moved it to the right side of the desktop. Suddenly, I was able to reduce the vertical size of the pref window.

2. Another thing that I did was make the pref window as tall as possible while the task bar was to the right and then moved the task bar back to the bottom. Miraculously, the 3 buttons popped upward into view!

I suppose these observations might give rise to the opening of another issue &ndash; perhaps for GTK3; but I will let you devs do it because I am unsure where it would fall under.

**Comment by TooWaBoo** [comment]
@afr-e 
If you change the font, font size or theme you always must restart RT.
The preferences window should fit to the screen if you use font size 9. (see screenshots)

1070px x 763px
![unbenannt](https://user-images.githubusercontent.com/13800920/43619845-052722f6-96d0-11e8-8bd8-a5d166ef0039.PNG)
1028px x 707px
![unbenannt2](https://user-images.githubusercontent.com/13800920/43619849-0a9b3f4c-96d0-11e8-9478-58dfdea86295.PNG)

PS: All your screenshots shows font size 10. Please cange it to **9**.

**Comment by afr-e** [comment]
Sorry for the confusion. My comment was after I followed your advice and restarted RT, although I uploaded the wrong screenshot (see next comment). The initial drawing of the window was extra tall, beyond the confines of the desktop space, because it didn't factor in the task bar. None of the preferences changed the height of the window and I couldn't resize it vertically; and the About-OK-Cancel group of buttons remained at the bottom of the window, despite how tall the rest of the contents were, and therefore hidden behind the task bar.

After moving the task bar, I was able to do everything. That is why I am saying that it might be a GTK3 or Windows 10 issue or both. Thanks for your patience. 👍 I will get better at writing these reports as I write more of them.

**Comment by afr-e** [comment]
To verify my experience,
1. I found and deleted the config file.
2. I changed the font size. Might I add that I tried restarting a few times before the setting went from 10 to 9, which might explain why my screenshot was still at 10.
3. I tried to resize the height of the prefs window but couldn't.

This is what I got.
![image](https://user-images.githubusercontent.com/42004791/43622569-c7dd6e52-96aa-11e8-880c-93f293a53ca1.png)

Moving the task bar to the right.
![image](https://user-images.githubusercontent.com/42004791/43622600-f8b57b5a-96aa-11e8-868a-eff2f87850df.png)

And back. This time, moving the task bar back doesn't snap the 3 buttons upward.
![image](https://user-images.githubusercontent.com/42004791/43622656-4e1c5690-96ab-11e8-9bb6-1b51c21203de.png)

This time, I cannot even change the height of the window. I don't know why that is. (All I could think of is that, last time, I didn't delete the config when changing versions.)

**Comment by afr-e** [comment]
>And back. This time, moving the task bar back doesn't snap the 3 buttons upward.
> [Image]
>This time, I cannot even change the height of the window. I don't know why that is. (All I could think of is that, last time, I didn't delete the config when changing versions.)

Oh, I just figured out why they didn't snap into view. Apparently, when TooWaBoo theme is active, this workaround works; i.e., move the task bar to the right and then back to the bottom with TooWaBoo as the theme. This doesn't work when the theme is RawTherapee.

**Comment by TooWaBoo** [comment]
You can change the height of a window also from the top. :-)
The TooWaBoo and RT theme work different. Changing the font size in the **RT theme** has no effect on min. window height. For your small monitor use the TooWaBoo theme with font size 9 or 8 (smaler = more free space) and use the font Arial. Arial takes less horizontal space.

**Comment by afr-e** [comment]
>You can change the height of a window also from the top. :-)

Exactly what I have been doing. I am quite thorough. ;-)

(The icons and spacing are greater in your themes compared with the default, making the functional space smaller, at least on my computer; but that is another topic for another time.)

**Comment by TooWaBoo** [comment]
... and here's a screeshot which should fit your monitor size.
![unbenannt](https://user-images.githubusercontent.com/13800920/43642852-67d61d0e-9729-11e8-9f5f-5e6c8abca014.PNG)
![unbenannt2](https://user-images.githubusercontent.com/13800920/43642769-24de61b4-9729-11e8-9925-1f60179e3011.PNG)

**Comment by afr-e** [comment]
Here is proof that I cannot resize the prefs window from the top if I use the RT Theme. If I use TooWaBlue, then I can do it.
![capture](https://user-images.githubusercontent.com/42004791/43645514-24d70d48-9700-11e8-8cae-b4c3edd21943.gif)

To address, the UI issue, which is kind of off-topic, switching to Multiple Editor Tabs Mode resolved the spacing issue.

Single Mode

![image](https://user-images.githubusercontent.com/42004791/43645792-fc592eb8-9700-11e8-8471-0ff431f43f99.png)

Notice how various elements occupy more room and the preview is being encroached upon (image is fit to screen but it isn't as you can see). This doesn't happen in Multiple Mode, where it is essentially the same as your screenshot.

**PS** It has been quite the chore exploring this stuff because my laptop is super slow. Everything I do takes 10 seconds of waiting time. So changing the settings, restarting, taking screenshots and double checking can take unreasonable amounts of time. But I hope this helps!

**Comment by TooWaBoo** [comment]
The Single-mode has more buttons in the bottom toolbar as the Multi-tab-mode. That's why it won't fit into your screen.

**Comment by afr-e** [comment]
Sure. However, it affects the size and positioning of all of the panels and tool bars. The fact that fit to screen doesn't fit the preview properly is evidence of this discrepancy. I tried to resize the panels but they either don't budge or bounce back. In any case, multi tab works for me and so I consider my editor view issue resolved.
___
Back on topic: I don't understand why I cannot resize the prefs window when in the RT Theme. As the default theme, it should be just as robust if not more than the TooWaBlue set. Also, having to change font size, theme, etc., just to see the About-OK-Cancel buttons is a non-starter for anyone coming to RT.

Adding a scroll button as suggested by _Stephan83c_ would not help because About-OK-Cancel buttons are behind the task bar and even below the screen itself. This should not be the case. In my screenshots, there is clearly enough space between the last vertical element and where the buttons end up. It is as if they are float justified to the bottom of the window. If the bottom window edge is behind the task bar or below the screen, then we have the problem that I have been encountering.

**Comment by TooWaBoo** [comment]
The preferences window issue is due to the tab File Browser.

**Comment by afr-e** [comment]
There is still a lot of padding there though... Anyway, I think I have reported all that I can. I will leave this in the devs' capable hands. Thanks for listening!

**Comment by Beep6581** [comment]
The Preferences window is now scrollable in branch [`prefscroll`](https://github.com/Beep6581/RawTherapee/tree/prefscroll), please test it.

**Comment by heckflosse** [comment]
Can we close?
