### ISSUE TITLE
Panasonic Lumix DC-TZ90 raw support

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#4004]
Raw sample available from https://raw.pixls.us/getfile.php/1629/nice/Panasonic%20-%20DC-TZ90%20-%204:3.rw2

**Comment by Beep6581** [comment]
The Panasonic Lumix DC-TZ90 has the following modes:
* 1:1
* 4:3
* 3:2
* 16:9

We already have the 4:3 ratio, @hettyme could you provide the other ones?

And finally, we need to measure the camera's white levels. Could you provide one shot where the whole frame is overexposed (i.e. shoot the sun or a lamp) for each major ISO value? This is explained in more detail here: http://rawpedia.rawtherapee.com/Adding_Support_for_New_Raw_Formats
I'm interested in points 1 and 2, you can skip point 3. And this whole thing needs to be done only for the camera's 4:3 ratio, we don't need it for the other ratios.

**Comment by LebedevRI** [comment]
> The Panasonic Lumix DC-TZ90 has the following modes:
> * 1:1
> * 4:3
> * 3:2
> * 16:9

since i was pinged, i should clarify that for https://raw.pixls.us/ we want such full set to be of some static scene, and it ideally should be shoot with stable (tripod or similar) camera.

**Comment by hettyme** [comment]
I’ll see what I can do tomorrow. This is all new to me. I just started yesterday with RawTherapee, because I wanted an app that can handle the new RW2 files. Tomorrow I’ll make some photos in the other formats.

On 6 Aug 2017, at 21:15, Beep6581 <notifications@github.com> wrote:

The Panasonic Lumix DC-TZ90 has the following modes:

1:1
4:3
3:2
16:9
We already have the 4:3, @hettyme <https://github.com/hettyme> could you provide the other ones?

**Comment by hettyme** [comment]
OK, Roman, give me some time to read and understand what is needed and I’ll see to it.
I’ll get my tripod ready.


On 6 Aug 2017, at 21:48, Roman Lebedev <notifications@github.com> wrote:

The Panasonic Lumix DC-TZ90 has the following modes:

1:1
4:3
3:2
16:9
since i was pinged, i should clarify that for https://raw.pixls.us/ <https://raw.pixls.us/> we want such full set to be of some static scene, and it ideally should be shoot with stable (tripod or similar) camera.

**Comment by Beep6581** [comment]
@hettyme for RawTherapee's needs, we need completely clipped (overexposed so much that they're just white) shots at every ISO level, one set with LENR off, one set with LENR on. See the link in the previous comment for more info. You just need to take the shots, we will measure them. That gives a total of 16 shots (80 100 200 400 800 1600 3200 6400 with LENR=off, and the same with LENR=on). Zip them, they will compress very well if they're completely clipped.

For raw.pixls.us 's needs, take only 1 well-exposed shot (not clipped) of a static scene for each crop mode. That Chinese lucky cat is a good scene. That gives a total of 4 shots (1:1, 4:3, 3:2, 16:9).

By doing this, you're helping not just RawTherapee but all libre projects interested in supporting that camera.

**Comment by hettyme** [comment]
OK. I’ll see to it.


On 6 Aug 2017, at 21:58, Beep6581 <notifications@github.com> wrote:

@hettyme <https://github.com/hettyme> for RawTherapee's needs, we need completely overexposed shots at every ISO level, one set with LENR off, one set with LENR on. See the link in the previous comment for more info. You just need to take the shots, we will measure them. That gives a total of 16 shots (80 100 200 400 800 1600 3200 6400 with LENR=off, and the same with LENR=on).

For raw.pixls.us 's needs, take only 1 well-exposed shot of a static scene at each crop mode. That Chinese lucky cat is a good scene. That gives a total of 4 shots (1:1, 4:3, 3:2, 16:9).

By doing this, you're helping not just RawTherapee but all libre projects interested in supporting that camera.

**Comment by iliasg** [comment]
@hettyme @Beep6581 

Preliminary support item included in the below attached camconst.json (replace your existing camconst.json with it)
[camconst-tz90.zip](https://github.com/Beep6581/RawTherapee/files/1203408/camconst-tz90.zip)

**Comment by Hombre57** [comment]
@Beep6581 @iliasg Does the shots for raw.pixls.us need to be a daylight scene or can I provide shots under tungsten light ? My dad has a TZ91 for 2 days now, and I'd like to see it supported by RT :) . I guess that there's no difference between TZ90 & TZ91.

**Comment by iliasg** [comment]
@Hombre57 

Yes, TZ90-91-92-93 are the same model named differently.

For the 4 aspect ratio shots we just need well lit shots so that the transition from exposed to not exposed pixels is easy to find.

For the totally_overexposed shots (with LENR ON and OFF) it's good to have samples at all ISO settings available (80-100-125-160-200 ...)

**Comment by Beep6581** [comment]
@Hombre57 RPU (raw.pixls.us) want "normal" photos, only 1 photo per raw mode (full-frame, cropped, small-raw, etc.). For our [camcons.json](http://rawpedia.rawtherapee.com/Adding_Support_for_New_Raw_Formats) needs I guess you know the drill :)

**Comment by Hombre57** [comment]
@iliasg The raw files can be found here : https://filebin.net/yqc0n4ac1yshftqv
I took the LENR OFF shots first, but given my low cerabral activity these days, I took 1EV increment first, then found out that I could turn on 1/3EV. That's why the intermediate values have been taken in a second batch.

For the LENR ON shots, they have been taken all in a single batch. However some birds crossed the sky while I was taking some of them, do not be surprised if some pixels have not reached their full capacity (however it is very unlikely). You'll notice that if the first ones have 2" exposure time, the last ones have 1" exposure time and the very last one has no LENR. Those are limitations done by the camera (it doesn't allow to shoot 2" with high ISO, I was in full manual mode).

@Beep6581 Is it worth to upload different crop size given that the raw files are the same ? The embedded preview is the exact same size and I don't see any difference in Metadata (as seen in RT, might be different with exiftool). Anyway, you'll find them at the same location if you want to examine them by yourself.

If the wether is sunny Saturday or Sunday, I'll try to create a DCP file.

**Comment by iliasg** [comment]
TZ91 camconst.json item is ready https://github.com/Beep6581/RawTherapee/issues/3988#issuecomment-332020846

**Comment by Beep6581** [comment]
@Hombre57 apologies, I didn't see your question. It would only make sense uploading a sample of a different crop size so that we can confirm that it's otherwise identical.
Have you had an opportunity to take the color target shots in daylight and tungsten?

**Comment by Hombre57** [comment]
@iliasg Thanks a lot !

@Beep6581 Yes, it's here : https://filebin.net/p7djduzb77eo8zi5, there are 1 for daylight and 2 for tungsten can't choose.

**Comment by Beep6581** [comment]
The raw data between different crop sized raws looks identical in RawDigger.

**Comment by Beep6581** [comment]
@Hombre57 @Floessie 
![screenshot_20180414_135821](https://user-images.githubusercontent.com/5844619/38768072-448a4c04-3fee-11e8-96c1-04e88af1973f.png)
![screenshot_20180414_135828](https://user-images.githubusercontent.com/5844619/38768073-47e7c200-3fee-11e8-916c-89a893760541.png)
