### ISSUE TITLE
operator delete(): rawtherapee killed by signal 6

### ISSUE THREAD

**Issue by mattiaverga** [Beep6581/RawTherapee#4057]
A user on Fedora has just experienced a crash.
He's not posted any detail about it, but there's a full backtrace available at https://bugzilla.redhat.com/show_bug.cgi?id=1487963

Let me know if these type of reports are useful to you. There are occasionally some of these crashes reported to Fedora bugzilla, I don't know if it's ok for you if I report them here.

**Comment by Hombre57** [comment]
@mattiaverga Yes this is usefull. I'm busy actually so won't have time to look before next week, unless someone else assigns itself.

**Comment by Hombre57** [comment]
@mattiaverga Is it possible that the bug's OP comes here to provide more information and answer some questions ?
   1. Could you try with current version 5.3, the RTExif module has been modified since then
   2. Does it occur every time for some images, or occasionally even with a given image ?
   3. If always reproducible with an image, could you upload it to filebin (or other file sharing service) as well as the pp3 and your `options` file ?
   3. Could you post your AboutThisBuild.txt file here

**Comment by mattiaverga** [comment]
I'll try to contact the OP and get some more clarifications.
In Fedora 26 we're still using 5.2, so it may be possible to reproduce the bug.

**Comment by Beep6581** [comment]
No response from OP ("mid"), closing.
