### ISSUE TITLE
Half-resolution demosaicing

### ISSUE THREAD

**Issue by hakkyou** [Beep6581/RawTherapee#4077]
It would be great to have half-res demosaicing a-la RPP.
In this type of demosaicing each 2x2px square containing similar bayer pattern (RGGB/RGWB, you name it) produces one pixel of demosaiced image. Crispy images, fast demosaicing, less res.

**Comment by heckflosse** [comment]
You mean Quarter-resolution I guess

**Comment by heckflosse** [comment]
Pixel binning currently is not on our todo list.

**Comment by hakkyou** [comment]
Looks like it's very easy to implement.
Is there any trouble to make resulting image smaller than pre-demosaiced?
If not, I can rewrite nodemosaic a bit and make a pull request.

**Comment by heckflosse** [comment]
pull requests are always welcome :+1:

**Comment by Benitoite** [comment]
@hakkyou I use `dcraw -h -T -4` for all my super pixel needs, having something like that in RT would be nice.

**Comment by Beep6581** [comment]
Usability-wise, this feature would be a competitor to RT's Fast Export. The advantage of Fast Export in Dedicated mode is that it can downscale the demosaiced image in the first step to any size the user wants, so that further processing is much faster. This feature doesn't give the user the option of downscaling to any size, it's only half-size or nothing. I believe pixel binning is also more prone to aliasing. @hakkyou have you tried Fast Export in Dedicated mode and, if so, what's missing that this seemingly less flexible method has to offer?
