### ISSUE TITLE
Exported JPEG does not match editor version

### ISSUE THREAD

**Issue by definitelyhuman** [Beep6581/RawTherapee#4126]
Saw the version release on HN (https://news.ycombinator.com/item?id=15380299), downloaded from that link.
Raw Therapee: Version: 5.3 Branch: 5.3 Commit: ec0f7936
Host: 2016 MBP 2.6ghz i7 16gb Radeon Pro 450 2gb/Intel 530 1.5gb OS X 10.12.6

I am a newb to RT, and my strategy was to open a file and smash settings all over the place, then save then save the result. While the settings were not deliberate, I thought it noteworthy that the input <> output. Screenshot attached to show what I see, in addition to output and input (D800 f2.8 38mm NIKKOR 24-70mm)

<img width="2019" alt="screen shot 2017-10-01 at 9 18 02 pm" src="https://user-images.githubusercontent.com/26014353/31061546-9b66bb9e-a6f0-11e7-9c66-e9e1e07539c5.png">
[input.zip] https://www.dropbox.com/s/jr2ygiv2x0c70fa/input.zip?dl=0
[output.zip](https://github.com/Beep6581/RawTherapee/files/1347719/output.zip)

**Comment by gaaned92** [comment]
@definitelyhuman What you are looking at is the undemosaiced image (raw pattern). I really dont know what happens when you output a jpg inthat situation.
You have to choose a demosaicer. here it is Amaze
![screen-2017-10-02_14-52-10](https://user-images.githubusercontent.com/13785581/31078394-3f94b374-a782-11e7-929d-8ed604905830.jpg)

Once here, you can adjust the image to your taste. Then generate an output file (jpg, tiff).
For documentation see rawpedia

**Comment by Beep6581** [comment]
Thank you for the good report. However, the preview does match the saved image, no bug here.

When it comes to not using demosaicing at all, which is what your PP3 does, you are no longer dealing with "ordinary" colors, but with a bayer pattern. What happens when you view that at any zoom level less than 100% is up to the scaling algorithm. Some will make the result lighter than others.

Another things that's happening is that you're viewing the image in RT at less than 100% and expect it to look identical to the saved image, when you're using some tools which are marked as "1:1", specifically "Raw tab > Sensor with Bayer Matrix > Raw Black Points". The tooltip tells you that "The effects of this tool are only visible or only accurate at a preview scale of 1:1.".
