### ISSUE TITLE
Resize - Scale slider wrong in batch edit

### ISSUE THREAD

**Issue by jtappin** [Beep6581/RawTherapee#4138]
In the batch edit tab (from the file browser) when setting resize by scale, there are what seem to be two (probably related) issues.
Firstly: the range of the slider goes from -3.99 to 3.99, when logically it should start from 0.
Secondly: to halve the size of an image I had to set it to -0.5 (+0.5 scaled the image up by a factor of 1.5).

While I doubt that the image type is relevant here, I was reducing TIFF images and resaving them as tiffs

How to cause the problem:

1.  Select a directory with several 16-bit TIFF files (mono in my case). I expect it applies to all types.
2. Select all files.
3. Select the batch edit tab and the the crop/resize sub tab
4. Enable resizing, and select "Scale"
5. Enter (by slider or in the box) 0.5
6. Right button -> Put to queue.
7. Go to the queue tab and select TIFF (16 bit) as output mode  -- probably not needed
8. Start the processing.
9. Keep an eye on the target directory.

Should see: new files with image size half of the orginals
Do see: new files with image size 1.5 times the originals.

The resize in the EDITOR tab does not show either of these problems.

**Comment by heckflosse** [comment]
@jtappin Please read [this](http://rawpedia.rawtherapee.com/Preferences#Batch_Processing_Tab), especially the sections about `Add` and `Set` Mode

**Comment by jtappin** [comment]
Is this a new feature as of about 5.3? As the last time I was bulk-reducing medium format scans there was no problem, and I certainly didn't **knowingly** change any batch processing settings.

**Comment by heckflosse** [comment]
No, afaik that's on old feature. Ping @Beep6581

**Comment by Beep6581** [comment]
@jtappin 
- When in "Add" mode, the slider goes from -3.99 to +3.99.
- When in "Set" mode, the slider goes from 0.01 to 4.

No bug there.

In all versions of RawTherapee prior to 5.3 there was a bug which sometimes caused the Add/Set values to be "Add" by default when they should have all been "Set" by default. This is fixed in 5.3, though some of the values may still be "Add" if you're using an [options file](http://rawpedia.rawtherapee.com/File_Paths#Config) from previous versions of RT.

I recommend deleting the old options file (while RT is turned off) so that you start with a new, clean one for 5.3. You need to do this only once.
