### ISSUE TITLE
Before/after syncing both views on filter on/off

### ISSUE THREAD

**Issue by lwann** [Beep6581/RawTherapee#4180]
Version: 5.3 Sept. 30 2017
Steps:
- load any file from any camera
- Enable the Before/After view
- make sure unlock is set (and not lock naturally)
- make some changes somewhere to see a clear difference with the original file
- turn on or off any processing filter
- both views are now identical

This can be repeated any number of time. Tweak again, enable or disable a filter > both views sync'ed.

I don't think a screenshot or a raw file will help, this is consistent on my new D500, my old 350D and my wife's Canon 60D raw files (and alos JPEG for what it's worth). It seems to be a bug in keeping the before view unsync'ed when a processing filter is turned on or off.
I did run a search through the issues forum without finding anything similar.

Thanks!

**Comment by heckflosse** [comment]
That's correct behaviour.

Example 1:

load any file
Enable Before/After view
don't lock
make some changes to see a clear difference...
turn on Shadows/Highlights
both views are identical now because the default settings of the sliders in Shadows/Highlights don't change the output

Example 2:

load any file
Enable Before/After view
don't lock
make some changes to see a clear difference...
turn on Black-and-White
both views are different now because the default settings of the Black-and-White tool change the output

**Comment by Beep6581** [comment]
The "Before" view is replaced with the "After" view every time a new history item appears. It is not replaced when the latest history item is changed.
Tested in latest dev, works correctly.

**Comment by lwann** [comment]
Alright, I found that odd because most of the time that I use a before/after view is to make sure the noise reduction and sharpening is not beyond acceptable compared to the original file. Usually that 'the' point where you want to make sure the result is going to be acceptable and has not degraded into a painting effect. I guess I still have some old camera raw habits :)
Then instead of an issue that would be a feature wish to have maybe a checkbox to 'show original'?

**Comment by Beep6581** [comment]
What is "original"?

**Comment by lwann** [comment]
The unedited file, prior to any change (this gives you a good idea if you indeed cranked sharpness and denoise too much or if it's just your brain)

**Comment by Beep6581** [comment]
A **raw** file is always edited when viewed (even if you go to the Raw tab and select Demosaicing > None, it's still had an input profile applied, transformations, etc). Something must be done in order to see the raw file. The best translation for your thought would be to show the image as it looked like at the beginning of the history stack, but that is easily doable now - just click the beginning of the history stack. Optionally lock the "Before" view if you want to make other edits.
