### ISSUE TITLE
GUI locale generateTranslationDiffs issue

### ISSUE THREAD

**Issue by TooWaBoo** [Beep6581/RawTherapee#4242]
There's an issue with generateTranslationDiffs.
bayerprocess.cc contains following lines:
```
//    pixelShiftOneGreen = Gtk::manage (new CheckBox(M("TP_RAW_PIXELSHIFTONEGREEN"), multiImage));
//    pixelShiftOneGreen->setCheckBoxListener (this);
//    pixelShiftOneGreen->set_tooltip_text (M("TP_RAW_PIXELSHIFTONEGREEN_TOOLTIP"));
//    pixelShiftOptions->pack_start(*pixelShiftOneGreen);
```
generateTranslationDiffs include the commented keys in the locale files.
```
TP_RAW_PIXELSHIFTONEGREEN
TP_RAW_PIXELSHIFTONEGREEN_TOOLTIP
```

**Comment by Beep6581** [comment]
It's not an issue with `generateTranslationDiffs` as the script doesn't scan source files, and doing so would be impossible without parsing C++. Scanning source files is `generateUnusedKeys` job, though it requires human intervention due to not parsing C++.

Those two keys are in the locales because they are in `default`, and they should stay in `default` as long as the commented-out code is there. When the code is deleted, the keys should be deleted.

**Comment by TooWaBoo** [comment]
Ok
