### ISSUE TITLE
Add an option to select a default profile of HDR images in Preferences

### ISSUE THREAD

**Issue by dnw3039** [Beep6581/RawTherapee#4282]
As the new HDR Tone Mapping works best if Auto Levels is not applied, and HDR files are already identified in the file browser, it might be useful to have a default profile for HDR images, that has Auto Levels = off and HDR Tone Mapping = on, and allow of any other setting users may want to add to HDR processing.

This would save the of having to select the Neutral  profile as the first step in HDR editing.

**Comment by Beep6581** [comment]
Hmm...
HDR Tone Mapping does not necessarily need to be used just because a raw file happens to come from HDRMerge. As such:
- We could disagree about the request,
- We could agree and add new options to the "Default processing profiles" panel,
- Or we could even phase out the "Default processing profiles" panel and instead enhance the "Dynamic profile rules" feature with a filter for non-raw, raw, HDR, PS, etc., and use it to set the default profile for raw and non-raw photos.

**Comment by Beep6581** [comment]
Solved by issues #4456 and #4488

**Comment by heckflosse** [comment]
Reopened because the changes are not committed

**Comment by Beep6581** [comment]
Assigning a dynamic profile to HDR files is already possible, and #4901 makes that even easier.
