### ISSUE TITLE
A new "advanced tools" tab?

### ISSUE THREAD

**Issue by agriggio** [Beep6581/RawTherapee#4298]
Many people who try RT for the first time often say that it seems powerful but also too complex to use / intimidating. I think there is some truth to that, but on the other hand, it is good to have powerful tools if you know how to use them.
So, I was thinking, what about having a dedicated tab for "advanced" tools? For example we could rename the wavelets tab to "advanced" or "expert" tools, and move e.g. retinex and ciecam02 in there, and possibly also "channel mixer".
What do you think? @Desmis, @Beep6581, how does this sound? (also the others @Hombre57 @heckflosse @Floessie of course)

**Comment by Floessie** [comment]
What about collapsing the "advanced" tools (what's advanced and what's basic might vary with each of us) by default (after installation)?

**Comment by Desmis** [comment]
Some time ago, Hombre had proposed something similar, with a choice "current", "expert", "math". (or something similar)
**For my part I am in favor.**

But, both in the "issues" and on the forum, some opposed to saying for example that a tool is complex only if it was not understood or used enough

**Comment by Beep6581** [comment]
@agriggio have you seen #2631?

**Comment by Beep6581** [comment]
By the way, as Retinex only works on raw files, it should be set to insensitive when opening a non-raw file, consistently with the Raw tab.

**Comment by agriggio** [comment]
@Beep6581 I hadn't seen that, no. Thanks for the pointer. But I think it went nowhere, right?
What I'm proposing here is much simpler than a full support for UI customization. That would be great, but who is going to do that? (hint: not me :-)

**Comment by agriggio** [comment]
Anyway, reading some more comments on #2631, and also to answer other questions asked above: I believe that certain tools are clearly more complex to use than others. Either because they have more parameters, or because it's easier to "shoot oneself in the feet", or because they are useful mostly in special situations. This doesn't make them bad or useless (on the contrary, they can be *extremely* useful in the right situations), but I think it just doesn't make sense for newcomers to consider them at the beginning. Having these more advanced tools grouped together in their own tab (**not** hidden!) would help, IMHO.

It's like, when you start learning English, you don't start from type 3 conditionals, don't you? And yet, nobody says they're useless... :-)
That's just MHO, of course.

**Comment by Beep6581** [comment]
Personally I have no interest in a customizable UI, I just wanted to point the issue out.

My position has always been that all tools are advanced until one learns how to use them - curves make a good example. However I agree that some tools like CIECAM02, Retinex, Wavelets and the seemingly-simple-but-not-quite Channel Mixer would belong well in an Advanced tab. What motivates my support for the idea is not only that, but also the "problem" that CIECAM02 and Retinex don't really belong in the Exposure tab since they have dedicated controls also for color. While they don't clearly belong in the Exposure tab, they do clearly belong in an Advanced tab.

I just wouldn't want an Advanced tab to turn into an excuse for including arcane and untestable tools.

**Comment by Hombre57** [comment]
Powetools like Retinex and Wavelet are way easier to understand with a proper GUI that makes things self explanatory. We're not there yet, we have to spend some time to master these tools and then work on the GUI to make things more evident. Probably a new issue to open.

On the short term, I agree with @Beep6581 that CIECAM, Retinex and Wavelet are kind of _all purpose_ tools that can't be part of Exposure or Color tab, but same apply to Lab and Exposure tool : they have a Saturation slider that act on color, not only exposure.

Maybe that, by the time, the label of the tab don't suite the tools anymore. What about renaming them like this, so that it shows some kind of workflow, not the nature of the tool :

General
   - Exposure
   - Local Contrast
   - Highlight/Shadows
   - EPD
   - HDR Compression
   - ICM

Effects
   - Gradient
   - Post-crop Vignetting
   - Color Toning
   - RGB curves
   - Channel Mixer
   - Film Simulation
   - Black & White
   - HSV Equalizer

Power Tools
   - Contrast by Detail Level
   - Retinex
   - Wavelet
   - CIECam

Pixel Peep
   - Denoise
   - Sharpen
   - Microcontrast
   - Impulse Denoise
   - Borders

Geometry
   - _(same as today, excepted that it would receive Purple Fringing tool too)_

Raw
   - _(same as today)_

Metadata
   - _(same as today)_

Maybe I forgot some tools, but you get the idea.

**Comment by Beep6581** [comment]
My opinion is that a change is worth it if it's clearly superior to the way things are now, making the benefit of the new arrangement outweigh the problems caused by forcing users to re-learn where to find which tool.

As I wrote [here](http://rawpedia.rawtherapee.com/Getting_Started#Advanced), while we could agree that one typically starts off by using the White Balance + Exposure tools, the order of things quickly becomes impossible to define. And even this example is flawed, because you might actually start off by setting the raw parameters such as demosaicing, flat-field, dark-frame, etc. A workflow-based arrangement is impossible. The order of things in the pipeline is also not stable, and while I would like to have it documented (hopefully after the pipeline unification), I don't think having the UI reflect it would necessarily be better for the user.

I agree that renaming the "Wavelet" tab to "Advanced" and moving the most sophisticated tools into it would be an improvement, and it would not cause much confusion. But rearranging all tools would only be worth it if the new arrangement was significantly superior to what we have, and I'm not aware of such an arrangement yet.

So if Retinex, CIECAM02, Wavelets and Channel Mixer(?) are in "Advanced" or "Expert", that leaves us with only one little itch to scratch... L\*a\*b\*. I personally cannot imagine life without the Lab tools and would find it odd if they were far away from the Exposure tool. This could be solved by:
- ignoring the itch.
- renaming the "Exposure" tab to "Tones".

I'm leaning towards ignoring that particular itch.

**Comment by agriggio** [comment]
@Beep6581 :+1:, I very much agree

**Comment by Desmis** [comment]
In this type of debate, the cognitive logics clash.

if we group together what is the underlying logic:
* process (once we understand all the features)
* ease of understanding - what is it for?
* ease of use - how to use it ?
* grouping by photographic functions (luminance, color, noise, etc.)
* etc.

These points are deeply modified by learning and training (tutorials, Rawpedia, videos, forum sharing, etc). What was difficult, complex becomes simple

The ideal would be a product with artificial intelligence such as "Deep learning" which reconfigure the architecture according to the evolution of the skills of the user.

Obviously it seems today utopian :)

In the current state of things DrSlony's proposal is reasonable.

jacques

**Comment by agriggio** [comment]
I just pushed a branch `advanced-tools`, which renames the wavelet tab to "advanced" and moves there also retinex, ciecam02 and channel mixer. 
Let me know how it feels -- we easily throw it away if you think it doesn't improve the situation.

**Comment by Beep6581** [comment]
Feels good.

What do you think about setting the initial (fresh install) state of all tools to collapsed?

**Comment by agriggio** [comment]
> What do you think about setting the initial (fresh install) state of all tools to collapsed?

Not sure about that. What about collapsing most of the tools, but leave the really basic ones open? E.g. exposure, wb, crop, resize.

**Comment by Beep6581** [comment]
My intention is to:
* Prevent slider-shock,
* Make all tools in the tab visible,
* Not cater to any particular skill level, certainly not the lowest common denominator.

**Comment by agriggio** [comment]
> Not cater to any particular skill level, certainly not the lowest common denominator.

Why not? That's what new users are, by definition (regarding their skills in RT, of course). If you're not a new user, the default won't matter anyway, as you already have your `options` file in place with the state of all the tools...

**Comment by Beep6581** [comment]
Ok, good point. Then it makes sense to have the four tools you listed expanded.

**Comment by agriggio** [comment]
Ok, I'll do that. Do we also need a new icon for the advanced tab? (I can't help here though)

**Comment by Beep6581** [comment]
I can help with that. Any ideas?

**Comment by agriggio** [comment]
> Any ideas?

how about a comlpex multiband equalizer?

**Comment by Beep6581** [comment]
I was thinking of a little Albert Einstein head, but with only 22 pixels to work with we can have pacman or a simplex monoband equalizer at best ;)

**Comment by Beep6581** [comment]
An abstraction of this could be nice:
https://i.imgur.com/pNbKlli.jpg

**Comment by agriggio** [comment]
How about something like this?  https://goo.gl/images/TzMNoe
should fit in 22pix maybe?

**Comment by Beep6581** [comment]
There's also this one:
http://fontawesome.io/icon/sliders/
Those icons tend to be used for "Settings", as in "Preferences".

**Comment by agriggio** [comment]
@Beep6581 you're right, I forgot about preferences. Then I'm out of ideas...

**Comment by Beep6581** [comment]
@agriggio odd, now when I open your link I get a completely different image than I got before...
I'll take care of this. Don't wait for the icon if you want to commit, go ahead and I'll commit directly to dev.

**Comment by agriggio** [comment]
@Beep6581 I'd like to get further testing from other people before committing -- perhaps I forgot something...

**Comment by heckflosse** [comment]
@agriggio I will test after the fattal stuff...

**Comment by Hombre57** [comment]
@agriggio I'll test tomorrow.

**Comment by Desmis** [comment]
@agriggio 
I'll test today

**Comment by Desmis** [comment]
@agriggio 

All seems to work well :)
I should prefered, to have the four in "expert", collapsed, to have a better visibility...But if not, no problem 

Jacques

**Comment by agriggio** [comment]
Thanks all for testing! 
Indeed the tools should be collapsed by default. One more thing: what about moving also color toning there? Opinions?

**Comment by Beep6581** [comment]
I have opinions :)
I think CT sits very snugly in the Color tab.

**Comment by agriggio** [comment]
good, less work to do :wink:

**Comment by Desmis** [comment]
Same questions for Black and White, in "expert" or not ?

**Comment by Beep6581** [comment]
I... have to take the dog for a walk ;)

**Comment by Floessie** [comment]
Okay, I gave it a quick look, and yes, I like it. Not so much scrolling and searching anymore. Some remarks, though:

- Having a simple tool like the channel mixer in "Advanced" doesn't make much sense to me. Why not color toning or edges, too?
- While we are at reordering tools, why not move the very important color management up right below WB?
- I always look for defringe in the "Color" tab, though it's located in the "Detail" tab. I guess, I'm not the only one.

@Beep6581 
> I... have to take the dog for a walk ;)

Lucky you. 😃 

Best,
Flössie

**Comment by Desmis** [comment]
I agree, for "Color management" near White Balance :)

**Comment by agriggio** [comment]
I don't see how channel mixer is simple, sorry... maybe I'm too simple :-)

**Comment by Floessie** [comment]
And I don't see how it's advanced. As @Hombre57 proposed above, it's more an "effect", a tweaking tool, and often gives a nice result when used with small numbers. I use it for fun to give an image a final color touch (more sunset-like, less greenish, colder...). There are surely more sophisticated tools to that, but tweaking with the channel mixer feels easier for me.

**Comment by Desmis** [comment]
The problem is always the same. it is easy if we don'used it, or summary.
It's difficult if we don't understand the goal. Deap lurning of "channel mixer" is complex, more if you research special effects. 

For having designed it, the Channel Mixer module of Black and White is much more complex

**Comment by Hombre57** [comment]
I think we should rather think of "advanced" by reference to the tool's GUI, i.e. monolithic tools with folders and subfolders. So I wouldn't put Channel Mixer in advanced tab, it's [not more/as] complex to get a predictable result from it than from e.g. RGB curves.

I have no opinion about WB's tool, it could be part of both tab.

And for ICM, I'd even put it on first place in Color tab.

**Comment by agriggio** [comment]
So, what is the consensus here? Put the channel mixer back to the color tab, and move the color management tool right after WB?

For the icon, how about something like these?
![atom](https://user-images.githubusercontent.com/11982086/35152282-16918470-fd22-11e7-9ee2-b1516751b49e.png)
![flasks-couple-of-different-shapes-with-liquids-inside](https://user-images.githubusercontent.com/11982086/35152283-16ae7328-fd22-11e7-82a3-ad522d39d762.png)
![microscope-scientific-tool-side-view](https://user-images.githubusercontent.com/11982086/35152284-16c58a72-fd22-11e7-93a7-521bca4e6f68.png)


<div>Icons made by <a href="http://www.freepik.com" title="Freepik">Freepik</a> from <a href="https://www.flaticon.com/" title="Flaticon">www.flaticon.com</a> is licensed by <a href="http://creativecommons.org/licenses/by/3.0/" title="Creative Commons BY 3.0" target="_blank">CC 3.0 BY</a></div>

**Comment by Desmis** [comment]
For me !
* only Retinex, Wavelet, Cieacm in expert
* move color management near WB
* first or third icon
Jacques

**Comment by Beep6581** [comment]
@agriggio I like the atom icon best _at that resolution_, but it does not look like an atom at 24px wide (the icon is 24px wide, the image inside it is ~20px wide).
The licence could be a problem. I saw no mention of CC on that site, I did find this:
https://file000.flaticon.com/downloads/license/license.pdf

Here's a WIP of https://github.com/Beep6581/RawTherapee/issues/4298#issuecomment-357705021
https://filebin.net/m240xeqq3xckbpsw/expert.svg

**Comment by agriggio** [comment]
I also like the atom. I think there are many around the Web, some of which CC0. those are cc-by, as the text below them says (I cut & pasted following the instructions when I downloaded them)

**Comment by Beep6581** [comment]
I finished making three possible icons, please choose:
![equalizer-wide](https://user-images.githubusercontent.com/5844619/35185743-438191c2-fe09-11e7-9d77-a43db2579c55.png)
![equalizer-narrow](https://user-images.githubusercontent.com/5844619/35185744-43a4aee6-fe09-11e7-969a-bce2843be891.png)
![atom](https://user-images.githubusercontent.com/5844619/35185745-43c4bd94-fe09-11e7-8994-00d084ba2516.png)

**Comment by Desmis** [comment]
for me the N°3 "atom"

**Comment by heckflosse** [comment]
👍 for atom

**Comment by agriggio** [comment]
both the 2nd equaliser and the atom look great to me!

**Comment by Beep6581** [comment]
I'll commit all since they can be used in the future, and leave it to you to choose which one to use for the Expert (or Advanced?) tab.
I'm most fond of the atom as well.

**Comment by agriggio** [comment]
@Beep6581 great, as soon as you put the icons in I'll merge then.

**Comment by Beep6581** [comment]
@agriggio ok, I'll upload them in the proper places tomorrow!

**Comment by Beep6581** [comment]
Done.

**Comment by agriggio** [comment]
merged
