### ISSUE TITLE
Improvement of histogram matching

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#4341]
I ran into an issue - I wanted to point it out and see what you think.

When going through photos using the new default profile, where most of these photos were low key concert photos, the auto-matched curve would often have a wonky end - see this real example:
(Embedded JPEG viewed in Geeqie on the left, RT with an auto-matched curve on the right)
![imgur-2018_01_29-21 07 50](https://user-images.githubusercontent.com/5844619/35531849-84262f7c-0538-11e8-9ec3-5711dccf23d4.png)
Despite the wonky curve, the image looks fine, better than the JPEG.

However, just about all of my photos needed added exposure compensation, and this is when the wonky curve becomes a problem:
![imgur-2018_01_29-21 06 36](https://user-images.githubusercontent.com/5844619/35531780-545c6180-0538-11e8-8673-f019a2b1c486.png)
The highlights (most visible on the arm and instrument) become ugly.

I had to de-wonk the curve in each photo. After several photos, I switched my default profile from "Auto-Matched Curve" to "Standard Film Curve" so that further tweaking would be easier.

Points 3, 4 and 5 all have O=63.529. Perhaps it would solve the issue if there was a condition which would prevent adding a new point if that point would have an output value equal to the previous point.

![imgur-2018_01_29-21 16 53](https://user-images.githubusercontent.com/5844619/35532211-c18660fc-0539-11e8-9b7b-78ec99036fe9.png)

**Comment by agriggio** [comment]
the problem is anchoring at 1,1... don't say I didn't tell you ;-)

p.s. if you look at the code there are heuristics for deciding whether to skip points that are in a plateau. but they are just heuristics, so by definition there will always pics in which this fails.

this said, I'll try to tweak them. if you can share a problematic raw, I'll see what I can do...

**Comment by agriggio** [comment]
Here's a patch that tries to mitigate the problem. Please test.

```diff
diff --git a/rtengine/histmatching.cc b/rtengine/histmatching.cc
--- a/rtengine/histmatching.cc
+++ b/rtengine/histmatching.cc
@@ -120,6 +120,15 @@
         curve.pop_back();
         curve.pop_back();
     }
+    // remove the plateau at the end (if any)
+    size_t j = curve.size() / 2;
+    for (; j > 1; --j) {
+        if (std::abs(curve[2*(j-1)-1] - curve.back()) > 0.01) {
+            break;
+        }
+    }
+    curve.resize(2*j);
+        
     curve.push_back(1.0);
     curve.push_back(1.0);
         
```

**Comment by Beep6581** [comment]
Points from IRC regarding issues with histogram matching:
1. It's not good that the curve shape depends on parameters from the raw tab,
2. It's worse that the shape of the curve depends on the options file (Preferences > Performance & Quality > Preview demosaicing method)
3. Its also not good that once I open an image and a curve shape is generated, if I then toggle raw CA correction for example, the curve changes. It changes even though it was already set. https://filebin.net/a38mr1i4j4x2zffl

**Comment by heckflosse** [comment]
@Beep6581 

> It's not good that the curve shape depends on parameters from the raw tab

To change that, we have to define, at which step in processing the curve matching should happen.

> It's worse that the shape of the curve depends on the options file (Preferences > Performance & Quality > Preview demosaicing method)

To change that, we have to define, at which step in processing the curve matching should happen.

> Its also not good that once I open an image and a curve shape is generated, if I then toggle raw CA correction for example, the curve changes. It changes even though it was already set.

To change that, we have to define, at which step in processing the curve matching should happen.

Suggestions which don't slow down the process are welcome.

**Comment by agriggio** [comment]
I just pushed a branch `histmatching-internal-demosaic` to fix the points raised by @Beep6581. This is done by demosaicing the image again when doing histogram matching. I am still not sure this is the "right" way though. If we decide to use this, I would propose to have an option (under "performance and quality") to reuse the demosaiced image instead of re-remosaicing. I know I will use this, because the differences are minor and to me the performance hit is annoying (especially when I'm on my old laptop...)

**Comment by agriggio** [comment]
I thought about this a bit more, and I convinced myself that re-demosaicing is the most robust thing to do in general. so I'm now +0.5 to have this for 5.4. there's still the performance issue to be addressed though, that's why I'm not +1 yet. I'll think about ways to avoid the re-demosaicing whenever possible. for example, when there was no CA correction, the demosaicing used was the fast one, and highlight recovery was not colour propagation, then there's no need of re-demosaicing...

**Comment by agriggio** [comment]
@Beep6581 @Hombre57 @Floessie @heckflosse 
I just noticed that for some reason the commit of the `histmatching-internal-demosaic` branch appears also on `dev`. I don't know why it is so, it was definitely not intentional. Sorry.

**Comment by agriggio** [comment]
I pushed a few changes to `histmatching-internal-demosaic` (and only there this time, hopefully! :stuck_out_tongue_winking_eye: ). Now I am happy with both the results (in general) and the performance. I am still redoing the demosaicing internally, but now using `Thumbnail::processImage` instead of the "normal" pipeline. Way faster, and the matches are still good, at least from my experiments.
Please test if/when you have the chance, thanks!

**Comment by Beep6581** [comment]
I tested on raw files of various formats in various styles (high key, low key, bracketed, cc24, etc). The changes are good, and ever so slightly match the embedded JPEG better.
