### ISSUE TITLE
Document our unicode support

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#4372]
This commit should be documented in RawPedia, here http://rawpedia.rawtherapee.com/Exif_Tab and/or here http://rawpedia.rawtherapee.com/IPTC_Tab
However, I'm not clear enough on the changes in order to do that. @Hombre57 could you help?

> 9d2ccc19 (5 weeks ago) Better UNICODE support (UCS-2/UTF-8) for Exif.UserComment (#2017) - Hombre
> - BOM is now checked and correctly handled
> - auto-detection of UTF-8 string if no BOM available, otherwise assume
> it's an UCS-2/UTF-16 string
> - try to autodetect endianess of UTF-16 string by counting zeros
> - possibility to enable writing BOM for this field (disabled for now)
> - for undefined charset (empty identifier), RT now assume that the
> string is what glib think is the local charset (not tested), and try to
> convert it to UTF-8 for display/editing
>
> JIS is still not handled though.

**Comment by heckflosse** [comment]
what's `BOM` ?

**Comment by Beep6581** [comment]
[Byte order mark](https://en.wikipedia.org/wiki/Byte_order_mark).

**Comment by Hombre57** [comment]
@Beep6581 Here we go :

Reading Exif.UserComment :

- ASCII values are, of course, read without problem
- For UNICODE values, RT detects if a the string has an odd length. If so, it's an UTF-8 string.
   - If not, it tries to detect if an UCS-2 Byte Order Mark is set.
   - If no BOM is provided, it look out if it's a valid UTF8 string and tries to auto-detect the Byte Order (based on "zeros" count)
   - If not an UTF8 string, it is assumed to be an UCS-2 string with the platform's Byte Order
- For UNDEFINED values, RT tries to convert the string from the local charset to UTF8

Saving Exif.UserComment :

- If the string is pure ASCII, it is saved as ACSII.
- Otherwise the string is converted to UTF16 and saved without Byte Order Mark, with the Metadata's Byte Order

For IPTC data, strings are handled by `libiptcdata`, so I can't say what's the logic but it looks like it works fine when reading the strings (I haven't tested all cases). But when saving them, RT sets `IPTC_TAG_CHARACTER_SET` to UTF8.

**Comment by Beep6581** [comment]
Thank you, I'll add that to RawPedia in the days to come.

**Comment by Beep6581** [comment]
Hey @Hombre57 
I documented the above:
http://rawpedia.rawtherapee.com/Exif_Tab
http://rawpedia.rawtherapee.com/IPTC_Tab

But what did you mean by "look out" here?
> it look out if it's a valid UTF8 string

and here (so with or without? Was there an "or" missing?):
> saved without Byte Order Mark, with the Metadata's Byte Order

**Comment by Hombre57** [comment]
> But what did you mean by "look out" here?

[Line 499 and 502 of stdattribs.cc](https://github.com/Beep6581/RawTherapee/blob/7096c9656a421692c31b9a63cf66ecb2d2b1ca48/rtexif/stdattribs.cc#L499) look for conformance of the first 4 bits of each character according to [this first table](https://fr.wikipedia.org/wiki/UTF-8). Not sure it's 100% bullet proof, but should detect most case.

> and here (so with or without? Was there an "or" missing?):
>> saved without Byte Order Mark, with the Metadata's Byte Order

You're confusing the Byte Order **Mark** and the string's Byte Order. I'm saying there is no BOM, but the string's BO will be the same than Metadata.

**Comment by Beep6581** [comment]
Done: http://rawpedia.rawtherapee.com/Exif_Tab
