### ISSUE TITLE
Memory leak when saving 32-bit TIFF

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#4375]
Several times my whole computer froze (I managed to unfreeze it once by switching to TTY1 and killing RT) when testing patches and saving to various formats including 32-bit TIFF. I didn't encounter these freezes when saving only to 16-bit TIFF so the problem probably involves 32-bit TIFF files.

Steps to reliably reproduce:
* Open `amsterdam.pef` with Filmstrip visible, neutral profile.
* Open the same folder in the File Browser which you will be saving to, I used `/tmp`
* Save a 32-bit uncompressed TIFF.

![screenshot_20180207_114141](https://user-images.githubusercontent.com/5844619/35912102-e63e7632-0bfb-11e8-8600-95a8d8627f08.png)

**Comment by Beep6581** [comment]
https://discuss.pixls.us/t/feature-request-save-as-floating-point/5696/37?u=morgan_hardwood

**Comment by Floessie** [comment]
> Does the file browser need to have the output folder open? 

Yes. It's the reading that triggers the bug.

> Does the TIFF need to be compressed?

Don't know, I used "uncompressed".

> Are any metadata changes necessary?

I didn't do anything to metadata myself.

Maybe you need a slow or otherwise busy machine to trigger it.

HTH,
Flössie

**Comment by Beep6581** [comment]
Reproduced, first post updated.

**Comment by Beep6581** [comment]
Could not reproduce using @Floessie 's patch:
```diff
diff --git a/rtexif/rtexif.cc b/rtexif/rtexif.cc
index 47d885e50..b6a60bbd8 100644
--- a/rtexif/rtexif.cc
+++ b/rtexif/rtexif.cc
@@ -3077,7 +3077,7 @@ void ExifManager::parse (bool isRaw, bool skipIgnored)
         root->printAll ();
 #endif
 
-    } while (ifdOffset && !onlyFirst);
+    } while (ifdOffset > 0 && !onlyFirst);
 
     // Security check : if there's at least one root, there must be at least one image.
     // If the following occurs, then image detection above has failed or it's an unsupported file type.
```

**Comment by Beep6581** [comment]
@Floessie if you're ok to commit, I could make a new coverity build right away.

**Comment by Floessie** [comment]
@Beep6581 Please go ahead and push the fix. But why the new Coverity trigger: This is an old bug and I bet it was in the Coverity log, so this won't reveal anything new. Wouldn't it make more sense to tackle #4376 first?

**Comment by Beep6581** [comment]
@Floessie only because you (or someone else?) asked me to make a new one two or three days ago.

**Comment by Floessie** [comment]
@Beep6581 In fact, it was me. That was because of the newly added code, but we don't have to trigger a scan for single line changes...

**Comment by Hombre57** [comment]
@Floessie I'd be interested to understand your patch : what's the difference between the suppressed line and the new one ?

I declared `ifdOffset` as int, while `IFDOffset` is unsigned int (as told in the specification). I'm coping one into the other [here](https://github.com/Beep6581/RawTherapee/blob/536ebb9974caf1c2189fdbc3ac858b9c43fee0be/rtexif/rtexif.cc#L2737). It might be a problem, but then I don't know what your patch solve if `ifdOffset` can't be negative.

**Comment by Floessie** [comment]
@Hombre57 The new one breaks the loop, if `ifdOffset` is negative, obviously. 😄 

> It might be a problem, but then I don't know what your patch solve if ifdOffset can't be negative.

Why can't `ifdOffset` be negative? It's signed. And it will be `-1`, if the `fread()` in [`get4()`](https://github.com/Beep6581/RawTherapee/blob/c1397446470e2cad95fb1754eca0face28ef5df5/rtengine/dcraw.cc#L301) fails, because the [`fseek()`](https://github.com/Beep6581/RawTherapee/blob/536ebb9974caf1c2189fdbc3ac858b9c43fee0be/rtexif/rtexif.cc#L2761) prior to the read failed, too. This can happen, when the file is just being written (or if it's maliciously crafted, the whole `rtexif` code is very susceptible for that).

> I'm coping one into the other here.

If a similar loop is copied from here, it should be fixed there, too.

I hope, this explanation makes things clearer. It's just a common unsigned vs. signed bug. If an entity should only be positive (like absolute offsets or sizes), make them unsigned. ~I didn't want to touch too much code in this phase, so I opted for changing a single line. Converting all those offsets to `size_t` would be the correct solution, as we don't support offsets beyond 2GB right now.~ **Edit:** Making it unsigned wouldn't have helped, what's needed is a real error flag or an exception.

Best,
Flössie

**Comment by Beep6581** [comment]
> we don't have to trigger a scan for single line changes

We don't. The last scan was 10 days and 68 commits ago, and I will make a new one for RC1.

**Comment by Floessie** [comment]
> The last scan was 10 days and 68 commits ago, and I will make a new one for RC1.

Ah, okay, I thought that was already [done](https://github.com/Beep6581/RawTherapee/issues/4028#issuecomment-363409814).
