### ISSUE TITLE
Replace dcraw with actively maintained raw decoding engine (e.g. LibRaw)

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#4462]
While in the past I would occasionally communicate with Dave Coffin, author of dcraw, I have not received any replies or seen any signs of progress on dcraw for over a year. It seems the project is abandoned, and we need a plan to move forward.

Options:
* RawSpeed https://github.com/darktable-org/rawspeed
* [LibRaw](https://www.libraw.org/) https://github.com/LibRaw/LibRaw
* [libopenraw](https://libopenraw.freedesktop.org/wiki/) https://github.com/hfiguiere/libopenraw

**Comment by agriggio** [comment]
Good idea. I think maybe we can adopt a two-tier approach in which we use the current code for the supported cameras, and fall back to something else for the unsupported ones. We would probably need a way to still be able to use our `camconst.json` though. 

Can someone describe the main differences between rawspeed and libraw? (I know nothing about libopenraw, though from the readme it seems that it lacks support for many cameras...)

**Comment by LebedevRI** [comment]
> differences between rawspeed and libraw

> rawspeed

* no releases, copylib.
* c++14 (clang-3.5+ / gcc-5+ / clang-cl; **NO** MSVC support!)
* is not a copy-paste from dcraw.
* actually readable, maintainable codebase.
* strong integration testing (see [Raw Samples Wanted](https://discuss.pixls.us/t/raw-samples-wanted/5420?u=lebedevri)), some unit tests.
* some kind of public ci setup

> libraw

* releases
* uses [old version of] rawspeed internally, unless the camera is blacklisted, then
* mostly copy-paste class-ified version of dcraw is used
* ??? fixme

There are a few more points, but i don't feel like posting them here, feel free to ping me in IRC.

I'm biased, i'm sure libraw is not all that bad :)

**Comment by agriggio** [comment]
Thanks @LebedevRI, I'll follow up on IRC when time permits.

**Comment by aferrero2707** [comment]
Some time ago I played with RT and RawSpeed, and came to the point where I could open and decode a RAW file with RawSpeed in RT. If you are interested, I can push my code in a dedicated branch in the next days...

**Comment by heckflosse** [comment]
@aferrero2707 great :+1: But keep in mind that we will need to support both for a while. Our dcraw code has some specialities, which are not covered by rawspeed code. This has to be solved before we can cut off dcraw.

**Comment by wbzqe** [comment]
hi,
use rt5.8 process a CR2 image, got result below , dcraw in RT seems have some bug .

![RT-result](https://user-images.githubusercontent.com/7522761/85989133-b36ad980-ba22-11ea-96cf-e6bb6b978776.png)

use darktable decode , it seems right..
![darktable-result](https://user-images.githubusercontent.com/7522761/85988929-5b33d780-ba22-11ea-88bf-71d1de31fd32.png)

look forward to RT adding support for rawspeed soon

**Comment by Thanatomanic** [comment]
@wbzqe Unfortunately, this is completely irrelevant to the discussion. The fact that one raw file doesn't get processed correctly, is zero reason for us to switch to a totally different decoding engine.
If your file is not being processed correctly, file a _specific_ bug report for _that problem_. Include your RAW file + PP3 file so that we can take a look what is going on.

**Comment by wbzqe** [comment]
@Thanatomanic  Think you for your patient reply .

**Comment by mokko** [comment]
Does libraw provide alternative these days?

**Comment by Lawrence37** [comment]
With 5.10 coming soon and 6.0 inching closer, I'd like to review the priorities for the next release. Replacing dcraw is important in my opinion. dcraw's last release was over 5 years ago. We have had to add support for new cameras and file formats by digging into LibRaw and rawspeed. It's not easy to stay on top of all new kinds of raw files, and there is at least one kind we know RawTherapee cannot read but is supported by LibRaw (see #6626). I'm willing to invest some time to make the switch from dcraw.

Before that can happen, we need to agree on the approach. In particular, which decoder(s) should we adopt? LibRaw and rawspeed look like the top contenders. LibRaw is an attractive option. It has roots in dcraw and Alberto already integrated it into ART. Using LibRaw would also maintain diversity because the other major FOSS raw development program darktable uses rawspeed. If one program can't decode a file, there's still a chance the other one can. On the other hand, rawspeed's development is more open and transparent.

**Comment by LebedevRI** [comment]
FWIW, i'm pretty sure i have asked many years ago
which particular features RT would require that are missing
in rawspeed as compared with whatever it is currently using,
and i don't recall ever getting any kind of coherent response.

But obviously, the choice in question is up to RT devs.

**Comment by Lawrence37** [comment]
I don't know of any specific features missing, but there's always a concern that adopting a radically different library can break things without our knowledge. It can be a big problem in this case due to the absence of comprehensive regression tests.

**Comment by Lawrence37** [comment]
@kmilos alerted me to a change in LibRaw's release policy. A few months ago, they increased the major release period from 1.5-2 years to 1.5-3 years. Very recently, the public snapshot period increased from 7-12 months (7-9 months a few months ago) to 9-18 months.
