### ISSUE TITLE
Eclipse talk

### ISSUE THREAD

**Issue by Hombre57** [Beep6581/RawTherapee#4529]
Following [this message](https://github.com/Beep6581/RawTherapee/pull/4523#issuecomment-385316713) (ping @Floessie), this issue is a host for discussion around the Eclipse IDE.

I'm opening the thread by asking about the Oxygen version of Eclipse, which seem to have a serious regression compared to Neon. I'm thinking about the project's `Properties` page, where the `Preprocessor Include Paths, Macro etc.` has simply gone (at least on my install). Could other confirm this ?

![eclipse-neon-properties](https://user-images.githubusercontent.com/13788115/39422839-5d602e1e-4c6f-11e8-9280-1ceb1a44dfb2.png)

I've installed both Neon and Oxygen through the official `eclipse-inst-win64.exe` which handle the bundle pool (Windows 7/64 bits).

This is a major problem because there's not `Configuration` anymore and the indexer just doesn't work at all. Then you have to import the `.project` file (given you used the `Eclipse CDT4 - MinGW Makefiles` cmake generator), than will create a new project next to your git repos (where the indexer works!) in the `C/C++ Projects` tab. Eclipse is just painful to use in these conditions. The Neon version allowed you to have only one `C/C++ Projects` entry, with a working indexer.

Please share your experience or advice on moving to Oxygen efficiently.

**Comment by Floessie** [comment]
I'll chime in on Wednesday.

**Comment by Floessie** [comment]
Hi @Hombre57,

I've fired up my Eclipse Oxygen.3 VM and installed RT. Everything is fine, including the "Paths and symbols" page. Here's how I set it up:

1. Cloned RT to `~/src/rawtherapee` and installed dependencies.
2. Created `~/src/rawtherapee/build` and ran `cmake` there.
3. Fired up the freshly installed Eclipse Oxygen.3.
4. File -> Import -> Git -> Projects from Git -> Existing local repository -> Add
5. Import as general project
6. On the newly created project: New -> Convert to a C/C++ project
7. Properties -> C/C++ Build -> Builder Settings -> Build location = `${workspace_loc:/rawtherapee/build}`
8. Change Behavior for parallel builds and "install" instead of "all" make target.
9. Add some paths in Properties -> C/C++ General -> Paths and Symbols -> [Includes](https://filebin.net/9sxmun057wufo1x7).
10. Rebuild index and freshen all files.

And you're good to go. :tada: 

HTH,
Flössie

**Comment by Hombre57** [comment]
@Floessie I'll try asap, thanks for the detailed info.

**Comment by Hombre57** [comment]
@Floessie Tested and approved, though there's more work necessary compared to previous version of Eclipse, especially adding the include folders and macros. I hope that the cmake devs will update their generator so it can provide ready to use `.project` & `.cproject` files. At least, I can work again on RT or any cloned repo with your method, so thanks again.

Please keep this issue opened.

**Comment by Floessie** [comment]
Hey @Hombre57,

I'm glad that this solved the problem for you. The above is my preferred way of attaching Eclipse to any project as I'm dealing with cross-compilation a lot. It's a bit more work, you're right, and I keep my fingers crossed, that the CMake generation method will soon work for you again.

Best,
Flössie
