### ISSUE TITLE
Have CMake check for libtiff >=4.0.4

### ISSUE THREAD

**Issue by LordVan** [Beep6581/RawTherapee#4653]
Due to the fact that I still had a quite old tiff lib I got an error message compiling:
(only relevant part copied)

/var/tmp/portage/media-gfx/rawtherapee-5.4/work/rawtherapee-5.4/rtengine/imagedata.cc: In constructor ‘rtengine::FrameData::FrameData(rtexif::TagDirectory*, rtexif::TagDirectory*, rtexif::TagDirectory*)’:
/var/tmp/portage/media-gfx/rawtherapee-5.4/work/rawtherapee-5.4/rtengine/imagedata.cc:576:31: error: ‘PHOTOMETRIC_CFA’ was not declared in this scope
     } else if (photometric == PHOTOMETRIC_CFA) {
                               ^~~~~~~~~~~~~~~
Took me a bit to figure out the problem, but an update to tiff 4.0.9 fixed it.
Might be good to check for this minimum requirement?

**Comment by Benitoite** [comment]
https://github.com/Beep6581/RawTherapee/blob/8c3e14b7f0a128d82369ebcbb88abe3ccb930c7d/CMakeLists.txt#L323

This can be changed to 
`pkg_check_modules(TIFF REQUIRED libtiff-4>=4.0.4)`

However as it stands you would have to either
* up the minimum cmake version to 2.8.8
Or
* put the findTIFF.cmake into the repository. 

I don’t know if changing the cmake version will break someone’s build system. 

I can make a pr later after the parade.   

Happy fourth!

**Comment by Beep6581** [comment]
Thank you @Benitoite 

CMake-2.8.4, our current requirement for Windows, is from [2011](https://cmake.org/pipermail/cmake/2011-February/042839.html)
CMake-2.6, our current requirement for Linux, is from [2008](https://cmake.org/pipermail/cmake/2008-May/021490.html)
CMake-2.8.8 was released in [2012](https://cmake.org/pipermail/cmake/2012-April/049955.html)

GCC-4.9.0 is from [2014](https://gcc.gnu.org/releases.html)
LCMS2-2.6 is from [2014](https://sourceforge.net/p/lcms/mailman/message/32110206/)
GTK+ 3.16.0 is from [2015](https://mail.gnome.org/archives/gnome-announce-list/2015-March/msg00029.html)

As such, I see no problem bumping the requirement to 2.8.8, especially since we can always revert to bundling `findTIFF.cmake` if anyone complains with a valid reason.
