### ISSUE TITLE
Rawtherapee help

### ISSUE THREAD

**Issue by swilso0053** [Beep6581/RawTherapee#4755]
could someone help me out. I am just a mom that shot some pics of my daughter for sr pics in raw. Some were slightly overexposed. I searched and came across raw therapee and I have been trying for a week to get to the edited picture I have saved like 25 times. I edited everything then click thesave as and I chose tif because I would like to print some as 8X10s for family so I did 16 bit. I have also tryed saving it as a jpeg i have tryed my flash drive and 3 folders. I then go out of raw therapee and search for the folder to open image and the folders are empty. Why arent they saving. I watch the bar at the bottom to make sure it says saved. 😞

**Comment by agriggio** [comment]
hi @swilso0053, and thanks for your interest in rawtherapee! from your description it looks like you are doing something wrong somewhere. in order to get more help, I suggest that you ask on the rawtherapee forum at http://discuss.pixls.us
I'm pretty sure you will find some user offering good advice. also, if you haven't already done so, make sure to check the documentation at rawpedia.rawtherapee.com

**Comment by swilso0053** [comment]
Thank you, I kept trying to sign up to post there but it never sends me the email to verify my email, i have checked in my spam also

**Comment by patdavid** [comment]
@swilso0053 can you try again and let me know what your username is?  I can check to make sure the email is working properly (we had some minor email problems recently and yours might have been lost in the shuffle - I see three new accounts with a similar name to what you're using).
