### ISSUE TITLE
Review 'AppVersion' key in pp3 files

### ISSUE THREAD

**Issue by heckflosse** [Beep6581/RawTherapee#4805]
Each pp3 file contains an `AppVersion` key, which is read from pp3 file, but not used. Should we remove it?

**Comment by Beep6581** [comment]
Well, I refer to it once in a while when helping users in the forum, but I don't _need_ it.

Our bundled profiles contain two keys:
```
AppVersion=4.2.84
Version=322
```
That was from `rtdata/profiles/Pop/Pop 1.pp3`

As @heckflosse and I agreed to in IRC, both of these should be removed. Reasons:
1. Regenerating over 70 profiles is not realistic, as that would require manually examining each profile and partial-saving a new one. Repeat for every release.
2. Due to 1, manually batch-changing the `AppVersion` and `Version` values would be wrong since they would then be lying about the contents of the profiles.
3. Leaving them alone is also not good, since RT will then trigger some obsolete-mode pathways when a user launches RT5.5 and applies one of the bundled profiles.

I will remove both keys this weekend unless someone has a good argument against that and a better solution.

**Comment by heckflosse** [comment]
@Beep6581 :+1: for removing both keys from bundled profiles. And also :+1: to remove AppVersion key handling from code completely.

**Comment by Hombre57** [comment]
@Beep6581 @heckflosse

> and a better solution

...to what problem ?

I'd keep them. They don't harm anyone and we don't need to update the bundled profiles. This `AppVersion` info can be interesting when getting pp3 file, given our poor backward compatibility support, we can deduce that a pp3 from a real old version _can_ be obsolete (about the desired output) even with the same `Version`, and/or compare the output with more recent version for debug purpose, if ever.

It's also an information that is sent to the Custom Profile Builder, they can use it as any metadata.

**Comment by heckflosse** [comment]
@Hombre57 
applying a bundled profile with old pp3 version will set the raw ca correction iterations value back to 1 where the current default is 2 because new default is two, old default is one and pp3version says 'use old default'

**Comment by Hombre57** [comment]
@heckflosse

> :+1: for removing both keys from bundled profiles.

So you expect predictable result in future release using those profiles ?

**Comment by agriggio** [comment]
I agree with hombre, I see no benefit in removing the info. it's actually useful for "forensics" purposes as well -- say when the implementation of some routine changes and some user reports a regression

**Comment by heckflosse** [comment]
I only care about the `Version` key in bundled profiles, not about the `AppVersion` key.

**Comment by Hombre57** [comment]
@heckflosse Remove them from bundled profiles if you want, however I wouldn't remove the mechanism in RT. If too much work to remove them, I can do it, but you'll suppress future backward compatibility handling.

**Comment by heckflosse** [comment]
@Hombre57 I don't intend to remove the mechanism. That would be clearly wrong. I just want to remove the Version key from bundled profiles because the bundled profiles are controlled by us, not by users saving profiles

**Comment by Hombre57** [comment]
@heckflosse

> I don't intend to remove the mechanism. That would be clearly wrong. I just want to remove the Version key from bundled profiles because the bundled profiles are controlled by us, not by users saving profiles

As said, :+1: for that.

**Comment by Beep6581** [comment]
To remove `AppVersion`:
```bash
find rtdata/profiles/ -iname "*.pp3" -print0 | xargs -0 sed -i '/AppVersion/d'
```

To remove the whole `[Version]` header:
```bash
find rtdata/profiles/ -iname "*.pp3" -print0 | xargs -0 sed -i '1,4d'
```

**Comment by Floessie** [comment]
Or even shorter:

    find rtdata/profiles/ -iname "*.pp3" -exec sed -i '/AppVersion/d' {} \;

**Comment by Beep6581** [comment]
I'm not sure we have a consensus. There are two things being discussed:
1. Whether to remove `Version` and `AppVersion` from our bundled PP3s.
2. Whether to remove the code which writes `AppVersion` to PP3s.

In support of point 1, if you apply our bundled `Auto-Matched Curve - ISO Low.pp3` you will find that, due to the old `Version` value, "raw CA correction iterations" are set to 1 when the [default is 2](https://github.com/Beep6581/RawTherapee/blob/dev/rtengine/procparams.cc#L2565), and that "avoid color shift" is disabled when the default is enabled. The relevant part of the PP3 is concise to take advantage of the defaults:
```
[RAW]
CA=true
```

So what do we do about 1 and about 2?

My opinion: yes for 1, ambivalent about 2.

**Comment by Hombre57** [comment]
@Beep6581 

There are other possibilities for 1, but I'm not against removing both parameters from the bundled profiles because there's an unwanted behavior in that particular case. I just wanted to point out that future change in version handling may also bring unwanted behavior because there's no parameters anymore, depending on the change.

For 2, I'm against removing that from the code.
