### ISSUE TITLE
Dropdown bad positioning

### ISSUE THREAD

**Issue by Barugon** [Beep6581/RawTherapee#4814]
When I click a dropdown, the list will very often be positioned somewhere else on the screen or worse, somewhere offscreen where I can't interact with it (please see the screenshot below). This only happens on my notebook with Intel Iris graphics. On my desktop with Nvidia 1070 this does not happen.

Specs:
Fedora 28
Intel i7-6560U CPU @ 2.20GHz
Intel Iris Graphics 540 (Skylake GT3e)

In the screenshot, I have clicked on the Camera dropdown in Profiled Lens Corrections:

![screenshot from 2018-09-17 10-48-33](https://user-images.githubusercontent.com/16503728/45640851-9f7dff80-ba68-11e8-8939-06f82fccff29.png)

**Comment by Beep6581** [comment]
Which version of GTK+ do you have on each computer?

**Comment by Barugon** [comment]
Both are using Fedora 28, so GTK 3.22.20.

**Comment by ff2000** [comment]
I get similar positioning errors when running kwin under Wayland. I also have an intel iGPU (sandybridge). I often can fix the positioning by resizing the main window. (didn't try RT... - back to X11 currently)
I just mention this because it seems you are using Gnome Shell which likely runs with wayland on your intel system. NVidia does not offer EGL but only an in-house invented EGLStreams which AFAIK no Wayland Compositor supports (yet).

**Comment by Beep6581** [comment]
Closing a this is likely a Wayland/GTK+ issue outside of our control.
