### ISSUE TITLE
Raw chromatic aberration correction's Avoid Color Shift causes purple halo

### ISSUE THREAD

**Issue by strongheart1** [Beep6581/RawTherapee#4838]
On some pictures I get a purple tone on the lower edge with an Auto-Matched Curve:
![img_5199-1](https://user-images.githubusercontent.com/35747159/46110657-a33a2080-c1e4-11e8-9c9b-69ea0055036a.jpg)
The same picture with Neutral profile:
![img_5199-2](https://user-images.githubusercontent.com/35747159/46110658-a3d2b700-c1e4-11e8-9bae-f94ebd839132.jpg)

RT Version: 5.4-911-g5ece078

I didn't see it with Version: 5.4   Commit: a5e8eb9c

**Comment by heckflosse** [comment]
@strongheart1 That looks like an issue with the raw auto ca-correction avoid colour shift feature.
Please test with raw ca correction avoid colour shift disabled and if possible please also provide the raw file

**Comment by strongheart1** [comment]
@heckflosse Yes, if I disable "avoid colour shift", the error disappears.
Here is the raw file: https://filebin.net/2tt0lb48rutk4gmk

**Comment by Beep6581** [comment]
@strongheart1 was CHDK used?

**Comment by strongheart1** [comment]
> @strongheart1 was CHDK used?


No, just original Canon EOS 50 D Firmware V 1.0.9

**Comment by heckflosse** [comment]
@strongheart1 The problem was, that the ca correction at the borders of the picture does not work well and led to wrong correction at the border even without Avoid color shift. This wrong correction was not visible when using the default border of 4 pixels, but using 'Avoid color shift' this wrong correction was spread to the neighbouring region.
