### ISSUE TITLE
Some icons are not visible on Win10

### ISSUE THREAD

**Issue by TooWaBoo** [Beep6581/RawTherapee#4847]
I saw this screenshot from @heckflosse .
![heckflosse](https://user-images.githubusercontent.com/13800920/46382983-44761a80-c6ae-11e8-8eeb-d1a28f06537c.jpg)
The `Select Crop` button shows an icon.

This is a screenshot from Windows 10.
![unbenannt](https://user-images.githubusercontent.com/13800920/46383017-77b8a980-c6ae-11e8-8721-1c84f3d60103.PNG)
The icon is not visible.

... and this is what the Inspector is showing
![unbenannt2](https://user-images.githubusercontent.com/13800920/46383265-ce72b300-c6af-11e8-85a2-a735494e4df6.PNG)
The image is greyed out

It's not theme related. I thought the icons are removed 'cause I can remeber they were shown in the past.
I've also tested with the latest dev from @gaaned92 too, same behaviour.
Checked the code in crop.cc but could'nt find anything wrong. The `crop-small.png` is not missing.
```
selectCrop = Gtk::manage (new Gtk::Button (M("TP_CROP_SELECTCROP")));
selectCrop->get_style_context()->add_class("independent");
selectCrop->set_image (*Gtk::manage (new RTImage ("crop-small.png")));

pack_start (*selectCrop, Gtk::PACK_SHRINK, 2);
```

```
Version: 5.4-918-gae12a4186
Branch: dev
Commit: ae12a4186
Commit date: 2018-09-29
Compiler: gcc 8.2.0
Processor: undefined
System: Windows
Bit depth: 64 bits
Gtkmm: V3.22.2
Lensfun: V0.3.2.0
Build type: release
Build flags: -Wno-parentheses -std=c++11 -march=native -Werror=unused-label -fopenmp -Werror=unknown-pragmas -Wall -Wno-unused-result -Wno-deprecated-declarations -Wno-aggressive-loop-optimizations -DNDEBUG -O3 -ftree-vectorize
Link flags: -m64 -mthreads -static-libgcc -march=native -s -O3
OpenMP support: ON
MMAP support: ON
```

**Comment by Beep6581** [comment]
Which version of GTK+ was used?

**Comment by TooWaBoo** [comment]
GTK+ 3.22.30

**Comment by heckflosse** [comment]
Here's my version info
```
Version: 5.4-918-gae12a41
Branch: dev
Commit: ae12a41
Commit date: 
Compiler: cc 6.4.0
Processor: x86_64
System: Linux
Bit depth: 64 bits
Gtkmm: V3.22.2
Lensfun: V0.3.2.0
Build type: release
Build flags:  -std=c++11  -Werror=unused-label -fopenmp -Werror=unknown-pragmas -Wall -Wno-unused-result -Wno-deprecated-declarations -O3 -DNDEBUG -ftree-vectorize
Link flags:   
OpenMP support: ON
MMAP support: ON
```

**Comment by TooWaBoo** [comment]
When I remove the button label in `crop.cc` the image is shown.

**Comment by Beep6581** [comment]
A Gtk::Button shows an image if one is set and if:
* `gtk-button-images` is `TRUE`, or
* there is no label.

The recommended, future-friendly way of handling this is to pack a GtkImage and GtkLabel in a GtkBox and to add that to the GtkButton.

Gtk::Button image handling in GTK4:
https://developer.gnome.org/gtk4/stable/gtk-migrating-3-to-4.html#id-1.6.4.3.11

> Stop using GtkButton's image-related API
The functions and properties related to automatically add a GtkImage to a GtkButton, and using a GtkSetting to control its visibility, are not supported in GTK+ 4. Instead, you can just pack a GtkImage inside a GtkButton, and control its visibility like you would for any other widget. If you only want to add a named icon to a GtkButton, you can use gtk_button_set_icon_name().

**Comment by Beep6581** [comment]
@TooWaBoo see if you can set `gtk-button-images=True`
https://github.com/shoes/shoes3/wiki/Changing-Gtk-theme-on-Windows

**Comment by TooWaBoo** [comment]
I've created folders and the file `settings.ini` in `share` (`etc\gtk-3.0\settings.ini`) and followed the instructions from your link but nothing has changed.

settings.ini
```
[Settings]
gtk-button-images=True
```

**Comment by TooWaBoo** [comment]
@Beep6581 
Bingo, it works.
I've created a folder `gtk-3.0` in the folder `share` of RT and copied `settings.ini` into this folder.

The file `settings.ini` looks like this. "True" doesn't work, has to be "1".
```
[Settings]
gtk-button-images=1
```

@gaaned92
fyi

**Comment by gaaned92** [comment]
@TooWaBoo 
OK I will apply that.
But first I have to revert some MSYS2 updates as you noticed.

**Comment by TooWaBoo** [comment]
Closing issue.

**Comment by DiegoBM** [comment]
I'm facing a similar issue to this one (I thought I could reuse this one instead of creating a new one).

This is the first time that I build the application. I created a new virtual machine just for this.
I have followed the instructions exactly as mentioned, and everything goes well to the point in which everything builds without issues and if I run the application from the mingw shell, everything looks fine. But the minute that I try to create a Windows bundle by copying the dlls, themes and other files indicated in the instructions (https://rawpedia.rawtherapee.com/Windows), when I try to run the program, it loses the classic windows "maximize", "minimize" and "close" window icons from the upper right corner of the window, it displays some sort of missing-icon-ish bitmap. Note that I've done everything as per the instructions, the only thing I did differently is that in the istructions the settings.ini file seems to have everything in one line, but i moved gtk-button-images=1 underneath [Settings] instead of keeping it in the same line
