### ISSUE TITLE
Why is png not enabled in the file browser by default?

### ISSUE THREAD

**Issue by Thanatomanic** [Beep6581/RawTherapee#4915]
Simple question. Is there a good reason for it?

```
ParseExtensions=3fr;arw;arq;cr2;crf;crw;dcr;dng;fff;iiq;jpg;jpeg;kdc;mef;mos;mrw;nef;nrw;orf;pef;png;raf;raw;rw2;rwl;rwz;sr2;srf;srw;tif;tiff;x3f;
ParseExtensionsEnabled=1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;0;1;1;1;1;1;1;1;1;1;1;1;
```

**Comment by Beep6581** [comment]
We disabled it because PNG files came in various shapes, sizes and odd aspect ratios and often lead to crashes or File Browser thumbnail screw-ups. Typical case: user opens a photo in some bad place like "Downloads", closes RT, then they download some PNG there, then RT keeps crashing on startup.

It would generally be good to enable PNG by default, especially since now RT writes metadata to PNG files (possibly even better than to TIFF files #4464).

**Comment by Thanatomanic** [comment]
Okay, I see. But isn't that equally possible with jpegs of strange dimensions?

**Comment by Beep6581** [comment]
Sure, but unusual JPEGs (e.g. 12-bit) are rare, and don't lead to crashes like PNGs do/did. I'm just pointing that out, I'm not defending that we should keep PNG disabled.
