### ISSUE TITLE
Tint slider re-calibrates to the left

### ISSUE THREAD

**Issue by RawConvert** [Beep6581/RawTherapee#5077]
Occasionally, infrequently, but just now, the Tint slider changes and instead of unity being in the middle, it goes to the left.  That is, "1" position is significantly to the left. 
![tint-gone-left](https://user-images.githubusercontent.com/16868433/49688673-660bdc00-fb0d-11e8-8f05-ca1d90687a03.png)
I had the same thing happen about a month ago, before RT5.5 therefore.
I've no idea how to reproduce this.  A PP3 is attached following the leftiness in case it helps. Today I had also adjusted the white point in the Raw tools, but the w.p. might well have been back to 1 by the time the 
tint went left.
[_6D_9278.CR2.pp3.zip](https://github.com/Beep6581/RawTherapee/files/2659902/_6D_9278.CR2.pp3.zip)
Version: 5.5-rc1      Branch: release-5.5      Commit: ca67245

**Comment by agriggio** [comment]
that's by design

**Comment by Thanatomanic** [comment]
@agriggio Out of curiosity, if it's by design, is there way to reproduce this behavior? I haven't managed so far..

**Comment by agriggio** [comment]
the slider sets the mid point to the tint of the camera wb. for some cameras (notably mine :-) this is almost never 1.0, and often it's significantly far from 1 even in normal lighting conditions

**Comment by agriggio** [comment]
in other words, 1 is not in general a neutral position. that depends on the camera matrix (dcraw_matrix in camconst). since there is no way of knowing what the neutral position is for the current camera, I decided to set as neutral the tint value of the camera wb. I know it's not optimal, but I couldn't find any other sensible choice. ideas are welcome

**Comment by RawConvert** [comment]
@agriggio , "thats by design" was a rather brief response, but at least @Thanatomanic  got some details from you.
I don't understand why "1" cannot always be in the middle of the slider.  The behaviour does not seem consistent.  Since mention of white balance, I have found how to reproduce this by switching between Neutral and "last Saved" profile and/or changing white balance method.  These two screenshots are both on Cloudy but the "1" positions are very different.  It must be to do with the Uni White Balance I'm using but I don't see why that should lead to two different positions for "1".
![t2](https://user-images.githubusercontent.com/16868433/49697111-5cd14c80-fbab-11e8-9cb8-d2832e4344b9.png)
![t6](https://user-images.githubusercontent.com/16868433/49697115-62c72d80-fbab-11e8-9eea-77215fe3c7e4.png)
Surely the slider can always be "calibrated" so that "1" is fairly central?

**Comment by agriggio** [comment]
the idea is to optimize the slider for the use-case in which you want to tweak the tint, by applying some compensation. the assumption is that whatever tint is set is "close enough" to be right, so that you want to apply very small modifications. for this, the slider works in log scale, with the "zero" point set to the tint in the initial pp3 (by default the camera tint). if you use uniwb, this whole assumption that the tint is "almost right" and you only have to tweak it slightly breaks. but if you are shooting with uniwb, I'd say there's a very high chance that you have a more reliable method to set the right wb in post than just tweaking the tint "by eye".

so, my reply was brief because I was in a hurry on my phone, but I wanted to say that this is not a bug, in the sense that it works as designed. if people don't like this, I have no problem reverting to the old behaviour (and keep this only in my own fork)

**Comment by RawConvert** [comment]
@agriggio , Alberto, I'd suggest reverting to the previous behaviour.  I don't think it's right that with seemingly identical situations as the pics above, "1" is in very different places.  I appreciate it's nice to have fine control, but I thought that was supposed to be provided by the press-and-hold facility which results in less movement per mouse unit.  I checked and this is working on the tint slider.  A way forward might be to slow the movement down further, say to twice as slow as at present.  Though as it's set now, it's quite easy to make small adjustments that are not really visible, so it's pretty useable.

**Comment by agriggio** [comment]
here's a patch to restore the old behaviour

```diff
diff --git a/rtgui/whitebalance.cc b/rtgui/whitebalance.cc
--- a/rtgui/whitebalance.cc
+++ b/rtgui/whitebalance.cc
@@ -322,7 +322,6 @@
 
     temp = Gtk::manage (new Adjuster (M("TP_WBALANCE_TEMPERATURE"), MINTEMP, MAXTEMP, 5, CENTERTEMP, itempL, itempR, &wbSlider2Temp, &wbTemp2Slider));
     green = Gtk::manage (new Adjuster (M("TP_WBALANCE_GREEN"), MINGREEN, MAXGREEN, 0.001, 1.0, igreenL, igreenR));
-    green->setLogScale(10, 1, true);
     equal = Gtk::manage (new Adjuster (M("TP_WBALANCE_EQBLUERED"), MINEQUAL, MAXEQUAL, 0.001, 1.0, iblueredL, iblueredR));
     tempBias = Gtk::manage (new Adjuster(M("TP_WBALANCE_TEMPBIAS"), -0.5, 0.5, 0.01, 0.0, itempbiasL, itempbiasR));
     cache_customTemp (0);
@@ -701,7 +700,6 @@
         set_inconsistent(multiImage && !pedited->wb.enabled);
     }
 
-    green->setLogScale(10, green->getValue(), true);
     
     methconn.block (false);
     enableListener ();
@@ -809,7 +807,6 @@
         listener->panelChanged (EvWBTemp, Glib::ustring::compose("%1, %2", (int)temp->getValue(), Glib::ustring::format (std::setw(4), std::fixed, std::setprecision(3), green->getValue())));
     }
 
-    green->setLogScale(10, vgreen, true);
 }
 
 void WhiteBalance::setAdjusterBehavior (bool tempadd, bool greenadd, bool equaladd, bool tempbiasadd)
```

**Comment by agriggio** [comment]
any objection to restore the old behaviour?

**Comment by RawConvert** [comment]
@agriggio , hi, what's the conclusion?  When you asked above about restoring, I assumed that was aimed at the wider community.  If it was at me, then no objection.  Are we going forward with old or new please?!

**Comment by agriggio** [comment]
I pushed the change to `dev`. Now it's up to @Beep6581 to cherry-pick the changeset and apply it to `release-5.5`
