### ISSUE TITLE
Rescaling, option for short edge as a ruling measure...

### ISSUE THREAD

**Issue by ghost** [Beep6581/RawTherapee#5182]
As RT’s batching is working well, I’d like to see an option for defining shorter edge as a ruling measure while rescaling.

Came up on me, while some on-line printing services tell you the exact pixel dimensions which they use and due to printer system I suppose, longer edge is flexible; shorter edge is constant; image orientation is ignored. 
At the moment I run command lines (Linux) and use Gimp to do the desired post processes. I like to shoot completely in RAW and while this resizing process is available in RT, I’d get also my “not so important but to be printed home photos” straight to the printer resolution.

All this to have more control of the print quality, also to save storage and such... Yet in a nutshell: 14Mp Raw -> cropped as I like --> rescaled so that shorter edge is for example 1210pix, longer edge measure is what ever, because some on-line print services sell "flexible lenghts" --> pixel per pixel process...

**Comment by Thanatomanic** [comment]
You mean this? 
![image](https://user-images.githubusercontent.com/6567747/53038409-fa36df80-347c-11e9-9ba1-384cfe20bf15.png)

Unless I understand your post wrong, this is already possible, closing.

**Comment by Beep6581** [comment]
@Thanatomanic though I haven't tried, I don't think it's currently possible to batch-apply resizing to images of various orientations so that the shortest side is some specified length.

**Comment by Thanatomanic** [comment]
@Beep6581 You're right, I was a little hasty. The difference between RT now and the request is setting a value for the shortest side instead of the width. That's a reasonable request.

**Comment by ghost** [comment]
http://www.imagemagick.org/Usage/resize/
Fill Area Flag ('^' flag)
This also represents the requested option..

for example : https://www.ifolor.fi/en/photos/photo-prints
They deliver a pile of prints, each different lenghts if they are cropped differently…
(further info describes resolution as 1210 x (y), 301dpi)

**Comment by ghost** [comment]
And to be clear, for batching I ment the "Queue" processing... But the tool in "Batch Edit" list was same above.. you got the idea, just got little tangled there..

**Comment by Bezierr** [comment]
Since I need this "short edge" resizing feature myself, I tried my hand on it and implemented this functionality.

![Capture](https://user-images.githubusercontent.com/38507161/115145595-e62d9f00-a041-11eb-81e5-460618abcdf4.JPG)

When testing, I haven't found any problems anymore so I'd say it seems to work. However, since this is my first attempt with programming RawTherapee, I cannot claim that I fully understand everything that happens. It may well be that some functionality of which I am not aware does not work in or with this addition. Only language is "default".

If you would like to see my changes and possibly include them in an upcoming release, please let me know how to get the code to you. I created a local branch based on "releases" in GitHub Desktop but am not familiar with the processes around/behind it.

An additional remark: I noticed that when, e.g., you change "Height", "Width" is changed accordingly. I'm not sure that I like this behavior but followed it in my code (i.e. changing the value for "Short Edge" or "Long Edge" will affect the values for "Width" and "Height"). I found, however, that it only happens when changing the value manually, not when loading it from a .pp3 profile. An added line of code in the rtgui\resize.cc seems to fix that, in case the current behavior is not intended.

**Comment by Bezierr** [comment]
Since we are at it, I don't believe that the option "Applies to / Full Image" makes sense for anything but "Scale" because if you use it on a cropped image with any other "Specify" option, what you will get is *not* an image resized to the values entered and shown. I haven't made any changes to that, though, since there may be a reason for this behavior that I am not aware of.

**Comment by Thanatomanic** [comment]
Thanks @Bezierr for looking into it. I am not familiar with GitHub Desktop, but if you have created a branch for your changes, you should probably also be able to make a pull request. Hopefully you can get that to work, so that others can test.

**Comment by Bezierr** [comment]
Ok, I'm trying... 

Github Desktop says:

![image](https://user-images.githubusercontent.com/38507161/115147396-488a9d80-a04a-11eb-949b-d18652a97239.png)

Sounds reasonable. After "publish branch", I get

![image](https://user-images.githubusercontent.com/38507161/115147417-648e3f00-a04a-11eb-84f4-1a28edd25b1f.png)

"Fork" doesn't sound right. Or does it? Any suggestions?

**Comment by Thanatomanic** [comment]
I believe that after making your own fork and push your own changes you can then make a pull request from your fork into our main development branch.

**Comment by Bezierr** [comment]
Ok, tried that; thanks. As far as I can see it seems to have worked.
