### ISSUE TITLE
Center new spots in preview

### ISSUE THREAD

**Issue by sguyader** [Beep6581/RawTherapee#5220]
Description of the current behavior: when you add a new RT-spot in the locallab build, the new spot is created at the center of the image, with a definite size. The problem is that sometimes you want to create smaller spots, while you work on a zoomed in preview, but then chances are that you will have to zoom out to see the spot and manipulate, and then zoom in again to work on your specific area. Each time you zoom in/out, the preview is recalculated.
A better behavior, if it is possible, would be to have the new RT-spot created appear at the center of the current preview area, with a size that makes it fit entirely in this preview area. This would make the new spots immediately available without the need to zoom out/pan the preview and would make the whole process significantly faster.

**Comment by Desmis** [comment]
@sguyader 
That seems to me a good idea...
But it's a GUI problem.... 

@Pandagrapher
Peux-tu donner ton avis ?

jacques

**Comment by sguyader** [comment]
@Desmis je pense que ça serait particulièrement pour le "spot healing".

**Comment by Pandagrapher** [comment]
@Desmis 
I agree: it seems to be a good idea but not trivial to implement. I add it to my todo list

Pierre

**Comment by Desmis** [comment]
@sguyader 

Cela n'a pas de rapport avec ta demande, mais comme cette issue est ouverte, j'en profite.
Je viens de pousser un changement très simple dans le principe qui permet de visualiser les changements

Dans les 3 menus "mask" j'ai ajouté une ligne "Preview selection deltaE"
En choisissant cette ligne, les couleurs sélectionnées s'affichent en jaunâtre plus ou moins prononcé.

Les sliders "color" sont sans effet.
Ceux relatifs à la luminance ont un effet
Scope et les 3 sliders "Threshold deltaE-scope", DeltaE weakening" et "Balance deltaE ab - L" permettent de voir les incidences sur la sélection.

Il y a je pense quelques dysfonctionnements ... dus à la multiplicité possible des choix...problème de logique dans le GUI...

Qu'en penses tu ?


This has nothing to do with your request, but as this issue is open, I take advantage.
I just pushed a very simple change in the principle that allows to visualize the changes

In the 3 menus "mask" I added a line "Preview selection deltaE"
By choosing this line, the selected colors are displayed in yellowish more or less pronounced.

Sliders "color" have no effect.
Those relating to luminance have an effect
Scope and the 3 sliders "Threshold deltaE-scope", DeltaE weakening "and" Balance deltaE ab - L "allow to see the effects on the selection
There is I think some dysfunctions ... due to the possible multiplicity of choices ... problem of logic in the GUI ...
what do you think before continuing ?

**Comment by Desmis** [comment]
I commit a change for "Preview selection deltaE"
It seems to work !

I put in option (Color Management)  Previewselection=5
You can change the value between 1 to 50, to set the intensity of the color

**Comment by Pandagrapher** [comment]
@sguyader @Desmis 
This issue is now implemented with commit `680dd1a`

How it works:
When adding/duplicating spot, new spot is now centered according to the preview area. Moreover ellipse/rectangle size takes into account the preview area size (but it is saturated at maximum at 250 for a creation, at duplicated spot size for a duplication). Center circle radius is unchanged.

@Hombre57 
I have updated `editcallbacks` to get some data about preview area: is it ok for you?

Pierre

**Comment by Hombre57** [comment]
@Pandagrapher Looks fine :+1:

**Comment by Desmis** [comment]
@Pandagrapher
Je regarderai cela samedi quand je serais rentré chez moi.
Merci :)
Jacques

**Comment by Pandagrapher** [comment]
Commit merged: is it ok to close this issue?
Pierre

**Comment by sguyader** [comment]
Nobody complained, closing.
