### ISSUE TITLE
GUI for adding tools to Favorites tab

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#5256]
The Favorites tab functionality was finished in #5016 and will be available in RawTherapee 5.6. Tools must currently be added manually: http://rawpedia.rawtherapee.com/Favorites_Tab

This issue is for creating a GUI to simplify adding tools to the Favorites tab.

**Comment by Hombre57** [comment]
@Beep6581 @heckflosse As a reminder, my first priority is to finish the spot removal tool first, probably update the preview to use `Gtk::Overlay` in the main preview afterwards (necessary for more fluid on preview editing) then the Favorite panel GUI. Are you fine with this order ?

**Comment by Beep6581** [comment]
Fine with me @Hombre57

**Comment by Lawrence37** [comment]
I'm interested in taking this up, but I'd like to collect some ideas on how the GUI should look like.

There's one idea from a fork [here](https://github.com/Beep6581/RawTherapee/issues/2631#issuecomment-252006108) that adds buttons to the tools themselves. Since we are only dealing with the Favorites tab, the end result will look something like [this](https://github.com/Beep6581/RawTherapee/issues/5016#issuecomment-441357946).

I personally like the layout used in darktable because it keeps the tool panel clean and has potential to support more customizability. I would add drag-and-drop for reordering and moving tools.
![image](https://user-images.githubusercontent.com/45837045/133006431-9f6f7489-69ae-4f60-b52d-314923bb3897.png)

The result will be similar to the way many KDE applications allow customizing toolbars. The right side is for favorite tools and the left side is for the rest.
![image](https://user-images.githubusercontent.com/45837045/133006698-58deac82-525d-4366-9062-2d81cf6ae3b4.png)

One challenge is how to represent subtools (Perspective inside Lens / Geometry for example). It should be clear to the user that adding a subtool to Favorites will remove it from the parent, and adding a parent to Favorites will not leave the subtool in the original tab.

**Comment by Lawrence37** [comment]
I've started working on the two list design and will have a basic working version soon.
