### ISSUE TITLE
Respect find/filter criteria when emptying trash

### ISSUE THREAD

**Issue by heckflosse** [Beep6581/RawTherapee#5337]
To reproduce:

1) create two copies of amsterdam.pef in file browser and move both to the trash
2) show the trash, looks so:
![grafik](https://user-images.githubusercontent.com/13733487/58328940-af3db700-7e33-11e9-831d-204daf262ebd.png)
3) Enter `1` ind the find box and hit enter, looks so
![grafik](https://user-images.githubusercontent.com/13733487/58328995-ced4df80-7e33-11e9-8877-a7526c4fab09.png)
4) press the button to permanently delete the files from trash, looks so
![grafik](https://user-images.githubusercontent.com/13733487/58329089-00e64180-7e34-11e9-8711-289980c85e8e.png)

which is bad, because only one file is visible. We should respect the find content here

**Comment by sguyader** [comment]
I don't know, this behaviour looks normal to me:
1. when you filter, you don't select, you just don't show what is filtered out (though the hidden files are still there),
2. the button says "Permanently delete the files from trash", it doesn't say it will delete only what is shown or selected, so it is implicit that pressing the button will delete all the files from trash.

**Comment by Beep6581** [comment]
> when you filter, you don't select

Then filtering should alter the selection.

**Comment by Beep6581** [comment]
In fact, it already does, just apparently not consistently.

1. Select a bunch of thumbnails.
2. Enable metadata filters.
3. Filter by anything so that some thumbnails disappear.
4. Right-click on any remaining selected thumb and apply some black-and-white profile.
5. Disable metadata filters.

The profile was applied only to the visible thumbs.

**Comment by Beep6581** [comment]
1. Select a bunch of thumbnails.
2. Type some keyword in the "Find" box so that some thumbnails disappear.
4. Hit tab to move focus out of the Find box, then press the delete key on your keyboard. The visible thumbs now have a "Deleted" icon.
5. Clear the find query.

Only visible files were deleted.

So again, actions are performed only on visible thumbnails, which in my opinion is correct and anything else would be wrong and dangerous.

**Comment by Beep6581** [comment]
Which takes me to the root of the problem - the "permanently delete the files from trash" message is wrong. 

Let's assume 10 files were selected but 3 are visible.
```
File delete confirmation
Are you sure you want to delete the selected 10 files?
```

The selection is completely ignored. You can select 3 or 0 files, and it will still want to delete all files in trash. So,
- either it should respect the selection, which IMHO is not a good idea, since then we have a problem of ambiguity if nothing is selected,
- or it should say "Delete all 3 visible files?"
- or it should say "Delete all 10 files in trash?"

The third solution is simplest.

**Comment by heckflosse** [comment]
@Beep6581 :+1: for the third solution
