### ISSUE TITLE
Bug: Filmnegative will not update thumbnail

### ISSUE THREAD

**Issue by TooWaBoo** [Beep6581/RawTherapee#5397]
If you enable/disable Filmnegative the thumbnails will not be updated. When you restart RT the thumbs are shown correct.

**Comment by heckflosse** [comment]
Confirmed. When enabling from editor the thumb will not be updated. Works fine from filebrowser.

**Comment by heckflosse** [comment]
ping @rom9

**Comment by rom9** [comment]
I think i've found the root cause. Actually, it's not just a problem with filmnegative; none of the tools in the "Raw" page seems to update the thumbnail automatically (for example try to move r,g,b black points to extreme values; the thumbnail won't get updated until you touch some other non-raw tool).
Looks like it's due to this `needsReprocessing`  flag :
https://github.com/Beep6581/RawTherapee/blob/2ec224c9ef2f9427e79d87d18367424c8c6cc576/rtgui/thumbnail.cc#L446

... i've printed it, and it's always false for non-raw parameters. When it's true, the thumbnail is updated.
So, what should i do now?
- add a specific condition to request reprocessing **just for filmnegative** params change?
- ... or, request reprocessing for **all** raw params changes?

I guess this optimization was there for a reason, so unlocking it for all raw params seems too much. Also, filmnegative is maybe the most evident of the raw params (it literally flips over your colors!), the others might not even be visible in a thumbnail.
So, maybe it makes sense to add the special case.
Opinions? :-)

**Comment by heckflosse** [comment]
:+1: for a special case

**Comment by heckflosse** [comment]
Works fine here :+1:
