### ISSUE TITLE
Hovered edit object not dragged if inside a red crop's rectangle

### ISSUE THREAD

**Issue by Hombre57** [Beep6581/RawTherapee#5415]
Step to reproduce :
  1. Edit an image
  2. Click on the Edit button of the Gradient tool
  3. Create a new detail tab
  4. Move the red rectangle to the location of the center spot of the edit widgets
  5. Hover the center spot and drag it

Result : it move the red rectangle instead of the spot. Lit widgets should take precedence over crop's rectangle.

**Comment by Hombre57** [comment]
Fix in branch `objectprecedence`

@Beep6581 I'd like to add this one to 5.7 too.

**Comment by ff2000** [comment]
Can it be solved the same way for this issue?
https://github.com/Beep6581/RawTherapee/issues/5354

**Comment by Hombre57** [comment]
@ff2000 I didn't saw that issue. I will fix it as well.

**Comment by Beep6581** [comment]
Issue confirmed, compiling `objectprecedence`...

**Comment by Beep6581** [comment]
@Hombre57 fix confirmed, :+1: for merge.

Some further things I observed:
* While the bug described in this issue is fixed, there is still a bug with the mouse cursor icon. Here you can see that the horizontal line is orange so I can rotate the widget, yet the cursor icon is for "resize crop vertically" ![node-move-y-hicontrast](https://user-images.githubusercontent.com/5844619/63224118-e962ee80-c1bf-11e9-9ef8-655d0963f6e7.png) when it should be "rotate" ![rotate-aroundnode-hicontrast](https://user-images.githubusercontent.com/5844619/63224123-f8e23780-c1bf-11e9-9748-273cf04a6eb3.png): 
![screenshot_20190818_135416](https://user-images.githubusercontent.com/5844619/63224100-aef95180-c1bf-11e9-82ef-423417ab8c80.png)
* The graduated filter's center spot "catching area" is quite large, too large I would say. In this screenshot, the spot is orange even though my cursor is far away from it: 
![screenshot_20190818_134654](https://user-images.githubusercontent.com/5844619/63224038-c257ed00-c1be-11e9-8a95-a587742769ab.png)
The catching area of the other elements of this on-preview widget is limited to the cursor actually hovering over them, e.g. the horizontal line turns orange only when I hover the cursor directly over it: 
![screenshot_20190818_134848](https://user-images.githubusercontent.com/5844619/63224047-f7643f80-c1be-11e9-97cf-3f1706691499.png)
So there is inconsistency.
The center spot's large catching area becomes annoying e.g. in this situation, where I'm hovering over the red frame and not the center spot: 
![screenshot_20190818_135006](https://user-images.githubusercontent.com/5844619/63224066-30041900-c1bf-11e9-9476-3ebbb0b84d5a.png)
I would suggest reducing the center spot's catching area, if possible.

**Comment by Hombre57** [comment]
@Beep6581

I'm investigating for point 1.

For point 2, I deliberately made it way bigger to avoid having to precisely go over it, and that's a feature to me :wink: . The visible spot is set to [6px here](https://github.com/Beep6581/RawTherapee/blob/ee38731328e3b4868650b5eb3a88779a6935998b/rtgui/gradient.cc#L72), the catching spot is set to [30px here](https://github.com/Beep6581/RawTherapee/blob/ee38731328e3b4868650b5eb3a88779a6935998b/rtgui/gradient.cc#L96) (i.e. 5x visible radius). Which value do you suggest for the catching point ? I'd say setting it to 2x, if you don't mind.

**Comment by Hombre57** [comment]
@Beep6581 Commit 8bb88073fa1fd59ec9723a521a7a890838520f75 fixes the cursor bug and set the catching spot of the Gradient widget to 12, instead of 30. I'll commit tonight if no one objects.

**Comment by Hombre57** [comment]
Committed to dev ( 5b320c9e3524fa7244307a9000d170ad9987ebde )

**Comment by ff2000** [comment]
I think this introduced a crash. For backtrace see here:
https://github.com/Beep6581/RawTherapee/issues/5419#issuecomment-522503509

EDIT:
Reset newlocallab to 48a5d276 and the crash doesn't appear anymore. So it seems to confirm my assumption that this fix introduced the crash.
To reproduce the crash simple enable crop and either gradient tool editor (overlay) or a spot in locallab. Close RT while tool overlay visible. That will crash RT.

**Comment by Beep6581** [comment]
@Hombre57 12 is good, and bugfix confirmed :+1:
