### ISSUE TITLE
Zoom axis and panning

### ISSUE THREAD

**Issue by fferreres** [Beep6581/RawTherapee#5455]
I use RT extensively as an amateur and wanted to suggest zoom would zoom in based on pointer position (center of zoom) and two finger panning. Many laptops have touchpads with no buttons but gesture enabled, requiring pressing down the entire surface as one pans, which has my finger becoming flat; two fingers would not interfere with anything. Please do delete this if any dev finds it not to fall within a suggestion guideline. I love RT and while I may want 10,000 things, I know it's a very small team doing what otherwise would require maybe a hundred.

**Comment by Beep6581** [comment]
Hi @fferreres 

If I understood your request correctly, you want RawTherapee to zoom centered on the cursor position when using the touchpad. Well it does that already - I just confirmed using a mouse and using a touchpad. Please clarify which version you're using, what behavior you want and what the current behavior is.

**Comment by Entropy512** [comment]
It sounds almost like he's asking for two-finger to be a pan instead of a zoom?

As you've pointed out, RT already zooms centered on cursor position, and at least on Ubuntu 19.04 on an Acer Aspire R15, a two-finger gesture will zoom.

The underlying implementation of this (as you're aware, but to explain to fferes) is that at a lower level than RT (either the touchpad driver, or GTK+, I'm not entirely sure as I haven't dug THAT deeply yet, although evtest implies that applications can see individual mulitouch events from my ELAN touchpad), a two-finger gesture is converted into a scroll axis movement.  By the time RT sees it, it is a scroll up/down event.  RT does not currently see, or process, individual finger multitouch events.

I'm not sure yet if there's a way for an app to request low-level multitouch events from GTK+, and even if there were, it would be a pretty significant architectural change for RT.  Not to say that it will never happen, but I'm pretty sure it wouldn't be simple by any means.  (Interestingly, such an architectural change would lay the groundwork for making RT touchscreen friendly too - it most definitely is not now.)

**Comment by fferreres** [comment]
I understand, I didn't know RT didn't have access to gestures. Yes, the mention is correct, to use pan with two fingers, and Z to zoom in under the cursor. In a few years, would be lovely to have a table mode.
