### ISSUE TITLE
Canon EOS 2000D white frames

### ISSUE THREAD

**Issue by falket** [Beep6581/RawTherapee#5495]
Shots required for adding camconst.json support for Canon EOS 2000D:

https://we.tl/t-cLc5yNsDM4

Following this: https://discuss.pixls.us/t/playraw-country-sunset/14199

I took pictures at F1:4.5 due to not powerful enougth lamp at iso 100, sorry.

Thank you in advance.

**Comment by Thanatomanic** [comment]
@falket Would it be possible for you to reupload these shots? It would be even better if you could try pointing your camera at a bright sky outside. That should make it easy to overexpose.

**Comment by falket** [comment]
Sorry but camera wasn't mine.

Here they are, for 6 days: https://we.tl/t-0TbBWRvt8o

Thank you!!

**Comment by Thanatomanic** [comment]
RT tells me all pictures were taken in f/11.0 which explains why it was harder for you to get a fully overexposed image I guess.
I've downloaded them and analyse them soon.

**Comment by falket** [comment]
Were they ok? Else i'll ask again to the owner. Tya.

**Comment by Thanatomanic** [comment]
@falket I have done the analysis, but I found some curious things that I need to understand and deal with first before I can get a proper estimate. There are clear lines appearing at random positions along the sensor where the readout values seem to differ a bit. I'm no expert on sensor tech, so I'm not sure if this is expected or not.

![image](https://user-images.githubusercontent.com/6567747/90369330-e5380e00-e06b-11ea-8a5c-8365c451858e.png)
Tested on your `IMG_5185.CR2` file (ISO 1600), but similar things are visible for other files and seem to getting worse with higher ISO.

Note that the effect is _greatly_ exaggerated here. In total, these lines amount to 0,8% of all pixels. All the white pixels have the same value of 15303 or 15304. The remaining pixels are distributed like this:

![image](https://user-images.githubusercontent.com/6567747/90369685-7d35f780-e06c-11ea-851f-b43382e0fc70.png)

For all non-LENR files the pixel distribution looks like this (on a log-scale):
![image](https://user-images.githubusercontent.com/6567747/90373066-aad16f80-e071-11ea-99aa-4037387ef40c.png)

It makes me think that the ISO100 picture is not fully over-exposed. For the others the cut-off is pretty clear, but the roll-off looks weird because of these lines.

This is the situation with LENR. Also ISO 100 seems not fully over-exposed. I expect the same for ISO 200 because of the large number of pixels at low values.
![image](https://user-images.githubusercontent.com/6567747/90373484-44991c80-e072-11ea-8989-7cd3288e75db.png)

It's interesting to see that Canon choose to cut off at 15303 without LENR, because _with_ LENR values can become higher, up to the limit of 2^14.

**Comment by falket** [comment]
If you think they could be useful, i'll ask for more overexposed picture (e.g. 2 seconds exposure or F5.6 instead of F11, or F8 1 second, just ask how much).

Thank you.

**Comment by Thanatomanic** [comment]
Comparing with different apertures can be tricky because of a possible aperture scaling effect.
So, if possible, it would be helpful to have another shot at ISO 100 and ISO 200, with and without LENR at f/11 _but_ properly over exposed while pointing at a very bright surface (a clear sky at midday should do the trick).

Additionally, to characterize a possible aperture scaling effect, it would help to have a series of over exposed shots at varying low apertures. Let's say from f/1.4 through f/5.6 at ISO 100. If your contact doesn't have a lens to accommodate this, please ignore this request. Aperture scaling is usually a very minor effect, or not even present at all.

Finally, to investigate the unexplained lines better, it would be interesting to see a series shot at the lowest aperture you can get at moderate ISO, let's say ISO 800 but vary the shutter speed, for example from 1 sec in steps down to whenever you cannot get full overexposure anymore. Would that be possible?

**Comment by falket** [comment]
asked, i'll post here if and when i'll receive the shots, thank you! iirc no fast lens.
