### ISSUE TITLE
Crop problems

### ISSUE THREAD

**Issue by akidee** [Beep6581/RawTherapee#5542]
Version: 5.6
Mac OS 10.11

- The UI (info above in image are and navigator) does not instantly reflect changes under Transform -> Crop. But the exported image will have the correct size.
- Rotating the image changes the crop: In landscape mode, I enter 16, 10, 6000, 4000 for left, top, width, height. After rotating by 90° to the left, I get 10, 13, 4000, 6000. By 270° (clicking 90° button three times): 9 16 4000 6000
- Applying a profile with a crop to a rotated image does not take rotation into account. I must apply it before any rotation. I prefer the Lightroom behavior.

**Comment by Beep6581** [comment]
Tested in `5.7-252-g`f054ed00e and 1 is not a bug, 2 cannot reproduce, 3 confirmed though the current behavior seems correct.

@akidee please test whether a bug exists in the latest release before reporting (yes I am aware that 5.7 does not run on some macs, but much has changed since 5.6), and then open 1 issue per problem along with a clear description and all necessary info.
https://rawpedia.rawtherapee.com/How_to_write_useful_bug_reports
