### ISSUE TITLE
Versioning for bugfix releases

### ISSUE THREAD

**Issue by Entropy512** [Beep6581/RawTherapee#5642]
This doesn't really affect me since I'm just running git master, but it does affect the project as a whole:

It seems like every time RT does a release, there are a few minor build issues identified and resolved.  Some of them need minor code changes, some just a rebuild/fix to the "release" build process like the lensfun data bundle situation on Windows.

After this, the builds are re-uploaded, but still with the same version.  e.g. "fixed" 5.8 release for Windows.

Perhaps these minor bugfix releases should get additional versioning info?  5.8.0, then 5.8.1 and so on?

Should there perhaps be a series of RC releases before formally announcing the final (which never really winds up being final) release?

**Comment by Thanatomanic** [comment]
I concur with the idea of bumping a minor version when the functionality of a downloadable installer is changed. @Beep6581 I know you said that there were no code changes and a version increase is not necessary. But to me this is simply an indication that _something_ was not completely right with the previous package and I am encouraged to update.

RC versions are also possible.

**Comment by Thanatomanic** [comment]
See also https://semver.org/ (which we kinda follow) and point 3 of the specs there.

**Comment by Entropy512** [comment]
I think the challenge here might be that in cases where it's JUST a build change for one OS - what to do with the OSes that didn't change?  Just rerelease the same package with a version bump to the minor rev, or just say in release notes that the point release is OS-specific or build-specific and thus other OSes will not get rebuild/re-released?

semver isn't very clear on exactly what the strategy is for this.

My proposal would be:
Minor version bump if anything changes, even if it's an OS-specific change or even a rebuild without code changes
If OS-specific, indicate in the release notes that only that OS is getting the version bump
Not sure what to do when another OS needs a minor OS-specific tweak - reuse the highest version number and update release notes, or have that be one above the previous OS-specific version?  I think reusing the highest version number might be less confusing to users in the long term, but in the short term could have some instances of MAJOR.MINOR.PATCH release notes that don't indicate that .PATCH includes fixes for the second OS.

**Comment by Beep6581** [comment]
> After this, the builds are re-uploaded, but still with the same version

Not so. In the past I made release candidates to catch issues before a final release, issues which required code changes, and each new candidate had a new tag.

Due to real life circumstances, I had no time for release candidates for 5.8. I hoped for the best, and it worked out, except for the Windows build which needed rebuilding. The rebuild required no changes to the source code, so the 5.8 tag is valid.

Point 3 of the semver link therefore does not apply. The 5.8 tarball has not changed. 

Calling the Windows build "5.8.1" would leave users asking us "why doesn't Linux/macOS/FreeBSD/YouNameIt have 5.8.1?" It would also be misleading, since the software would not have changed at all. Besides, the third digit in the version is reserved for real tags which describe real code changes.

I also have no time nor interest in going through the whole release process again because there's an omission in one build which does not affect the source code at all and which does not affect other builds or other platforms at all.

I see no solution which doesn't have down-sides, but I am certain that adding a new tag is not it. Perhaps in the future should such a situation reoccur I will just append "-r1" (revision 1) to the build filename (not the tag). Yes, the more I think of it, the more I'm sure this is the best solution.
