### ISSUE TITLE
Localization - Do not update translations until default is reviewed

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#5664]
Following today's large merges, some changes need to be made to `rtdata/languages/default` and possibly relevant keys in source files. Please do not make translations until this issue is closed.

**Comment by Beep6581** [comment]
Review in progress...

**Comment by Beep6581** [comment]
English terminology reference: https://www.researchgate.net/publication/238778749_Applying_CIECAM02_for_Mobile_Display_Viewing_Conditions

**Comment by Beep6581** [comment]
@Desmis et al are these keys really used? I can't seem to trigger them. There is code using them, but it appears that the code is excluded from the UI and so should be deleted (either in `review_default` or after this branch is merged into `dev`):
```
HISTORY_MSG_CAT02PRESET
TP_COLORAPP_PRESETCAT02
TP_COLORAPP_PRESETCAT02_TIP
```

**Comment by Desmis** [comment]
@Beep6581 
I did this some time ago to simplify the interface of "Color appearance & lighting" which is a complex module.

I am not in favor of deleting this part of code which I think will one day be the subject of a request. Of course we can delete (it's easier to delete than to add), but I repeat myself it is likely that one day (??) we will ask again for this "preset" which is more in line with Ciecam... But if I am told "delete", no problem....

Jacques

**Comment by Beep6581** [comment]
This is called 'boat anchor code', because like an anchor it weighs down the boat. It's a design anti-pattern.

**Comment by Desmis** [comment]
@Beep6581 
This is your point of view, not mine. It turns out that we don't have the same conception (to put it mildly) of complex subjects...

**So tomorrow when I have time, I delete..**.

Another detail, as you have been away for a long time, you are probably unaware of my state of health...I have been (very) ill for more than 2 years now. Currently I am on radiotherapy combined with chemotherapy...and the future is more than unlikely. I could have a lack of dynamism, even burnout...especially in front of inaction, but I try by all means to keep my head above water. Fortunately and finally it seems to be moving forward.

Jacques

**Comment by Beep6581** [comment]
@Desmis I'm sorry to hear about your health issues and hope you get better soon.

**Comment by Beep6581** [comment]
Branch is ready for merging.

**Comment by Lawrence37** [comment]
Reopening this because the key name changes have not been propagated to the translations. Otherwise, this can cause translators to waste time translating strings that have already been translated.

**Comment by Beep6581** [comment]
Done, all localization files are ready for translation.

@TechXavAL et al: compare `default` from tag 5.8 against HEAD to see what existing keys changed:
https://github.com/Beep6581/RawTherapee/compare/5.8...HEAD#diff-7331859744901fabea4eb0f1fa10e2155f68c4177b3fb62fca3838ebe0148bb9
