### ISSUE TITLE
Regression in lens identification

### ISSUE THREAD

**Issue by Barugon** [Beep6581/RawTherapee#5670]
Version: 5.8 AppImage for Linux.
OS: Fedora 31, x86_64.

The lens EXIF shows as "Unknown".

![lens_exif](https://user-images.githubusercontent.com/16503728/75406319-07bf4a80-58c5-11ea-97ca-85c5ef8b976d.png)

This seems to cause Profiled Lens Selection to not be able to automatically find the correct lens (even thought it's in the list).

![lens_select](https://user-images.githubusercontent.com/16503728/75406700-ff1b4400-58c5-11ea-93b5-3f92af715fd5.png)

You can get a raw file [here](https://www.dpreview.com/reviews/image-comparison/download-image?s3Key=c44354db78824e85b37b34253e5d593b.arw) that will show this issue.

**Comment by Beep6581** [comment]
```text
$ exiftool -G5 -s -args ~/downloads/a7M3Studio0008.ARW | grep -E "Lens(Info|Model|Type|Spec|ID)"
-TIFF-IFD0-ExifIFD:LensInfo=85mm f/1.8
-TIFF-IFD0-ExifIFD:LensModel=FE 85mm F1.8
-TIFF-IFD0-ExifIFD-MakerNotes:LensType=E-Mount, T-Mount, Other Lens or no lens
-TIFF-IFD0-ExifIFD-MakerNotes:LensSpec=FE 85mm F1.8
-TIFF-IFD0-ExifIFD-MakerNotes-Tag940c:LensType3=Sony FE 85mm F1.8 or Viltrox PFU RBMH 85mm F1.8
-TIFF-IFD0-ExifIFD-MakerNotes-Tag9050b:LensType2=Sony FE 85mm F1.8 or Viltrox PFU RBMH 85mm F1.8
-TIFF-IFD0-ExifIFD-MakerNotes-Tag9050b:LensSpecFeatures=FE
-Composite:LensID=Sony FE 85mm F1.8
```

The lens metadata is in RT:
```
$ grep -rni viltrox rtexif/sonyminoltaattribs.cc
1059:        choices.insert (p_t (32796, "Sony FE 85mm f/1.8 or Viltrox PFU RBMH 85mm f/1.8"));
```

**Comment by aferrero2707** [comment]
@Beep6581 Is this a problem that needs to be investigated? Could this be due to the packaging process for the AppImage?

**Comment by Barugon** [comment]
I switched to Fedora's package and it's still a problem.

**Comment by Floflo81** [comment]
I have exactly the same issue with another Sony camera and another lens.

Camera: Sony ILCE-6000
Lens: Sony E PZ 18-105 f/4 G OSS

In previous versions of RawTherapee (5.6 or 5.7, not sure), the lens was detected automatically.

OS: Windows 10 Pro 64-bit version 1909
RawTherapee version: 5.8 official (downloaded 2020 13th Feb)

Here is a RAW sample that exhibits the problem:
[RawTherapee bug sample.zip](https://github.com/Beep6581/RawTherapee/files/4399311/RawTherapee.bug.sample.zip)

**Comment by Barugon** [comment]
> I have exactly the same issue with another Sony camera and another lens.
> 
> Camera: Sony ILCE-6000
> Lens: Sony E PZ 18-105 f/4 G OSS
> 
> In previous versions of RawTherapee (2.6 or 2.7, not sure), the lens was detected automatically.
> 
> OS: Windows 10 Pro 64-bit version 1909
> RawTherapee version: 2.8 official (downloaded 2020 13th Feb)
> 
> Here is a RAW sample that exhibits the problem:
> [RawTherapee bug sample.zip](https://github.com/Beep6581/RawTherapee/files/4399311/RawTherapee.bug.sample.zip)

Do you mean previous versions 5.6, 5.7 and the current version 5.8?

**Comment by Floflo81** [comment]
> Do you mean previous versions 5.6, 5.7 and the current version 5.8?

Yes that was a typo. I'll fix it. Thanks for the proofreading :)

**Comment by Floflo81** [comment]
I don't really know the RawTherapee codebase, but I think this bug is probably related to this change made between version 5.7 and version 5.8 by developer @Beep6581 :
https://github.com/Beep6581/RawTherapee/commit/24684e5cb35a2d487cc74407941b795788566a9f#diff-c48d3b4090810e8ab4709ac8f8a2a5e5

In file "sonyminoltaattribs.cc", several lenses were removed from the **SALensIDInterpreter** class, including the 2 lenses I use (appeared twice before):

- {6553, "Sony E PZ 18-105mm f/4 G OSS"}
- {6553, "Sigma 56mm f/1.4 DC DN | C"}
- {65535, "Sony E PZ 18-105mm f/4 G OSS"}
- {65535, "Sigma 56mm f/1.4 DC DN | C"}

They are still listed in the **SALensID2Interpreter** class, but that's probably not enough? Is that 2nd class used correctly?

**Comment by th-rt** [comment]
I've got the same problem here in RT 5.8 (AppImage on Ubuntu 19.10) with a Sony ILCE-7M3 and a Sony FE 24-70 F2.8 GM lens. The lens model is shown correctly in the Exif pane, but it is not recognized by RT and the related dynamic profile is not selected.

![grafik](https://user-images.githubusercontent.com/63954862/79685839-f9920880-823b-11ea-8f56-91206124d0c0.png)
![grafik](https://user-images.githubusercontent.com/63954862/79685881-51307400-823c-11ea-9c6a-06d5e7a5a890.png)

In RT 5.7 (also AppImage on Ubuntu 19.10) it works:
![grafik](https://user-images.githubusercontent.com/63954862/79685942-c734db00-823c-11ea-869a-b07963c14320.png)

**Comment by aferrero2707** [comment]
If I understand correctly the issue, this is not related to the AppImage package itself, but to a change in `sonyminoltaattribs.cc`. @Beep6581 could you confirm?

**Comment by Beep6581** [comment]
@aferrero2707 hey, yes I confirm that this is unrelated to the AppImage or to packaging and derives from what seems to be a cleanup in ExifTool's DB which is where RT still derives its lens data from.

**Comment by Beep6581** [comment]
Keep an eye on upstream issue https://github.com/exiftool/exiftool/issues/54

**Comment by Beep6581** [comment]
The proper solution is and has been to adopt Exiv2 or ExifTool to handle metadata in RT #3801.

**Comment by aradzie** [comment]
I am experiencing the same problem.

- RawTherapee version: **5.8**
- Camera Name: **Sony Alpha 6400** (**ILCE-6400**)
- Lenses: **Sony E 35mm F1.8 OSS** and **Sony E PZ 16-50mm F3.5-5.6 OSS**

ExifTool reports lens info correctly:

```
exiftool DSC00149.ARW | grep -i lens
Lens Type                       : E-Mount, T-Mount, Other Lens or no lens
Lens Spec                       : E 35mm F1.8 OSS
Lens Zoom Position              : 0%
Lens Mount 2                    : E-mount
Lens Type 3                     : Sony E 35mm F1.8 OSS
Lens E-mount Version            : 1.20
Lens Firmware Version           : Ver.01.000
Lens Mount                      : E-mount
Lens Format                     : APS-C
Lens Type 2                     : Sony E 35mm F1.8 OSS
Lens Spec Features              : E OSS
Lens Info                       : 35mm f/1.8
Lens Model                      : E 35mm F1.8 OSS
Lens ID                         : Sony E 35mm F1.8 OSS
```

I have re-built RawTherapee from the dev branch (commit `6b749bcbff`) but the problem still persists.

How can I help with fixing this bug?

**Comment by Beep6581** [comment]
The missing lenses result from an ExifTool cleanup and RT not keeping up with the changes:

> Before version 11.56, Sony E-type lenses were duplicated in both Minolta.pm and Sony.pm, which was a bit of a bookkeeping headache. So instead, LensType 65535 is handled specially for Sony NEX and ICLE models, and the sonyLensType2 list is used instead: https://exiftool.org/TagNames/Sony.html#LensType2

https://github.com/exiftool/exiftool/issues/54#issuecomment-661060428

Though I don't understand why RT doesn't identify
`32810 | = Sony FE 70-200mm F4 G OSS`
for instance, since RT seems to support `LensType2` via `SALensID2Interpreter` where that lens can be found as
`choices.insert (p_t (32810, "Sony FE 70-200mm f/4 G OSS"));`

**Comment by Floflo81** [comment]
> Though I don't understand why RT doesn't identify
> `32810 | = Sony FE 70-200mm F4 G OSS`
> for instance, since RT seems to support `LensType2` via `SALensID2Interpreter` where that lens can be found as
> `choices.insert (p_t (32810, "Sony FE 70-200mm f/4 G OSS"));`

Yeah I think that's the root of the problem. My 2 lenses that are not recognized since RT 5.8 are also listed in SALensID2Interpreter.
Please check how this class is used by RawTherapee

**Comment by Floessie** [comment]
@Beep6581 @Floflo81 There's no tag 0x0114 in the file provided, thus the `SALensID2Interpreter` path isn't taken.

**Comment by Floessie** [comment]
@Beep6581 
> So instead, LensType 65535 is handled **specially** for Sony NEX and ICLE models,

It seems, RT is missing that special sauce. :wink:

**Comment by Beep6581** [comment]
Yes:
https://github.com/exiftool/exiftool/blob/master/lib/Image/ExifTool/Exif.pm#L5314

**Comment by Bezierr** [comment]
![Capture](https://user-images.githubusercontent.com/38507161/115381867-89f28880-a1c3-11eb-9a17-3ac071b16957.JPG)

Having experienced the same problem with Sony lenses, I looked into the RT code and found the following:

The "Unknown (55m f1.8)" value (in my case) is returned by the line

lens = mnote->getTag ("LensID")->valueToString ();

in file rtengine\imagedata.cc for Sony. So assuming the "getTag" works correctly, it is apparently what some (?) Sony cameras write for this tag. Whereas "exiftool -lensmodel" gives a much better "FE 55mm F1.8 ZA".


I see three possibilities to deal with this.

1) Leave it as it is -- as long as you don't own two Sony lenses with the same specs, you should be fine, and can distinguish them.

2) Change the code that checks for the Sony lens to something like

                } else if (mnote && (!make.compare (0, 4, "SONY") || !make.compare (0, 6, "KONICA"))) {
                    if (mnote->getTag ("LensID")) {
                        lens = mnote->getTag ("LensID")->valueToString (); 
                    }
                    if (!lens.compare (0, 7, "Unknown")) {
                        lens_from_make_and_model();
                    }
                } else if (!make.compare (0, 7, "OLYMPUS")) {

3) Follow the FUJIFILM model and change the Sony code (further up in imagedata.cc) to something like

        if(!make.compare (0, 8, "FUJIFILM")) {
            if(exif->getTag ("LensModel")) {
                lens = exif->getTag ("LensModel")->valueToString ();
            }
        } else if(!make.compare (0, 4, "SONY")) {
            if(exif->getTag ("LensModel")) {
                lens = exif->getTag ("LensModel")->valueToString ();
            }
            if (iso_speed == 65535 || iso_speed == 0) {
                rtexif::Tag* isoTag = exif->getTag ("RecommendedExposureIndex");

                if(isoTag) {
                    iso_speed = isoTag->toDouble();
                }
            }
         }
 
Both option 2 and 3 get the correct lens.![Capture2](https://user-images.githubusercontent.com/38507161/115381882-8e1ea600-a1c3-11eb-82a9-3f3eb57be7bf.JPG)

I personally would prefer option 3 since I know that my pictures will always have the right lens name in the exif:lensmodel tag, whereas I don't know whether Sony lenses in makernotes/LensID will always begin with "Unknown".

If you would like me to upload my code please let me know.

**Comment by Bezierr** [comment]
Given that this issue is now almost 2 years old and apparently still persists in the dev branch (I might not use the very latest, though): Any idea on how to proceed with this? I'm perfectly happy with my solutions on my local build, but wouldn't it be good to have a solution for everyone?

**Comment by Bezierr** [comment]
Ok. Having had some time available, I tried my hand on this lenstype2 issue, but having never worked with the tag structure before, I'm somewhat out of my depths here. Unless someone can give me a useful hint, I'll have to give up.

What I found:

First, I haven't found a place in the code where the special situation "lenstype==65535", or rather, "lensmount==2", indicating an E-Mount lens, is handled. This could be fixed by adding something like this in imagedata.cc:

if (mnote->getTag ("LensID")->toInt()==65535
     && mnote->getTag ("Tag9405")
     && mnote->getTag ("Tag9405")->getDirectory()
     && mnote->getTag ("Tag9405")->getDirectory()->getTag ("LensType2")) {
     lens = mnote->getTag("Tag9405")->getDirectory()->getTag("LensType2")->valueToString ();
 } else {
     lens = mnote->getTag ("LensID")->valueToString ();
}


Second, there seems to be a bug in sonyTag9405Attribs[] in file sonyminoltaattribs.cc. I should think that it is supposed to be
    {0, AC_WRITE, 0, nullptr, 0x0060, SHORT, "LensType2", &saLensID2Interpreter},
instead of
    {0, AC_WRITE, 0, nullptr, 0x0060, SHORT, "LensType2", &stdInterpreterr},


Third, the mechanism in rtexif.cc/TagDirectoryTable that tries to retrieve the values for the 9405 tags doesn't seem to work correctly, at least for this case. It creates the tags but writes meaningless values (usually zeroes, in my case). The pointer to the data in the file apparently is not computed correctly. 
If, however, I set manually (i.e. in the code), e.g.,
newTag->value[0]=48;
newTag->value[1]=128;
with the additional changes described above, the lens is finally correctly identified as "Sony FE 28mm f/2" :-)
But I have no idea how to get RT to extract these values from the ARW file.

The information in my ARW file for tag 9405 is as follows:
0594 0700 0008 0000 9427 0000

Can anyone give me an idea how, based on this information, I can retrieve the value for lenstype2?

Or, in case I'm barking up a very wrong tree here, please let me know.

**Comment by yajo** [comment]
I seem to be hitting this same bug. Fortunately I can use the lens dropdown and select the lens, but I gotta admit it's not so comfortable.

FWIW:

```
> exiftool DSC00874.ARW | grep Lens
Lens Type                       : E-Mount, T-Mount, Other Lens or no lens
Lens Spec                       : E PZ 16-50mm F3.5-5.6 OSS
Lens Zoom Position              : 0%
Lens Mount 2                    : E-mount
Lens Type 3                     : Sony E PZ 16-50mm F3.5-5.6 OSS
Lens E-mount Version            : 1.20
Lens Firmware Version           : Ver.01.009
Lens Mount                      : E-mount
Lens Format                     : APS-C
Lens Type 2                     : Sony E PZ 16-50mm F3.5-5.6 OSS
Lens Spec Features              : E PZ OSS
Lens Info                       : 16-50mm f/3.5-5.6
Lens Model                      : E PZ 16-50mm F3.5-5.6 OSS
Lens ID                         : Sony E PZ 16-50mm F3.5-5.6 OSS
```

According to https://lensfun.github.io/lenslist/ this lens is supported, although it's named  `E 16-50mm f/3.5-5.6 OSS PZ` there. I can find [two more names in lensfun codebase](https://github.com/lensfun/lensfun/blob/7731c83c219ede6463275f836078f5e82ba8d0be/data/db/mil-sony.xml#L695-L696). The differences between the names are subtle, but they exist. 

Also the name displayed in RT is slightly different because it includes the brand (possibly this is OK and on purpose):
![image](https://user-images.githubusercontent.com/973709/201996725-dc8ce8ff-ee7d-477c-9b09-1a2e8604cbb9.png)


Summarizing:

```
E PZ 16-50mm F3.5-5.6 OSS
E PZ 16-50mm f/3.5-5.6 OSS
E 16-50mm f/3.5-5.6 OSS PZ
```

Maybe it is because of these slight differences that it can't find the lens?

Is there any build where I can test https://github.com/Beep6581/RawTherapee/pull/6437 to see if it fixes the problem?

Thanks!

**Comment by Beep6581** [comment]
@yajo https://github.com/Beep6581/RawTherapee/releases/tag/nightly-github-actions

**Comment by yajo** [comment]
Nice! It works with my 2 Sony lenses. Thanks!

**Comment by Beep6581** [comment]
Lens metadata for `a7M3Studio0008.ARW` and `chicken.arw ` displays fine in current code.

> It seems, RT is missing that special sauce. wink

@Floessie has RT gained that special sauce?

Shall we close?

**Comment by Floessie** [comment]
> @Floessie has RT gained that special sauce?

I didn't track this issue. Maybe a change by @Thanatomanic did the trick?

**Comment by Thanatomanic** [comment]
I can take a look. I have propagated some changes from ExifTool recently which may have broken something...

**Comment by Floessie** [comment]
> I have propagated some changes from ExifTool recently which may have broken something...

... or fixed something (like here). :wink:

**Comment by Floflo81** [comment]
I just downloaded RawTherapee version 5.9.

This issue seems 100% fixed to me. Now the lens info for ARW files from my Sony camera appears correctly, and in "Profiled Lens Correction", the "Automatically selected" option works!

That's maybe thanks to the changes by @Thanatomanic !?

**Comment by Thanatomanic** [comment]
Perhaps! In any case, thanks for confirming the bug is gone. We can close.
