### ISSUE TITLE
Thumb Browser scrolling proposal

### ISSUE THREAD

**Issue by oisanjaya** [Beep6581/RawTherapee#5680]
Hello, sorry it's first time i'm posting on github.

The Thumb Browser scrolling i feel a little bit weird with mouse scrolling. It feels like static grid with thumbnail jumping around inside them. I suggest it scrolls not by whole height of grid height but slightly more or slightly less.

I found modifiying rtgui/thumbrowserbase.cc a little bit will do the trick, like : 
`bool ThumbBrowserBase::Internal::on_scroll_event (GdkEventScroll* event)
{
    // Gtk signals automatically acquire the GUI (i.e. this method is enclosed by gdk_thread_enter and gdk_thread_leave)
    parent->scroll (event->direction, event->delta_x, event->delta_y * 0.8);
    return true;
}`
or maybe even better, create smooth scrolling animation.

I don't know how to contribute or discuss about this, should i post pull request or what?

**Comment by Thanatomanic** [comment]
Hi! And thanks for your submission. This issue has been discussed in the past, and it seems to boil down to a matter of taste. See https://github.com/Beep6581/RawTherapee/pull/4652 and old https://github.com/Beep6581/RawTherapee/issues/1901. There may still be real UI/UX problems like this https://github.com/Beep6581/RawTherapee/issues/4663, but otherwise, in particular for large folders or scrolling using the arrow keys on your keyboard, having the current behaviour would still be much preferred. You want to be able to navigate quickly imho. For what reason should it be smooth?

**Comment by oisanjaya** [comment]
ah, i see then.
before posting this i try to search similar topic about scrolling but failed to read about #4652

i always thinking scrolling at exactly image height feels weird, like the grid, which i expect to be scrolling up/down, looks static while the images iside look like just changes quickly. but if it is the preffered behaviour then, i will be fine with that.
