### ISSUE TITLE
5.8 is applying irreversable crop to the image

### ISSUE THREAD

**Issue by bertoo87** [Beep6581/RawTherapee#5712]
Hey guys.

i got a little issue with SOME of my files - not all of them are affected.
My issue is triggered very simple: open the Image. it applies a heavy crop which i cant really reset. I can reset the Profile Changes made after i switched the image, but as soon as i open these images again, the crop is back. Ive made a little video and attached the example RAW File here: https://filebin.net/e3304ht4w1jj6ddd

Im running Windows 10 Home, Version 1903, Build 18362.720

I really hope there is a way to fix this.

**Comment by Thanatomanic** [comment]
This was fixed in the development version two days ago: https://github.com/Beep6581/RawTherapee/issues/5709
You can download a [nightly build](https://github.com/Beep6581/RawTherapee/releases/tag/nightly) if you want the correct functionality now, or otherwise you'll have to wait until version 5.9 comes out.

**Comment by bertoo87** [comment]
Thanks for the response. works like a charm :)
