### ISSUE TITLE
RT windows 5.8-2330: Libssp-0.dll library is missing

### ISSUE THREAD

**Issue by arturoisilvia** [Beep6581/RawTherapee#5841]
In:
RawTherapee_dev_5.8-2330-g53aec5e13_20200710.exe
RawTherapee_dev_5.8-2330-g53aec5e13_20200710_win64.zip

In both cases, running rawtherapee.exe gives the error.
![Error libssp-0 dll](https://user-images.githubusercontent.com/55624244/87222411-b3000600-c373-11ea-8281-cec901bbb18e.JPG)

**Comment by Thanatomanic** [comment]
Reported also [here](https://discuss.pixls.us/t/im-unable-to-run-rawtherapee-developer-versions-in-windows-any-more/19128) and [here](https://discuss.pixls.us/t/problems-installing-rawtherapee-dev-5-8-2334/19129).

**Comment by Thanatomanic** [comment]
Ping @aferrero2707, any clues for what could be going on in the automated build process? I have no trouble compiling and running `dev` manually...

**Comment by aferrero2707** [comment]
@arturoisilvia @Thanatomanic the `libssp-0.dll` library was part of the libraries that were explicitly removed from the bundle because considered as not needed. Something most have changed somewhere recently, which requires the bundling of this library. I have modified the build scripts and I am currently generating a new package. I will write a post here a s soon as there will be a fixed package to test...
Thanks!

**Comment by arturoisilvia** [comment]
@aferrero2707 : Tested the 2 new builds of windows:

RawTherapee_dev_5.8-2339-g8af287aa8_20200712.exe
RawTherapee_dev_5.8-2339-g8af287aa8_20200712_win64.zip

Now they work fine.

Thanks. Problem solved.

Regards.
