### ISSUE TITLE
Error in any parametric curve

### ISSUE THREAD

**Issue by arturoisilvia** [Beep6581/RawTherapee#5859]
Error in any parametric curve.
Points appear instead of curves:
I think this behavior is not correct. I don't know what to call it. 
It occurs with any parametric curve: Tone, Lab, local adjustments ... etc.
Process:
**1)**
![CParametrica01](https://user-images.githubusercontent.com/55624244/88107577-9d76b180-cba7-11ea-9b1b-c7e168ecce6a.JPG)
.
**2)**
![CParametrica02](https://user-images.githubusercontent.com/55624244/88107599-a6678300-cba7-11ea-96e2-47c6ba4e77cc.JPG)
.
**3)**
![CParametrica03](https://user-images.githubusercontent.com/55624244/88108560-5e496000-cba9-11ea-8c20-a0643e73c57d.JPG)

-----
Version: 5.8-2374-g746be1816
Branch: dev
Commit: 746be1816
Commit date: 2020-07-19
Compiler: gcc\ 10.1.0
Processor: generic x86
System: Windows
Bit depth: 64 bits
Gtkmm: V3.24.2
Lensfun: V0.3.2.0
Build type: Release
Build flags: -mwin32\ -m64\ -mthreads\ -msse2\ -std=c++11\ -mtune=generic\ -Werror=unused-label\ -Werror=delete-incomplete\ -fno-math-errno\ -Wall\ -Wuninitialized\ -Wcast-qual\ -Wno-deprecated-declarations\ -Wno-unused-result\ -Wunused-macros\ -fopenmp\ -Werror=unknown-pragmas\ -Wno-aggressive-loop-optimizations\ -DNDEBUG\ -O3\ -ftree-vectorize
Link flags: -m64\ -mthreads\ -static-libgcc\ -mtune=generic\ -s\ -O3
OpenMP support: ON
MMAP support: ON
Build OS: Linux 4.4.0-101-generic x86_64
Build date: Sun, 19 Jul 2020 21:20:58 +0000 UTC
Build epoch: 1595193658
Build UUID: c19ead07-bb99-4cd4-a2df-8b86fb414179

**Comment by jonathanBieler** [comment]
I've had a look at this and I think the issue arise around here :

https://github.com/Beep6581/RawTherapee/blob/f47f23a4dc04750ee8baee83724cf094a771ecb9/rtengine/diagonalcurves.cc#L451

The issue is that when the highlight point is dragged to the right `hbase` becomes smaller than 1e-14 and the curve value becomes just `mfc`, which is a constant.

Strange thing is that I translated this piece of code to Julia and in Julia removing the clamping to zero solves the issue, but doing the same in Rawtherapee doesn't. My guess is that the xlog and xexp functions of rawtherapee have less precision or something like that.

**Edit :** I think I've found a way to bypass the problem, seems to produce the same curve without the glitch :

![image](https://user-images.githubusercontent.com/5859344/115563804-31e97e00-a2b8-11eb-8c1e-4192211e2cc0.png)

I'll test a bit more and make a PR.
