### ISSUE TITLE
Hide/Show panel shortcuts don't work

### ISSUE THREAD

**Issue by rebio** [Beep6581/RawTherapee#5992]
`I` should toggle the left panel
`Shift + I` should toggle the top panel
`Alt + I` should toggle the right panel

The only thing that happens when either of the shortcuts is pressed is that the image information is toggled.

Happens on Win7 and Win10.

Version: 5.8
Branch: releases
Commit: 9a9e0acbf
Commit date: 2020-02-04
Compiler: x86_64-w64-mingw32-gcc\ 8.2.0
Processor: generic x86
System: Windows
Bit depth: 64 bits
Gtkmm: V3.24.2
Lensfun: V0.3.2.0
Build type: Release
Build flags: -mwin32\ -m64\ -mthreads\ -msse2\ -std=c++11\ -mtune=generic\ -Werror=unused-label\ -Werror=delete-incomplete\ -Wall\ -Wuninitialized\ -Wcast-qual\ -Wno-deprecated-declarations\ -Wno-unused-result\ -fopenmp\ -Werror=unknown-pragmas\ -Wno-aggressive-loop-optimizations\ -DNDEBUG\ -O3\ -ftree-vectorize
Link flags: -m64\ -mthreads\ -static-libgcc\ -mtune=generic\ -s\ -O3
OpenMP support: ON
MMAP support: ON

**Comment by Lawrence37** [comment]
The shortcuts are shown in lowercase, so the letter is `l`, not `I`.

**Comment by Thanatomanic** [comment]
The RawPedia page showed uppercase L's as shortcuts, but they are lowercase l's. I've just updated that.

**Comment by ff2000** [comment]
But that's how everywhere shortcuts are listed.
If Shift is involved it is printed explicitly, like "Alt + Shift + L".
I think that imight be because the labels printed on the keyboard are all uppercase and it might confuse users if shortcuts are listed lowercase.

Edit:
Just for reference:
https://support.mozilla.org/en-US/kb/keyboard-shortcuts-perform-firefox-tasks-quickly
https://www.gimpusers.com/gimp/hotkeys
Also Gnome/Gtk applications list their shortcuts with uppercase keys ind menus/help/shortcut settings - try e.g. gimp, nautilus, gnome-control-center.
On the Qt/KDE side it's the same.

**Comment by Thanatomanic** [comment]
~~I must admit that I didn't check, but at least I saw a mix of upper and lowercase mentions. So that means things may be inconsistent. I'll run through them asap and homogenize where necessary. Thanks for the notification!~~

Edit: it's early morning, sorry my post didn't make sense.

**Comment by Thanatomanic** [comment]
@ff2000 Actually, if you look at the list on RawPedia you see that all shortcuts are listed with lowercase indicators not uppercase. So whatever other software does, we apparently chose for lowercase. And the capital L for the panels was the exception that I fixed.
