### ISSUE TITLE
Output Resolution Problem

### ISSUE THREAD

**Issue by Chadt54** [Beep6581/RawTherapee#5998]
Is it possible for you to guarantee the image output resolution is exactly equal to the input resolution?

I find it odd that when I process a 6000x4000 pixel image, the output becomes 6016x4014, but I would like it to stay exactly 6000x4000.

Thank you!

**Comment by Thanatomanic** [comment]
This is most likely not a bug.

If the output is 6016×4014 pixels, the input is also 6016×4014 pixels, unless you've enabled Resize and allow Upscaling. RawTherapee usually uses more of the available raw data to process your image, whereas other software or your camera itself may crop a little off from the full sensor resolution to alleviate edge artifacts.

See here: http://rawpedia.rawtherapee.com/Demosaicing#Border
You can adjust this to your liking.

**Comment by Chadt54** [comment]
Here's my image details, I see 6000x4000 shown in multiple places, that's why I was confused. Although, looking closer, I do see something resembling borders, but the values are a little confusing. The Demosaicing Border does affect the output resolution as you say, but wouldn't it be more intuitive for users if you used the 6000x4000 values instead of what's currently being used? Or, have a setting that attempts to use the 6000x4000 value for the output somehow (since Adobe Bridge and Adobe Camera Raw seems to always output using the 6000x4000 parameter, as it's closer to the user's expectation, and the camera's advertised resolution)?

Although, I do see the predicament with the design decision. Seems like a tough one.

[online metadata and exif viewer.pdf](https://github.com/Beep6581/RawTherapee/files/5566020/online.metadata.and.exif.viewer.pdf)

**Comment by Thanatomanic** [comment]
The philosophy is that we want to squeeze as much as possible out of a raw file, so if there are pixels we don't _need_ to crop, we don't. If you look in your file, you'll see the sensor is bigger than 6000×4000 pixels: SensorWidth 6096, SensorHeight 4056. There are probably some rows or columns that are unused (black or bogus data) and need to be discarded. This happens a lot, see our [`camconst.json` file](https://github.com/Beep6581/RawTherapee/blob/dev/rtengine/camconst.json) and look for `raw_crop` values. 
But, whatever remains, we use. This is also regardless of the choices of other software or even camera manufacturers that often prefer 'nice numbers'.

You can always create a default profile that is applied to your images upon opening that enables the Resize module set to 6000×4000 pixels, so that your exported images will have your preferred dimensions.

**Comment by Chadt54** [comment]
Ok, I see. Thank you for explaining everything
