### ISSUE TITLE
Canon EOS 90D

### ISSUE THREAD

**Issue by HansRos51** [Beep6581/RawTherapee#6019]
Canon EOS 90D firmware v1.1.1
raw file (cr3) not recognised by rawtherapee 5.8

workaround: convert to DNG

**Comment by Thanatomanic** [comment]
Hello @HansRos51, can you provide a sample file so we can test this in the current development builds? The 90D pictures usually load fine.

**Comment by Thanatomanic** [comment]
Also, is this a recent firmware update? Did the images prior to this firmware version load correctly?

**Comment by HansRos51** [comment]
Purchased the camera last week. 3Dec2020

**Comment by HansRos51** [comment]
The file is about 30mb
https://drive.google.com/file/d/1-1R1Dqhe90icm5EDaOSFEuLl3O2eXVUC/view?usp=sharing

**Comment by HansRos51** [comment]
Firmware v1,1.1 released 31Oct2019

**Comment by Thanatomanic** [comment]
There is really no problem opening your file, so your initial report was either unnecessary or imprecise, sorry. The lack of metadata support (Exif) is well-known and will hopefully be fixed in the near future https://github.com/Beep6581/RawTherapee/issues/5319, however it depends on support in a third-party library. See here for more details: https://github.com/Exiv2/exiv2/issues/1229

Edit: In the future, if you're unsure about whether something is a bug or not, feel free to join our lovely support forum at https://pixls.us

![image](https://user-images.githubusercontent.com/6567747/101400124-b8389100-38d0-11eb-9be4-b414372f54b9.png)

**Comment by HansRos51** [comment]
Thx

Imprecise. 
CR3 dont show up in the file browser, only but dng, jpg do

![eos90d](https://user-images.githubusercontent.com/75640221/101401713-634e4800-38db-11eb-9be7-c64b3cace2ea.PNG)

**Comment by Thanatomanic** [comment]
@HansRos51 I see, please check your preferences and add CR3 to the extension list to have them show up. Happy editing!

![image](https://user-images.githubusercontent.com/6567747/101401863-3a29b980-38d3-11eb-8d1e-0bb12c2a56d8.png)

**Comment by HansRos51** [comment]
t1e6
