### ISSUE TITLE
Local Adjustments: preview DeltaE does not work with Black-and-White tool enabled

### ISSUE THREAD

**Issue by chaimav** [Beep6581/RawTherapee#6092]
The preview DeltaE function does not work when Color: Black-and-White tool is enabled. The image remains B & W and there is no green overlay.
RT 5.8-2745, Win 10, i3-8100.

**Comment by Desmis** [comment]
@chaimav 
Thank you for testing :)

for me I don't think I can find a solution. 

When the PR will be merged (BW after LA) we see a little better the incidences of the BW settings...
https://github.com/Beep6581/RawTherapee/pull/6080

jacques

**Comment by chaimav** [comment]
Can you at least write in the tooltip to warn of the issue? It took me a bit of time to narrow down why preview DeltaE was not working.

**Comment by Desmis** [comment]
@chaimav 
I push this change with the PR 
https://github.com/Beep6581/RawTherapee/pull/6080

Thank you

Jacques

**Comment by Desmis** [comment]
@chaimav 
With the new placement LA in the pipeline. Now it is before "Black and white", I think it is possible to do...
Before with LA after it was totally impossible because BW neutralized all scope deltaE actions.

I push a commit - 856d445802 - in branche "lanewlocation". I hope if fixed this behavior

Jacques
