### ISSUE TITLE
External Profile Builder interferes with Win10 security

### ISSUE THREAD

**Issue by polezhaevdmi** [Beep6581/RawTherapee#6101]
Investigated, why the Custom Processing Profile Builder, being configured as shown below, does not invoking upon profile reset. And found:
- RTProfileSelector does not run in "C:\Program Files" and "C:\Program Files (x86)" catalogs;
- RTProfileSelector does run from "D:\RTPS", "C:\1", and "C:\1 1" catalogs;
- If RT was started 'as Administrator', RTPS works fine in ALL catalogs mentioned above (so, this is possible workaround);

<img width="349" alt="rt02" src="https://user-images.githubusercontent.com/29210645/107280410-00a33500-6a61-11eb-8add-a3a0249226f0.png">

Proposition:
- Add a executable file selector button to 'Executable path' parameter to simplify the selection to dummies (like me);
- After the external file is selected, check, and, possibly, set the user rights to the file folder, which will be appropriate to run the chosen application. Possibly, such mechanism will be useful for Linux as well.

Thank You!

----- OS Info --------
Edition Windows 10 x64
Version 20H2
OS build 19042.789

------- RT Info --------
[AboutThisBuild.txt](https://github.com/Beep6581/RawTherapee/files/5946694/AboutThisBuild.txt)

**Comment by Thanatomanic** [comment]
Is this caused by us or by https://github.com/marcapelini/RTProfileSelector/?
Ping @Marcapelini for some ideas.

> After the external file is selected, check, and, possibly, set the user rights to the file folder, which will be appropriate to run the chosen application. Possibly, such mechanism will be useful for Linux as well.

It sounds very unlikely we will implement such a thing. imo, in case of calling external programs it is up to the user to ensure the file system is set up properly.

**Comment by marcapelini** [comment]
> Is this caused by us or by https://github.com/marcapelini/RTProfileSelector/?
> Ping @marcapelini for some ideas.
> 
> > After the external file is selected, check, and, possibly, set the user rights to the file folder, which will be appropriate to run the chosen application. Possibly, such mechanism will be useful for Linux as well.
> 
> It sounds very unlikely we will implement such a thing. imo, in case of calling external programs it is up to the user to ensure the file system is set up properly.

Agreed, this is not an issue with RawTherapee.  Currently, RTProfileSelector doesn't follow proper Windows guidelines for writing files do AppData: it writes its log and debug files to the same folder where the application is located. There's no installer either (nor do I plan to release one any time soon), and the user is expected to "install" it manually into folder with full read/write access for the current user.  On Windows, the "Program Files" is expected to contain just the binary and protected files, so placing RTProfileSelector there prevents normal users from properly running it (since it cannot write the needed files). 

As a side note, I plan to keep RTPS as simple as possible, with all code contained in a single file, and without using any external libraries.  This makes it easier for anyone to just download and compile the source code, and "install" it as one sees fit, but it does make it more cumbersome to write code that adheres to the proper application guidelines, especially for Windows, such as in this case.

**Comment by polezhaevdmi** [comment]
@Thanatomanic, @marcapelini, OK: the possible workaround is here, let it remain, and hope, this will be enough. Great thanks!

**Comment by marcapelini** [comment]
I have updated the documentation for [RTProfileSelector installation](https://github.com/marcapelini/RTProfileSelector/wiki/Installing-RTProfileSelector).  It's my fault that the original text didn't make it clear that RTProfileSelector requires full read/write access to its own folder.
