### ISSUE TITLE
Color shift due to local adjustments

### ISSUE THREAD

**Issue by Lawrence37** [Beep6581/RawTherapee#6144]
**Steps to reproduce**
1. Apply neutral profile.
2. Add local adjustment spot. Change spot method to full image to see the bug more easily.
3. Add tool which should have no effect by default.

Using this image, the effect is more pronounced.
![flat-color-cube](https://user-images.githubusercontent.com/45837045/109402645-4474b600-790c-11eb-8474-5180bacfc211.png)
![image](https://user-images.githubusercontent.com/45837045/109402915-96b6d680-790e-11eb-9d45-66b8c569f3a0.png)

**Comment by Desmis** [comment]
@Lawrence37 
I don't know if it can be called a "bug", but the behavior is what I expected.

Indeed "LA" uses almost everywhere L*a*b*. This means that if colors are out of gamut, imaginary colors will be generated by the Lab conversion ... This opens the door to uncontrollable drifts.
https://rawpedia.rawtherapee.com/Toolchain_Pipeline#Colorimetry

That's why I put by default an "avoid color shift" before and after each RT-spot.
1) First to put datas in gamut
2) to get linear response (Use of 200 Lut Munsell correction)

However you can disable this feature in "settings" / "Specific cases" / Avoid color shift

Jacques

**Comment by TechXavAL** [comment]
@Desmis 

If you set ACESp0 as working profile and then follow the instructions given by @Lawrence37, the problem is the same.

ACESp0 covers the full visible gamut, so I don't expect that image to be out of gamut in ACESp0.

According to Rawpedia:

>it is also said that L*a*b* addresses imaginary colors if the working profile allows it. This is also true but again, this can be compensated in Rawtherapee by enabling "Avoid Color shift". In this case, a relative colorimetric correction is applied to the working gamut as follows:
>
>    1. it examines the image data
>    2. if it is within gamut: no action

So again, if that image is within gamut in ACESp0 and LA causes a shift in colors, I would call it a bug, too: the user sets an option to avoid color shifts, which indeed causes color shifts (and pretty serious ones, by the way).

Even if you set sRGB as working profile, with _Avoid colors shifts_ there are shifts, and if you turn it off, then the image works fine (up to the point of just adding a tool).

**Comment by heckflosse** [comment]
An easy solution would be to disable 'Avoid color shift' by default...

**Comment by heckflosse** [comment]
Why doesn't the `avoid color shift` in Lab adjustments generate the same color shift?
![grafik](https://user-images.githubusercontent.com/13733487/109415939-c07a0700-79bb-11eb-80dd-c4f79a74d65f.png)

**Comment by Desmis** [comment]
@heckflosse @TechXavAL 

Yes, I found a bug...in some cases...
I can easily disabled "avoid color shift"...

I look at differences between "avoid color shift" in LA and in Lab adjustemnts... I found a difference...I will correct

**Comment by heckflosse** [comment]
> I found a difference...I will correct

\o/

**Comment by Desmis** [comment]
I just push a change in dev with
* disable by default "avoid color shift" - in procparams.cc
*  always activated "Munsell" with "needHH" always at "true" ...before it was to "lp.chro != 0.f"...(when LA was only with Color and light...some years ago..)

Jacques

**Comment by heckflosse** [comment]
@Desmis Jacques, while the output is better than before, there is still a significant difference between avoid color shift in LA (left) and Lab adjustments (right)

![grafik](https://user-images.githubusercontent.com/13733487/109419208-9ed54b80-79cc-11eb-936c-429baf01c43e.png)

Thanks for changing the default :+1:

**Comment by Desmis** [comment]
@heckflosse 
Yes, but in Lab adjustemnts, it depends a lot on the settings of  "lab adjustments"...
And in LA it depends of Scope...

With this image (which contains very saturated colors), try in Lab adjustemnts to increase Lightness...you will see big changes in blues...and purple...and stronger than in LA...I Think it's due to the placement in the pipeline.

**Comment by TechXavAL** [comment]
I agree that disabling the _Avoid color shift_ option is good, in a way. We were able to do that by hand, and it doesn't solve the problem. It just hides it.

To me, if you added that option is because it's needed somewhere, sometimes, and you may not have to get rid of it.

The solution would be to make it work as intended: solve certain problems without causing others. If that is even possible, of course!

**Comment by Desmis** [comment]
@heckflosse  @TechXavAL 

Maybe I'm going to surprise you, but for me the "right" solution is with  "avoid color shift"...
There was a bug, it is corrected...

But the very good question is why do a gamut control, and why want to make Lab data linear ?
And what do you expect when you're out of gamut ?
This algorithm (relative colorimetry) date of 2011.... and it works correctly in the majority of the cases. In some cases (rare) as this image - with very saturated color, it's can leeds to artifacts

We had this debate in 2011...and came up with this solution. Some developers tries in 2011 - "Uniform perceptual lab" whitout success... http://www.brucelindbloom.com/
If you look at Dartable you will see that some developers don't want to hear about Lab...
As I say, Lab is usable with some conditions I speak in Rawpedia


jacques

**Comment by heckflosse** [comment]
I am fine with the current solution (default to disabled and bug fixed) :+1: 

> We had this debate in 2011

That was before I started contributing to RT ;-)

**Comment by Desmis** [comment]
@heckflosse 

At the time it was a very "virile" debate...and we came up with this solution. Of course we can refine a bit the control of "relative" gamut, we will increase the treatment times for few differences in the final result. 

jacques

**Comment by Lawrence37** [comment]
The results are much better now. If the remaining color shift is due to the extreme colors in conjunction with "Avoid color shift", I consider this issue solved. Thank you @Desmis.
