### ISSUE TITLE
Local Adjustments Noise Reduction with narrow preview causes discoloration

### ISSUE THREAD

**Issue by Lawrence37** [Beep6581/RawTherapee#6179]
The noise reduction in local adjustments generates colorful pixels when the preview is narrow, about 100 pixels or less. The height does not seem to matter.

**Steps to reproduce**
1. Add spot with Blur/Grain & Denoise.
2. Set Denoise mode to Conservative, Aggressive, or NL Means.
3. Make a narrow preview area e.g. by zooming in or using a detail window.

![image](https://user-images.githubusercontent.com/45837045/111894972-a933a580-89cc-11eb-9838-c08a9cb57b5a.png)

**Comment by Desmis** [comment]
@Lawrence37 

Thank you for testing :)

This is due to the impossibility of decomposing the wavelets in a too small window. 
Denoise uses 7 levels of decomposition. The 7th level requires at least 128x128 pixels.
There is no question of changing the denoising algo  (complex)  but to avoid artifacts in preview - if the window is too small, we leave the process. (return)...in 

I push a commit branch "ladenoise"

jacques

**Comment by Lawrence37** [comment]
I'm curious why it works correctly for small heights. I can see the de-noising action with very short detail windows as long as the width is sufficient.
Is it possible to apply partial noise reduction by skipping the wavelet levels that are too large? This would make the preview at least semi-accurate. I don't know how the algorithm works, so maybe this is an impossible request. If disabling the de-noise is the only solution, a way of alerting the user would be nice.

**Comment by Desmis** [comment]
Excuse my bad english...

A brief reminder of how wavelets work. here for "local denoise", but also for "local wavelet", "denoise (main)" and "wavelet levels.  Note that a similar problem appeared in the recent development of wavelet levels...where I made essentially the same answer

The decomposition method used is efficient (there is a little better to process levels 0, 1, 2, but the processing time and the memory consumed would be prohibitive). It use "Deaubechies" with 3 components – Horizontal – Vertical – Diagonal. And a selector on « edge performance »

for each level and direction the decomposition produces a signal made of positive and negative data representing the local contrast at each pixel. 

For each level a minimum space is required !
From : 
level 0 : 2 x 2 pixels
Till :
Level 9 : 1024x1024

In fact, here with the required level 7, the minimum size needed is 256x256, but the Dcrop preview "handles" this by bringing different constraints that can lead to visible window sizes smaller than 256

This explains for example why some users say they can't see the last level (although it is present in Output), because the preview window is too small.
Unfortunately there is no solution. Of course you can add a tooltip, in addition to the documentation

The method I used to avoid color drift is the same as in « Wavelet Levels » and « LA Wavelet »...I just "forgot" to implement it in "LA denoise ». The absence of this control can even lead to a crash.


In the case of "denoise", whether in Wavelet Levels or LA, it is considerably more complicated, because two different processes are married. The one specific to « Wavelet Levels » or « LA » plus Ftblockdn.

As you probably know, I am very bad in C++ and GUI, my only real area of expertise is algorithms.
Maybe there is a way to make "denoise" more flexible (in Wavelet Levels and LA) but it seems to me very, very complex.

jacques

**Comment by Desmis** [comment]
@Lawrence37  @waynesutton50

I added a warning in "LA denoise" when the preview  or detail window are too small (a lot of code...11 files changed)

can you give me your opinion :
1) on this option
2) on the 2 labels

Thank you

Jacques

**Comment by waynesutton50** [comment]
>     2\. on the 2 labels

@Desmis  Jacques, I can only find one label: "Wavelet - sufficient size of preview". I'm not sure what this means exactly so could you send me the French version please?

**Comment by Desmis** [comment]
@waynesutton50

To see the label change - 2 cases

* Either you have to reduce the preview window horizontally so that there is almost nothing left...
* or you have to use "Open (new) detail window" in the bar at the bottom of the screen and there, if you zoom in the small window at more than 200% you will see "Wavelet- insufficient size of the preview" appear

My last change concerns Nlmeans which continues to work

In french

Pour voir changer le label - 2 cas

* Soit il faut réduire considérablement la fenêtre du preview en horizontal pour qu’il ne reste presque plus rien…
* soit il faut utiliser “Open (new) detail window” dans la barre en bas de l’écran et là, si tu zoom dans la petite fenêtre à plus de 200% tu verras apparaître “Wavele- insufficient size of the preview”

Mon dernier changement concerne Nlmeans qui lui continue de fonctionner

**Comment by Desmis** [comment]
@Lawrence37  @waynesutton50

In fact, there are 2 solutions, because I don't see what else to add

1) Either I merge the minimum solution, i.e. prevent artifacts and crashes and enrich the documentation

2) Or I merge the current solution with the "label" in addition. This solution complicates a lot the code, from my point of view doesn't bring much, or even is a bit harmful in the sense that it makes the interface less readable.

I made this 2nd solution to allow a choice, the work done should not be taken into account in the decision 

What do you think, for my part, I am in favor of 1)

jacques

**Comment by Lawrence37** [comment]
@Desmis thanks for the explanation. I think the first solution is best for now. I imagine it's not common to have a preview smaller than 128. Displaying a warning message is ideal, but I prefer there be a dedicated area for all RawTherapee messages, which is a separate issue. I'm fine with merging the simple solution and closing this.

**Comment by Desmis** [comment]
@Lawrence37 @waynesutton50

OK, thank you, I merge the "simple" solution :)

jacques
