### ISSUE TITLE
Missing Camera Profiles under Profiled Lens Correction

### ISSUE THREAD

**Issue by AndyAstbury** [Beep6581/RawTherapee#6246]
Just playing around with the new Camera-based Perspective Control lines etc and noticed some missing cameras under PLC.

Nikon D850
Canon 1DX Mk2
Canon 1DX MK3
Canon 5D Mk4

This needs to be remedied FAST to maintain public credibility of RT on next release, as two of those listed have gone out of production so can not be considered new, and Libraw supports all 4.

**Comment by Floessie** [comment]
@AndyAstbury Hi Andy, this is a matter of `lensfun`, AFAIK. Under Linux you can update the database with `lensfun-update-data`. Glenn (@butcherg) has hacked a multi-platform tool for this, too, see [lensfun_dbupdate](https://github.com/butcherg/lensfun_dbupdate). The D850 in already in the [DB](https://github.com/lensfun/lensfun/blob/master/data/db/slr-nikon.xml#L235).

HTH,
Flössie

**Comment by AndyAstbury** [comment]
@Floessie "Under Linux you can update the database with lensfun-update-data"

As a total non-coder I am clueless how to do this!

**Comment by Thanatomanic** [comment]
We will also package the latest version of the database when releasing the new version.

It might be good for us to update RawPedia with instructions.

**Comment by AndyAstbury** [comment]
Brilliant, and a really good idea!

**Comment by AndyAstbury** [comment]
And with Wayne Suttons help I've even managed to update the lensfun database - Woo-Hoo!
That's given me Nikon D850, Canon 1DX Mk2 & Canon 5D Mk4.

Anyone know what's happening with the 1DX Mk3 by any chance?

**Comment by Beep6581** [comment]
> Anyone know what's happening with the 1DX Mk3 by any chance?

https://lensfun.github.io/faq/

**Comment by Beep6581** [comment]
How does one update the Lensfun database in Windows?

**Comment by Beep6581** [comment]
I updated the whole Lensfun section of RawPedia:
http://rawpedia.rawtherapee.com/Lens/Geometry#Lensfun

Please check that I did not write bullshit.

Does RawTherapee still only use lensfun DB version1?

**Comment by Thanatomanic** [comment]
@Beep6581 The write-up on RawPedia looks good, thanks! One thing only for Windows, the path containing `darktable` is odd. Since we ship the Lensfun database with a release version, I guess you should update the files there. So on my machine: `C:\Program Files\RawTherapee\5.8\share\lensfun`.
There is something fishy going on, though, because I have xml files in the main `lensfun` folder (dated 2020) _and_ the `version_1` subfolder (dated 2015).

> Does RawTherapee still only use lensfun DB version1?

Yes, afaik because the 0.3.95 version is still officially an alpha release with breaking API changes to 0.3.2. See https://lensfun.github.io/news/ second item dated 2018. Not sure if distro's have simply upgraded anyhow... 
There is a long discussion about it over at darktable who have been supporting for some years with an #ifdef https://github.com/darktable-org/darktable/pull/2793
