### ISSUE TITLE
Clarify usage of perspective tool through tooltips / disabling

### ISSUE THREAD

**Issue by marter001** [Beep6581/RawTherapee#6250]
i just played around with the today nighly build Version: 5.8-2934-gc32623882 and tried to understand the perspective correction tool.
There are two aspects i stumbled: (method camera based)
-  drawing only one control-line isnt enough (of course), may be this could be mentioned in GUI or Tooltip. With this, the button "apply" should be activated earliest after two existing control-lines.
- the tooltip for control-lines can be found in default (TP_PERSPECTIVE_CONTROL_LINES_TOOLTIP;<b>Ctrl</b>+<b>drag</b>: Draw new line\n<b>Right-click</b>: Delete line) but in GUI only "Edit" can be read.

**Comment by rebio** [comment]
I tested this and I have to agree with both

1.  Add tooltip: There should be a tooltip when on the button. We have quite detailed tooltips on some buttons (which I think is good) and this one here just says "Edit"
2. Add single lines: Well, with just one line the image could be rotated... If it is intended to not do anything if there is only one line, the _Apply_ button could maybe only be active (greyed out) if there were at least two lines

**Comment by Lawrence37** [comment]
Disabling the Apply button makes sense. I will make this change. The tooltip appears when you hover over the label. The reason why the buttons have short tooltips is because of the many complaints we've had about tooltips being intrusive. See #2221 and #6007.

**Comment by rebio** [comment]
> Disabling the Apply button makes sense. I will make this change. The tooltip appears when you hover over the label. The reason why the buttons have short tooltips is because of the many complaints we've had about tooltips being intrusive. See #2221 and #6007.

Disable if it is not supposed to be also a tool to turn the image. If it's disabled it should also tell you what you would need to do (eg. "There have to be at least to lines to apply the perspective correction")

What if there was an 'expert mode' like there is for many other programs that hides the tooltips or makes them shorter. It could also be an option the the configs to hide long tooltips.

I would not have checked the lable if you wouldn't have told me. The lable area does not look any different from the regular background so I wouldn't expect to find a tooltip there. And since many areas in RT have the description right on the slider I searched on the buttons first.

**Comment by Lawrence37** [comment]
I think it is reasonable to add the longer tooltip to the disabled button.

AFAIK there is no consensus on tooltip usage. Please add your ideas to the appropriate issue to help move the tooltip discussion forward.
