### ISSUE TITLE
ipwavelet.cc possible array out of bounds

### ISSUE THREAD

**Issue by Thanatomanic** [Beep6581/RawTherapee#6285]
@Desmis When doing some cppcheck analysis, I got the following warning:

```
Checking ipwavelet.cc ...
ipwavelet.cc:452:16: error: Array 'cp.mulC[9]' accessed at index 9, which is out of bounds. [arrayIndexOutOfBounds]
        cp.mulC[m] = 0.f;
               ^
```

The relevant lines of code:
https://github.com/Beep6581/RawTherapee/blob/a6a8ee0e4074205cceab2df3c76fb79e2dee3d93/rtengine/ipwavelet.cc#L451-L453

The definition of `mulC`:
https://github.com/Beep6581/RawTherapee/blob/a6a8ee0e4074205cceab2df3c76fb79e2dee3d93/rtengine/ipwavelet.cc#L91

So the highest index for `mulC` should be 8, not 9 according to the loop. Either the `mulC` array should be bigger, or the loop should not run to 10. Can you check which one it should be?

**Comment by Desmis** [comment]
@Thanatomanic 

You are true...There is something wrong :)

For contrast value, I allow 10 levels (which should be very rare and difficult to observe on screen).
But for chroma, only 9 levels....which is more than enough

so I will keep the mulC[9] declaration and change the loop limit.

I will change soon 

But it is a very very old bug....since 2012..or 2013

Thank you very much

Jacques
