### ISSUE TITLE
Partial Profile not saved correctly

### ISSUE THREAD

**Issue by Bezierr** [Beep6581/RawTherapee#6303]
RT 5.8 release version (commit a9e0acbf) on Windows 10 20H2

There seems to be an interference between copying/pasting and saving a partial profile.

To reproduce:
1. Open a picture in Editor.
2. Do Ctrl-"Copy current processing profile to clipboard"
3. Select "Color Toning"
4. "Paste Profile from clipboard"
5. Do Ctrl-"Save current profile"
6. Select "White Balance" and "Exposure"
7. Save
8. Open saved profile in editor => Profile is empty

If you include "Color Toning" in your selection of parameters, the saved profile won't be empty but will contain the values for "Color Toning" (and nothing else).

Only restarting RT fixed this issue for me.

I would consider this a critical issue because a user may lose data. In fact, I lost several hours of work before I realized that the partial profiles I created for different ISO settings for my camera were never saved.

**Comment by ghost** [comment]
I'm not able to reproduce this.

Following your steps I end up with a filled and usable sidecar file. I tried this multiple times with both edited and neutral (via neutral profile) versions of some RAW files.

Some info:

* RawTherapee version : 5.8-3051-g71e8eeaf8
* OS                : Linux (kernel 5.9.15-1 x86_64 amd64)
* Distro            : Debian Buster (rel. 10.10)
* Graphics driver   : nvidia (460.39)
* Compiler      : gcc 8.3.0
* Cmake         : 3.13.4
* Glib          : 2.58.3-2
* Gtk+          : 3.24.5-1
* Exiv2         : 1.0.0.9
* Lensfun       : 0.3.2-4

**Comment by Bezierr** [comment]
Hmm... Interesting. Tried it again, with RAW from a different camera, same result. Both for "Dynamic Profile" (which I normally use) and "Neutral".

> [Version]
> AppVersion=5.8
> Version=346

is all I have in the file.

You did do the "Paste" step, didn't you? Because without it, it works.

My RT version is 5.8 release, downloaded from the RT website on 2020-02-26.


Interestingly, when I tried the same with a self-compiled dev version (not the most recent one), I got the following result:

> [Version]
> AppVersion=5.8-2850-g36e6a188c
> Version=349
>
> [Film Negative]
> BackCompat=0

And that's it. Which seems even more wrong because "Film Negative" was never selected.

Any idea how I can help pinpoint the problem?

**Comment by ghost** [comment]
Ah, yes I made an assumption yesterday which I should have asked about. Sorry about that!

First of all: If I follow your steps by the numbers I _can_ reproduce. But...

The assumption I made yesterday concerned the *Do Ctrl-"Copy current processing profile to clipboard"* step. You do not select anything that needs to be copied to the clipboard. So I assumed that you meant copy and not ctrl-copy. The latter will create an empty clipboard and isn't at all useful.

Not sure if the end-result, an empty profile, is a logical result from that or not.

BTW: You can ignore the *\[Film Negative\]* entry. It is always added ever since the *Film Negative* module was implemented. I don't think it should be but it doesn't do anything in this form.

**Comment by Bezierr** [comment]
The idea is that you do Ctrl-"Copy current processing profile to clipboard" (Step 2) and in the window that opens select "Color Toning" (Step 3). So the profile on the clipboard is _not_ empty but contains the settings for, well, color toning. (Probably selecting something else would do, too, but I haven't tried it.)

In the same way, Step 6 is meant to do the selection in the window that opens after Ctrl-"Save current profile".

Sorry if that was not clear; I hope it is now?

**Comment by Bezierr** [comment]
![image](https://user-images.githubusercontent.com/38507161/125652893-a3d922a8-7263-4cd1-b112-c600b579b29d.png)

**Comment by Thanatomanic** [comment]
I can confirm as well, good catch. I have no intimate knowledge of the code that handles profile copying/pasting/saving, so I cannot really help out without a much more careful look. Perhaps @heckflosse @Lawrence37 or @rom9 has some time and idea?

**Comment by rom9** [comment]
By looking at this line:
https://github.com/Beep6581/RawTherapee/blob/d7f9e1f51c740e625485155e9ecb17b1ffa15acf/rtgui/profilepanel.cc#L362

it seems that parameters are saved only if they were edited (see `toSave->pedited`), but when "Custom" is selected, none of the ParamsEdited flags are set ... so, the Exposure and WB sections are not saved, even though they were selected in the partial save dialog.
I think in this case we could cut it short and avoid the PE filtering altogether, by changing that line to:
```diff
                     PartialProfile ppTemp(true);
-                    partialProfileDlg->applyPaste(ppTemp.pparams, ppTemp.pedited, toSave->pparams, toSave->pedited);
+                    partialProfileDlg->applyPaste(ppTemp.pparams, ppTemp.pedited, toSave->pparams, nullptr);
                     // Save partial profile
```

This way, every section that is flagged in the partial save dialog will be written, period.
I'd think this should be the expected behavior, but maybe i'm missing something? Please, can someone confirm this, before i make a big mess? :-D

@jade-nl thanks for the FilmNeg catch, that's super ugly, i'll try to fix that as well ;-)

**Comment by Lawrence37** [comment]
Give me some time to look into this. I want to understand what's happening to `pedited` here.

**Comment by Lawrence37** [comment]
It seems like the use of `pedited` is a mistake. @rom9 OK from me to make the change.

**Comment by rom9** [comment]
Sorry for the delay! Both problems should be fixed now :-)
