### ISSUE TITLE
Ciecam Curve Brightness

### ISSUE THREAD

**Issue by Desmis** [Beep6581/RawTherapee#6348]
@jade-nl 

I re-enable curve Brightness in Ciecam.

I changed the place in the process (and others changes), and it seems to work now.

Now you can use either Lightness or Brightness for the 2 Tone curves

Branch  "ciecam_curve_brightness"

I hope all works fine ??? otherwise it is enough to delete :)

Jacques

**Comment by ghost** [comment]
That's good news!

I'll merge/build that branch and give that a test run. Might take a few hours before I report back though. I'm not able to drop what I'm doing atm :-)

**Comment by ghost** [comment]
@Desmis 

Did some tests and the changes you implemented are working for as far as I can tell/test.

Tests I performed:

* The situation as mentioned in my original bug report (#6344),
* Stand alone - just the brightness curve and nothing else,
* Brightness curve and Brightness slider (nothing else),
* Full CIEcam: Brightness curve and a mix of many different other CIEcam settings,
* A normal full blown edit using, among other things:
   - CIEcam,
   - Wavelet levels,
   - Local adjustments (log encoding -> advanced + brightness),
   - Chromatic Aberration Correction (on the NEF only),
   - Defringe,
   - Colour Management (abstract profile -> custom).
   - Capture Sharpening,
   - Colour toning (tried both: _L\*a\*b blending_ and _Colour correction regions_),
* Extreme edit: Using the above normal edit and pushing it beyond normal settings.

The above tests where done both on a NEF (Bayer Matrix) and a RAF (X-Trans matrix) RAW file.

Not once did I get an undesired result when using the Brightness Tone Curve in CIEcam.

Although I'm not able to test all possible scenarios the above seems to be a good indicator that all works as originally planned.

Thanks for having another look at this and coming up with and implementing the better solution!

---

I do have a question/request:

Tone curve 1 and tone curve 2 are both set to Lightness by default. Is there a reason why this is so? I would think that showing both types that are available would be a more logical starting point. Using the same curve type twice might be needed at times, but I'm all but sure that using one of each type is the more common scenario.

I.e.: This:
![scsh0](https://user-images.githubusercontent.com/56407344/131510888-ef98a1f8-4f5f-47b6-8213-f58871b49102.png)
Instead of this:
![scsh1](https://user-images.githubusercontent.com/56407344/131510934-396f0005-c88c-4f71-b1ca-5f55b92b6796.png)
As a default starting point when using the *Complexity: Advanced*.

**Comment by Desmis** [comment]
Thank you for these complete tests. for my part I did not find any malfunctions.

I just change defaut tone curve2 to brightness


Commit 4e0c9d9a4

Tommorow, I will create a Pull Request

Jacques

**Comment by Desmis** [comment]
Merge

**Comment by ghost** [comment]
@Desmis 

Just a heads up: I just pulled and build this one and noticed that the request I had about _lightness + brightness_ instead of _lightness + lightness_ as a default  (see *I do have a question/request:* above) did not get integrated. I'm sure I saw it correctly changed in a previous build from your personal branch.

**Comment by Desmis** [comment]
@jade-nl 

By default the system is for TC2 to brightness....
It needs to set neutral, or a new file

But I found a bug in some cases, when you change standard/advanced or press Reset

I just fixed this bad behavior

Thank you

Jacques

**Comment by ghost** [comment]
Understood and it seems to be all fixed now.

Thanks!

**Comment by Desmis** [comment]
OK :)
