### ISSUE TITLE
Crash with White Balance and Haze Removal in particular image 

### ISSUE THREAD

**Issue by arturoisilvia** [Beep6581/RawTherapee#6364]
With the image: 
[https://discuss.pixls.us/t/difficult-orange-flower/27001](https://discuss.pixls.us/t/difficult-orange-flower/27001)

(In principle only with this image, I haven't found the error in other images)

Set neutral mode
Activate the Haze Removal module
Deactivate White Balance
Crash.

---------------
Version: 5.8-3046-g5268b94cf
Branch: dev
Commit: 5268b94cf
Commit date: 2021-09-04
Compiler: cc 10.3.0
Processor: generic
System: Windows

**Comment by syyrmb** [comment]
I can replicate this in RT 5.8 and 5.8 dev. My two discoveries:
1. The order of enable Dehaze and disable WB doesn't matter. Deactive WB first will still result in a crash.
2. The problem seems to occur because in the ICM panel, neutral profile set the "input profile" to Auto-Matched Camera Profile, switch it to "Camera Standard" will result in no crash.

**Comment by heckflosse** [comment]
Crash confirmed. Looking...

**Comment by arturoisilvia** [comment]
Thanks Ingo.
I have changed the title to make it more descriptive when searching.
