### ISSUE TITLE
lensfun path in nightly-github-actions not consistent with earlier automated builds (lensfun not loaded due to different options file)

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#6426]
Apparently the current [automated Windows builds](https://github.com/Beep6581/RawTherapee/releases/tag/nightly-github-actions) lack lensfun data.

https://github.com/Beep6581/RawTherapee/issues/6424#issuecomment-1034598687

**Comment by Thanatomanic** [comment]
This is incorrect. Lensfun is packaged correctly, however, the database path that is hardcoded into the executable may be different from the current entry in a user's options file. There is currently no way that this is overridden, so a manual change is required.
Imo the most user friendly change we should make, is to make the lensfun path configurable through Preferences. There should be two options: default (pointing to the RT share folder) and custom.

**Comment by gaaned92** [comment]
put `-DLENSFUNDBDIR=share/lensfun` in the cmake command.

**Comment by Thanatomanic** [comment]
> put -DLENSFUNDBDIR=share/lensfun in the cmake command.

This would make things consistent with the earlier nightly builds and not give issue with an existing entry in the `options` file. All xml files should also be copied to this folder, instead of the `version_1` subfolder.

Relevant code:
https://github.com/Beep6581/RawTherapee/blob/c8e3bf030a6a198305c39f012a6b4cffe5548e73/.github/workflows/windows.yml#L71

https://github.com/Beep6581/RawTherapee/blob/c8e3bf030a6a198305c39f012a6b4cffe5548e73/.github/workflows/windows.yml#L90

@Lawrence37 Okay if I push a fix?

Side-note: the release branch should adopt this method as well. The 5.8 release has two instances of a set of xml files: in `./share/lensfun` and `./share/lensfun_version_1`. The `DLENSFUNDBDIR` path does not seem to be set.

**Comment by Lawrence37** [comment]
@Thanatomanic Go ahead. I've been busy lately.
