### ISSUE TITLE
Automated debug builds fail

### ISSUE THREAD

**Issue by Thanatomanic** [Beep6581/RawTherapee#6455]
@Lawrence37 Perhaps you have seen it too, but the automated debug builds fail on the following:

![image](https://user-images.githubusercontent.com/6567747/162611621-23cf079a-c79b-47f9-aac9-eb674a89e273.png)

Seems a bit weird to me. Any clues?

**Comment by Lawrence37** [comment]
The GDB executable changed either because it was updated or, less likely, someone has tampered with it. If the first is true, we need to update the checksum in the build script.

**Comment by Lawrence37** [comment]
Looks like they update the GDB executable frequently. http://www.equation.com/servlet/equation.cmd?fa=programminglog

We can
- update the checksum when the builds fail, or
- remove the integrity check and caution users about using the bundled GDB, or
- stop bundling GDB with the debug build, or
- download from a link that updates less often, or
- ???

**Comment by Thanatomanic** [comment]
I think I prefer removing it. It seems logical to assume that whoever is using the debug build also knows how to hook it into gdb or another debugger. There are very few cases where one would use the debug build without running it through the debugger (only in case of compiler optimization issues). Or am I overlooking something?

**Comment by Lawrence37** [comment]
RawPedia "encourages" package maintainers to bundle GDB (http://rawpedia.rawtherapee.com/Windows#Creating_a_distributable_package). It's not so encouraging if the official builds don't 😉.

**Comment by Entropy512** [comment]
I agree with @Thanatomanic that if someone is using a debug build, they'll need to know how to hook it into gdb.  Perhaps instead of recommending that packagers bundle it on Windows, alter the relevant section of http://rawpedia.rawtherapee.com/How_to_write_useful_bug_reports to point to GDB.  In fact, right now that section DOES point to an alternative source of GDB, so perhaps just remove the references to bundling GDB on Windows both from the packager instructions and that page?

If desired, I'll submit a rawpedia account request and work on this.  I've been meaning to do so for years to add a few clarifications to https://rawpedia.rawtherapee.com/How_to_create_DCP_color_profiles anyway

**Comment by Lawrence37** [comment]
I've removed GDB in the PR and the Windows debug build is working there.
