### ISSUE TITLE
Danish translation

### ISSUE THREAD

**Issue by mogensjaeger** [Beep6581/RawTherapee#6461]
I would like to have my translation of the RawTherapee added to the project.
But I cannot find out how to upload it to the project - please helt
Sincerely mogens jæger

**Comment by rebio** [comment]
You would have to use git (https://git-scm.com/) for this. Since you asked, I guess you don't know how the application works.
You could upload the txt file with the translation here by drag & dropping.

Example:
- See issue #6454
- File: [danish.txt](https://github.com/Beep6581/RawTherapee/files/8539625/danish.txt)

**Comment by mogensjaeger** [comment]
Thanks - and no, I do not know how to do this.
You say I have to upload the danish.txt - but from start of, it did not have an extension.
But I will try to upload it here - thanks for the help - aparantly it worked - great ;-)
[Danish.txt](https://github.com/Beep6581/RawTherapee/files/8541463/Danish.txt)
.

**Comment by rebio** [comment]
Pull request: ~~#6462~~ Fork with changes is deleted. Seems that the pull request is done for as well because of it
