### ISSUE TITLE
Highligh recovery cause the false color ring

### ISSUE THREAD

**Issue by hsqaihkl** [Beep6581/RawTherapee#6539]
Hi I run the Rawtherapee5.8 in windows10. When I just run Autolevel and enable the Highlight recovery.But  I found that it will cause the false color ring at the overexposure area.

![Highlight_recovery_color_ring](https://user-images.githubusercontent.com/24558764/182564729-2f91e12f-66a1-46d3-8cde-30d5eebcbfd8.png)

The source image  DNG file in here:
https://drive.google.com/file/d/1fsRwgJlI59rN1_FJncNWZagGZBQNIgGJ/view?usp=sharing

**Comment by ghost** [comment]
What is your expectation when doing this?

This is what RawPedia says about the _Auto Levels_:

> [...] Auto Levels comes up with as a good starting point. It has been tuned to work best with "typical shots"

This isn't a typical shot to begin with due to 2 channels being blown, some manual (fine-)tuning needs to be done and *Highlight Reconstruction* can only do so much out-of-the-box.

This image needs tweaking done by a human and you can't expect any *auto* button to come up with a good end result. That being said, here's a 200% zoom screenshot:

![sc blown sky](https://user-images.githubusercontent.com/56407344/182579717-e91913d7-8922-4e8e-9ed8-b06d54ac33d6.png)

No fine-tuning/editing in any way, just:
* used _auto levels_
* *clip out of gamut colours* turned off
* _highlight reconstruction_ turned on
  * *method* set to *colour propagation*

**Comment by hsqaihkl** [comment]
Sorry,I am new-lazy guy to hope it to be automatic! Because I have so much picture to handled！
Thanks for your reply!
