### ISSUE TITLE
Sony ILCE-9 APS-C crop format ARW files always cause force stop.

### ISSUE THREAD

**Issue by sun-jiao** [Beep6581/RawTherapee#6544]
**Short description**
Sony ILCE-9 APS-C crop format ARW files always cause force stop.
[20220804.zip](https://github.com/Beep6581/RawTherapee/files/9297231/20220804.zip)

**Additional information**
- Version of RawTherapee 5.8
- Version of your operating system Win11

**Comment by ghost** [comment]
This is due to the old RawTherapee version that's being used (tested and I can confirm this).

This doesn't happen with the latest self build development version or the appimage (tested with 5.8.3105).

@sun-jiao : You can wait for the upcoming new stable version (whenever that will be) or you can install/use one of the latest all-but-100%-stable development versions. If a development version sounds good have a look here:
[Direct download links to the latest RawTherapee development version.](https://discuss.pixls.us/t/direct-download-links-to-the-latest-rawtherapee-development-version/29806?u=jade_nl) (a link to pixls.us).

**Comment by sun-jiao** [comment]
@jade-nl thank you so much. It works fine.
