### ISSUE TITLE
Linux automated build needs upgrade (to work with GitHub Actions)

### ISSUE THREAD

**Issue by Thanatomanic** [Beep6581/RawTherapee#6567]
In a similar vein as #6566, we also need to update our Linux Automated build to something more current to ensure nightly will be built.

See https://github.com/actions/runner-images/issues/6002 for more information.

**Comment by Lawrence37** [comment]
The upgrade can and should wait until after the release. In the long term, we should containerize the build with Docker, just like with the old automated builds.

Some context:

It is recommended to package AppImages in the oldest LTS operating system version possible. The reason is because AppImages are not completely self-contained and rely on host system libraries that should already exist in every Linux installation. From https://docs.appimage.org/reference/best-practices.html:
> Some core libraries, such as glibc, tend to break compatibility with older base systems quite frequently, which means that binaries will run on newer, but not on older base systems than the one the binaries were compiled on.

Therefore, it's best to use the oldest operating system that we plan to support.

Ubuntu is a popular Linux distribution with long-term-support (LTS) versions released every 2 years. They reach end-of-life after 5 years. GitHub Actions supports the latest two LTS versions of any operating system they offer. We have reached a point when GitHub is removing the Ubuntu 18.04 release from Actions, but that operating system will not reach its end-of-life until April of next year. If we move the AppImage builds to Ubuntu 20.04, we risk breaking the AppImage for those who are still on Ubuntu 18.04 (and possibly other OSs). Fortunately for us, the 18.04 runners will still be available (with brownout periods) until the end of November.

We can use the current automated builds for the 5.9 release, then upgrade the runner to Ubuntu 20.04. The next step is to containerize the build so we have more control over the build environment.
