### ISSUE TITLE
Automated macOS build - arch is missing

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#6617]
macOS build filenames lack a field as can be seen by the double underscore:
`RawTherapee_macOS_10.15__6aa4c87.zip`
https://github.com/Beep6581/RawTherapee/actions/runs/3559871755/jobs/5979523410#step:6:320

Probably caused by missing `arch` in `/tools/osx/macosx_bundle.sh`
https://github.com/Beep6581/RawTherapee/blob/dev/tools/osx/macosx_bundle.sh#L95

@Benitoite can you take a look?

**Comment by Beep6581** [comment]
@Benitoite the field is still missing, and additionally the current action seems to be making separate uploads for every commit, instead of just replacing the latest one:
https://github.com/Beep6581/RawTherapee/releases/tag/nightly-github-actions

**Comment by Benitoite** [comment]
@Beep6581 I saw it! The fix https://github.com/Beep6581/RawTherapee/pull/6675/commits/fe69ebff6abbb7d5756f909b3d6abf246215cd4c  just hasn't been merged yet:
https://github.com/Beep6581/RawTherapee/actions/runs/4279859557/jobs/7450992580#step:8:6
Separate nightlies seem to be not needed so let me see if I can get it to u/l the generic named zip instead.

**Comment by Benitoite** [comment]
https://github.com/Beep6581/RawTherapee/actions/runs/4289787604/jobs/7473169619#step:8:7
Now produces generic-named zips.

**Comment by Beep6581** [comment]
@Benitoite could you please make it use the format:
`RawTherapee_<branch>_macOS_<buildtype>.zip`
e.g.
`RawTherapee_dev_macOS_release.zip`

When I visit your https://github.com/Beep6581/RawTherapee/commit/fe69ebff6abbb7d5756f909b3d6abf246215cd4c link GitHub unhelpfully and confusingly tells me "This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository" without showing which fork and branch this commit resides in, so could you also link me to the appropriate fork/branch.

**Comment by Benitoite** [comment]
This is currently running in #6675 which is:
> https://github.com/Beep6581/RawTherapee/pull/6675
>

**Comment by Benitoite** [comment]
https://github.com/Beep6581/RawTherapee/actions/runs/4369631229
With the latest run, the format is programmed as you suggested above.  The artifact of the run within the PR is detached from the HEAD of any branch, so it shows that hash abbreviated instead of a blank. 
ie. `RawTherapee_03284c6_macOS_Release.zip`
Once HEAD refers to a branch (eg. when merged into a repo) the branch will show, like `dev` instead of the hash, ie.  `RawTherapee_dev_macOS_Release.zip`

btw, AboutThisBuild and UpdateInfo seem to also display the branch in PRs similarly with the abbreviated hash, and normally with the named branches.

**Comment by Beep6581** [comment]
@Benitoite great!
