### ISSUE TITLE
Support for OM System OM-1

### ISSUE THREAD

**Issue by MichalStaruch** [Beep6581/RawTherapee#6620]
Please add support for OM System OM-1. I tried recently released RawTherapee 5.9, but when trying to open ORF files from OM-1 only black screen is displayed.

Link to RAW photo set: https://filebin.net/bhyf773iepkpifyq

**Comment by Beep6581** [comment]
It's already supported by libraw #4462

**Comment by MichalStaruch** [comment]
@Beep6581 Any schedule / milestone for implementing #4462? From my perspective it's a blocker - I cannot use RawTherapee, if it's unable to open RAW files from my camera. Other people using new cameras might have similar problems, so I think it's worth increasing priority for integrating libraw (or any other actively maintained library).

**Comment by Beep6581** [comment]
Adopting libraw #6623 and libexiv2 #3801 probably belongs on the [6.0](https://github.com/Beep6581/RawTherapee/milestone/10) milestone. Keep an eye on those issues, and help test patches/builds once available to speed things up.

**Comment by Entropy512** [comment]
Given the roadmaps (6.0 vs. 5.10) - I MAY take a quick crack at fixing this on the legacy codebase so that 5.10 can at least limp along.  The OM-1 support patch in libraw did not seem *that* painful, I just have been procrastinating horribly on messing with it.  If you read the RT OM-1 thread over on pixls, you'll see that I've been procrastinating on this one since mid-March...

Obviously if an OM-1 owner with some C and git skills ports https://github.com/LibRaw/LibRaw/commit/adcb898a00746c8aa886eb06cc9f5a1cb1834fca to RT's legacy-dcraw engine things may go a bit faster.

Another option is to convert the images to DNG for processing.  I'm going to be publishing a basic Python libraw-supported-camera-to-DNG converter later this week.  It's mostly pointless (I'm using it as a stepping stone for some image stacking stuff) but this might be a valid interim use case.

**Comment by rgcmce** [comment]
Don't forget support for the even newer OM-5.  (I'm assuming that OM-5 files fail to open as well, but I haven't tried nor have I seen any reports.)

**Comment by MichalStaruch** [comment]
Btw. for anyone using new camera, that is not yet supported in RawTherapee - I've found another DNG-based solution: you can use [Adobe DNG Converter](https://helpx.adobe.com/camera-raw/using/adobe-dng-converter.html) (which supports more cameras) to convert RAW to DNG format, and then import DNG in RT. Worked fine for ORFs from OM-1.

**Comment by Entropy512** [comment]
Yup, obviously Adobe DNG converter is an option, but it's kinda clunky and bloated and doesn't run on Linux unless you use WINE - and even then, newer versions can be problematic in WINE (or at least were for a while)

**Comment by Beep6581** [comment]
http://rawpedia.rawtherapee.com/How_to_convert_raw_formats_to_DNG

**Comment by Beep6581** [comment]
And I just updated "How_to_convert_raw_formats_to_DNG" to reflect the latest version of ADC 15.0.

**Comment by michael-lenz** [comment]
> Don't forget support for the even newer OM-5. (I'm assuming that OM-5 files fail to open as well, but I haven't tried nor have I seen any reports.)

I can confirm that ORFs from an OM-5 also fail to open. They show black in preview and editor and on opening, rawtherapee prints the following to the command line
```
P2280176.ORF: Unexpected end of file
Cannot use camera white balance.
``` 

Here's an [example file](https://github.com/Beep6581/RawTherapee/files/10874747/P2280190.ORF.TXT)  (remove ".TXT" extension)
What other information can I provide that allows for including OM-5 in #6667 as well?

**Comment by michael-lenz** [comment]
Having just built rawtherapee from the `om-1` branch: ORF files produced by OM-5 can be previewed and opened in the editor with that branch's changes.

Since @Lawrence37's code changes contain some - apparently OM-1-specific - magic numbers (that IDK the origin/meaning of), I can't tell if it is fine as is for OM-5 as well

**Comment by Lawrence37** [comment]
@michael-lenz http://rawpedia.rawtherapee.com/Adding_Support_for_New_Raw_Formats This page describes the information needed to provide various levels of support for new raw image formats. Create new issue(s) as appropriate.

**Comment by MichalStaruch** [comment]
I confirm it works properly - tested on latest sources from the dev branch (5.9-105-gae3155a17).

**Comment by hinakhan09** [comment]
Download Now https://pclife.info/raw-image-extension-crack/

**Comment by Lawrence37** [comment]
A suspicious link from a new user with no explanation other than a directive to download? Please, no one click the link.

This issue is closed and the latest release supports the OM-1.
