### ISSUE TITLE
Automated build 5.9-58 will not open - missing library

### ISSUE THREAD

**Issue by chaimav** [Beep6581/RawTherapee#6671]
Windows 10, RawTherapee_dev_win64_release build 5.9-58 gives an error when I try to open it.

![Capture](https://user-images.githubusercontent.com/47765782/214581485-cee61c6d-76db-4412-b3f7-49de432202a8.JPG)

**Comment by ghost** [comment]
**EDIT**

Sorry for the noise, turns out that my issue is not related to @chaimav's. See my last post for more info.

**EDIT**

**Comment by Desmis** [comment]
@jade-nl 

I do not know.
I haven't added any library, nor modified anything that could affect the organization of the compilation (I can't).
I only added a function in "Color.cc" which is not extraordinary and which does not touch with the architecture of the system.

But maybe ?
if the last commit causes this problem, why?
In this case, but I don't know how to "just" go back to the previous commit. That does not bother me
jacques

**Comment by Desmis** [comment]
@jade-nl 

For each change,  I look at the PR before to see if everything is OK.
"All checks have passed."

And the same for the merge: "All checks have passed."
In this case, everything was OK, without any reports.
There was one "float to double", but that has been resolved, and I think (??) unrelated to the missing library

Jacques

**Comment by ghost** [comment]
@Desmis 

I'm not a coder but I do notice this when looking at the *color.cc* code you created/changed:

`#include <iostream>`

Shouldn't that be:

`#include "iostream"`

**Comment by Thanatomanic** [comment]
No, standard libraries are referred to with angled brackets.

Also, I don't have any immediate thoughts about what libsharpyuv could be doing. It doesn't ring a bell...

**Comment by Desmis** [comment]
@jade-nl 
there are already 40 references `#include <iostream>`
  
in the current version of RT.

Probably it's not that...


Jacques

**Comment by Thanatomanic** [comment]
fter a small search, it has to do with AVIF/webp. We're not using that directly, so it must be a secondary dependency. Still, not sure why or what suddenly broke.

**Comment by ghost** [comment]
Fixed my issue and it turns out that itis not related to chaimav's original post!

Bit strange that this happens in this way though: There is a directory that holds profiles, appropriately called *profiles*. I want to test something in the upcoming days and this morning created a new (sub)directory for that in *profiles*.  That created sub-directory was not readable by this specific user and RawTherapee stops working without any sane message. A permission denied or something similar is kinda expected in the terminal if this happens.

Anyway, solved for me and I'll edit my previous backtrace post to reflect this.

**Comment by Souzaadauri** [comment]
Windows 11, RawTherapee_dev_win64_release build 5.9-60 apresenta um erro quando tento abri-lo. 
está ausente: libsharpyuv-0.dll
