### ISSUE TITLE
Support for OM Digital Solutions OM-5

### ISSUE THREAD

**Issue by michael-lenz** [Beep6581/RawTherapee#6699]
With the recent merge of initial support for the OMDS OM-1 (2d37dec49b693687008dba8c1ae02f468f180f45), rt can open raw files from OM-5.
Colors are a bit off and white frames show up as pink, so a camconst.json entry needs to be created/derived.

I have taken two sets of white frames for all ISO levels at F5.6 with LENR on (3" exposure) and off (1" exposure).
The files are available [*here*](https://filebin.net/7ql2q8sgsbq9k2ne/OM_Digital_Solutions_OM-5.tgz)

**Comment by michael-lenz** [comment]
I am willing to learn/invest the time and create the camera constants myself, but I'll need some guidance.

What I understand from the comments in camconst.json is that I'd need to get the average maximum values of R, G1, B, G2 for clipped pixels for each ISO and enter them accordingly.

How do I determine the masked sensor borders?

**Comment by michael-lenz** [comment]
Using the full-picture averages (with sigma=0) from the shots without LENR results in the following white ranges for camconst.json:
```
    { // Quality X
        "make_model": ["OM Digital Solutions OM-5"],
        "ranges": {
			// i5.6, 1" expsoure, no LENR
			"white": [ 
				{ "iso": 64, "levels": [ 3839, 3841, 3839, 3841 ] },
				{ "iso": 100, "levels": 3839 },
				{ "iso": 200, "levels": 3841 },
				{ "iso": 250, "levels": [ 3839, 3840, 3839, 3840 ] },
				{ "iso": 320, "levels": 3840 },
				{ "iso": 400, "levels": 3839 },
				{ "iso": 500, "levels": 3839 },
				{ "iso": 640, "levels": 3840 },
				{ "iso": 800, "levels": 3839 },
				{ "iso": 1000, "levels": [ 3839, 3840, 3839, 3840 ] },
				{ "iso": 1250, "levels": 3840 },
				{ "iso": 1600, "levels": [ 3840, 3841, 3840, 3841 ] },
				{ "iso": 2000, "levels": [ 3838, 3839, 3838, 3839 ] },
				{ "iso": 2500, "levels": [ 3839, 3841, 3839, 3841 ] },
				{ "iso": 3200, "levels": [ 3836, 3837, 3836, 3837 ] },
				{ "iso": 4000, "levels": [ 3839, 3842, 3839, 3842 ] },
				{ "iso": 5000, "levels": [ 3837, 3840, 3837, 3840 ] },
				{ "iso": 6400, "levels": [ 3837, 3841, 3837, 3841 ] },
				{ "iso": 8000, "levels": [ 3837, 3843, 3837, 3842 ] },
				{ "iso": 10000, "levels": [ 3837, 3843, 3837, 3843 ] },
				{ "iso": 12800, "levels": [ 3840, 3846, 3841, 3847 ] },
				{ "iso": 16000, "levels": [ 3839, 3848, 3841, 3848 ] },
				{ "iso": 20000, "levels": [ 3841, 3853, 3842, 3852 ] },
				{ "iso": 25600, "levels": [ 3860, 3873, 3861, 3872 ] }
			]
		},
        "raw_crop" : [ // FIXME: taken from OM-1
           { "frame" : [5220, 3912], "crop": [0, 0, 5220, 3912] }
        ]
    },
```

With this, white frames are actually white.

According to the comments, those values can be subsumed under a conservative 3820 or 3830.

**Comment by Thanatomanic** [comment]
Seeing as all white levels are roughly the same, it has no added value to specify them for different ISO's.

Something is wrong with the values though. Not having any pixel value above 4096 would mean the camera shoots in 12-bit color depth. I would definitely not expect that from a modern device.

**Comment by michael-lenz** [comment]
I have just had a look at random samples with LENR and have seen values mostly in the 3830 and (slightly) above range. Even with images in hand-held Hi-Res mode, I don't see any values higher than 3840 in RawDigger.

So the camconst entry boils down to:

```
    { // Quality X
        "make_model": ["OM Digital Solutions OM-5"],
        "raw_crop" : [ // FIXME: taken from OM-1, get proper values 
           { "frame" : [5220, 3912], "crop": [0, 0, 5220, 3912] }
        ]
    },
```

OM Workspace apparently has no way of displaying/accessing raw pixel values and shows only RGB values - 0xFFFFFF isn't overly helpful. :sweat_smile: 

According to [*this site*](https://www.digitalkamera.de/Kamera/OM_System/OM-5.aspx), the color depth is indeed 12bit.



Regarding `raw_crop`, how does one determine the correct offset(s)?
* per spec, the RAW image size is 5184x3888
* per OM workspace / EXIF, actual size is 5240x3912

**Comment by michael-lenz** [comment]
Regarding `raw_crop`, how does one determine the correct offset(s)?
* per spec, the RAW image size is 5184x3888
* per OM workspace / EXIF, actual size is 5240x3912

**Comment by Entropy512** [comment]
> I would definitely not expect that from a modern device.

Given how small the photosites are in an MFT sensor, that doesn't surprise me at all.

**Comment by Beep6581** [comment]
@michael-lenz 

> How do I determine the masked sensor borders?

https://github.com/Beep6581/RawTherapee/blob/dev/rtengine/camconst.json#L67

1. With RawTherapee closed, edit the `options` file and set `Verbose=true`
1. Download every OM-5 file from https://raw.pixls.us/
1. Make sure there is no `raw_crop` entry in `camconst.json` for the OM-5.
1. Open each raw file in RT and create an appropriate `raw_crop` entry in `camconst.json` . Use the "raw dimensions" printed in the console for the `frame`, and get the `x` and `y` coordinates from the preview.


e.g. When you open the 50MP [`OM Digital Solutions - OM-5 - 16bit (4:3).ORF`](https://raw.pixls.us/getfile.php/6344/nice/OM%20Digital%20Solutions%20-%20OM-5%20-%2016bit%20(4:3).ORF) you will see the following in the console:
```
raw dimensions: 8200 x 6132
raw crop: 0 0 8200 6132 (provided by dcraw)
```

RawTherapee shows in the Navigator that the image is 8192 x 6124. This is because in the Raw tab > Sensor with Bayer Matrix > Demosaicing, the [Border](https://rawpedia.rawtherapee.com/Demosaicing#Border) parameter is set to 4 by default. Set it to 0 and the image size becomes 8200 x 6132.

The preview in RawTherapee shows a black border along the right edge of the image. Hover over the bottom-rightmost pixel, and the coordinates in the Navigator appear as 8199 x 6131 (indexing starts at 0 not 1, so add 1). Now hover over the first non-black column from the right, and you see it is 8171 x 6131. Add 1 (because of 0-based indexing), and you get your entry for camconst:
```
           { "frame" : [8200, 6132], "crop": [0, 0, 8172, 6132] }
```

**Comment by ghost** [comment]
Hello, I have been a RawTherapee happy user for years until I switched to the OM-5 and realised that RawTherapee (5.9, released on 2022-11-27) cannot handle the .ORF files. They are all back. I don't know how I can help. Therefore, I switched to [ART](https://bitbucket.org/agriggio/art/wiki/Home) 1.19.3 that can handle the .ORF files correctly(?)

**Comment by michael-lenz** [comment]
No need to help, anymore, as this has been fixed, but just not merged (or released) yet. 

This means that until the next release, you'll need to build rt yourself. 
For the moment you'll need to do this on the `om5` branch, i. e. switch the branch before compilation. When #6703 has been merged, you can just follow the [build instructions](https://github.com/Beep6581/RawTherapee#compilation-branches-and-git) as-is.
