### ISSUE TITLE
Sony ZV-1 support - White Frames

### ISSUE THREAD

**Issue by pi99y** [Beep6581/RawTherapee#6731]
Hi,
I've shot the white frames with Sony's Z-V1. Please add the (improved) support. Thank you!
https://filebin.net/7aeqx5tbu6z9w2d4/szv1.zip

Best, pi99y

**Comment by pi99y** [comment]
Re-upload, previous link expired.
https://www.swisstransfer.com/d/8c4cb663-0ba1-4950-a9ec-c4485f0b12ae

@Lawrence37 Please download before May 6th, thanks.

**Comment by Lawrence37** [comment]
I downloaded the files, but since I have never processed white frames before, I cannot guarantee any results.

**Comment by Entropy512** [comment]
I'll try and grab the files later this week (since it sounds like they expire May 6) - I can do some histogram checks to find the white level.

That said, chances are likely that the ZV-1 can be handled merely by declaring it to be an alias for the A7SIII/FX3 as they all share the same sensor.

**Comment by kmilos** [comment]
> the ZV-1 can be handled merely by declaring it to be an alias for the A7SIII/FX3 as they all share the same sensor

You're perhaps thinking of the more recent ZV-E1? The ZV-1 is a 1" camera...

**Comment by pi99y** [comment]
Yeah, it's a 1 inch sensor camera. Any progress?

**Comment by pi99y** [comment]
Re-uploaded to keep the link alive https://www.swisstransfer.com/d/c3e6d1a4-483d-44da-9a79-3a1626a98080

**Comment by Lawrence37** [comment]
These images have sensible white levels in the EXIF and override any values set in `camconst.json`. For lower ISO images, there are some pixels in the center organized in rows (for PDAF?) that have slightly lower white levels. The difference is small and only a tiny fraction of pixels are affected, so overall it's insignificant. @pi99y, have you encountered any issues with the white level such as magenta coloration or noise in clipped highlights? If not, I don't think there is anything else to be gained from analyzing these white frames.

**Comment by pi99y** [comment]
Hi, @Lawrence37, thanks for looking into this.
The raw images (RT version: 5.9-151-g677aaf2ec) with the (Neutral) preset look like this:

![_DSC0061](https://github.com/Beep6581/RawTherapee/assets/10639257/611356cb-f1a0-44b8-bf7b-125099f28855)

![_DSC0082](https://github.com/Beep6581/RawTherapee/assets/10639257/50012c7e-5667-4757-8fbc-6ddfbdc87b6d)

In my limited tests I only managed to bring some of the images to normal-ish appearance by playing with "raw black points" and "white balance", so the default is far from what I'm used to with other raw files (of other cameras). The histogram here looks very squeezed at default settings.

Here's a raw file, if it helps: https://www.swisstransfer.com/d/22b070d6-9750-43f5-9728-3853ef18a25c

Thanks very much, let me know if there is something I can test.

**Comment by Lawrence37** [comment]
@pi99y, I've added the correct black level and a color matrix in #6758. To test it, you can add the new entry to you own `camconst.json` if you know how to do that, or get the [pre-dev build](https://discuss.pixls.us/t/rawtherapee-pre-dev/35595) for the linked pull request.

**Comment by pi99y** [comment]
Thank you @Lawrence37 this fixes it! 
BTW, what's missing - seeing that it's marked as "// Quality C" in camconst.json? Are additional examples / shots needed?

**Comment by Lawrence37** [comment]
I added the PDAF patterns. There's nothing else remaining as far as the camconst entry goes.

**Comment by pi99y** [comment]
Thank you!

**Comment by nicustraton** [comment]
I can solve Sony, Nikon, Canon cameras firmware problems/issues after firmware update etc.

If you want to unlock region for your Sony FX3/FX30 camera or other model, in order to have latest firmware and PAL-NTSC, write me on whatsap +40727005523, country code Romania (+40) and number 727005523 or mail me: nicustraton.baron at gmail dot com.

You just have download a USB remote software, enter my IP, connect the camera with USB cable in Image Transfer (MSC) mode to a windows PC/laptop with Windows OS and Intel CPU and share the connection. I will unlock camera first and you pay after.

PS: if you have an older firmware version on camera and you know you have your camera from grey market If you want to update firmware to latest version, if you will update, you will lose PAL/NTSC so I recommend to let me unlock region first, update firmware to latest version and then unlock region again.

* this is a safest way becauseI will backup your camera original settings and firmware before any procedures.
