### ISSUE TITLE
RawTherapee crashed while loading the photos from a folder, now everything inside is deleted

### ISSUE THREAD

**Issue by chuvak889** [Beep6581/RawTherapee#6757]
So, i can't believe i just lost everything.
RawTherapee crashed twice trying to load a folder from my SD card, now all the photos (both RAW and JPG, along with everything else) are gone. 

How can i find out what happened exactly? Before panicking, maybe they were moved somewhere or something.

**Comment by Lawrence37** [comment]
It could be because your SD card is failing. I would make a backup of all the files on the card then attempt to recover the lost images with a file recovery program. It might be wise to make a disk clone first in case the card fails completely while running the recovery. Hopefully it's something less serious like corrupted folder entry. In that case, recovery software should have no problem finding the files.

**Comment by Floessie** [comment]
@chuvak889 I can only second what @Lawrence37 already wrote. This must be a more generic problem. I had a similar problem with my camera once and managed to rescue all files from a corrupted SD card with [PhotoRec](https://www.cgsecurity.org/wiki/PhotoRec). I wrote about my experience [here](https://discuss.pixls.us/t/last-exit-photorec/13696).

HTH,
Flössie

**Comment by Lawrence37** [comment]
@chuvak889 I hope you were able to recover your photos. I'm closing this issue as it seems unrelated to RawTherapee. Feel free to comment if you think otherwise.
