### ISSUE TITLE
Inpaint opposed highlight reconstruction cache strategy

### ISSUE THREAD

**Issue by Lawrence37** [Beep6581/RawTherapee#6815]
If inpaint opposed highlight reconstruction is activated, the editor becomes much slower when applying other adjustments because the image is reprocessed completely. The full reprocessing may have been added to ensure the white balance is correctly taken into account for the highlight reconstruction. There should be a more efficient way to do this.

**Comment by Lawrence37** [comment]
Inpaint opposed is enabled in several of the bundled processing profiles, so it's important to resolve this or change the reconstruction method back to Blend before the release.

**Comment by Desmis** [comment]
@Lawrence37 
When Inpaint-opposed was 'merged', I said that:

In terms of overall quality the best was "Color propagation", then "Inpaint opposed", then "blend", then the others. Even if there are exceptions or "Inpaint opposed" is the best.

In terms of processing time:
* blend = 1
* inpaint opposed = 2
* Color spread = 4

Hence my proposal to put "Inpaint opposed" as the default choice.

I don't know how to refresh the image without reactivating the process. Maybe there is a solution?
Otherwise if you want to save time "blend" is the solution.

Jacques

**Comment by Benitoite** [comment]
@Lawrence37 @Desmis Would it be possible to have a chache containing the Demosaiced and possibly Retinex image data in order that they would not be retriggered?

**Comment by Lawrence37** [comment]
The pipeline has caches at various stages, but something is telling it to override the caches when inpaint opposed is enabled.

**Comment by Desmis** [comment]
I have creta a PR 
https://github.com/Beep6581/RawTherapee/pull/6818

To ensure a faster refresh, I replace "Inpaint opposed" by "Blend" in "Highlight reconstruction".

Of course this is accompanied by a less good treatment of highlights

**Comment by Benitoite** [comment]
Aha, I did not realize that as https://rawpedia.rawtherapee.com/Toolchain_Pipeline does list hilite recon as coming before WB, and I believe this color opposition method require analysis of the cube3 space to compute the reference averages additionally.  On a darktable GPU reassesing the cube3 img may not be as noticable as it is here?

**Comment by Desmis** [comment]
@Benitoite 
In the case of "Inpaint opposed" white balance is performed before.

**Comment by Hombre57** [comment]
So I guess that switching to `DEMOSAIC` instead of `ALL_NORAW` on WB events when HLRecovery is on Inpaint mode should be sufficient, so we could delete [this condition](https://github.com/Beep6581/RawTherapee/blob/bd94fbd6b6512bafd030494c1a7921634fe2a086/rtengine/rawimagesource.cc#L852) ?

**Comment by Desmis** [comment]
@Hombre57 
I am still away from my home, still for a few days.
Can you suggest a PR or a patch so we can try

Thank you

**Comment by Hombre57** [comment]
@Desmis Yes, I'm trying to find something clean, though I'm not familiar with the `ProcEventMapper` and `RefreshMapper` if it has to be decided at event time.

**Comment by Lawrence37** [comment]
I tried adding white balance to the refresh mapper and it seems to have the desired effect. See [this commit](https://github.com/Lawrence37/RawTherapee/commit/7e0f3243b8ebd4863cc2d1e9d41119eae83f6ae9). If anyone has a better idea, please let me know. Otherwise I will make a pull request for this.

**Comment by Hombre57** [comment]
I've created the `wb-event-fix` branch which hopefully will fix the problem. 

The `ProcEventMapper` now has a method to register several actions with the same history message. The white balance tool will use that feature and will decide which action to trigger depending on the value of the HL reconstruction method (and if enabled). This tool has became a `PParamsChangeListener` to keep track of the required parameter.

On the engine side, the `iscolor` parameter being true in `rawimagesiource.cc` on line [848](https://github.com/Beep6581/RawTherapee/blob/9ae8c79c3a6133b8b37a89a6a2fa2c403e834b8d/rtengine/rawimagesource.cc#L848) for `Color` && `Coloropp` but only for `Color` in `improccoordinator.cc` on line [417](https://github.com/Beep6581/RawTherapee/blob/9ae8c79c3a6133b8b37a89a6a2fa2c403e834b8d/rtengine/improccoordinator.cc#L417) was triggering the demozaicing and capture sharpening, because when `Coloropp` was set, this

```
(params->toneCurve.hrenabled && !iscolor && imgsrc->isRGBSourceModified()
```
...was always true. I've changed the condition to `Color` && `Coloropp` for `iscolor` in `improccoordinator.cc` and it seem better, though I'd like you have a look @Desmis and @Lawrence37, if that's still working properly.

I decided to keep the ProcEventCode for the events to leave the language files untouched and use the existing `HISTORY_MSG_*`, though that may not be the cleanest way to do.

@Lawrence37 Don't hesitate to make this more C++11 if you want, I'm still mainly a C++03 guy, unfortunately.

**Comment by Hombre57** [comment]
@Lawrence37 I just saw that there's something possibly wrong in `refreshmap.h` : because of [this line](https://github.com/Lawrence37/RawTherapee/blob/69c1caafa10f5996a1213c1c851bf727a356b855/rtengine/improccoordinator.cc#L2847), `M_VOID` should remain the highest bit. Any new tool dependent event bit entry should be added below `M_HIGHQUAL` and the numerical bit shift should remain incremental from bottom to top. So the code should probably be :

```C++
// Use M_VOID if you wish to update the proc params without updating the preview at all !
#define M_VOID       (1<<20)  // Keep this one the highest bit
// Use M_MINUPDATE if you wish to update the preview without modifying the image (think about it like a "refreshPreview")
// Must NOT be used with other event (i.e. will be used for MINUPDATE only)
#define M_MINUPDATE  (1<<19)
// Force high quality
#define M_HIGHQUAL   (1<<18)

// Elementary functions that can be done to
// the preview image when an event occurs
#define M_WB          (1<<17)
#define M_SPOT        (1<<16)
#define M_CSHARP      (1<<15)
#define M_MONITOR     (1<<14)
#define M_RETINEX     (1<<13)
#define M_CROP        (1<<12)
#define M_PREPROC     (1<<11)
#define M_RAW         (1<<10)
#define M_INIT        (1<<9)
#define M_LINDENOISE  (1<<8)
#define M_HDR         (1<<7)
#define M_TRANSFORM   (1<<6)
#define M_BLURMAP     (1<<5)
#define M_AUTOEXP     (1<<4)
#define M_RGBCURVE    (1<<3)
#define M_LUMACURVE   (1<<2)
#define M_LUMINANCE   (1<<1)
#define M_COLOR       (1<<0)
```

I'll test your branch with this change included.

**Comment by Lawrence37** [comment]
Wow, that's a good find. What a "nice" surprise. I wonder why it is `if (change & (M_VOID - 1))` instead of `if (change & (~M_VOID))`. Then `M_VOID` doesn't need to be the highest bit.

I will also test your branch.

**Comment by Lawrence37** [comment]
@Hombre57 The functionality of `wb-event-fix` is fine. I will take a look a the code next.

**Comment by Hombre57** [comment]
Because when I added `M_VOID` and updated line 2847 for optimization purpose, I just didn't though about your solution. `M_VOID` was the top entry and I though it would remain the highest bit shift. But you're right, it doesn't need to be (even more without any comment explaining the requirement), so you can change to `if (change & (~M_VOID))`.

That's probably why opensource project should restrain committers to professionals :wink: .

Your solution works fine too and is way simpler, no problem to merge it.

**Comment by Lawrence37** [comment]
@Hombre57 I created a pull request for my branch which includes the fix for the refresh mapper bits. What I like about your solution is that it's not prone to breaking anything if `DEMOSAIC` or `ALLNORAW` change or if a new one is added between them.

**Comment by Desmis** [comment]
@Lawrence37 @Hombre57 
I am always not at home...

I just compiled and tested.
It seems to work well. It's a clever solution :) (but it's complicated in RT to handle events!)
Now the refresh is better, but of course the processing time - it's obvious - is higher for "Inpaint opposed" than "blend", but I think it's worth it.

Thank you

Jacques

**Comment by Hombre57** [comment]
> What I like about your solution is that it's not prone to breaking anything if `DEMOSAIC` or `ALLNORAW` change or if a new one is added between them.

@Lawrence37 That's right, the mapping should stay in `refreshmap.h` to handle the combinations in one place. Could you please add this patch to make things more conventional ?

[wb_event.txt](https://github.com/Beep6581/RawTherapee/files/12333391/wb_event.txt)

**Comment by Lawrence37** [comment]
@Hombre57 I applied your suggestion and also removed the M_WB + inpaint opposed condition in favor of using `DEMOSAIC` when M_WB + inpaint opposed is detected, i.e.
```c++
if ((todo & M_WB) && params->toneCurve.hrenabled && params->toneCurve.method == "Coloropp") {
    todo |= DEMOSAIC;
}
```

I think with both these changes, it will be hard to accidentally break the logic.

**Comment by Desmis** [comment]
@Hombre57 @Lawrence37 
You did a great job, congratulations.

Jacques
