### ISSUE TITLE
RawTherapee crashes often on different actions in 

### ISSUE THREAD

**Issue by kaelte** [Beep6581/RawTherapee#6875]
Quite often, RT chrashes when working in Single Editor Tab. The actions leading to a crash differ; to me it appears random. The crash of which gdb's log file is attached happened:

1. I started RT and opened a folder which contains DNG-images
This opened the Single Editor Tab.
2. I pressed several times <F4> to browse forward the images
3. I pressed<F3> to backwards.
This caused the crash

# Version and OS details
- dev-branch self build with on following commit
` 72bf27121 - (HEAD -> dev, origin/dev, origin/HEAD) Removed gzip from windows.yml workflow #6864 (Fri, 13 Oct 2023 23:04:33 +0200) <Morgan Hardwood>`
But the release 5.9 crashes as well.
- NixOS 23.05
`uname -a`
`Linux maxiTower 6.5.9 #1-NixOS SMP PREEMPT_DYNAMIC Wed Oct 25 10:16:30 UTC 2023 x86_64 GNU/Linux` 

# GDB Log File
[log.txt](https://github.com/Beep6581/RawTherapee/files/13199136/log.txt)

**Comment by Lawrence37** [comment]
Crash confirmed. It happens sometimes when another image is loading and you move the cursor over the image in the editor. It tries to sample the raw color of the pixel under the cursor but the data is invalid because the previous image data is cleared but the next image hasn't been loaded yet.

Edit: The demosaic algorithm of the next image must be None to enter the getRawValues function seen in the GDB report.

**Comment by kaelte** [comment]
The crash happens also for
- monochrome images (Leica M Monochrome) without demosaicing.
- when the mouse pointer is over the filmstrip

**Comment by Lawrence37** [comment]
What steps did you perform immediately before those crashes?

The GDB report is specifically for the crash that happens when loading an image with the demosaic method set to None and the cursor is moving over the editor image. That crash will only happen under those circumstances, so you are seeing at least one other distinct bug. Note that it is preferable to open a separate issue for each different bug so they can be tracked independently.

**Comment by kaelte** [comment]
The first gdb report is from a crash without demosaicing.
Here I have a second crash report when the mouse pointer was over the film strip: 
[rt_gdb_2023-11-02_1615.txt](https://github.com/Beep6581/RawTherapee/files/13241457/rt_gdb_2023-11-02_1615.txt)

The behaviour differs a lot: Yesterday I could work for more than an hour without a crash.
Today RT crashed immediately after starting: I could see the RT-window for a fraction of a second.

I work under NixOS with KDE Plasma.

**Comment by Lawrence37** [comment]
The second GDB report shows the same type of crash: moving the cursor over a loading image with the demosaic method set to None.

**Comment by kaelte** [comment]
> The second GDB report shows the same type of crash: moving the cursor over a loading image with the demosaic method set to None.

Maybe I moved the cursor over the image to the film strip: I cannot exclude that.
I suggest that we focus on the bug _moving the cursor over a loading image with the demosaic method set to None_ and afterwards I will test and watch whether RT keeps on crashing.
