### ISSUE TITLE
Queue template improvement for better mirroring of directory structure

### ISSUE THREAD

**Issue by sgilbertson** [Beep6581/RawTherapee#6915]
I propose providing improved support for the following use-case:

- Raw files are under a base directory
- Place exported files under a different base directory
- Retain the directory structure from the base directory when exporting

For example suppose the raw images are in the base folder `D:\raw_photos\forProcessing`, and you want to export into `E:\exported_photos`, so that a raw image in `D:\raw_photos\forProcessing\some\more\directory\terms` is exported to `E:\exported_photos\some\more\directory\terms`. The existing `%p` and `%dN` template terms defined in [https://rawpedia.rawtherapee.com/Queue](https://rawpedia.rawtherapee.com/Queue) can't do that unless every image is at the same depth under the base directory.

I propose adding a variant of the `%dN` term with a minus sign, so `%d-N` means "the entire directory, but with the first N terms removed". That means `%d-1` would remove just the drive letter (`D:` in the example above). In the example, `%d-2` would remove `D:\raw_photos\' and `%d-3` would remove `D:\raw_photos\forProcessing`, which is what desired in this case.

In the queue tab you would enter `E:/exported_photos/%d-3/%f` to accomplish the stated goal.

The attached patch implements this enhancement in a branch taken from the 5.9 tag. To issue it as a pull request I should target the `release-5.10` branch, correct?

[0001-Added-queue-template-term-d-N-to-insert-the-full-dir.patch](https://github.com/Beep6581/RawTherapee/files/13806096/0001-Added-queue-template-term-d-N-to-insert-the-full-dir.patch)

**Comment by Lawrence37** [comment]
Hi @sgilbertson, thanks for the patch. Development takes place on the `dev` branch, so raise a pull request against `dev`.

I want to discuss the ideal syntax for the new variable. `d` represents a single directory in the path. `p` represents a path. `N` is the distance from the file name. Since negative numbers are often used to count from the opposite direction, how about using `%P-N`? `p` is the prefix. `P` is the suffix. A negative number means distance from the start of the path. So given a path `/a/b/c/d/e.raw`,
`%d1` = `d`
`%d2` = `c

**Comment by Lawrence37** [comment]
Hi @sgilbertson, thanks for the patch. Development takes place on the `dev` branch, so raise a pull request against `dev`.

I want to discuss the ideal syntax for the new variable. `d` represents a single directory in the path. `p` represents a path. `N` is the distance from the file name. Since negative numbers are often used to count from the opposite direction, how about using `%P-N`? `p` is the prefix. `P` is the suffix. A negative number means distance from the start of the path. So given a path `/a/b/c/d/e.raw`,

Directory
`%d1` = `d`
`%d2` = `c`
`%d3` = `b`
`%d4` = `a`
Directory (counting from left)
`%d-1` = `a`
`%d-2` = `b`
`%d-3` = `c`
`%d-4` = `d`
Path prefix
`%p1` = `/a/b/c/d`
`%p2` = `/a/b/c`
`%p3` = `/a/b`
`%p4` = `/a`
Path prefix (counting from left)
`%p-1` = `/a`
`%p-2` = `/a/b`
`%p-3` = `/a/b/c`
`%p-4` = `/a/b/c/d`
Path suffix
`%P1` = `/d`
`%P2` = `/c/d`
`%P3` = `/b/c/d`
`%P4` = `/a/b/c/d`
Path suffix (counting from left)
`%P-1` = `/a/b/c/d`
`%P-2` = `/b/c/d`
`%P-3` = `/c/d`
`%P-4` = `/d`

What do you think?

**Comment by sgilbertson** [comment]
@Lawrence37 your proposal makes it a more generally-applicable feature, which sounds good to me. A possible way to summarize is:

- percent sign + letter + N
- letter d means "one of the directory names in the path (not including the filename)", "p" means "from dN back to the start of the path" and "P" means "from dN forward to the end of the path"
- N = 1..9 is position to the left of the filename
- N = -1..-9 is position from the left end of the path, where -1 is the first path component
- in a Windows path, the leftmost component is the drive letter and colon (in "C:\a\b\c", for example, "%d-1" is "C:")
- in a UNC path it's the computer name (in "\\\\computer\a\b" it's "computer") (or is it "\\\\computer"?)

The explanation has to fit in a reasonably-sized tooltip (`QUEUE_LOCATION_TEMPLATE_TOOLTIP`). 

I'm wondering if there might also be a reasonable way to show the user the resulting path on the screen. Some possibilities there would be:

- When you hover over a file in the queue, it shows the destination for that file's export, rather than the file name.
- Add a label in "Output Location", showing the destination for the selected file's export (perhaps showing the destination for the first queued file if none is selected).

The idea is that you can see as you enter the template what the effect of that template will be. Thoughts?

**Comment by sgilbertson** [comment]
@Lawrence37, I'm new here... would @Beep6581 need to assign this issue to me?

I forked the repo in preparation to start working on it. I don't have much time available, but I don't think it's a very big job (even if I add a label to read out the destination path). I guess it would trigger some language translation work, though, for `QUEUE_LOCATION_TEMPLATE_TOOLTIP`.

**Comment by Lawrence37** [comment]
I've assigned the issue to you (all collaborators have this permission). Thanks for taking the initiative.

The resulting path preview is a nice idea. I don't know which option is the best. I like the first one for the ability to see the path for any image. It's not an easily discoverable feature though.

**Comment by sgilbertson** [comment]
I'm still looking at some details, but I have %dN, %d-N, %pN, %p-N, %PN and %P-N working as described above. I added a label to preview the selected image's destination path. For discoverability, the label's initial text is:

```
Select a thumbnail to preview its destination path here
```
[edited -- i had some incorrect information here earlier] The tooltip is "Destination path for the first selected image appears here". I am considering removal of the word "first", because it might introduce more confusion than it prevents. The previewed path is for the leftmost of the selected images, but in real life I think you'd normally just select one image when using this feature.

The label is updated whenever any of its input values changes. For example, as you type into the template box, the effect on the previewed destination appears immediately. Same thing if you click a template/folder radio button or select a file path, and I'll be adding code to also update when you change the file format.

Then we come to the tooltip for the location template (QUEUE_LOCATION_TEMPLATE_TOOLTIP), the existing text for which is reproduced below. I'm wondering whether there really ought to be this much text in a tooltip, and whether there's a better way to display this information. Ideally, it would be possible to have the help information stay on the screen while you're editing the template, so you can refer to it as you go along.

One option might be a small "?" toggle button to the right of the template entry field, which when clicked enables or disables display of a panel that's inserted between the control panel and the image thumbnail panel, containing the help information. The tooltip could then just say something general about the template feature and invite you to click the "?" button. It seems to me a big enough change to warrant a separate issue, or at least a separate pull request, but @Lawrence37 do you have any thoughts on that?

Existing value of QUEUE_LOCATION_TEMPLATE_TOOLTIP:
```html
Specify the output location based on the source photo's location, rank, trash status or position in the queue.

Using the following pathname as an example:
<b>/home/tom/photos/2010-10-31/photo1.raw</b>
the meaning of the formatting strings follows:
<b>%d4</b> = <i>home</i>
<b>%d3</b> = <i>tom</i>
<b>%d2</b> = <i>photos</i>
<b>%d1</b> = <i>2010-10-31</i>
<b>%f</b> = <i>photo1</i>
<b>%p1</b> = <i>/home/tom/photos/2010-10-31/</i>
<b>%p2</b> = <i>/home/tom/photos/</i>
<b>%p3</b> = <i>/home/tom/</i>
<b>%p4</b> = <i>/home/</i>

<b>%r</b> will be replaced by the photo's rank. If the photo is unranked, '<i>0</i>' is used. If the photo is in the trash, '<i>x</i>' is used.

<b>%s1</b>, ..., <b>%s9</b> will be replaced by the photo's initial position in the queue at the time the queue is started. The number specifies the padding, e.g. <b>%s3</b> results in '<i>001</i>'.

If you want to save the output image alongside the source image, write:
<b>%p1/%f</b>

If you want to save the output image in a folder named '<i>converted</i>' located in the source photo's folder, write:
<b>%p1/converted/%f</b>

If you want to save the output image in
'<i>/home/tom/photos/converted/2010-10-31</i>', write:
<b>%p2/converted/%d1/%f</b>
```

**Comment by sgilbertson** [comment]
All checks pass in #6920. I've installed it on Windows 10 using the built artifact and confirmed that it works as expected. I also built and ran it on Ubuntu 22.04, and confirmed that slashes vs. backslashes work properly and so on. @Lawrence37 as I'm a first-time contributor, is there anything special I need to do after posting a pull request, to have it on the radar of potential reviewers, or do people just peruse the list of open requests from time to time?

**Comment by Floessie** [comment]
@sgilbertson Hi Scott,

Thanks for you contribution! :+1: 

I skimmed through the diff and found no apparent mistakes. If you don't mind, here are some minor things you might want to  improve:

* I know the code isn't super consistent due to the many people who have contributed, but you should take a look at the code style above and below your new code and maybe adapt the braces accordingly. And a little bit more whitespace in the `for (...)` might also help readability.
* `if (selected.size())` should probably be `if (!selected.empty())`. And if you're at it: there's an `if (selected.size() > 0)` in the old code, that could be corrected as well.
* `static inline unsigned decodePathIndex(unsigned & ix, Glib::ustring & templateText, size_t numPathElements)`: A better C++ approach would drop the `static inline` and place it in an anonymous namespace at the beginning of the file. There are multiple examples of that in other places. And you should decide where to put the `&`. I prefer to append it to the type (as I read it as part of the type), but there are other places where it is prepended to the variable. Just be consistent with the code around.
* I can't say for sure that there are no `unsigned`s in the codebase, but we usually name the type with it, so better go for `unsigned int`.
* There are some suboptimal string assignments like `path = path + ...` which could be changed to `path += ...` throughout the file.

HTH,
Flössie

**Comment by sgilbertson** [comment]
@Floessie thank you for your constructive feedback. I think I have handled all of your points in commit 9e310b7 and b3bbaa6 (I forgot to do the ampersand change in the first commit). I wasn't totally sure about the one involving whitespace in the `for`, but I did what I think you were asking for.

I had never encountered the anonymous/unnamed namespace point before, and I'll definitely be using that from now on in my day job! Also I have bookmarked [C++ Core Guidelines](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines), where it's `SF.22`.

**Comment by Lawrence37** [comment]
> or do people just peruse the list of open requests from time to time?

Yes, people just check the list of pull requests or subscribe to notifications.

**Comment by Floessie** [comment]
@sgilbertson 

> I had never encountered the anonymous/unnamed namespace point before, and I'll definitely be using that from now on in my day job! Also I have bookmarked [C++ Core Guidelines](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines), where it's SF.22.

I also had an epiphany once in this very project, when @Lawrence37 [made me aware](https://github.com/Beep6581/RawTherapee/issues/6298#issuecomment-874533373) that `for (auto&& var : container)` was better than `for (auto& var : container)`, so I changed my whole codebase at work. That's the nice thing about collaborating on the net: you learn a lot of practical things. :+1: 

Best,
Flössie
