### ISSUE TITLE
Discussion about using local-adjustment tools globally

### ISSUE THREAD

**Issue by waynesutton50** [Beep6581/RawTherapee#6922]
The Local Adjustments tab contains a number of tools that are also useful as global adjustments (e.g. Log Encoding). Currently they can be used as such by creating a full-image spot and setting the Scope to 100 to disable the deltaE detection. While this works well in most cases, it requires a number of clicks and often considerable scrolling to set up. From a workflow standpoint it is cumbersome and could deter some users. 
One solution to this would be to add the possibility of choosing between global or local adjustments at the top of the current local-adjustments menu. Selecting the global option would ideally hide the spot set-up menu along with the Preview deltaE and Scope options and let the user add the appropriate tool as the next step. Although this would help de-clutter the local-adjustments menu, having to go into the Local Adjustments tab to select global-adjustment tools isn't optimal.
Another alternative, which would no doubt require considerably more work (I speak from a position of blissful ignorance about what this might entail), would be to have access to selected Local Adjustments modules (set up as global adjustments) in the Advanced tab. There is already some duplication of functionality between the Advanced and Local Adjustment tabs (Wavelets, CIECAM, Retinex) so conceptually it wouldn’t be inconsistent with what exists already. Access to any of the local-adjustments modules from the advanced tab would also presumably give access to the C, L, L(ch) masks associated with the particular tool thereby enhancing RawTherapee's global masking capabilities, which are currently restricted to Color Correction Regions.

**Comment by Lawrence37** [comment]
Another benefit of having the global option in local adjustments is the ability to apply a tool multiple times.

Ideally, in my opinion at least, each local adjustments tool should also have a global counterpart. It does require extra work and it doesn't always make sense to have a 1 to 1 duplication. Shadows/highlights and tone equalizer for example is one tool in local adjustments, but is two separate ones in the exposure tab (I have plans to extend and improve the tone equalizer and don't want the tool to become too complex by combining it with shadows and highlights).

**Comment by Desmis** [comment]
The essential question for me is “what do we want?”.
And of course I agree in principle :)

Please note that some "LA" tools resemble those of "main" but are different either by their design:
* Color & Light  and  Exposure (main) 
* etc.

But they are also different in their design and resource requirements
* wavelet, denoise, ciecam...

At a minimum it will be necessary to keep something resembling Settings in this form or another, and maintain compatibility.

Some time ago @Pandagrapher  (thanks to him) who designed a good part of the current GUI of LA proposed a new GUI interface that was more "simple" and "user-friendly", perhaps a solution this way is possible.

But, it seems obvious, LA is mainly in Lab (even if there are RGB conversions), it is located relatively at the start of the pipeline.
Maintaining the compatibility of pp3, recursive calls to the GUI (Listener), the multiplicity of Spots and the multiplicity of possible tools for each Spot must obviously be maintained.

Jacques

**Comment by Desmis** [comment]
I create a PR.
https://github.com/Beep6581/RawTherapee/pull/6928

**Comment by epadepa** [comment]
I would suggest merging the Local and Advanced tabs into the Advanced tab and renaming the Local Adjustment module. A new name is tricky but something referring to how you can compose multiple tools perhaps.

There are only three tools in the Advanced tab so adding the (former) local adjustments won't clutter much. The discussed global/local toggle could then be the top checkbox of the module.

**Comment by Lawrence37** [comment]
I'm against placing the local adjustments in the advanced tab. I'm my view, the advanced tab is for tools that require an understanding of complex ideas to use them effectively. Local adjustments has some advanced features, but they are not central to the operations and the tool can produce great results with ease.

**Comment by Desmis** [comment]
Hello

Me too, I'm against placing the local adjustments in the advanced tab. 
For several reasons:
* as @Lawrence37  says, the "advance tab" was put there to group together the so-called complex modules (of which I was the main contributor). This is not the purpose of LA which, although it contains some complex concepts, is made up of common tools.
* we will add one more step to access the tool.

What can be done (I hope easily) is rename the tool, instead of "Local Adjustments" find another name, everyone can make a suggestion
What can also be done is change the icon in "Local Tab", but excuse me, I don't know how to make icons and integrate them into the GUI.

More generally I am giving a tiny summary of the history of LA:
* 2014 - I have the idea to do local control, close in spirit to Nikon CX2
* But I am not at all a GUI specialist, and not not a computer scientist either. Today I am an old man (76 years old), sick, but full of enthusiasm. My hobby is algorithms
* Of course it is the work of a team, but 2 actors made a major contribution to the algorithm and the code that I proposed; 
*  @Pandagrapher  (Pierre) for the GUI (about 2018, 2019) in its current form which is complex. Some years ago, he had planned to modify it to be more user-friendly (icons, etc.), @heckflosse (Ingo) to improve and optimize the code, or even rewrite it. 
* Other people as @waynesutton50 (Wayne) @jade_NL (Jacques) provided significant assistance in making the system more user-friendly and completing documentation

But for various reasons the team has shrunk... and modifying the GUI is not at all my strong point.

 Thank you for your suggestions and your participation.

Jacques
