### ISSUE TITLE
RawTherapee git: conflict file on Arch system

### ISSUE THREAD

**Issue by maderios** [Beep6581/RawTherapee#6980]
Conditions:
Arch system
Compiled sources
hicolor-icon-theme 0.17-3 package https://archlinux.org/packages/extra/any/hicolor-icon-theme/
Due to conflict file with hicolor-icon-theme, can't install/upgrade RawTherapee git since recent commit
May be  this commit ? https://github.com/Beep6581/RawTherapee/commit/7f45af1182f77e5ff731a848e22f9788d0492cde
When I try to install:
```
error: failed to commit transaction (conflicting files)
rawtherapee-git: /usr/share/icons/hicolor/index.theme exists in filesystem (owned by hicolor-icon-theme)
Errors occurred, no packages were upgraded.

```

**Comment by Lawrence37** [comment]
@Pandagrapher Is the hicolor index.theme required for all Linux builds or just our AppImage?

**Comment by Pandagrapher** [comment]
@Lawrence37 If I remember well: `rawtherapee` icon shall be located in a hicolor icon theme folder to be set as AppImage icon. For other linux build, `rawtherapee` shall be located in an icon theme (not necessary `hicolor` one) to be used by the `Gtk::Window::set_icon` function. That's why I have answered to both needs putting the icon in an `hicolor` theme installed during linux/AppImage builds.

I don't know yet how to fix that issue the best.
