### ISSUE TITLE
CDBL not always working

### ISSUE THREAD

**Issue by hholtm** [Beep6581/RawTherapee#7017]
<
**Short description**
While editing pictures with CDBL and Colour Appearance & Lighting enabled CDBL works only if inside CDBL the process After Black and White is chosen. With Before Black and White there is no action. 

**Steps to reproduce**
1. Open a piucture
2. activate CDBL with Colour Appearance & Lighting deactivated. CDBL works in both modes after and before black and white.
4. Activate Colour Appearance &Lighting with CDBL activated. CDBL works only in the mode After Black and White.-->

**Expected behavior**
CDBL should work always in both modes.
If the described behavior is intended there should be a hint and the appropriate mode in CDBL should be set by activating Colour Appearance & Lighting automatically.

**Additional information**
Version: 5.10-179-g11240bc97
Branch: dev
Commit: 11240bc97
Commit date: 2024-03-28
Compiler: cc 11.4.0
Processor: x86_64
System: Linux
Bit depth: 64 bits
Gtkmm: V3.24.5
Lensfun: V0.3.95.0
Build type: release

-->

**Comment by Lawrence37** [comment]
Confirmed in `dev`. 5.10 does not have the same issue.

**Comment by Desmis** [comment]
@hholtm @Lawrence37 

This looks like a bug, but it's not a bug.

Around 2015, we encountered artifacts when using Ciecam and CBDL together. Hence these restrictions... There were others restrictions  linked to the "quality" of Ciecam02.
Since Ciecam16 (2022) is installed - you can choose - the CAM you want - for compatibility reasons, perhaps these artifacts have disappeared.

I'll look at what we can do... It's not easy to nest the codes, to limit the disadvantages only to the CAM02 choice... To check

Jacques

**Comment by Desmis** [comment]
I just create a PR to solve (?) this old problem. Limitation only to Cam02
https://github.com/Beep6581/RawTherapee/pull/7023

Branch : cbdlciecam
Executables
https://github.com/Beep6581/RawTherapee/releases/tag/pre-dev-github-actions

This change affects CBDL, but also Tone-mapping, and in certain cases Defringe, Impulsedenoise, Microcontrast.
Now if you select Cam16, everything is activated, in all cases. To check if any artifacts do not appear - I think there should not be any, because under "LA" it is Cam16 which is implemented...and that would have consequences. Certainly there is the position in the pipeline.

Jacques

**Comment by hholtm** [comment]
After some testing everything works fine for me. 
@Desmis: Thank you very much for your work!
I found one small thing: With CBDL and Colour Appearance & Lighting activated you can change CAM16 to CAM02. CBDL is not working as expected. If you change back to CAM16 CBDL works only if you deactivate and activate it again. Perhaps there could be a not to complicated way to automate this?
@Desmis @Lawrence37: CAM02 is an older Definition with some limitations. Is there a reason to use it any longer except for backwards compatibility? Perhaps we can remove it for V5.11 orV6 of RT?

Heinrich

**Comment by Desmis** [comment]
@hholtm @Lawrence37 

For the first part, it will be very complicated to change this, which is still a marginal case.

For the second part, as I'm the author (oh sure not of the concept) of both the presentation style and the Ciecam code, I think it's important to maintain both (Cam16 and Cam02). On the one hand, for the sake of compatibility, and on the other, to keep track of the CAM (Color Appearance Model) history.

Jacques

**Comment by Lawrence37** [comment]
@Desmis What is the cause of the artifacts when using CBDL with Ciecam? Is it a bug, an inherent incompatibility, or is one of the tools having problems with extreme inputs?

**Comment by Desmis** [comment]
@Lawrence37 
Ciecam is a complex concept. In 2011 I was asked to introduce it into RT. Note that I think RT is probably the only system to have a complete, usable version. There's also a macro in Photoshop and the way to build and deconstruct CAM in LCMS.  

Researchers originally worked on CIECAM97, then CIECAM02. The basic idea was to introduce an eye-brain link in addition to Cartesian colorimetry. Here are just a few of the possibilities offered by Ciecam 
https://rawpedia.rawtherapee.com/CIECAM02#Introduction_-_history

Initially, everything worked in double precision, then we switched to "float", which in rare cases led to a few minor artifacts. But the bulk of the artifacts were produced by anything to do with color or contrast at pixel level.
CIECAM uses 6 variables: J Lightness, Q Brigtness, C chroma, S Saturation, M Colorfullnes, H hue and works pixel by pixel. It's very difficult to call a function from inside the (complex) process, which includes 3 phases : Scene, Adjustments, Viewing.

It turned out that for some images, certain processes caused artifacts for only a few images (Tone mapping, CBDL, Sharp, etc.). Black dots would appear. The researchers' work has evolved, and traces of it remain in the code, in an attempt to avoid these artifacts as far as possible. I've adapted the code, and even created it from the researchers' spreadsheets and B.Briggs' code. With Ingo's help, I added to the researchers' code as it evolved, for example M.H.Brill S.Susstrunk.

Nevertheless, artefacts remained, and we decided to isolate the functions (2015, 2016) that could create these artefacts.

The arrival of Ciecam16, scheduled for completion in 2022, seems to have resolved these problems without any apparent loss of quality. To the best of my knowledge, Cam16 is the only CAM that works..

But I think, given the experimental nature of this approach, we should keep the code from Ciecam02 and Ciecam16. On the one hand, for reasons of compatibility, and on the other, to preserve the history and experience.
By default, the system uses Ciecam16

Jacques
