### ISSUE TITLE
Incorrect black level for Sony ILME-FX3

### ISSUE THREAD

**Issue by wzging** [Beep6581/RawTherapee#7180]
I"m trying to open .CR2 image ,CR3 image And ARW image in Rawtherapee 5.10,but the colors not correct.
CR2
camera:Canon EOS 5D Mark IV
<img width="1270" alt="image" src="https://github.com/user-attachments/assets/81faabc6-7e95-477d-990e-411cbd4153dc">
CR3
camera:Canon EOS R6m2
<img width="988" alt="image" src="https://github.com/user-attachments/assets/3c0eb695-5ecd-4feb-9931-1e97ef947e91">
ARW
camera :ILME-FX3
<img width="1026" alt="image" src="https://github.com/user-attachments/assets/a5348cfa-9819-48d8-930d-e5946fd30ec1">

**Comment by syyrmb** [comment]
I assume the first two pictures are not problematic as RawTherapee doesn't (and can't) use the camera manufacture's color profile, hence the color difference. Third photo, I downloaded a FX3 raw file sample and color is weird in RT 5.10, documented in this Pixls thread (https://discuss.pixls.us/t/rawtheapee-and-sony-fx3/28777). However, I also tested RT 5.11 (with "Use Libraw" enabled) and this seems to be fixed.
I think it's better to provide raw file sample and your .pp3 sidecar to let other people replicate your problem easier.
Below is my reply in Chinese in case op can understand it (as I see Chinese is used in RT):

我觉得前两张图片比较正常，RawTherapee在解raw时是无法使用原厂的色彩配置的，所以可能和其他图片预览软件的色彩不一样。至于第三张图片，我自己找到了一张FX3的raw文件，发现RT 5.10有发紫现象，这在RT 5.8的时候就已经有记录了（https://discuss.pixls.us/t/rawtheapee-and-sony-fx3/28777）。但是，如果使用RT 5.11（请到Release页面下载）并启用“Use Libraw”选项（参数设置-图片处理-Raw Decoder-勾选Use Libraw），色彩就正常了。
一般而言，提交图片相关的问题时最好提供Raw文件以及对应的.pp3档案，以便其他人复现问题。希望对你有帮助。

**Comment by Lawrence37** [comment]
For the ILME-FX3, the black levels are wrong. As a temporary fix, you can go to Raw tab > Sensor with Bayer Matrix > Raw Black Points and set all the values to 512.

**Comment by nicustraton** [comment]
I can solve Sony, Nikon, Canon cameras firmware problems/issues after firmware update etc.

If you want to unlock region for your Sony FX3/FX30 camera or other model, in order to have latest firmware and PAL-NTSC, write me on whatsap +40727005523, country code Romania (+40) and number 727005523 or mail me: nicustraton.baron at gmail dot com.

You just have download a USB remote software, enter my IP, connect the camera with USB cable in Image Transfer (MSC) mode to a windows PC/laptop with Windows OS and Intel CPU and share the connection. I will unlock camera first and you pay after.

PS: if you have an older firmware version on camera and you know you have your camera from grey market If you want to update firmware to latest version, if you will update, you will lose PAL/NTSC so I recommend to let me unlock region first, update firmware to latest version and then unlock region again.

* this is a safest way becauseI will backup your camera original settings and firmware before any procedures.
