### ISSUE TITLE
Pasting copied profile on photo removes photo rating

### ISSUE THREAD

**Issue by kostrahb** [Beep6581/RawTherapee#7218]
**Short description**
Not entirely sure whether it's bug or intended behavior, but I noticed that for some strange reason my photo ratings began disappearing between editing sessions as I edited the images. I was able to troubleshoot it little bit and in the end it seems that when user copies profile from one photo, if processing profile fill mode is on, the rating is not preserved. Same happens for color coding and I presume also  for "in trash" property (but that one does not really matter)

**Steps to reproduce**
1. Turn on processing profile fill mode
2. Load at least two photos
3. Rate both of them
4. Check pp3 profile of second image (it contains general.rank value)
5. Edit randomly first image
6. Copy profile from first image (via the "copy current processing profile to clipboard" button)
7. Paste profile to second image (via the "paste profile from clipboard" button)
8. Check second image rating in UI (it does not change)
9. Check pp3 profile of second image (it is missing general.rank value)
10. Restart RawTherapee
11. Check second image rating in UI (now the change propagated and rating is also missing)

**Expected behavior**
I would expect that ranking, color coding and other similar properties are exempt from the replacement with hardcoded values and are preserved no matter what.

**Additional information**
- Version of RawTherapee: 5.11

**Comment by Lawrence37** [comment]
I cannot reproduce. The rating of the second image stays. To confirm, when you say "Load at least two photos", you mean open both images in editors using multiple editor mode?

**Comment by kostrahb** [comment]
I am trying things mainly on this screen:
![rawtherapee](https://github.com/user-attachments/assets/91d75a7c-12e4-4aa4-bbf5-3a57b5b09682)

It seems that there are some other conditions that I was unable to find out so far. On top of that the removal of rating seems to be happening randomly on some photos upon RawTherapee restarts (but this might be just due to delayed save of pp3 files - see below).

Otherwise I did some more troubleshooting today:
Firstly I created tmp folder, moved two photos there, opened RawTherapee for that folder (right click on the folder, and "open with"), ranked both photos, tried to reproduce the bug by following above instructions and when I was unable to reproduce it, I switched to my standard photo library and immediately noticed that I have only 87 5-star photos (it was certainly over 90 during my last editing session few days ago) - I also tried to unsuccessfully reproduce the bug there. During this process only things I touched were that "processing profile fill mode" button, some rather random processing properties (mainly from exposure tab) and buttons "copy current processing profile to clipboard" and "paste profile from clipboard". Then I started new instance of RawTherapee to see if there are possibly any differences in how the program is started and after a few unsuccessful retries I quit it. But after that I noticed that profiles in the tmp folder do not contain rating anymore.

After that I tried multiple times to do these steps:
- Started RawTherapee
- Made sure the two photos in tmp folder are rated
- Checked whether pp3 files contain rating
- Changed some properties in Exposure tab (it seems that when multiple properties are changed, the bug manifests itself more often)
- Copied profile from one image
- Pasted profile to one of the images
- Checked whether pp3 files contain rating
- Restarted RawTherapee and checked whether photo is rated

Results are that the occurence of bug is rather random. Sometimes this process does not result in rating removal, sometimes it does. I also noticed one potentially related thing, the save of pp3 files is probably asynchronous - the changes were sometimes saved to the file immediately after profile paste and sometimes they were saved only after I quit RawTherapee. 

I work under Linux, specifically EndeavourOS if this helps you.

**Comment by makerbeleg** [comment]
There Is something weird with ratings since latest major release.

On first pass through photos a rate ones with right composition and overall decent quality.
On second I edit _some_ of those.
I exit. Open again to find that two thirds of photos reverted back to 0 stars.

Do not know if this related to profile copying. Need more tests.

**Comment by makerbeleg** [comment]
Ok. Changing any setting in transform tab removed rating in my test folder.

As well as in Color tab.

Exposure tab the same.


Bug persists in large folder containing 100 files as well in smaller of 10 files.

**Comment by Lawrence37** [comment]
@makerbeleg Does it consistently remove the ratings whenever you change something in those tabs?

I have not been able to reproduce the loss of rating. Maybe it depends on the settings. @makerbeleg and @kostrahb, could you two share your `options` file from the [config folder](https://rawpedia.rawtherapee.com/File_Paths#Config)?

**Comment by makerbeleg** [comment]
Update.
It is _not_ when I change something in those tabs. It is when I open those in Editor mode.
Once I open rated photo and exit. Rating reverts back to none.
I assume it is because my default profile is applied to photo.

For testing I 
1. Created folder and copied 100 raw sony files.
2. Rated those without opening in editor mode.
3. Reopen program to see if rating persisted. It did.
4. Initially I started changing settings in editor tabs, but now even opening in editor mode is enough.
5. Reopen program to see changes. Rating reverts back to none.

[DSC05941.ARW_before.pp3.txt](https://github.com/user-attachments/files/17409465/DSC05941.ARW_before.pp3.txt)
[DSC05941.ARW_after.pp3.txt](https://github.com/user-attachments/files/17409467/DSC05941.ARW_after.pp3.txt)
[default.pp3.txt](https://github.com/user-attachments/files/17409464/default.pp3.txt)
[options.txt](https://github.com/user-attachments/files/17409469/options.txt)

This being said, initially rating reverted to none even on photos with default profile already applied.

**Comment by makerbeleg** [comment]
And with profile copying.
The act of copy profile removes rating, not just pasting to another

For testing I
1. Created folder and copied 2 raw sony files. `1` and `2`
2. Opened both of them in editor mode to make sure default profile is applied.
3. Rated `2` as 5-stars in editor mode.
4. Reopen program to see if rating persisted. It did.
5. Copied profile `2` to `1` and closed program
6. On open none of them had rating.
7. I repeated without pasting profile to another image. None of them had rating on next open.
8. I repeated with rating both images. 4 and 5 stars. Copying profile one to another removed rating from both of them.

Exactly same behavior have color labels.

**Comment by makerbeleg** [comment]
> It is _not_ when I change something in those tabs. It is when I open those in Editor mode.

It Is when I edit something in tabs as well.
If I edited something in Editor mode and close program then rating reverts to none.

For testing I
1. Created folder and copied a raw sony file.
2. Opened it in editor mode to make sure default profile is applied.
3. Rated as 5-stars in editor mode.
4. Reopen program to see if rating persisted. It did.
5. Edited it in any way then closed program.
6. On open it has no rating.

**Comment by makerbeleg** [comment]
Being in Editor mode, saving current picture (Ctrl+s shortcut) also removes rating.
Putting image in queue seems like also removes rating.

Even opening dialog box (ctrl+s), without actually saving picture, removes rating.

**Comment by Lawrence37** [comment]
Most likely the cause is one thing. It just looks like all the different things you tried are causing it because that one thing also happened while you were testing. Do any of the methods you wrote reproduce the issue 100% of the time?

**Comment by makerbeleg** [comment]
I tried those across 3 days and multiple reboots. Yes, all those reproduce the issue 100% of the time.

To me it looks like that anything profile related one way or another remove rating.

**Comment by makerbeleg** [comment]
> To me it looks like that anything profile related one way or another remove rating.

Proff of concept. Saving current profile (Ctrl+shift+s) removes rating.

1. Created folder and copied a raw sony file.
2. Opened it in editor mode to make sure default profile is applied.
3. Rated as 5-stars in editor mode.
4. Reopen program to see if rating persisted. It did.
5. Saved current profile (ctrl+shift+s) and closed program.
6. On open it has no rating.

[DSC05912.ARW_before.pp3.txt](https://github.com/user-attachments/files/17444586/DSC05912.ARW_before.pp3.txt)
[DSC05912.ARW_after.pp3.txt](https://github.com/user-attachments/files/17444585/DSC05912.ARW_after.pp3.txt)

**Comment by Lawrence37** [comment]
I managed to reproduce the issue and reduced the steps to
1. Rate image.
2. Restart RawTherapee.
3. Open image in editor.

The processing profile does not contain the rating and will erase the rating in the pp3 once it is overwritten, either manually or automatically. My guess is that the rating is not properly read from the pp3 upon opening the image in the editor. A restart is required to trigger the bug since the rating is cached in memory.

5.11 and dev are affected. 5.10 is not.

**Comment by Lawrence37** [comment]
I propose a fix in the linked pull request.

**Comment by backbonemedia** [comment]
Just upgraded from 5.10 to 5.11 and ran into this bug trying edit the photos rated with 5.10. Loosing information is a no-go for me, I will revert to 5.10 until this is solved. Luckily I did not proceed much before noticing, so only a few ratings are lost. Seems to be worth making backups of the pp3 files from time to time...

I would like to suggest to start a known bugs section on the download page of each release, so one can judge if the bugs might affect your workflow before upgrading.

**Comment by chunyang** [comment]
I am also running into this issue and can reproduce consistently via a similar procedure to https://github.com/Beep6581/RawTherapee/issues/7218#issuecomment-2424597402. This issue is particularly problematic because every image opened and closed will have its ranking removed.

1. Rate image by writing a .pp3 file (I'm doing it via a script I run).
2. Open RawTherapee (I use 5.11 with multiple editor tabs mode)
3. Open image in editor
4. Close image in editor

Immediately after step 4, the `Rank` inside the .pp3 file will disappear.

**Comment by kostrahb** [comment]
Any chance for hotfix instead of waiting with this for normal release? This seems to be particularly evil bug and is apparently affecting people.

**Comment by hujuice** [comment]
This problem happens quite randomly, but frequently.
Now I have lost the rank simply opening a file. Many other times I lose the rank when I generate jpg/tif outputs, both from the editing mode or from the file browser. It doesn't happen every time, but it happens frequently.

I find it quite serious: ranking photos is a significant work.

**Comment by kostrahb** [comment]
@Lawrence37 So as more and more people are losing their work (yes, rating of good images is quite time demanding), I need to ask again, would it be possible to release a hotfix for this bug instead of including it in next normal release?

**Comment by hujuice** [comment]
> @Lawrence37 So as more and more people are losing their work (yes, rating of good images is quite time demanding), I need to ask again, would it be possible to release a hotfix for this bug instead of including it in next normal release?

I would also appreciate it.
