### ISSUE TITLE
Best way to add more than one graduated filter

### ISSUE THREAD

**Issue by graphikeye** [Beep6581/RawTherapee#7271]
I read through the other thread but i can't quite make sense of it. Is there another way to add more than one graduated filter?

**Comment by Lawrence37** [comment]
Which other thread?

**Comment by graphikeye** [comment]
https://github.com/Beep6581/RawTherapee/issues/3206

**Comment by Lawrence37** [comment]
Selective editing is the only way to add multiple graduated filters. The easiest way is to add one spot per filter.
1. After adding a spot, change the "Spot method" to Global.
2. Add one of the tools that has a graduated filter. I recommend "Vibrance & Warm/Cool" because it has few distractions and has more graduated filter options.
3. Set the tool complexity to Standard or Advanced to reveal the graduated filter. I recommend Advanced (with the "Vibrance & Warm/Cool" or "Color & Light" tool) because it allows you to adjust the chroma, which is necessary to achieve results similar to the stand-alone Graduated Filter tool.
4. Reposition the spot to move the graduated filter where you want it to go.
5. Adjust the "Gradient strength", "Gradient angle", and "Gradient feather" to taste.
6. (Optional) Copy the "Gradient strength" value into the "Chroma gradient strength". This will preserve the saturation of the affected areas.

You can add more spots for each graduated filter you need and repeat the steps. A nice shortcut to skip steps 1-3 for subsequent graduated filters is to use the "Duplicate" spot button.

For other further questions about using RawTherapee, I recommend using the official forum at https://discuss.pixls.us/c/software/rawtherapee/14. There is a larger community of users there (this site is focused on development).

**Comment by Desmis** [comment]
@graphikeye @Lawrence37 

Completely agree with Lawrence.
One additional point, a bug currently prevents correct operation #7232 when moving the window in the Preview, or when Zooming.
To adjust, put yourself in "File whole image to screen"
I am trying to improve this behavior in the Preview, the PR on GHS #7251 brings notable progress, without being perfect : with executables https://github.com/Beep6581/RawTherapee/releases/tag/pre-dev-github-actions   with GHS in the text.

Jacques

**Comment by graphikeye** [comment]
Thank you so much! This explanation makes total sense. I appreciate it.
